import { KnowledgeRegistrySchema } from "./schemas";
import type { KnowledgeRegistry, SourceRecord, SourceVersion } from "./types";

export const KNOWLEDGE_REGISTRY_VERSION = "2026-08-13";
export const KNOWLEDGE_LAST_VERIFIED_AT = "2026-08-13";

function publicSource(
  source: Omit<SourceRecord, "language" | "licenseStatus" | "accessStatus"> &
    Partial<Pick<SourceRecord, "language" | "licenseStatus" | "accessStatus">>,
): SourceRecord {
  return {
    language: "fr",
    licenseStatus: "official_public_access",
    accessStatus: "public",
    ...source,
  };
}

const records: SourceRecord[] = [
  publicSource({
    id: "lpf-a47-a1",
    title: "Livre des procedures fiscales - Article A.47 A-1",
    publisher: "Legifrance",
    authorityLevel: "law",
    sourceNature: "law_or_regulation",
    authorityRank: 1,
    jurisdiction: "FR",
    canonicalUrl: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000027804775/",
    documentType: "code_article",
  }),
  publicSource({
    id: "bofip-fec-format",
    title: "BOFiP - Format du fichier des ecritures comptables",
    publisher: "Direction generale des finances publiques",
    authorityLevel: "professional_guidance",
    sourceNature: "official_administrative_doctrine",
    authorityRank: 1,
    jurisdiction: "FR",
    canonicalUrl:
      "https://bofip.impots.gouv.fr/bofip/9028-PGP.html/identifiant%3DBOI-CF-IOR-60-40-20-20170607",
    documentType: "official_tax_doctrine",
  }),
  publicSource({
    id: "pcg-anc-2014-03",
    title: "Plan comptable general - Reglement ANC 2014-03, version consolidee 2026",
    publisher: "Autorite des normes comptables",
    authorityLevel: "regulation",
    sourceNature: "law_or_regulation",
    authorityRank: 1,
    jurisdiction: "FR",
    canonicalUrl: "https://www.anc.gouv.fr/plan-comptable-general-0",
    documentType: "accounting_regulation",
    accessStatus: "public_pdf",
  }),
  publicSource({
    id: "anc-2026-03",
    title: "Reglement ANC 2026-03 relatif aux produits des ventes",
    publisher: "Autorite des normes comptables",
    authorityLevel: "regulation",
    sourceNature: "law_or_regulation",
    authorityRank: 1,
    jurisdiction: "FR",
    canonicalUrl: "https://www.anc.gouv.fr/reglement-anc-ndeg2026-03-du-6-mars-2026",
    documentType: "accounting_regulation_pending_endorsement",
    accessStatus: "public_pdf",
  }),
  publicSource({
    id: "anc-2026-04",
    title: "Reglement ANC 2026-04 relatif a l'impot sur les benefices",
    publisher: "Autorite des normes comptables",
    authorityLevel: "regulation",
    sourceNature: "law_or_regulation",
    authorityRank: 1,
    jurisdiction: "FR",
    canonicalUrl: "https://www.anc.gouv.fr/reglement-anc-ndeg-2026-04-du-4-mai-2026",
    documentType: "accounting_regulation_pending_endorsement",
    accessStatus: "public_pdf",
  }),
  publicSource({
    id: "h2a-referentiel-normatif",
    title: "H2A - Referentiel normatif des commissaires aux comptes",
    publisher: "Haute Autorite de l'audit",
    authorityLevel: "professional_guidance",
    sourceNature: "french_professional_standard",
    authorityRank: 2,
    jurisdiction: "FR",
    canonicalUrl:
      "https://h2a-france.org/referentiel-normatif-et-code-de-deontologie/acceder-au-referentiel-normatif/",
    documentType: "professional_standard_index",
    licenseStatus: "open_licence_2_0",
  }),
  ...[
    ["230", "Documentation de l'audit des comptes", "documentation-de-laudit-des-comptes"],
    ["300", "Planification de l'audit", "planification-de-laudit"],
    [
      "315",
      "Connaissance de l'entite et evaluation des risques",
      "connaissance-de-lentite-et-de-son-environnement-et-evaluation-du-risque-danomalies-significatives-dans-les-comptes",
    ],
    [
      "320",
      "Caractere significatif",
      "application-de-la-notion-de-caractere-significatif-lors-de-la-planification-et-de-la-realisation-dun-audit",
    ],
    [
      "330",
      "Reponses aux risques evalues",
      "procedures-daudit-mises-en-oeuvre-par-le-commissaire-aux-comptes-a-lissue-de-son-evaluation-des-risques",
    ],
    ["450", "Evaluation des anomalies relevees", "evaluation-des-anomalies-relevees-au-cours-de-laudit"],
    ["500", "Caractere probant des elements collectes", "caractere-probant-des-elements-collectes"],
    [
      "501",
      "Elements probants - applications specifiques",
      "caractere-probant-des-elements-collectes-applications-specifiques",
    ],
    ["530", "Selection des elements a controler", "selection-des-elements-a-controler"],
    [
      "700",
      "Rapport sur les comptes annuels et consolides",
      "rapports-du-commissaires-aux-comptes-sur-les-comptes-annuels-et-consolides",
    ],
  ].map(([number, title, slug]) =>
    publicSource({
      id: `h2a-nep-${number}`,
      title: `NEP ${number} - ${title}`,
      publisher: "Haute Autorite de l'audit",
      authorityLevel: "professional_standard",
      sourceNature: "french_professional_standard",
      authorityRank: 2,
      jurisdiction: "FR",
      canonicalUrl: `https://h2a-france.org/normes/${slug}/`,
      documentType: "professional_standard",
      licenseStatus: "open_licence_2_0",
    }),
  ),
  publicSource({
    id: "ifrs-required-2026",
    title: "IFRS Accounting Standards - Required 2026",
    publisher: "IFRS Foundation",
    authorityLevel: "international_standard",
    sourceNature: "international_standard",
    authorityRank: 3,
    jurisdiction: "IASB",
    canonicalUrl:
      "https://www.ifrs.org/news-and-events/news/2026/01/now-available-ifrs-accounting-standards-required-2026-two-editions/",
    documentType: "ifrs_standards_collection_metadata",
    language: "en",
    licenseStatus: "copyrighted_metadata_only",
    accessStatus: "purchase_or_subscription",
  }),
  ...[
    [
      "ifrs-18",
      "IFRS 18 - Presentation and Disclosure in Financial Statements",
      "https://www.ifrs.org/issued-standards/list-of-standards/ifrs-18-presentation-and-disclosure-in-financial-statements/",
    ],
    [
      "ifrs-19",
      "IFRS 19 - Subsidiaries without Public Accountability: Disclosures",
      "https://www.ifrs.org/issued-standards/list-of-standards/ifrs-19-subsidiaries-without-public-accountability-disclosures/",
    ],
  ].map(([id, title, canonicalUrl]) =>
    publicSource({
      id,
      title,
      publisher: "IFRS Foundation",
      authorityLevel: "international_standard",
      sourceNature: "international_standard",
      authorityRank: 3,
      jurisdiction: "IASB",
      canonicalUrl,
      documentType: "ifrs_standard_metadata",
      language: "en",
      licenseStatus: "copyrighted_metadata_only",
      accessStatus: "public_summary",
    }),
  ),
  publicSource({
    id: "ifrs-taxonomy-2025-2026",
    title: "IFRS Accounting Taxonomy 2025 - version courante pour le reporting 2026",
    publisher: "IFRS Foundation",
    authorityLevel: "international_standard",
    sourceNature: "international_standard",
    authorityRank: 3,
    jurisdiction: "IASB",
    canonicalUrl:
      "https://www.ifrs.org/news-and-events/news/2026/02/ifrs-accounting-taxonomy-2025-to-remain-current-for-2026/",
    documentType: "ifrs_taxonomy_guidance",
    language: "en",
    licenseStatus: "copyrighted_metadata_only",
    accessStatus: "public_summary",
  }),
  publicSource({
    id: "efrag-endorsement-status",
    title: "EFRAG - EU endorsement status report",
    publisher: "EFRAG",
    authorityLevel: "professional_guidance",
    sourceNature: "official_administrative_doctrine",
    authorityRank: 1,
    jurisdiction: "EU",
    canonicalUrl: "https://www.efrag.org/en/financial-reporting/endorsement-status",
    documentType: "eu_endorsement_status_report",
    language: "en",
  }),
  publicSource({
    id: "eurlex-ifrs18-endorsement",
    title: "Reglement (UE) 2026/338 portant adoption d'IFRS 18",
    publisher: "Union europeenne",
    authorityLevel: "regulation",
    sourceNature: "law_or_regulation",
    authorityRank: 1,
    jurisdiction: "EU",
    canonicalUrl: "https://eur-lex.europa.eu/eli/reg/2026/338/oj/fra",
    documentType: "eu_regulation",
  }),
  publicSource({
    id: "acpr-ifrs",
    title: "ACPR - Normes comptables internationales (IFRS)",
    publisher: "ACPR",
    authorityLevel: "professional_guidance",
    sourceNature: "professional_doctrine",
    authorityRank: 4,
    jurisdiction: "FR",
    canonicalUrl:
      "https://acpr.banque-france.fr/fr/lacpr/lacpr-en-europe-linternational/cadre-comptable/standards-internationaux/normes-comptables-internationales-ifrs",
    documentType: "supervisory_guidance",
  }),
  publicSource({
    id: "acpr-isa",
    title: "ACPR - Normes d'audit internationales (ISA)",
    publisher: "ACPR",
    authorityLevel: "professional_guidance",
    sourceNature: "professional_doctrine",
    authorityRank: 4,
    jurisdiction: "FR",
    canonicalUrl:
      "https://acpr.banque-france.fr/fr/lacpr/lacpr-en-europe-linternational/cadre-comptable/standards-internationaux/normes-daudit-internationales-isa",
    documentType: "supervisory_guidance",
  }),
  publicSource({
    id: "cncc-ifrs-referentiel",
    title: "CNCC - Referentiel IFRS",
    publisher: "CNCC",
    authorityLevel: "professional_guidance",
    sourceNature: "professional_doctrine",
    authorityRank: 4,
    jurisdiction: "FR",
    canonicalUrl: "https://doc.cncc.fr/docs/referentiel-ifrs",
    documentType: "professional_doctrine",
  }),
  publicSource({
    id: "ey-ifrs-18-analysis",
    title: "EY - Applying IFRS: A closer look at IFRS 18",
    publisher: "EY",
    authorityLevel: "interpretive_analysis",
    sourceNature: "secondary_analysis",
    authorityRank: 5,
    jurisdiction: "EU",
    canonicalUrl:
      "https://www.ey.com/en_gl/technical/ifrs-technical-resources/applying-ifrs-a-closer-look-at-ifrs-18-updated-april-2026",
    documentType: "secondary_analysis",
    language: "en",
    licenseStatus: "secondary_analysis_metadata_only",
  }),
  publicSource({
    id: "pwc-ifrs-18-analysis",
    title: "PwC France - IFRS 18, une norme qui transforme la lecture des etats financiers",
    publisher: "PwC France",
    authorityLevel: "interpretive_analysis",
    sourceNature: "secondary_analysis",
    authorityRank: 5,
    jurisdiction: "FR",
    canonicalUrl: "https://www.pwc.fr/fr/publications/2026/04/ifrs-18-lectures-des-etats-financiers.html",
    documentType: "secondary_analysis",
    licenseStatus: "secondary_analysis_metadata_only",
  }),
  {
    id: "probant-internal-parameters",
    title: "Parametres internes PROBANT",
    publisher: "PROBANT",
    authorityLevel: "internal",
    sourceNature: "internal_rule",
    authorityRank: 6,
    jurisdiction: "INTERNAL",
    canonicalUrl: "internal://probant/knowledge/parameters",
    documentType: "internal_parameters",
    language: "fr",
    licenseStatus: "internal",
    accessStatus: "repository",
  },
];

function nepVersion(
  number: string,
  orderDate: string,
  joDate: string,
  codeReference: string,
  contentHash: string,
): SourceVersion {
  return {
    sourceId: `h2a-nep-${number}`,
    versionLabel: `arrete-${orderDate}`,
    publicationDate: joDate,
    effectiveFrom: joDate,
    status: "effective",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash,
    homologationDate: orderDate,
    codeReference,
  };
}

const versions: SourceVersion[] = [
  {
    sourceId: "lpf-a47-a1",
    versionLabel: "version-en-vigueur-2013-08-02",
    publicationDate: "2013-08-02",
    effectiveFrom: "2013-08-02",
    status: "effective",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:c36b8411b76b5ea627fceab8e4215906715828d77c58d6f646faab87476c94b4",
  },
  {
    sourceId: "bofip-fec-format",
    versionLabel: "BOI-CF-IOR-60-40-20-20170607",
    publicationDate: "2017-06-07",
    status: "effective",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:25dfa05c4295921a9b08c32bb63ced181f51cd347fdc8852af794e34b86e446c",
  },
  {
    sourceId: "pcg-anc-2014-03",
    versionLabel: "version-2026-01-01",
    publicationDate: "2026-03-09",
    effectiveFrom: "2026-01-01",
    status: "effective",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:f34c11116cac54ba7b405f5e7c5bbcfc153e7669564c00eff889dde10fb4831d",
  },
  {
    sourceId: "anc-2026-03",
    versionLabel: "adopted-2026-03-06",
    publicationDate: "2026-06-03",
    status: "pending_endorsement",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:cf47827944b88648b9baa58fd102be8dcfc7e4ac04220c4d430f6e5207909322",
  },
  {
    sourceId: "anc-2026-04",
    versionLabel: "adopted-2026-05-04",
    publicationDate: "2026-06-30",
    status: "pending_endorsement",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:c2d60df875c7bbd37d89438daf51b7ae197a580ff4da5ce7813aaae2613f15c2",
  },
  {
    sourceId: "h2a-referentiel-normatif",
    versionLabel: "verified-2026-08-13",
    status: "effective",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:354896ce6eef63aa994712a04764b234a9893be46fa52a377d52d75ec78ec85e",
  },
  nepVersion("230", "2023-12-28", "2023-12-31", "Code de commerce art. A.821-66", "sha256:0934821a4baeb536db1b0bf487b73afd388b6d2014e1f65fc28d257a89a2c291"),
  nepVersion("300", "2024-11-27", "2024-11-30", "Code de commerce art. A.821-69", "sha256:732f7377f42ea8454f257184ca4e172c7430eb9439237dc190fb701159addc6c"),
  nepVersion("315", "2024-11-13", "2024-11-19", "Code de commerce art. A.821-72", "sha256:8b7836793c68f6c9d9f813175232ea1fbf2ce0378e1af68d72ea6cb4b6834afb"),
  nepVersion("320", "2023-12-28", "2023-12-31", "Code de commerce art. A.821-70", "sha256:761baa0af616a79842afc983c49e54e9de9406ba452cbc7cc8e34f8a8022f828"),
  nepVersion("330", "2024-11-13", "2024-11-19", "Code de commerce art. A.821-73", "sha256:3e09839d56a38665ae8f315956776af5ad64f72ab684e4621938dc5270eb76bb"),
  nepVersion("450", "2023-12-28", "2023-12-31", "Code de commerce art. A.821-71", "sha256:daa4ab3169344630df5674da382f8984f221c80727023f362b84994fc1a2fc44"),
  nepVersion("500", "2023-12-28", "2023-12-31", "Code de commerce art. A.821-74", "sha256:148dcd350929c13dddeeaaa41a53913f920b48a5fce3b390c4cac1b40fb921bd"),
  nepVersion("501", "2024-11-27", "2024-11-30", "Code de commerce art. A.821-75", "sha256:bf4ef306e41a6ccf99d512c40a60e94f8fa663b0aecb3c54f74f5b69e5130397"),
  nepVersion("530", "2024-11-13", "2024-11-19", "Code de commerce art. A.821-78", "sha256:d9ade899312e2204347de2ea568006f5030969b5e344ef1822593cb0136bcb3d"),
  nepVersion("700", "2023-12-28", "2023-12-31", "Code de commerce art. A.821-92", "sha256:2884f255a1f86e83640b5f574f589ca4c5c98abba350b995328437bb4fb56e2b"),
  {
    sourceId: "ifrs-required-2026",
    versionLabel: "required-2026",
    effectiveFrom: "2026-01-01",
    status: "effective",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:a4e2473823c6c7a176b0e4fa724942b58a050f35dd1a2eff529feb4903745478",
    iasbStatus: "required",
    iasbEffectiveFrom: "2026-01-01",
    euEndorsementStatus: "review_required",
    euEndorsementSource: {
      sourceId: "efrag-endorsement-status",
      sourceVersion: "update-2026-07-23",
      locator: "per-standard endorsement table",
    },
  },
  {
    sourceId: "ifrs-18",
    versionLabel: "issued-2024-04-09",
    publicationDate: "2024-04-09",
    effectiveFrom: "2027-01-01",
    status: "future",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:da6e7845e4a4b6fdc3234b10313ac83faaec4b13846be04268126d135b45a4e9",
    iasbStatus: "future",
    iasbEffectiveFrom: "2027-01-01",
    euEndorsementStatus: "endorsed",
    euEndorsementDate: "2026-02-13",
    euEffectiveFrom: "2027-01-01",
    euEndorsementSource: {
      sourceId: "eurlex-ifrs18-endorsement",
      sourceVersion: "regulation-eu-2026-338",
      locator: "Reglement (UE) 2026/338, article 2 et annexe",
    },
  },
  {
    sourceId: "ifrs-19",
    versionLabel: "issued-2024-05-09",
    publicationDate: "2024-05-09",
    effectiveFrom: "2027-01-01",
    status: "future",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:b43995fb17dd4bcfbfa6a6d4cf4ec4446254ce30238412464d5267976fae5976",
    iasbStatus: "future",
    iasbEffectiveFrom: "2027-01-01",
    euEndorsementStatus: "pending",
    euEndorsementSource: {
      sourceId: "efrag-endorsement-status",
      sourceVersion: "update-2026-07-23",
      locator: "IFRS 19 row",
    },
  },
  {
    sourceId: "ifrs-taxonomy-2025-2026",
    versionLabel: "taxonomy-2025-current-for-2026",
    effectiveFrom: "2026-01-01",
    effectiveTo: "2026-12-31",
    status: "effective",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:c3531189d06a46530a0421593ebeefe25b447d131681baca8a7fd156ecd41553",
  },
  {
    sourceId: "efrag-endorsement-status",
    versionLabel: "update-2026-07-23",
    publicationDate: "2026-07-23",
    status: "effective",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:cd903d01e4a0f68100805c4e8836561658d49bb26e5732279b1ed584150e6e5e",
  },
  {
    sourceId: "eurlex-ifrs18-endorsement",
    versionLabel: "regulation-eu-2026-338",
    publicationDate: "2026-02-16",
    status: "effective",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:10f9c20136ab33f9d416892a2e4a173ccbc5a8095e8f50b47ceed7dcb5fcbc84",
    codeReference: "CELEX 32026R0338",
  },
  {
    sourceId: "acpr-ifrs",
    versionLabel: "page-2025-01-05",
    publicationDate: "2025-01-05",
    status: "effective",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:86cb805b85886f3eb1617743f7a7cfb15ce1638cb82a439394f0cf3b8dabab73",
  },
  {
    sourceId: "acpr-isa",
    versionLabel: "page-2024-12-27",
    publicationDate: "2024-12-27",
    status: "effective",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:5d8fdf0feb2d1cb7f830a1b6d969bfb55c279f38c09a2e0ef7545f0ee67efb97",
  },
  {
    sourceId: "cncc-ifrs-referentiel",
    versionLabel: "page-2024-01-26",
    publicationDate: "2024-01-26",
    status: "effective",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:44aa424daa547173b30fa675568587057e35fa126798e97bf839478e99a8269e",
  },
  {
    sourceId: "ey-ifrs-18-analysis",
    versionLabel: "update-2026-04-29",
    publicationDate: "2026-04-29",
    status: "effective",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:dd0282ed201675bc93f459952b985ad4659cebc7807d9ff24643003aa6add00d",
  },
  {
    sourceId: "pwc-ifrs-18-analysis",
    versionLabel: "article-2026-04-02",
    publicationDate: "2026-04-02",
    status: "effective",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:c18612f40a8ae9f369eda0fc8900bb36dc2f1b719f6803ad8c9176265c3b7a1b",
  },
  {
    sourceId: "probant-internal-parameters",
    versionLabel: "internal-2026-08-13",
    status: "internal",
    lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    contentHash: "sha256:a680cd73854845f343f8f5a0a89c62112f8349813b670f10a2daf6d7e31a16c6",
  },
];

const rawRegistry: KnowledgeRegistry = {
  records,
  versions,
  requirements: [
    {
      id: "fec-18-fields-order",
      label: "FEC - 18 champs obligatoires dans l'ordre",
      summary: "Le FEC standard comporte les dix-huit informations prescrites, dans l'ordre fixe par l'article A.47 A-1.",
      force: "mandatory",
      applicability: "direct_fr",
      authorityLevel: "law",
      sourceId: "lpf-a47-a1",
      sourceVersion: "version-en-vigueur-2013-08-02",
      paragraphReference: {
        sourceId: "lpf-a47-a1",
        sourceVersion: "version-en-vigueur-2013-08-02",
        locator: "VII-1",
        label: "Tableau des dix-huit informations",
      },
      numericThreshold: { value: 18, unit: "fields", operator: "eq" },
      appliesFrom: "2013-08-02",
    },
    {
      id: "fec-date-format",
      label: "FEC - dates AAAAMMJJ",
      summary: "Les dates du FEC sont exprimees sans separateur au format AAAAMMJJ.",
      force: "mandatory",
      applicability: "direct_fr",
      authorityLevel: "law",
      sourceId: "lpf-a47-a1",
      sourceVersion: "version-en-vigueur-2013-08-02",
      paragraphReference: {
        sourceId: "lpf-a47-a1",
        sourceVersion: "version-en-vigueur-2013-08-02",
        locator: "XII-4",
      },
      appliesFrom: "2013-08-02",
    },
    {
      id: "nep-documentation",
      label: "Audit francais - documentation du dossier",
      summary: "La NEP 230 fonde l'exigence de documentation des travaux pour une mission d'audit legale francaise.",
      force: "mandatory",
      applicability: "direct_fr",
      authorityLevel: "professional_standard",
      sourceId: "h2a-nep-230",
      sourceVersion: "arrete-2023-12-28",
      paragraphReference: {
        sourceId: "h2a-nep-230",
        sourceVersion: "arrete-2023-12-28",
        locator: "paragraphes 01-03",
      },
    },
    {
      id: "fr-nep-primary-isa-correspondence",
      label: "NEP principales en France; ISA en correspondance",
      summary: "L'ACPR confirme que les ISA n'etant pas adoptees par la Commission europeenne, les NEP francaises s'appliquent en France; les ISA restent un cadre de convergence.",
      force: "interpretive",
      applicability: "direct_fr",
      authorityLevel: "professional_guidance",
      sourceId: "acpr-isa",
      sourceVersion: "page-2024-12-27",
      paragraphReference: {
        sourceId: "acpr-isa",
        sourceVersion: "page-2024-12-27",
        locator: "paragraphes 1-3",
      },
    },
    {
      id: "ifrs-18-eu-2027",
      label: "IFRS 18 adoptee dans l'Union europeenne pour 2027",
      summary: "IFRS 18 est adoptee par le reglement (UE) 2026/338 et s'applique dans l'UE selon le perimetre du reglement IAS a compter du 1er janvier 2027.",
      force: "mandatory",
      applicability: "direct_eu",
      authorityLevel: "regulation",
      sourceId: "eurlex-ifrs18-endorsement",
      sourceVersion: "regulation-eu-2026-338",
      paragraphReference: {
        sourceId: "eurlex-ifrs18-endorsement",
        sourceVersion: "regulation-eu-2026-338",
        locator: "article 2 et annexe",
      },
      appliesFrom: "2027-01-01",
    },
    {
      id: "ifrs-19-eu-pending",
      label: "IFRS 19 - adoption UE en attente",
      summary: "L'IASB fixe l'application d'IFRS 19 au 1er janvier 2027, tandis que l'adoption UE reste en attente dans le rapport EFRAG du 23 juillet 2026.",
      force: "review_required",
      applicability: "review_required",
      authorityLevel: "international_standard",
      sourceId: "ifrs-19",
      sourceVersion: "issued-2024-05-09",
      appliesFrom: "2027-01-01",
    },
    {
      id: "anc-2026-03-pending",
      label: "ANC 2026-03 - homologation a confirmer",
      summary: "Le PDF ANC consulte porte encore la mention En cours d'homologation; aucune date d'effet n'est promue avant verification du Journal officiel.",
      force: "review_required",
      applicability: "review_required",
      authorityLevel: "regulation",
      sourceId: "anc-2026-03",
      sourceVersion: "adopted-2026-03-06",
    },
    {
      id: "anc-2026-04-pending",
      label: "ANC 2026-04 - homologation a confirmer",
      summary: "Le PDF ANC consulte porte encore la mention En cours d'homologation; aucune date d'effet n'est promue avant verification du Journal officiel.",
      force: "review_required",
      applicability: "review_required",
      authorityLevel: "regulation",
      sourceId: "anc-2026-04",
      sourceVersion: "adopted-2026-05-04",
    },
  ],
  crosswalks: [
    ...["230", "300", "315", "320", "330", "450", "500", "530", "700"].map(
      (number) => ({
        id: `nep-${number}-isa-${number}`,
        fromKind: "NEP" as const,
        fromId: `NEP ${number}`,
        toKind: "ISA" as const,
        toId: `ISA ${number}`,
        relation: "corresponds_to" as const,
        applicability: "international_correspondence_only" as const,
        sourceId: "acpr-isa",
        sourceVersion: "page-2024-12-27",
        status: "review_required" as const,
        note: "Correspondance de travail a valider au niveau du contenu; la NEP reste la norme applicable en France.",
      }),
    ),
    {
      id: "ifrs18-ias1",
      fromKind: "IFRS",
      fromId: "IFRS 18",
      toKind: "IFRS",
      toId: "IAS 1",
      relation: "supersedes",
      applicability: "informative",
      sourceId: "ifrs-18",
      sourceVersion: "issued-2024-04-09",
      status: "future",
      note: "Remplacement IASB a compter du 1er janvier 2027.",
    },
    {
      id: "pcg-ifrs-revenue",
      fromKind: "PCG",
      fromId: "ANC 2026-03 produits des ventes",
      toKind: "IFRS",
      toId: "IFRS 15",
      relation: "differs_from",
      applicability: "informative",
      sourceId: "anc-2026-03",
      sourceVersion: "adopted-2026-03-06",
      status: "review_required",
      note: "Crosswalk de haut niveau seulement; homologation ANC et correspondances par paragraphe a confirmer.",
    },
    {
      id: "pcg-ifrs-tax",
      fromKind: "PCG",
      fromId: "ANC 2026-04 impot sur les benefices",
      toKind: "IFRS",
      toId: "IAS 12",
      relation: "differs_from",
      applicability: "informative",
      sourceId: "anc-2026-04",
      sourceVersion: "adopted-2026-05-04",
      status: "review_required",
      note: "Crosswalk de haut niveau seulement; homologation ANC et correspondances par paragraphe a confirmer.",
    },
    {
      id: "fec-control-source",
      fromKind: "CONTROL",
      fromId: "FEC-STRUCTURE-ORDER",
      toKind: "PCG",
      toId: "LPF A.47 A-1",
      relation: "supports",
      applicability: "direct",
      sourceId: "lpf-a47-a1",
      sourceVersion: "version-en-vigueur-2013-08-02",
      status: "effective",
    },
  ],
  statistics: [
    {
      id: "fec-field-count",
      label: "Nombre de champs principaux FEC",
      value: 18,
      unit: "fields",
      period: "version en vigueur verifiee le 2026-08-13",
      geographicScope: "France",
      populationScope: "FEC standard vise au VII-1 de l'article A.47 A-1",
      methodology: "Comptage des informations du tableau officiel.",
      sourceId: "lpf-a47-a1",
      sourceVersion: "version-en-vigueur-2013-08-02",
      lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    },
    {
      id: "h2a-content-count",
      label: "Contenus affiches dans le referentiel normatif H2A",
      value: 42,
      unit: "contents",
      period: "page verifiee le 2026-08-13",
      geographicScope: "France",
      populationScope: "Referentiel normatif H2A affiche en ligne",
      methodology: "Valeur du compteur officiel Nombre de contenus affiches.",
      sourceId: "h2a-referentiel-normatif",
      sourceVersion: "verified-2026-08-13",
      lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    },
    {
      id: "ifrs-18-effective-date",
      label: "Date d'application IASB d'IFRS 18",
      value: 20270101,
      unit: "yyyymmdd",
      period: "standard publie le 2024-04-09; statut verifie le 2026-08-13",
      geographicScope: "IASB",
      populationScope: "Entites appliquant les IFRS selon leur juridiction",
      methodology: "Metadonnee IASB; adoption UE suivie separement.",
      sourceId: "ifrs-18",
      sourceVersion: "issued-2024-04-09",
      lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    },
    {
      id: "ifrs-taxonomy-current-for-2026",
      label: "Millesime de taxonomie IFRS courant pour le reporting 2026",
      value: 2025,
      unit: "taxonomy_version_year",
      period: "reporting periods 2026",
      geographicScope: "IASB",
      populationScope: "Reporting numerique IFRS, sous reserve des regles locales",
      methodology: "Guidance IFRS Foundation indiquant l'absence de taxonomie annuelle 2026.",
      sourceId: "ifrs-taxonomy-2025-2026",
      sourceVersion: "taxonomy-2025-current-for-2026",
      lastVerifiedAt: KNOWLEDGE_LAST_VERIFIED_AT,
    },
  ],
  verifications: [
    {
      sourceId: "lpf-a47-a1",
      sourceVersion: "version-en-vigueur-2013-08-02",
      checkedAt: KNOWLEDGE_LAST_VERIFIED_AT,
      checkedBy: "Codex",
      result: "pass",
      notes: "Version en vigueur et tableau des dix-huit champs verifies sur Legifrance.",
    },
    {
      sourceId: "anc-2026-03",
      sourceVersion: "adopted-2026-03-06",
      checkedAt: KNOWLEDGE_LAST_VERIFIED_AT,
      checkedBy: "Codex",
      result: "pass_with_limitations",
      notes: "La page ANC emploie un libelle Journal Officiel mais le PDF porte encore En cours d'homologation.",
      unverifiedFields: ["homologationDate", "effectiveFrom"],
    },
    {
      sourceId: "anc-2026-04",
      sourceVersion: "adopted-2026-05-04",
      checkedAt: KNOWLEDGE_LAST_VERIFIED_AT,
      checkedBy: "Codex",
      result: "pass_with_limitations",
      notes: "Le PDF ANC porte encore En cours d'homologation; aucune date d'effet n'est inferee.",
      unverifiedFields: ["homologationDate", "effectiveFrom"],
    },
    {
      sourceId: "ifrs-18",
      sourceVersion: "issued-2024-04-09",
      checkedAt: KNOWLEDGE_LAST_VERIFIED_AT,
      checkedBy: "Codex",
      result: "pass",
      notes: "Date IASB et adoption UE 2026/338 verifiees separement.",
    },
    {
      sourceId: "ifrs-19",
      sourceVersion: "issued-2024-05-09",
      checkedAt: KNOWLEDGE_LAST_VERIFIED_AT,
      checkedBy: "Codex",
      result: "pass_with_limitations",
      notes: "Date IASB verifiee; adoption UE encore en attente selon EFRAG au 2026-07-23.",
      unverifiedFields: ["euEndorsementDate", "euEffectiveFrom"],
    },
    {
      sourceId: "ey-ifrs-18-analysis",
      sourceVersion: "update-2026-04-29",
      checkedAt: KNOWLEDGE_LAST_VERIFIED_AT,
      checkedBy: "Codex",
      result: "pass",
      notes: "Analyse secondaire uniquement; ne fonde aucune obligation PROBANT.",
    },
    {
      sourceId: "pwc-ifrs-18-analysis",
      sourceVersion: "article-2026-04-02",
      checkedAt: KNOWLEDGE_LAST_VERIFIED_AT,
      checkedBy: "Codex",
      result: "pass",
      notes: "Analyse secondaire uniquement; ne fonde aucune obligation PROBANT.",
    },
  ],
};

export const knowledgeRegistry = KnowledgeRegistrySchema.parse(rawRegistry);
