DROP TRIGGER IF EXISTS "review_events_append_only_update" ON "review_events";
DROP TRIGGER IF EXISTS "review_events_append_only_delete" ON "review_events";
DROP FUNCTION IF EXISTS "probant_reject_review_event_mutation"();
DROP INDEX IF EXISTS "review_events_dossier_event_hash_uq";
DROP INDEX IF EXISTS "review_events_dossier_previous_hash_uq";
DROP INDEX IF EXISTS "review_events_dossier_root_uq";
DROP INDEX IF EXISTS "review_events_dossier_created_idx";
DROP INDEX IF EXISTS "synthesis_snapshots_dossier_version_idx";
CREATE UNIQUE INDEX "synthesis_snapshots_dossier_version_uq" ON "synthesis_snapshots" USING btree ("dossier_id", "snapshot_version");
ALTER TABLE "review_events" DROP CONSTRAINT IF EXISTS "review_events_event_hash_ck";
ALTER TABLE "review_events" DROP CONSTRAINT IF EXISTS "review_events_previous_hash_ck";
ALTER TABLE "review_events" DROP CONSTRAINT IF EXISTS "review_events_dossier_id_dossiers_id_fk";
ALTER TABLE "review_events" DROP CONSTRAINT IF EXISTS "review_events_finding_id_findings_id_fk";
ALTER TABLE "review_events" ADD CONSTRAINT "review_events_finding_id_findings_id_fk" FOREIGN KEY ("finding_id") REFERENCES "public"."findings"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "review_events" ALTER COLUMN "previous_status" TYPE "review_status" USING "previous_status"::text::"review_status";
ALTER TABLE "review_events" ALTER COLUMN "new_status" TYPE "review_status" USING "new_status"::text::"review_status";
ALTER TABLE "review_events" ALTER COLUMN "comment" DROP NOT NULL;
ALTER TABLE "review_events" ALTER COLUMN "comment" DROP DEFAULT;
ALTER TABLE "review_events" DROP COLUMN "event_hash";
ALTER TABLE "review_events" DROP COLUMN "previous_event_hash";
ALTER TABLE "review_events" DROP COLUMN "dossier_id";
DROP TYPE IF EXISTS "review_event_status";
