import type { TaxCoverage } from "@/lib/canonical-model";
import {
  createTaxAdjustment,
  createFiscalSynthesisSnapshot,
  createTaxComputationSnapshot,
  createTaxControlExecution,
  createTaxDeclarationField,
  createTaxDocumentSnapshot,
  createTaxPeriod,
  createTaxProfile,
  createTaxReconciliationLine,
  type TaxAdjustmentInput,
  type FiscalSynthesisSnapshotInput,
  type TaxComputationSnapshotInput,
  type TaxControlExecutionInput,
  type TaxDeclarationFieldInput,
  type TaxDocumentSnapshotInput,
  type TaxPeriodInput,
  type TaxProfileInput,
  type TaxReconciliationLineInput,
} from "@/lib/tax";

export const CREATED_AT = "2026-08-16T10:00:00.000Z";
export const SHA_A = "a".repeat(64);

export const emptyCoverage: TaxCoverage = {
  applicableControlCount: 0,
  executedControlCount: 0,
  blockedControlCount: 0,
  requiredDocumentCount: 0,
  availableDocumentCount: 0,
  requiredFieldCount: 0,
  usableFieldCount: 0,
  verifiedFieldCount: 0,
  coveredPeriodIds: [],
  uncoveredPeriodIds: [],
  excludedScopes: [],
};

export function profileInput(overrides: Partial<TaxProfileInput> = {}): TaxProfileInput {
  return {
    id: "profile-1",
    organizationId: "org-a",
    dossierId: "dossier-1",
    entityId: "entity-1",
    version: "1",
    jurisdiction: "FR",
    status: "draft",
    corporateIncomeTaxRegime: "standard",
    vatRegime: "real_normal",
    accountingPeriod: { startDate: "2026-01-01", endDate: "2026-12-31" },
    corporateIncomeTaxGroupStatus: "none",
    vatGroupStatus: "none",
    turnoverAmountCents: 1_000_000_00,
    capitalPaidStatus: "unknown",
    ownershipStatus: "unknown",
    qualifyingIndividualOwnershipBasisPoints: null,
    vatLiabilityRatioStatus: "unknown",
    vatLiabilityRatioBasisPoints: null,
    establishments: [{
      establishmentId: "head-office",
      countryCode: "FR",
      postalCode: "75001",
      municipality: "Paris",
      isPrincipal: true,
      verificationStatus: "verified",
    }],
    parameters: [{
      key: "tax_residence",
      value: "FR",
      verificationStatus: "unverified",
      sourceRefs: ["document-1"],
      verifiedBy: null,
      verifiedAt: null,
    }],
    confirmedBy: null,
    confirmedAt: null,
    createdAt: CREATED_AT,
    ...overrides,
  };
}

export function periodInput(overrides: Partial<TaxPeriodInput> = {}): TaxPeriodInput {
  return {
    id: "period-1",
    organizationId: "org-a",
    dossierId: "dossier-1",
    entityId: "entity-1",
    taxType: "corporate_income_tax",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    fiscalYear: 2026,
    formVintage: 2026,
    frequency: "annual",
    accountingPeriodId: "accounting-period-1",
    status: "filed",
    version: "1",
    sourceRefs: ["form-2065-v2026"],
    createdAt: CREATED_AT,
    ...overrides,
  };
}

export function fieldInput(overrides: Partial<TaxDeclarationFieldInput> = {}): TaxDeclarationFieldInput {
  return {
    id: "field-1",
    organizationId: "org-a",
    dossierId: "dossier-1",
    taxDocumentSnapshotId: "tax-document-1",
    formVintage: 2026,
    fieldCode: "XN",
    label: "Benefice fiscal",
    dataType: "amount",
    rawValue: "1000,00",
    amountCents: 100_000,
    normalizedValue: null,
    percentageBasisPoints: null,
    unit: "cent",
    sign: "positive",
    documentHash: SHA_A,
    sourceLocation: {
      page: 9,
      sheet: null,
      cell: null,
      box: "XN",
      zone: "case-XN",
      structuredPath: null,
    },
    extractionMethod: "manual",
    parserVersion: "1",
    confidence: 1,
    processingStatus: "accepted",
    usableForAutomatedCalculation: true,
    reviewStatus: "verified",
    warnings: [],
    evidenceStrength: "direct",
    ...overrides,
  };
}

export function documentInput(overrides: Partial<TaxDocumentSnapshotInput> = {}): TaxDocumentSnapshotInput {
  return {
    id: "tax-document-1",
    organizationId: "org-a",
    dossierId: "dossier-1",
    entityId: "entity-1",
    logicalDocumentId: "logical-2065",
    sourceDocumentId: "source-document-1",
    taxPeriodId: "period-1",
    taxPeriodVersion: "1",
    taxType: "corporate_income_tax",
    documentType: "form_2058_a",
    formNumber: "2058-A-SD",
    formVintage: 2026,
    snapshotVersion: "1",
    schemaVersion: "2026.1",
    parserName: "manual-fixture",
    parserVersion: "1",
    sourceHash: SHA_A,
    fields: [createTaxDeclarationField(fieldInput())],
    warnings: [],
    limitationIds: [],
    supersedesSnapshotId: null,
    status: "active",
    createdAt: CREATED_AT,
    createdBy: "reviewer-1",
    ...overrides,
  };
}

export function executionInput(overrides: Partial<TaxControlExecutionInput> = {}): TaxControlExecutionInput {
  return {
    id: "execution-1",
    organizationId: "org-a",
    dossierId: "dossier-1",
    entityId: "entity-1",
    taxPeriodId: "period-1",
    fiscalYear: 2026,
    formVintage: 2026,
    executionVersion: "1",
    controlId: "IS.REVIEW.001",
    controlVersion: "1",
    definitionHash: SHA_A,
    taxProfileId: "profile-1",
    taxProfileVersion: "1",
    taxDocumentSnapshotIds: ["tax-document-1"],
    inputHashes: [SHA_A],
    status: "blocked",
    proposedOutcome: "missing_information",
    evidenceStrength: "insufficient",
    trace: [],
    reconciliationLineIds: [],
    adjustmentIds: [],
    findingIds: [],
    coverage: emptyCoverage,
    limitations: [{
      id: "limitation-1",
      code: "missing_information",
      scope: "control",
      capabilityStatus: "available",
      reason: "missing_field",
      message: "Une information requise manque.",
      blockedOutcomes: ["passed", "confirmed_non_compliance"],
      requiredInputs: ["supporting_document"],
      relatedIds: ["execution-1"],
      resolvability: "user_can_supply",
    }],
    engineVersion: "tax-model-only-1",
    executedAt: CREATED_AT,
    ...overrides,
  };
}

export function reconciliationInput(overrides: Partial<TaxReconciliationLineInput> = {}): TaxReconciliationLineInput {
  return {
    id: "line-1",
    organizationId: "org-a",
    dossierId: "dossier-1",
    executionId: "execution-1",
    lineKey: "declared-vs-ledger",
    label: "Montant declare et comptabilise",
    leftOperand: { amountCents: 100_000, currency: "EUR", snapshotId: "tax-document-1", fieldCode: "XN" },
    rightOperand: { amountCents: 100_000, currency: "EUR", snapshotId: "ledger-snapshot-1", fieldCode: null },
    normalizationNotes: [],
    differenceAmountCents: 0,
    toleranceAmountCents: 0,
    toleranceFamily: "internal",
    status: "matched",
    evidenceRefs: ["field-1"],
    traceStepIds: [],
    ...overrides,
  };
}

export function adjustmentInput(overrides: Partial<TaxAdjustmentInput> = {}): TaxAdjustmentInput {
  return {
    id: "adjustment-1",
    organizationId: "org-a",
    dossierId: "dossier-1",
    executionId: "execution-1",
    taxPeriodId: "period-1",
    taxType: "corporate_income_tax",
    version: "1",
    adjustmentCode: "REVIEW_ONLY",
    label: "Proposition de revue non chiffree",
    direction: "unquantified",
    baseAmountCents: null,
    taxAmountCents: null,
    currency: "EUR",
    originRefs: ["field-1"],
    sourceVersionIds: ["cgi-art-38-v2025-02-16"],
    trace: [],
    proposalStatus: "proposed",
    reviewStatus: "pending",
    reviewEventId: null,
    supersedesAdjustmentId: null,
    ...overrides,
  };
}

export function computationInput(overrides: Partial<TaxComputationSnapshotInput> = {}): TaxComputationSnapshotInput {
  return {
    id: "computation-1",
    organizationId: "org-a",
    dossierId: "dossier-1",
    entityId: "entity-1",
    taxPeriodId: "period-1",
    fiscalYear: 2026,
    formVintage: 2026,
    taxType: "corporate_income_tax",
    calculationType: "model_only",
    calculationVersion: "1",
    inputSnapshotIds: ["tax-document-1"],
    sourceVersionIds: ["cgi-art-38-v2025-02-16"],
    proposedAdjustmentIds: [],
    acceptedAdjustmentIds: [],
    outputs: [{ code: "declared_result", label: "Resultat declare", amountCents: 100_000, currency: "EUR", status: "declared" }],
    trace: [],
    coverage: emptyCoverage,
    limitations: [],
    evidenceStrength: "direct",
    createdAt: CREATED_AT,
    createdBy: "reviewer-1",
    ...overrides,
  };
}

export function fiscalSynthesisInput(
  overrides: Partial<FiscalSynthesisSnapshotInput> = {},
): FiscalSynthesisSnapshotInput {
  return {
    id: "fiscal-synthesis-1",
    organizationId: "org-a",
    dossierId: "dossier-1",
    entityId: "entity-1",
    snapshotVersion: "1",
    fiscalYear: 2026,
    formVintage: 2026,
    periodIds: ["period-1"],
    executionIds: ["execution-1"],
    computationSnapshotIds: ["computation-1"],
    outcomeCounts: {
      passed: 0,
      confirmed_non_compliance: 0,
      reconciliation_difference: 0,
      potential_tax_risk: 0,
      missing_information: 1,
      inconclusive: 0,
      review_recommendation: 0,
    },
    coverage: emptyCoverage,
    limitations: [],
    reviewSummary: { pending: 1, accepted: 0, rejected: 0, amended: 0 },
    headlineStatus: "missing_information",
    headlinePolicyVersion: "1",
    trace: [],
    generatedAt: CREATED_AT,
    ...overrides,
  };
}

export const fixtures = {
  profile: () => createTaxProfile(profileInput()),
  period: () => createTaxPeriod(periodInput()),
  field: () => createTaxDeclarationField(fieldInput()),
  document: () => createTaxDocumentSnapshot(documentInput()),
  execution: () => createTaxControlExecution(executionInput()),
  reconciliation: () => createTaxReconciliationLine(reconciliationInput()),
  adjustment: () => createTaxAdjustment(adjustmentInput()),
  computation: () => createTaxComputationSnapshot(computationInput()),
  fiscalSynthesis: () => createFiscalSynthesisSnapshot(fiscalSynthesisInput()),
};

