import { PDFDocument, StandardFonts } from 'pdf-lib';
import { previewImport, type ImportBatch, type ImportMapping } from './imports';
import { EQUITY_FAMILIES, EQUITY_FAMILY_LABELS, previewEquityPdf, stampEquityWork, evaluateEquity, type EquityDraft } from './equity-dossier';
import { freezePopulation, selectPopulation } from './selection';
import { periodId, type WorkpaperScope, type WorkpaperRun } from './model';
import { EQUITY_TEMPLATE } from './equity-adapter';
import type { AccountingPeriod } from '@/lib/canonical-model/period';
import { stableSha256 } from '@/lib/synthesis/canonical';
import type { Principal } from './policy';
export const EQUITY_DEMO_PERIOD={startDate:'2024-01-01',closingDate:'2024-12-31',asOfDate:'2025-02-01',currency:'EUR' as const,validation:'provisional' as const} satisfies AccountingPeriod;
export const EQUITY_DEMO_MAPPING:ImportMapping={version:'equity-dossier-1',headerRow:1,columns:{key:'id',amount:'amount',date:'date'},equity:{componentColumn:'component',accountColumn:'account',decisionColumn:'decision',kindColumn:'kind',effectiveColumn:'effective',transferColumn:'transfer',currencyColumn:'currency',descriptionColumn:'description'},delimiter:';',decimal:'.',dateFormat:'ISO',sign:1,currency:'EUR'};
export const equityFixtureCsv:Record<string,string>={
 equity_balances:'id;amount;date;component;account;decision;kind;effective;transfer;currency;description\nOC;100.00;2024-01-01;capital;101;;opening;;;EUR;Capital ouverture\nCC;100.00;2024-12-31;capital;101;;closing;;;EUR;Capital clôture\nOR;50.00;2024-01-01;reserves;106;;opening;;;EUR;Réserves ouverture\nCR;70.00;2024-12-31;reserves;106;;closing;;;EUR;Réserves clôture\nORE;40.00;2024-01-01;result;120;;opening;;;EUR;Résultat ouverture\nCRE;-5.00;2024-12-31;result;120;;closing;;;EUR;Résultat clôture',
 equity_ledger:'id;amount;date;component;account;decision;kind;effective;transfer;currency;description\nDISTR-25;-25.00;2024-07-10;result;120;DIST;decision;2024-07-01;;EUR;Distribution comptabilisée 25\nTR-RES;20.00;2024-06-20;reserves;106;TR;decision;2024-06-20;TRANSFER;EUR;Transfert vers réserves\nTR-RESULT;-20.00;2024-06-20;result;120;TR;decision;2024-06-20;TRANSFER;EUR;Transfert depuis résultat\nORPHAN;0.00;2024-08-01;capital;101;;decision;2024-08-01;;EUR;Mouvement sans décision renseignée',
 equity_variation:'id;amount;date;component;account;decision;kind;effective;transfer;currency;description\nVC;0.00;2024-12-31;capital;101;;variation;;;EUR;Capital stable\nVR;20.00;2024-12-31;reserves;106;;variation;;;EUR;Réserves\nVRE;-45.00;2024-12-31;result;120;;variation;;;EUR;Résultat',
 equity_decisions:'id;amount;date;component;account;decision;kind;effective;transfer;currency;description\nDIST;30.00;2024-06-15;result;120;;decrease;2024-07-01;;EUR;Distribution votée 30, comptabilisée 25\nTR;20.00;2024-06-20;reserves;106;;transfer;2024-06-20;TRANSFER;EUR;Transfert interne neutre\nNO-PV;10.00;2024-08-20;reserves;106;;increase;2024-09-01;;EUR;Décision annoncée, PV absent\nNEXT;15.00;2024-12-15;capital;101;;increase;2025-01-15;;EUR;Effet après clôture\nNO-ENTRY;12.00;2024-09-10;capital;101;;increase;2024-10-01;;EUR;Décision documentée sans écriture',
 equity_payments:'id;amount;date;component;account;decision;kind;effective;transfer;currency;description\nPAY-1;25.00;2025-01-12;;;DIST;payment;;;EUR;Règlement ultérieur distinct'
};
export async function equitySyntheticPdf(){const pdf=await PDFDocument.create();pdf.setCreationDate(new Date('2025-02-01T12:00:00Z'));pdf.setModificationDate(new Date('2025-02-01T12:00:00Z'));pdf.setProducer('PROBANT synthetic fixture');pdf.setCreator('PROBANT synthetic fixture');const font=await pdf.embedFont(StandardFonts.Helvetica);for(const lines of [['EXEMPLE SYNTHETIQUE - PV v1','Decision DIST : distribution votee 30 EUR.','Vote : 15 juin 2024 ; effet : 1 juillet 2024.'],['EXEMPLE SYNTHETIQUE - PV v1','Transfert TR : 20 EUR du resultat vers les reserves.','Effet : 20 juin 2024 ; total des capitaux propres inchange.'],['EXEMPLE SYNTHETIQUE - ACTE','NO-ENTRY : augmentation declaree de 12 EUR ; effet 1 octobre 2024.','Cartographie et conventions de la recette, sans regle juridique.']]){const page=pdf.addPage([595,842]);lines.forEach((text,i)=>page.drawText(text,{x:45,y:780-i*30,size:14,font}));}return await pdf.save();}
export function equityDraftFor(batches:ImportBatch[],incomplete=false):EquityDraft{const pdf=batches.find(b=>b.document.documentType==='equity_minutes')!,first=pdf.rows[0].id;return{schemaVersion:'equity-dossier-1',method:{id:'METHODE-INTERNE-EQUITY',version:'1',note:'Comparer les montants par décision et date d’effet ; signe comptable conservé. Aucun avis juridique.',proofRowIds:[first]},socialForm:'Forme sociale à corroborer — exemple synthétique',completeComponentSet:!incomplete,ledgerCoverage:'documented',decisionsCoverage:'documented',components:EQUITY_FAMILIES.map(f=>({id:f,label:EQUITY_FAMILY_LABELS[f],family:f,accounts:f==='capital'?['101']:f==='reserves'?['106']:f==='result'?['120']:[],state:['capital','reserves','result'].includes(f)?'in_scope':'not_applicable',reason:['capital','reserves','result'].includes(f)?'':'Non applicable dans cette recette, à justifier pour une mission',proofRowId:first})),interpretations:[{decisionId:'DIST',proofRowId:first,note:'Lecture du montant 30 et de sa date d’effet.'},{decisionId:'TR',proofRowId:pdf.rows[1].id,note:'Deux mouvements opposés, transfert équilibré.'},{decisionId:'NO-ENTRY',proofRowId:pdf.rows[2].id,note:'Décision présente, écriture à rechercher.'}]};}
export async function equityFixture(scope:WorkpaperScope={organizationId:'SYN-EQUITY',dossierId:'SYN-EQUITY-RECETTE',periodId:periodId(EQUITY_DEMO_PERIOD),mode:'demo'},incomplete=false,longText=false){const actor:Principal={id:'Préparateur synthétique',grants:[{scope,permissions:['read','prepare','review','download']}]},batches:ImportBatch[]=[],files=new Map<string,File>();for(const[type,text]of Object.entries(equityFixtureCsv)){let body=longText&&type==='equity_decisions'?text.replace('Distribution votée 30, comptabilisée 25','Distribution votée 30, comptabilisée 25 — '+ 'Décision à corroborer, justificatif versionné et portée de la revue. '.repeat(12)):text;if(incomplete&&type==='equity_balances')body=body.split('\n').filter(row=>!row.startsWith('CC;')&&!row.startsWith('CR;')).join('\n');const file=new File([body],type+'.csv',{type:'text/csv'}),preview=await previewImport(file,scope,EQUITY_DEMO_MAPPING,actor,type,scope.mode==='real'?'equity.review':undefined);const b={...preview,approval:{actorId:actor.id,at:'2025-02-01T12:00:00.000Z',previewHash:preview.previewHash},report:{...preview.report,calculationAllowed:true}};batches.push(b);files.set(type,file);}const pdfFile=new File([Uint8Array.from(await equitySyntheticPdf()).buffer],'EXEMPLE-PV-v1.pdf',{type:'application/pdf'}),p=await previewEquityPdf(pdfFile,scope,EQUITY_DEMO_MAPPING,actor,'equity_minutes',EQUITY_DEMO_PERIOD);batches.push({...p,approval:{actorId:actor.id,at:'2025-02-01T12:00:00.000Z',previewHash:p.previewHash},report:{...p.report,calculationAllowed:true}});files.set('equity_minutes',pdfFile);const imports=batches;const draft=equityDraftFor(imports,incomplete),population=freezePopulation(scope,imports,'equity_decision_movement',actor),selection=selectPopulation(population,{method:'targeted',criteria:'Toutes les décisions et mouvements de la recette',requestedSize:population.items.length,selectedIds:population.items.map(i=>i.id),exclusions:[]},actor),work=stampEquityWork(draft,imports,scope,EQUITY_DEMO_PERIOD,'SYN-EQUITY-RUN',actor.id,'2025-02-01T12:00:00.000Z'),result=evaluateEquity(scope,EQUITY_DEMO_PERIOD,imports,'SYN-EQUITY-RUN',population,selection,work);
 const run:WorkpaperRun={id:'SYN-EQUITY-RUN',rootId:'SYN-EQUITY-RUN',revision:1,version:1,schemaVersion:'1.0.0',scope,period:EQUITY_DEMO_PERIOD,template:EQUITY_TEMPLATE,state:'executed',preparedBy:actor.id,importIds:imports.map(b=>b.id),population,selection,equityWork:work,result:{id:'SYN-CALC',scope,period:EQUITY_DEMO_PERIOD,calculationKey:'equity.review',ruleVersion:'1.0.0',inputHash:stableSha256({scope,work,population,selection}),execution:'completed',outcome:'exceptions_detected',sourceRefs:[],input:{},result,findings:[],warnings:result.limitations,blockedControls:[]},evidence:result.evidence,findings:[],notes:result.exceptions.map(e=>({id:e.id,kind:'observation',text:e.text,amount:e.amount,authorId:actor.id,blocking:true})),events:[{id:'SYN-EVENT',action:'synthetic_example',actorId:actor.id,at:'2025-02-01T12:00:00.000Z',version:1}]};return{scope,actor,imports,files,draft,work,population,selection,result,run};}
