import { z } from 'zod';
import { PDFDocument } from 'pdf-lib';
import { cents, money, type KnownAmount, type Money } from '@/lib/canonical-model/money';
import type { AccountingPeriod } from '@/lib/canonical-model/period';
import { isCivilDate } from '@/lib/canonical-model/period';
import { stableSha256 } from '@/lib/synthesis/canonical';
import { sha256 } from '@/lib/evidence/hash';
import { assertScope, frozen, type WorkpaperScope, type EvidenceLink, type SourceRow, type Population, type SelectionSet } from './model';
import type { ImportBatch, ImportMapping } from './imports';
import { reviewEquity, type EquityInput } from './equity';
import { known, unknown, type SupportedAmount } from './cycle-review';
import { authorize, type Principal } from './policy';
import { EQUITY_TYPES, EQUITY_LABELS, EQUITY_FAMILIES, EQUITY_FAMILY_LABELS, EQUITY_STATUS } from "./equity-program";
export { EQUITY_TYPES, EQUITY_LABELS, EQUITY_FAMILIES, EQUITY_FAMILY_LABELS, EQUITY_STATUS };
const text=z.string().trim().min(1).max(1000);
export const equityMappingSchema=z.object({version:z.literal('equity-dossier-1'),sheet:z.string().optional(),headerRow:z.number().int().positive(),columns:z.object({key:text,amount:text,date:text}).strict(),equity:z.object({componentColumn:text,accountColumn:text,decisionColumn:text,kindColumn:text,effectiveColumn:text,transferColumn:text,currencyColumn:text,descriptionColumn:text}).strict(),delimiter:z.enum([';',',','\t']),decimal:z.enum([',','.']),dateFormat:z.enum(['ISO','DD/MM/YYYY']),sign:z.literal(1),currency:z.literal('EUR')}).strict();
export { equityDraftSchema, equityWorkSchema } from './equity-contract';
export type { EquityDraft, EquityWork } from './equity-contract';
import { equityDraftSchema, equityWorkSchema, type EquityDraft, type EquityWork } from './equity-contract';
export type EquityDatum={row:SourceRow;batch:ImportBatch;id:string;amount:Money;date:string;component:string;account:string;decisionId:string;kind:string;effectiveDate:string;transferId:string;description:string;proof:EvidenceLink};
export function equityData(scope:WorkpaperScope,period:AccountingPeriod,imports:ImportBatch[],runId:string){
 const result:EquityDatum[]=[];
 for(const b of imports){assertScope(scope,b.scope);if(!b.approval||!b.report.calculationAllowed)throw Error('EQUITY_IMPORT_UNAPPROVED');assertEquityBatch(b,period);for(const r of b.rows){const m=b.mapping.equity!,value=(column:string)=>r.original[column]?.trim()??'',body={scope,procedureId:runId,documentVersionId:b.document.id,rowId:r.id,locator:r.locator,precision:r.locator.page?'page' as const:'row' as const,status:b.document.format==='pdf'?'suggestion' as const:'verified' as const,purpose:EQUITY_LABELS[b.document.documentType]};result.push({row:r,batch:b,id:r.normalized!.key,amount:r.normalized!.amount,date:r.normalized!.date,component:value(m.componentColumn),account:value(m.accountColumn),decisionId:value(m.decisionColumn),kind:value(m.kindColumn),effectiveDate:value(m.effectiveColumn),transferId:value(m.transferColumn),description:value(m.descriptionColumn),proof:{id:'evidence-'+stableSha256(body),...body}});}}
 return result;
}
export function assertEquityBatch(batch:ImportBatch,period:AccountingPeriod){
 equityMappingSchema.parse(batch.mapping);if(!EQUITY_TYPES.includes(batch.document.documentType as typeof EQUITY_TYPES[number]))throw Error('EQUITY_SOURCE_TYPE_INVALID');
 const seen=new Set<string>();for(const r of batch.rows){if(!r.normalized||r.errors.length)throw Error('EQUITY_SOURCE_ROW_INVALID');assertScope(batch.scope,r.scope);if(seen.has(r.normalized.key))throw Error('EQUITY_SOURCE_DUPLICATE_ID');seen.add(r.normalized.key);cents(r.normalized.amount);const m=batch.mapping.equity!,get=(c:string)=>r.original[c]?.trim()??'';
 if(get(m.currencyColumn)!=='EUR')throw Error('EQUITY_CURRENCY_UNSUPPORTED');if(get(m.effectiveColumn)&&!isCivilDate(get(m.effectiveColumn)))throw Error('EQUITY_EFFECT_DATE_INVALID');if(r.normalized.date>period.asOfDate)throw Error('EQUITY_SOURCE_AFTER_REVIEW');
 if(batch.document.documentType==='equity_balances'&&(!['opening','closing'].includes(get(m.kindColumn))||r.normalized.date!==(get(m.kindColumn)==='opening'?period.startDate:period.closingDate)||!get(m.accountColumn)||!get(m.componentColumn)))throw Error('EQUITY_BALANCE_SCOPE_INVALID');
 if(['equity_ledger','equity_variation'].includes(batch.document.documentType)&&(!get(m.componentColumn)||!get(m.accountColumn)))throw Error('EQUITY_COMPONENT_MAPPING_REQUIRED');
 if(batch.document.documentType==='equity_ledger'&&!['decision','other'].includes(get(m.kindColumn)))throw Error('EQUITY_LEDGER_KIND_INVALID');
 if(batch.document.documentType==='equity_decisions'&&(!['increase','decrease','transfer','none'].includes(get(m.kindColumn))||!isCivilDate(get(m.effectiveColumn))||cents(r.normalized.amount)<0n))throw Error('EQUITY_DECISION_INVALID');
 if(batch.document.documentType==='equity_payments'&&(!get(m.decisionColumn)||cents(r.normalized.amount)<0n))throw Error('EQUITY_PAYMENT_ALLOCATION_REQUIRED');
 if(batch.document.format==='pdf'&&(!Number.isSafeInteger(r.locator.page)||r.locator.page!<1))throw Error('EQUITY_PDF_PAGE_INVALID');
 }
}
export function stampEquityWork(draft:EquityDraft,imports:ImportBatch[],scope:WorkpaperScope,period:AccountingPeriod,runId:string,actorId:string,at:string):EquityWork{
 const d=equityDraftSchema.parse(draft),data=equityData(scope,period,imports,runId),ids=new Set<string>(),accounts=new Set<string>();
 for(const c of d.components){if(ids.has(c.id))throw Error('EQUITY_COMPONENT_DUPLICATE');ids.add(c.id);if(c.state==='in_scope'&&!c.accounts.length)throw Error('EQUITY_COMPONENT_ACCOUNTS_REQUIRED');if(c.state==='not_applicable'&&(!c.reason.trim()||!data.some(r=>r.row.id===c.proofRowId)))throw Error('EQUITY_EXCLUSION_PROOF_REQUIRED');for(const a of c.accounts){if(accounts.has(a))throw Error('EQUITY_ACCOUNT_DUPLICATE');accounts.add(a);}}
 if(d.components.filter(c=>c.family==='capital').length!==1)throw Error('EQUITY_CAPITAL_GROUPING_REQUIRED');
 if(EQUITY_FAMILIES.some(f=>!d.components.some(c=>c.family===f)))throw Error('EQUITY_COMPONENT_INVENTORY_INCOMPLETE');
 if(d.method.proofRowIds.some(id=>!data.some(r=>r.row.id===id)))throw Error('EQUITY_METHOD_PROOF_REQUIRED');
 const decisions=data.filter(r=>r.batch.document.documentType==='equity_decisions'),read=new Set<string>();for(const i of d.interpretations){if(read.has(i.decisionId)||!decisions.some(r=>r.id===i.decisionId))throw Error('EQUITY_DECISION_READING_INVALID');read.add(i.decisionId);const p=data.find(r=>r.row.id===i.proofRowId);if(!p||!['equity_minutes','equity_acts'].includes(p.batch.document.documentType)||!p.row.locator.page)throw Error('EQUITY_PV_VERSION_PAGE_REQUIRED');}
 return frozen(equityWorkSchema.parse({...d,authorId:actorId,authoredAt:at}));
}
export async function previewEquityPdf(file:File,scope:WorkpaperScope,mapping:ImportMapping,actor:Principal,type:string,period:AccountingPeriod):Promise<ImportBatch>{
 authorize(actor,scope,'prepare');equityMappingSchema.parse(mapping);if(!['equity_minutes','equity_acts'].includes(type)||file.size>3*1024*1024||!file.size||!file.name.toLowerCase().endsWith('.pdf')||!['application/pdf','application/octet-stream',''].includes(file.type))throw Error('EQUITY_PDF_FORMAT_INVALID');
 const bytes=Buffer.from(await file.arrayBuffer());if(bytes.subarray(0,5).toString()!=='%PDF-')throw Error('EQUITY_PDF_SIGNATURE_INVALID');const pdf=await PDFDocument.load(bytes);if(pdf.getPageCount()>200)throw Error('EQUITY_PDF_PAGE_LIMIT');
 const byteHash=sha256(bytes),parserVersion='equity-pdf-index-1',documentId='source-'+stableSha256({scope,byteHash,type,parserVersion}),mappingHash=stableSha256(mapping),id='import-'+stableSha256({scope,byteHash,type,mappingHash,parserVersion}),m=mapping.equity!;
 const rows=pdf.getPages().map((_p,i):SourceRow=>({id:'row-'+stableSha256({documentId,page:i+1}),scope,documentVersionId:documentId,locator:{page:i+1},original:{[m.currencyColumn]:'EUR',[m.descriptionColumn]:'Page '+(i+1)+' — lecture humaine requise'},normalized:{key:'PAGE-'+(i+1),amount:money(0n),date:period.closingDate},errors:[]}));
 const base={id,scope,document:{id:documentId,scope,logicalId:type,fileName:file.name,format:'pdf' as const,documentType:type,byteHash,storageRef:documentId,sizeBytes:bytes.length,parserVersion},mapping,mappingHash,rows,report:{status:'accepted_with_warnings' as const,acceptedRows:rows.length,rejectedRows:0,duplicateRows:0,sourceTotal:unknown('PDF indexé sans extraction de montant'),normalizedTotal:money(0n),warnings:['Index des pages ; aucun montant ni approbation extrait du PDF.'],blocking:[],calculationAllowed:false}};
 return frozen({...base,previewHash:stableSha256(base)});
}
const plus=(values:Money[])=>money(values.reduce((n,v)=>n+cents(v),0n));
const supported=(values:EquityDatum[],date:string,amount?:Money):SupportedAmount=>({amount:amount??plus(values.map(v=>v.amount)),date,basis:'equity-EUR-signed',evidence:values.map(v=>v.proof)});
export function evaluateEquity(scope:WorkpaperScope,period:AccountingPeriod,imports:ImportBatch[],runId:string,population:Population,selection:SelectionSet,work:EquityWork){
 if(work.components.filter(c=>c.family==='capital').length!==1)throw Error('EQUITY_CAPITAL_GROUPING_REQUIRED');
 const data=equityData(scope,period,imports,runId),byType=(type:string)=>data.filter(r=>r.batch.document.documentType===type),ledger=byType('equity_ledger'),decisions=byType('equity_decisions'),balances=byType('equity_balances'),variation=byType('equity_variation'),payments=byType('equity_payments'),selected=new Set(selection.selectedIds),inPeriod=(d:string)=>period.startDate<=d&&d<=period.closingDate;
 const mapped=work.components.filter(c=>c.state==='in_scope'),components=mapped.map(c=>{
  const rows=balances.filter(r=>r.component===c.id&&c.accounts.includes(r.account)),opening=rows.filter(r=>r.kind==='opening'),closing=rows.filter(r=>r.kind==='closing'),moves=ledger.filter(r=>r.component===c.id&&c.accounts.includes(r.account)&&inPeriod(r.date)),tv=variation.filter(r=>r.component===c.id&&inPeriod(r.date));
  const completeAt=(kind:string)=>c.accounts.every(a=>rows.filter(r=>r.account===a&&r.kind===kind).length===1),movementComplete=work.ledgerCoverage==='documented'&&c.accounts.every(a=>tv.some(r=>r.account===a));
  const o=completeAt('opening')?known(plus(opening.map(r=>r.amount))):unknown('Ouverture incomplète par compte'),cl=completeAt('closing')?known(plus(closing.map(r=>r.amount))):unknown('Clôture incomplète par compte'),observed=plus(moves.map(r=>r.amount)),mv=movementComplete?known(observed):unknown('GL ou tableau de variation incomplet');
  const difference=o.kind==='known'&&cl.kind==='known'&&mv.kind==='known'?known(money(cents(cl.value)-cents(o.value)-cents(mv.value))):unknown('Pont de soldes non concluant');
  const variationDifference=movementComplete?known(money(cents(plus(tv.map(r=>r.amount)))-cents(observed))):unknown('Tableau de variation absent ou partiel');
  return {...c,opening:o,closing:cl,variation:mv,observedMovement:observed,difference,variationDifference,movements:moves,evidence:[...rows,...tv,...moves].map(r=>r.proof),complete:o.kind==='known'&&cl.kind==='known'&&mv.kind==='known'};
 });
 const unmapped=data.filter(r=>['equity_balances','equity_ledger','equity_variation'].includes(r.batch.document.documentType)).filter(r=>!mapped.some(c=>c.id===r.component&&c.accounts.includes(r.account))),complete=work.completeComponentSet&&components.length>0&&components.every(c=>c.complete)&&unmapped.length===0&&work.components.some(c=>c.family==='capital'&&c.state==='in_scope')&&work.components.some(c=>c.family==='reserves'&&c.state==='in_scope');
 const transferGroups=new Map<string,EquityDatum[]>();for(const m of ledger.filter(r=>r.transferId&&inPeriod(r.date))){transferGroups.set(m.transferId,[...(transferGroups.get(m.transferId)??[]),m]);}
 for(const group of transferGroups.values())if(group.length<2||new Set(group.map(r=>r.component)).size<2||cents(plus(group.map(r=>r.amount)))!==0n)throw Error('UNBALANCED_INTERNAL_TRANSFER');
 const allocations:EquityInput['allocations']=[],decisionRows=decisions.map(d=>{
  const relatedEntries=ledger.filter(l=>l.decisionId===d.id),entries=relatedEntries.filter(l=>inPeriod(l.date)),settlements=payments.filter(p=>p.decisionId===d.id),reading=work.interpretations.find(i=>i.decisionId===d.id),pv=reading?data.find(r=>r.row.id===reading.proofRowId):undefined,readProof=pv?{...pv.proof,status:'verified' as const,purpose:'Lecture humaine : '+reading!.note}:undefined;
  const grossBooked=plus(entries.map(e=>e.amount)),bookedValue=d.kind==='decrease'?money(-cents(grossBooked)):d.kind==='transfer'?plus(entries.filter(e=>cents(e.amount)>0n).map(e=>e.amount)):grossBooked;
  const decisionAmount=readProof?{amount:d.amount,date:d.date,basis:'equity-decision-EUR',evidence:[d.proof,readProof]}:null,booked=entries.length?{...supported(entries,entries[0].date,bookedValue),basis:'equity-decision-EUR'}:null;
  const statuses:string[]=[];if(!selected.has(d.row.id))statuses.push('not_tested');else if(!inPeriod(d.effectiveDate))statuses.push('outside');else {if(!readProof)statuses.push('missing_minutes');if(!entries.length)statuses.push(work.ledgerCoverage==='documented'&&readProof&&d.kind!=='none'?'decision_unbooked':'inconclusive');else if(readProof){if(work.ledgerCoverage!=='documented')statuses.push('inconclusive');else if(d.kind==='transfer'){const t=new Set(entries.map(e=>e.transferId).filter(Boolean));if(!t.size||entries.some(e=>!e.transferId)||cents(grossBooked)!==0n)statuses.push('inconclusive');else statuses.push(cents(bookedValue)===cents(d.amount)?'transfer':'divergent');}else if(d.kind==='none')statuses.push(cents(grossBooked)===0n?'matched':'divergent');else statuses.push(cents(bookedValue)===cents(d.amount)?'matched':'divergent');}}
  const difference=inPeriod(d.effectiveDate)&&decisionAmount&&booked&&work.ledgerCoverage==='documented'&&selected.has(d.row.id)?known(money(cents(booked.amount)-cents(d.amount))):unknown('Lecture, écriture, sélection ou période insuffisante');
  allocations.push({id:d.id,decision:selected.has(d.row.id)?decisionAmount:null,booked:selected.has(d.row.id)&&work.ledgerCoverage==='documented'?booked:null,payment:settlements.length?supported(settlements,settlements[0].date):null,decisionReference:pv?.batch.document.id??'',readingValidated:!!pv,effectiveDate:d.effectiveDate});
  return {id:d.id,description:d.description,component:d.component,kind:d.kind,decisionDate:d.date,effectiveDate:d.effectiveDate,amount:d.amount,booked:booked&&work.ledgerCoverage==='documented'?known(booked.amount):unknown(work.ledgerCoverage==='documented'?'Écriture non trouvée dans le GL fourni':'GL partiel — comptabilisation totale non concluante'),difference,payments:settlements.map(p=>({id:p.id,amount:p.amount,date:p.date,proof:p.proof})),movementIds:entries.map(e=>e.id),bookings:relatedEntries.map(e=>({id:e.id,date:e.date,amount:e.amount,inPeriod:inPeriod(e.date),proof:e.proof})),statuses,evidence:[d.proof,...relatedEntries.map(e=>e.proof),...settlements.map(p=>p.proof),...(readProof?[readProof]:[])],pv:pv?{documentVersionId:pv.batch.document.id,rowId:pv.row.id,page:pv.row.locator.page!,fileName:pv.batch.document.fileName,format:pv.batch.document.format}:null};
 });
 const orphans=ledger.filter(l=>selected.has(l.row.id)&&l.kind==='decision'&&(!l.decisionId||!decisions.some(d=>d.id===l.decisionId))).map(l=>({...l,status:work.decisionsCoverage==='documented'?'entry_undecided':'inconclusive'}));
 const engineComponents=components.filter(c=>c.complete).map(c=>({id:c.id,accounts:c.accounts,opening:supported(balances.filter(r=>r.component===c.id&&c.accounts.includes(r.account)&&r.kind==='opening'),period.startDate),closing:supported(balances.filter(r=>r.component===c.id&&c.accounts.includes(r.account)&&r.kind==='closing'),period.closingDate),movements:c.movements.map(m=>({id:m.id,internalTransferId:m.transferId&&transferGroups.get(m.transferId)?.every(t=>components.find(c=>c.id===t.component)?.complete)?m.transferId:undefined,value:supported([m],m.date)}))}));
 const technical=reviewEquity({context:{scope,period,purpose:scope.mode==='real'?'real':'synthetic_technical',procedure:'equity.review'},components:engineComponents,allocations,events:decisionRows.map(d=>({id:d.id,effectiveDate:d.effectiveDate,description:d.description||d.id,evidence:d.evidence,review:'pending',accountingMovementId:d.movementIds[0]??null})),coverageComplete:complete,capitalComponentId:work.components.find(c=>c.family==='capital')!.id,reserveComponentIds:work.components.filter(c=>c.family==='reserves').map(c=>c.id)});
 const exceptions=decisionRows.flatMap(d=>d.statuses.filter(s=>!['matched','transfer','not_tested'].includes(s)).map(s=>({id:d.id+':'+s,targetId:d.id,status:s,text:EQUITY_STATUS[s]+' : '+d.id,amount:d.difference})));for(const o of orphans)exceptions.push({id:o.id+':orphan',targetId:o.id,status:o.status,text:EQUITY_STATUS[o.status]+' : '+o.id,amount:unknown('Décision non documentée')});
 for(const c of components)if(!c.complete||c.difference.kind==='known'&&cents(c.difference.value)!==0n||c.variationDifference.kind==='known'&&cents(c.variationDifference.value)!==0n)exceptions.push({id:c.id+':bridge',targetId:c.id,status:'inconclusive',text:'Composante incomplète ou pont divergent : '+c.label,amount:c.difference});
 for(const u of unmapped)exceptions.push({id:u.row.id+':mapping',targetId:u.id,status:'inconclusive',text:'Compte ou composante hors cartographie : '+u.account,amount:unknown('Cartographie à compléter')});
 if(!complete)exceptions.push({id:'inventory',targetId:'inventory',status:'inconclusive',text:'Cartographie des capitaux propres incomplète — total et ratios non concluants',amount:unknown('Cartographie ou sources incomplètes')});
 const evidence=[...new Map([...components.flatMap(c=>c.evidence),...decisionRows.flatMap(d=>d.evidence),...orphans.map(o=>o.proof),...data.filter(d=>work.method.proofRowIds.includes(d.row.id)).map(d=>d.proof)].map(p=>[p.id,p])).values()];
 const total=(field:'opening'|'closing'|'variation'):KnownAmount=>complete?known(plus(components.map(c=>(c[field] as {kind:'known';value:Money}).value))):unknown('Périmètre déclaré ou données incomplets');
 const controls=[{label:'Composantes avec ouverture, GL, variation et clôture',numerator:components.filter(c=>c.complete).length,denominator:components.length,unit:'composantes'},{label:'Décisions comparables à leurs écritures',numerator:decisionRows.filter(d=>d.difference.kind==='known').length,denominator:decisionRows.length,unit:'décisions'},{label:'Mouvements appelant une décision documentée',numerator:ledger.filter(l=>l.kind==='decision'&&selected.has(l.row.id)&&decisions.some(d=>d.id===l.decisionId)).length,denominator:ledger.filter(l=>l.kind==='decision').length,unit:'mouvements'},{label:'Décisions avec citation de pièce/version/page',numerator:decisionRows.filter(d=>d.pv&&selected.has(decisions.find(x=>x.id===d.id)!.row.id)).length,denominator:decisionRows.length,unit:'décisions'}];
 return frozen({schemaVersion:'equity-result-1' as const,scope,period,runId,work,components,unmapped,decisions:decisionRows,orphans,transfers:[...transferGroups].map(([id,rows])=>({id,movementIds:rows.map(r=>r.id),amount:money(0n),label:'Transfert interne équilibré — aucun effet sur le total'})),totals:{opening:total('opening'),closing:total('closing'),variation:total('variation')},ratios:technical.ratios,legalConclusion:unknown('Aucune règle juridique implémentée ; forme sociale et période à instruire'),technical,controls,exceptions,evidence,coverage:{selected:selection.selectedIds.length,denominator:population.items.length,exclusions:selection.exclusions,unit:'décisions et mouvements'},limitations:['Cartographie interne déclarée ; aucune limitation au compte 10 et aucune classification légale automatique.','Le GL, le registre des décisions et le tableau de variation doivent documenter leur périmètre ; les pièces manquantes restent inconnues.','Décision, date d’effet, comptabilisation et règlement sont distincts.','Une lecture humaine cite la pièce versionnée et sa page ; elle ne certifie pas son authenticité.','Les ratios ne valent aucune conclusion juridique.','Montants EUR uniquement ; aucun envoi, aucune écriture automatique.']});
}
export type EquityResult=ReturnType<typeof evaluateEquity>;
