import { sql } from 'drizzle-orm';
import { ApiError } from '@/lib/api/errors';
import type { AccountingPeriod } from '@/lib/canonical-model/period';
import { ClientsRuntime } from './clients-runtime';
import { ClientsImports, ClientsWorkpaperRepository, rows, scopeWhere, type ClientsSql } from './clients-persistence';
import { EQUITY_TYPES, assertEquityBatch, previewEquityPdf, stampEquityWork, equityData, type EquityResult } from './equity-dossier';
import { EquityRegistry, EQUITY_TEMPLATE } from './equity-adapter';
import { WorkpaperService } from './service';
import { freezePopulation, selectPopulation } from './selection';
import { periodId, type WorkpaperRun, type WorkpaperScope } from './model';
import type { ImportBatch, ImportMapping } from './imports';
import type { Principal } from './policy';
import type { EquityCommand } from './equity-commands';
import { buildEquityMission } from './equity-mission';
import { buildEquityPackage } from '@/lib/evidence/equity-package';
export class EquityRuntime extends ClientsRuntime {
 protected override readonly procedureIds=['equity.review'];
 protected override readonly sourceTypes=EQUITY_TYPES;
 protected override importAdapter(): 'equity.review' {return 'equity.review';}
 protected override validateSource(batch:ImportBatch,period:AccountingPeriod){assertEquityBatch(batch,period);}
 protected override makePreview(file:File,scope:WorkpaperScope,mapping:ImportMapping,actor:Principal,type:string,period:AccountingPeriod){return file.name.toLowerCase().endsWith('.pdf')?previewEquityPdf(file,scope,mapping,actor,type,period):super.makePreview(file,scope,mapping,actor,type,period);}
 async previewEquity(request:Request,dossierId:string,period:AccountingPeriod,file:File,mapping:ImportMapping,type:typeof EQUITY_TYPES[number],key:string){return this.previewSource(request,dossierId,period,file,mapping,type,key);}
 async equityRead(request:Request,dossierId:string,pid:string,id?:string,history=false,version?:number){const view=await super.read(request,dossierId,pid,id,history,version);const facts=await this.transaction(request,dossierId,pid,'read',async(tx,scope)=>{const imports=await ClientsImports.load(tx,scope);return Object.fromEntries(view.runs.map(run=>{const ids=run.importIds.length?run.importIds:view.sourceHeads.map(h=>h.import_id),batches=imports.batches.filter(b=>ids.includes(b.id)&&b.approval&&this.sourceTypes.includes(b.document.documentType as typeof EQUITY_TYPES[number]));return[run.id,equityData(scope,run.period,batches,run.id).map(d=>({id:d.id,rowId:d.row.id,type:d.batch.document.documentType,documentVersionId:d.batch.document.id,version:d.batch.document.byteHash,fileName:d.batch.document.fileName,page:d.row.locator.page,component:d.component,account:d.account,description:d.description,format:d.batch.document.format,amount:d.amount,date:d.date}))];}));});const response={...view,facts};if(Buffer.byteLength(JSON.stringify(response))>8*1024*1024)throw new ApiError('EQUITY_STATE_LIMIT','État trop volumineux.',413);return response;}
 async equityCommand(request:Request,dossierId:string,pid:string,command:EquityCommand,key:string){return this.transaction(request,dossierId,pid,['review','lock'].includes(command.command)?'review':'prepare',async(tx,scope,actor)=>this.receipt(tx,scope,actor,key,{operation:'equity_command',...command},async()=>{
  const repository=new ClientsWorkpaperRepository(tx),imports=await ClientsImports.load(tx,scope),at=new Date(this.now()*1000).toISOString(),service=new WorkpaperService(repository,imports,new EquityRegistry(),async()=>actor,()=>at,'equity.review');
  if(command.command==='create_equity'){if(periodId(command.period)!==pid)throw Error('WORKPAPER_PERIOD_INVALID');return{run:await service.create(scope,command.period,EQUITY_TEMPLATE,command.instanceKey)};}
  const current=await repository.get(scope,command.id);if(!current||current.template.id!=='equity.review')throw Error('WORKPAPER_NOT_FOUND');const[latest]=await rows<{id:string}>(tx,sql`SELECT h.id FROM clients_workpaper_heads h JOIN clients_workpaper_versions v USING (organization_id,dossier_id,period_id,id,version) WHERE h.organization_id=${scope.organizationId} AND h.dossier_id=${scope.dossierId} AND h.period_id=${scope.periodId} AND v.run->>'rootId'=${current.rootId} ORDER BY (v.run->>'revision')::int DESC LIMIT 1`);if(latest?.id!==current.id)throw Error('EQUITY_REVISION_REPLACED');if(command.command!=='revise')await this.assertCurrent(tx,scope,current);
  const id=current.id,v=command.expectedVersion;let run:WorkpaperRun;
  const cite=(citation:{documentVersionId:string;rowId:string;page?:number},text:string)=>{const b=imports.batches.find(b=>current.importIds.includes(b.id)&&b.approval&&b.document.id===citation.documentVersionId),r=b?.rows.find(r=>r.id===citation.rowId);if(!b||!r||r.errors.length||(citation.page!==undefined&&citation.page!==r.locator.page)||(b?.document.format==='pdf'&&citation.page!==r?.locator.page))throw Error('EQUITY_CITATION_VERSION_INVALID');return text+'\nPièce : '+b.document.fileName+' ; version '+b.document.byteHash+' ; document '+b.document.id+' ; '+(r.locator.page?'page '+r.locator.page:'ligne '+r.locator.row);};
  switch(command.command){
   case 'freeze_equity':{if(current.state!=='draft'||current.population)throw Error('INPUTS_ALREADY_FROZEN');const heads=await this.heads(tx,scope),batches=command.importIds.map(i=>imports.get(scope,i,actor));if(batches.some(b=>!this.sourceTypes.includes(b.document.documentType as typeof EQUITY_TYPES[number])||!heads.some(h=>h.import_id===b.id)))throw Error('EQUITY_CURRENT_SOURCES_REQUIRED');const work=stampEquityWork(command.draft,batches,scope,current.period,id,actor.id,at);run=await service.configureEquity(scope,id,v,work);const population=freezePopulation(scope,batches,'equity_decision_movement',actor),selected=command.selectedIds??population.items.filter(i=>!command.excluded.some(e=>e.id===i.id)).map(i=>i.id),selection=selectPopulation(population,{method:'targeted',criteria:command.criteria,exclusions:command.excluded,requestedSize:selected.length,selectedIds:selected},actor);run=await service.attachInputs(scope,id,run.version,population,selection);for(const b of batches)run=await service.addEvidence(scope,id,run.version,b.id,b.rows[0].id,'Source approuvée du dossier de décisions');run=await service.transition(scope,id,run.version,'ready');break;}
   case 'configure_equity':{if(!current.population)throw Error('EQUITY_FROZEN_INPUTS_REQUIRED');run=await service.configureEquity(scope,id,v,stampEquityWork(command.draft,current.importIds.map(i=>imports.get(scope,i,actor)),scope,current.period,id,actor.id,at));break;}
   case 'execute':{if(!current.equityWork)throw Error('EQUITY_WORK_REQUIRED');run=await service.execute(scope,id,v,{work:current.equityWork,runId:id});if(run.state==='executed')for(const e of (run.result!.result as EquityResult).exceptions)run=await service.addNote(scope,id,run.version,{id:'equity:'+e.id,kind:'observation',text:e.text,amount:e.amount,blocking:true});break;}
   case 'resolve':run=await service.resolveNote(scope,id,v,command.noteId,cite(command.citation,command.text));break;
   case 'conclude':run=await service.conclude(scope,id,v,cite(command.citation,command.text));break;
   case 'review':run=await service.transition(scope,id,v,command.decision,cite(command.citation,command.text),command.submittedHash);break;
   case 'submit':run=await service.transition(scope,id,v,'awaiting_review');break;
   case 'lock':run=await service.lock(scope,id,v);break;
   case 'revise':run=await service.revise(scope,id,v);break;
  }return{run};
 }));}
 private async equityData(tx:ClientsSql,scope:WorkpaperScope,selection:{id?:string;version?:number}){const[size]=await rows<{count:string;bytes:string}>(tx,sql`SELECT count(*)::text AS count,coalesce(sum(octet_length(run::text)),0)::text AS bytes FROM clients_workpaper_versions WHERE ${scopeWhere(scope)}`);const[sourceSize]=await rows<{bytes:string}>(tx,sql`SELECT coalesce(sum(octet_length(preview::text)+octet_length(original_base64)),0)::text AS bytes FROM clients_imports WHERE ${scopeWhere(scope)}`);if(Number(size.count)>500||Number(size.bytes)>24*1024*1024||Number(sourceSize.bytes)>24*1024*1024)throw new ApiError('EQUITY_STATE_LIMIT','Historique ou sources trop volumineux.',413);const imports=await ClientsImports.load(tx,scope),versions=(await rows<{run:WorkpaperRun}>(tx,sql`SELECT run FROM clients_workpaper_versions WHERE ${scopeWhere(scope)} ORDER BY id,version`)).map(r=>r.run),heads=await this.heads(tx,scope),batches=imports.batches.filter(b=>this.sourceTypes.includes(b.document.documentType as typeof EQUITY_TYPES[number])),mission=buildEquityMission(scope,versions,batches,heads,selection);if(Buffer.byteLength(JSON.stringify(mission))>8*1024*1024)throw new ApiError('EQUITY_STATE_LIMIT','Synthèse trop volumineuse.',413);return{mission,imports:batches,run:mission.run};}
 async equityMission(request:Request,dossierId:string,pid:string,selection:{id?:string;version?:number}={}){return this.transaction(request,dossierId,pid,'read',async(tx,scope,actor)=>({actorId:actor.id,permissions:actor.grants[0].permissions,mission:(await this.equityData(tx,scope,selection)).mission}));}
 async equityExport(request:Request,dossierId:string,pid:string,selection:{id?:string;version?:number},kind:'diagnostic'|'approved',expectedSnapshotHash:string){const data=await this.transaction(request,dossierId,pid,'download',async(tx,scope)=>{const d=await this.equityData(tx,scope,selection);if(d.mission.hash!==expectedSnapshotHash)throw Error('EXPORT_SNAPSHOT_CONFLICT');return d;});const pack=await buildEquityPackage(data.mission,data.run,data.imports,kind,data.run?.events.at(-1)?.at??'1970-01-01T00:00:00.000Z');await this.transaction(request,dossierId,pid,'download',async(tx,scope)=>{if((await this.equityData(tx,scope,selection)).mission.hash!==expectedSnapshotHash)throw Error('EXPORT_SNAPSHOT_CONFLICT');});return pack;}
 async proof(request:Request,dossierId:string,pid:string,documentId:string){return this.transaction(request,dossierId,pid,'download',async(tx,scope,actor)=>{const imports=await ClientsImports.load(tx,scope),batch=imports.batches.find(b=>b.document.id===documentId&&b.approval&&['equity_minutes','equity_acts'].includes(b.document.documentType)&&b.document.format==='pdf');if(!batch)throw Error('SOURCE_NOT_FOUND');return{bytes:imports.download(scope,documentId,actor)!,fileName:batch.document.fileName};});}
}
