import { assertScope, contentHash, type WorkpaperRun, type WorkpaperScope } from './model';
import type { ImportBatch } from './imports';
import type { EquityResult } from './equity-dossier';
import { equityEventTarget } from './equity-program';
import { stableSha256 } from '@/lib/synthesis/canonical';
export function buildEquityMission(scope:WorkpaperScope,runs:WorkpaperRun[],imports:ImportBatch[],heads:{document_type:string;import_id:string}[],selection:{id?:string;version?:number}={}){
 const versions=runs.filter(r=>r.template.id==='equity.review').map(r=>{assertScope(scope,r.scope);return r;}).sort((a,b)=>b.revision-a.revision||b.version-a.version),roots=new Set(versions.map(r=>r.rootId));
 const run=selection.id?versions.find(r=>r.id===selection.id&&(selection.version===undefined||r.version===selection.version)):roots.size===1?versions[0]:undefined;
 const current=run?versions.filter(r=>r.rootId===run.rootId)[0]:undefined,result=run?.result?.execution==='completed'?run.result.result as EquityResult:undefined,stale=!!run&&(current?.id!==run.id||current.version!==run.version||run.importIds.some(id=>!heads.some(h=>h.import_id===id)));
 const sources=imports.filter(i=>run?.importIds.includes(i.id)).map(i=>({id:i.document.id,importId:i.id,fileName:i.document.fileName,version:i.document.byteHash,parserVersion:i.document.parserVersion,mappingVersion:i.mapping.version,approvedBy:i.approval?.actorId,approvedAt:i.approval?.at,current:heads.some(h=>h.import_id===i.id),format:i.document.format,rows:i.rows.length,originalInPackage:false}));
 const queue=[...(!run?[{id:'unprepared',kind:'blocked',text:roots.size>1?'Plusieurs dossiers de travail : choisir une feuille':'Dossier de décisions à préparer',href:'/equity?'+new URLSearchParams({dossierId:scope.dossierId,periodId:scope.periodId})}]:[]),...(stale?[{id:'stale',kind:'stale',text:'Version ou source remplacée — nouvelle révision requise',href:'/equity?'+new URLSearchParams({dossierId:scope.dossierId,periodId:scope.periodId,id:current!.id})}]:[]),...(result?.exceptions.map(e=>({id:e.id,kind:e.status,text:e.text,href:'/equity?'+new URLSearchParams({dossierId:scope.dossierId,periodId:scope.periodId,id:run!.id,version:String(run!.version),event:equityEventTarget(e),filter:e.status})}))??[]),...(run?.state==='awaiting_review'?[{id:'review',kind:'review',text:'Revue par une autre identité autorisée attendue',href:'/equity?'+new URLSearchParams({dossierId:scope.dossierId,periodId:scope.periodId,id:run.id,version:String(run.version),tab:'review'})}]:[])];
 const body={schemaVersion:'equity-mission-1' as const,scope,run:run??null,current:current?{id:current.id,version:current.version}:null,versions:versions.map(v=>({id:v.id,version:v.version,revision:v.revision,state:v.state,authorId:v.events.at(-1)?.actorId??v.preparedBy})),result:result??null,stale,sources,queue,program:{procedures:1,controls:4},approved:!!run&&run.state==='locked'&&!stale&&run.approval?.snapshotHash===contentHash(run),limitations:result?.limitations??['Dossier non exécuté ; aucune conclusion juridique.']};return {...body,hash:stableSha256(body)};
}
export type EquityMission=ReturnType<typeof buildEquityMission>;
