import { contentHash, type WorkpaperRun } from './model';
import type { ExceptionalResult } from './exceptional-dossier';
const esc = (v: unknown) => String(v ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
export function exceptionalDiagnostic(run: WorkpaperRun) {
    const result = run.result?.result as ExceptionalResult | undefined;
    if (!result || result.schemaVersion !== 'exceptional-result-1')
        throw Error('EXCEPTIONAL_RESULT_REQUIRED');
    const table = (headers: string[], rows: unknown[][]) => '<table><thead><tr>' + headers.map(x => '<th>' + esc(x) + '</th>').join('') + '</tr></thead><tbody>' + rows.map(r => '<tr>' + r.map(v => '<td>' + esc(v) + '</td>').join('') + '</tr>').join('') + '</tbody></table>';
    const body = result.rows.map(r => '<section><h2>' + esc(r.label) + '</h2><p>' + esc(r.status) + ' ; ' + esc(r.entry.decision?.reason ?? 'Décision humaine requise') + '</p>' + table(['Écriture', 'Compte actuel', 'Montant EUR signé', 'Qualification proposée', 'Motif'], r.lines.map(l => [l.piece, l.account, l.amount.amount, l.proposed ?? 'Bloquée', l.reason])) + '<p>' + esc(r.issues.join(' ; ')) + '</p><h3>Pièces client</h3>' + table(['Document', 'Pack', 'Date', 'Page', 'Ligne', 'Version locale'], r.support.map(f => [f.details.title, f.details.pack, f.details.documentDate, f.details.page ?? 'Non disponible', f.line, f.version])) + '<h3>Comparatif historique</h3><p>' + esc(JSON.stringify(r.comparison)) + '</p></section>').join('');
    const official = result.facts.filter(f => f.type === 'exceptional_rules'), html = '<!doctype html><html lang="fr"><meta charset="utf-8"><title>PROBANT · Résultat exceptionnel</title><style>body{font:14px/1.5 system-ui;margin:30px;color:#17243b}table{border-collapse:collapse;width:100%;margin:14px 0}th,td{padding:8px;border-bottom:1px solid #aab5c4;text-align:left;overflow-wrap:anywhere}section{break-inside:avoid;margin:24px 0}@media print{body{margin:0}}</style><h1>Résultat exceptionnel · dossier de qualification</h1><p>' + esc(run.scope.dossierId) + ' ; version ' + run.version + ' ; état ' + esc(run.state) + ' ; ' + esc(run.period.startDate) + ' à ' + esc(run.period.closingDate) + '</p><p>Diagnostic de revue. GL inchangé. Un hash local ne constitue pas une signature. Aucun avis sur les comptes.</p><h2>Sources officielles</h2>' + table(['Document', 'Organisme', 'URL', 'Section et version', 'Pack', 'Date / consultation', 'Page'], official.map(f => [f.details.title, f.details.organization, f.details.url, f.details.section + ' ; ' + f.details.version, f.details.pack, f.details.documentDate + ' / ' + f.details.consultedOn, f.details.page ?? 'Non disponible'])) + '<p>' + esc(result.gate.issues.join(' ; ')) + '</p>' + body + '<h2>Pont de présentation</h2>' + table(['Destination', 'Avant', 'Après décisions éligibles', 'Variation'], Object.keys(result.bridge.before).map(d => [d, result.bridge.before[d].amount, result.bridge.after[d].amount, result.bridge.deltas[d].amount])) + '<p>' + esc(result.bridge.label) + ' ; présentation ' + (result.bridge.complete ? 'complète sur la population sélectionnée' : 'partielle') + ' ; total préservé ' + result.bridge.totalPreserved + '</p><h2>Documentation</h2><p>' + esc(run.exceptionalWork?.documentation) + '</p><p>Empreinte locale : ' + esc(contentHash(run)) + '</p></html>';
    return { html, json: JSON.stringify({ schemaVersion: 'exceptional-diagnostic-1', run, result, hash: contentHash(run), limits: ['GL original intact', 'Diagnostic sans originaux ni signature', 'Qualification soumise aux sources et à une revue distincte'] }, null, 2) };
}
