import { z } from 'zod';
import { cents, money, type Money } from '@/lib/canonical-model/money';
import type { AccountingPeriod } from '@/lib/canonical-model/period';
import { stableSha256 } from '@/lib/synthesis/canonical';
import { assertScope, frozen, moneySchema, type EvidenceLink, type WorkpaperScope, type Population, type SelectionSet } from './model';
import type { ImportBatch, ImportMapping } from './imports';
import { dateSchema, type SupportedAmount } from './cycle-review';
import { reviewInvestment, type InvestmentInput, type InvestmentModel } from './investments';
export const INVESTMENT_TYPES=['investment_register','investment_rights','investment_distributions','investment_ledger','investment_receipts','investment_carrying','investment_models'] as const;
export const INVESTMENT_LABELS:Record<string,string>={investment_register:'Registre de titres',investment_rights:'Catégories de droits',investment_distributions:'Décisions de distribution',investment_ledger:'Produits enregistrés / GL',investment_receipts:'Encaissements',investment_carrying:'Coût et dépréciation',investment_models:'Modèles externes versionnés'};
const text=z.string().trim().min(1).max(2000),ref=z.string().min(1).max(200);
export const investmentMappingSchema=z.object({version:z.literal('investment-review-1'),sheet:z.string().optional(),headerRow:z.number().int().positive(),columns:z.object({key:text,amount:text,date:text}).strict(),delimiter:z.enum([';',',','\t']),decimal:z.enum([',','.']),dateFormat:z.enum(['ISO','DD/MM/YYYY']),sign:z.literal(1),currency:z.literal('EUR')}).strict();
export const INVESTMENT_MAPPING:ImportMapping={version:'investment-review-1',headerRow:1,columns:{key:'Key',amount:'Amount',date:'Date'},delimiter:';',decimal:'.',dateFormat:'ISO',sign:1,currency:'EUR'};
const baseSchema=z.object({kind:z.enum(['cost','net_carrying']),label:text,perimeter:text}).strict();
const nature=z.enum(['enterprise_value','equity_value','holding_value']);
const metadata:Record<string,z.ZodType>={
 investment_register:z.object({securityId:text,label:text,intention:text,categoryProposed:text,accountingBase:baseSchema}).strict(),
 investment_rights:z.object({securityId:text,distributionId:text,classId:text,from:dateSchema,to:dateSchema,entitlementDate:dateSchema,numerator:z.string().regex(/^\d+$/),denominator:z.string().regex(/^[1-9]\d*$/),homogeneous:z.boolean(),basis:text,allocationReason:text.optional()}).strict(),
 investment_distributions:z.object({securityId:text,entitlementDate:dateSchema,basis:text}).strict(),
 investment_ledger:z.object({securityId:text,distributionId:text,basis:text}).strict(),
 investment_receipts:z.object({securityId:text,distributionId:text,basis:text}).strict(),
 investment_carrying:z.object({securityId:text,kind:z.enum(['cost','impairment']),basis:text}).strict(),
 investment_models:z.object({securityId:text,id:text,version:text,nature,originNature:nature,perimeter:text,basis:text,assumptions:z.array(text).max(100),scenarios:z.array(z.object({label:text,amount:moneySchema,date:dateSchema,basis:text}).strict()).max(50)}).strict()
};
export type InvestmentFact={rowId:string;documentVersionId:string;fileName:string;pack:string;version:string;sourceDate:string;line?:number;sheet?:string;type:string;id:string;date:string;amount:Money;details:Record<string,unknown>;proof:EvidenceLink};
export function assertInvestmentBatch(b:ImportBatch,period:AccountingPeriod){
 investmentMappingSchema.parse(b.mapping);if(!INVESTMENT_TYPES.includes(b.document.documentType as typeof INVESTMENT_TYPES[number]))throw Error('INVESTMENT_SOURCE_TYPE_INVALID');
 const ids=new Set<string>();for(const r of b.rows){assertScope(b.scope,r.scope);if(!r.normalized||r.errors.length||ids.has(r.normalized.key))throw Error('INVESTMENT_SOURCE_ROW_INVALID');ids.add(r.normalized.key);if(r.normalized.date>period.asOfDate)throw Error('INVESTMENT_SOURCE_AFTER_REVIEW');metadata[b.document.documentType].parse(JSON.parse(r.original.Details??''));}
}
export function investmentFacts(scope:WorkpaperScope,period:AccountingPeriod,batches:ImportBatch[],runId:string){
 const facts:InvestmentFact[]=[];for(const b of batches){assertScope(scope,b.scope);assertInvestmentBatch(b,period);if(!b.approval||!b.report.calculationAllowed)throw Error('INVESTMENT_IMPORT_UNAPPROVED');for(const r of b.rows){const proof:EvidenceLink={id:'proof-'+stableSha256({runId,document:b.document.id,row:r.id}),scope,procedureId:runId,documentVersionId:b.document.id,rowId:r.id,locator:r.locator,precision:'row',status:'verified',purpose:INVESTMENT_LABELS[b.document.documentType]};facts.push({rowId:r.id,documentVersionId:b.document.id,fileName:b.document.fileName,pack:b.document.logicalId,version:b.document.byteHash,sourceDate:r.normalized!.date,line:r.locator.row,sheet:r.locator.sheet,type:b.document.documentType,id:r.normalized!.key,date:r.normalized!.date,amount:r.normalized!.amount,details:metadata[b.document.documentType].parse(JSON.parse(r.original.Details)) as Record<string,unknown>,proof});}}
 return facts;
}
const entrySchema=z.object({registerRowId:ref,distributionRowId:ref.nullable(),rightsRowId:ref.nullable(),ledgerIds:z.array(ref).max(500),receiptIds:z.array(ref).max(500),costRowId:ref.nullable(),impairmentRowId:ref.nullable(),modelRowId:ref.nullable(),previousModelRowId:ref.nullable(),decision:z.object({category:text,reason:text,proposedAmount:moneySchema.optional(),citationRowId:ref,date:dateSchema}).strict().nullable()}).strict();
export const investmentDraftSchema=z.object({schemaVersion:z.literal('investment-review-1'),entries:z.array(entrySchema).min(1).max(2000)}).strict();
export type InvestmentDraft=z.infer<typeof investmentDraftSchema>;
export const investmentWorkSchema=investmentDraftSchema.extend({authorId:text,authoredAt:z.string().datetime()}).strict();
export type InvestmentWork=z.infer<typeof investmentWorkSchema>;
export function initialInvestmentDraft(facts:InvestmentFact[]):InvestmentDraft{
 const entries:InvestmentDraft['entries']=[];
 for(const register of facts.filter(f=>f.type==='investment_register')){
  const same=facts.filter(f=>f.details.securityId===register.details.securityId),distributions=same.filter(f=>f.type==='investment_distributions');
  for(const distribution of distributions.length?distributions:[null]){const find=(type:string,kind?:string)=>{const options=same.filter(f=>f.type===type&&(!kind||f.details.kind===kind));return options.length===1?options[0].rowId:null;},related=(f:InvestmentFact)=>f.details.distributionId===distribution?.id;entries.push({registerRowId:register.rowId,distributionRowId:distribution?.rowId??null,rightsRowId:(()=>{const options=same.filter(f=>f.type==='investment_rights'&&related(f));return options.length===1?options[0].rowId:null;})(),ledgerIds:same.filter(f=>f.type==='investment_ledger'&&related(f)).map(f=>f.rowId),receiptIds:same.filter(f=>f.type==='investment_receipts'&&related(f)).map(f=>f.rowId),costRowId:find('investment_carrying','cost'),impairmentRowId:find('investment_carrying','impairment'),modelRowId:null,previousModelRowId:null,decision:null});}
 }
 return {schemaVersion:'investment-review-1',entries};
}
export function investmentInput(scope:WorkpaperScope,period:AccountingPeriod,facts:InvestmentFact[],entry:InvestmentDraft['entries'][number]):InvestmentInput{
 const get=(id:string|null,type:string)=>{if(!id)return null;const f=facts.find(f=>f.rowId===id&&f.type===type);if(!f)throw Error('INVESTMENT_BINDING_INVALID');return f;};
 const register=get(entry.registerRowId,'investment_register')!;const securityId=register.details.securityId as string;
 const scoped=(f:InvestmentFact|null)=>{if(f&&f.details.securityId!==securityId)throw Error('INVESTMENT_BINDING_SCOPE_MISMATCH');return f;};
 const d=scoped(get(entry.distributionRowId,'investment_distributions')),r=scoped(get(entry.rightsRowId,'investment_rights')),cost=scoped(get(entry.costRowId,'investment_carrying')),impairment=scoped(get(entry.impairmentRowId,'investment_carrying'));
 if(cost&&cost.details.kind!=='cost'||impairment&&impairment.details.kind!=='impairment')throw Error('INVESTMENT_COST_KIND_INVALID');
 const amount=(f:InvestmentFact|null):SupportedAmount|null=>f?{amount:f.amount,date:f.date,basis:(f.details.basis as string)??securityId,evidence:[f.proof]}:null;
 const aggregate=(ids:string[],type:string)=>{if(!ids.length)return null;if(new Set(ids).size!==ids.length)throw Error('INVESTMENT_DUPLICATE_BINDING');const rows=ids.map(id=>scoped(get(id,type))!);if(rows.some(f=>f.details.distributionId!==d?.id))throw Error('INVESTMENT_DISTRIBUTION_BINDING_MISMATCH');if(new Set(rows.map(f=>f.details.basis)).size!==1)throw Error('INVESTMENT_AGGREGATE_DATE_OR_BASE_INVALID');return {...amount(rows[0])!,date:type==='investment_ledger'?period.closingDate:rows.map(f=>f.date).sort().at(-1)!,amount:money(rows.reduce((s,f)=>s+cents(f.amount),0n)),evidence:rows.map(f=>f.proof)};};
 const model=(id:string|null):InvestmentModel|null=>{const f=get(id,'investment_models');if(!f)return null;const m=f.details;return {id:m.id as string,version:m.version as string,nature:m.nature as InvestmentModel['nature'],originNature:m.originNature as InvestmentModel['nature'],securityId:m.securityId as string,perimeter:m.perimeter as string,units:'EUR',value:amount(f)!,assumptions:m.assumptions as string[],scenarios:(m.scenarios as {label:string;amount:Money;date:string;basis:string}[]).map(s=>({label:s.label,value:{amount:s.amount,date:s.date,basis:s.basis,evidence:[f.proof]}}))};};
 const base=register.details.accountingBase as InvestmentInput['accountingBase'];
 const decision=entry.decision;if(decision&&(!facts.find(f=>f.rowId===decision.citationRowId)||facts.find(f=>f.rowId===decision.citationRowId)!.details.securityId!==securityId))throw Error('INVESTMENT_DECISION_CITATION_INVALID');
 return {context:{scope,period,purpose:scope.mode==='demo'?'synthetic_technical':'real',procedure:'investments.review'},securityId,categoryProposed:register.details.categoryProposed as string,intention:register.details.intention as string,classificationMethod:null,distribution:amount(d),distributionId:d?.id,entitlementDate:d?.details.entitlementDate as string|undefined,rights:r?{...r.details,evidence:[r.proof],preferentialAllocation:r.details.homogeneous?null:amount(r)} as InvestmentInput['rights']:null,bookedDividend:aggregate(entry.ledgerIds,'investment_ledger'),bookedEntries:entry.ledgerIds.map(id=>amount(get(id,'investment_ledger'))!),receivedEntries:entry.receiptIds.map(id=>amount(get(id,'investment_receipts'))!),receivedDividend:aggregate(entry.receiptIds,'investment_receipts'),cost:amount(cost),bookedImpairment:amount(impairment),accountingBase:base,externalModel:model(entry.modelRowId),previousModel:model(entry.previousModelRowId),decision:decision?{id:'decision-'+stableSha256(decision),version:'1',category:decision.category,reason:decision.reason,date:decision.date,evidence:[facts.find(f=>f.rowId===decision.citationRowId)!.proof],...(decision.proposedAmount?{proposedAmount:{amount:decision.proposedAmount,date:period.closingDate,basis:amount(cost)?.basis??securityId,evidence:[facts.find(f=>f.rowId===decision.citationRowId)!.proof]}}:{})}:null};
}
export function stampInvestmentWork(draft:InvestmentDraft,batches:ImportBatch[],scope:WorkpaperScope,period:AccountingPeriod,runId:string,authorId:string,authoredAt:string){const parsed=investmentDraftSchema.parse(draft),facts=investmentFacts(scope,period,batches,runId);if(new Set(parsed.entries.map(e=>e.registerRowId+'|'+e.distributionRowId)).size!==parsed.entries.length)throw Error('INVESTMENT_DUPLICATE_UNIT');parsed.entries.forEach(e=>investmentInput(scope,period,facts,e));return investmentWorkSchema.parse({...parsed,authorId,authoredAt});}
export function evaluateInvestments(scope:WorkpaperScope,period:AccountingPeriod,batches:ImportBatch[],runId:string,population:Population,selection:SelectionSet,work:InvestmentWork){
 investmentWorkSchema.parse(work);const facts=investmentFacts(scope,period,batches,runId),selected=new Set(selection.selectedIds);
 const entries=work.entries.filter(e=>selected.has(e.registerRowId)&&(!e.distributionRowId||selected.has(e.distributionRowId)));
 const uncovered=population.items.filter(i=>selected.has(i.id)&&!entries.some(e=>e.registerRowId===i.id||e.distributionRowId===i.id)).map(i=>i.id);
 const rows=entries.map(e=>{const input=investmentInput(scope,period,facts,e);return {id:e.registerRowId+'|'+(e.distributionRowId??'none'),label:facts.find(f=>f.rowId===e.registerRowId)!.details.label as string,entry:e,input,review:reviewInvestment(input)};});
 const exceptions=rows.flatMap(row=>{const points:{id:string;rowId:string;text:string;amount:KnownAmountType}[]=[];if(row.review.bookedDifference.kind==='unknown'||row.review.bookedDifference.kind==='known'&&cents(row.review.bookedDifference.value)!==0n)points.push({id:row.id+':distribution',rowId:row.id,text:row.review.bookedDifference.kind==='unknown'?'Produit non concluant : '+row.review.bookedDifference.reason:'Écart arithmétique du produit enregistré',amount:row.review.bookedDifference});if(row.review.valuation.status!=='comparable'||row.review.valueDifference.kind==='known'&&cents(row.review.valueDifference.value)!==0n)points.push({id:row.id+':value',rowId:row.id,text:row.review.valuation.reason,amount:row.review.valueDifference});return points;});
 return frozen({schemaVersion:'investment-result-1' as const,scope,period,runId,work,rows,uncovered,exceptions,evidence:facts.map(f=>f.proof),facts,coverage:{unit:'lignes de titres et distributions',selected:selection.selectedIds.length,denominator:population.items.length,exclusions:selection.exclusions},inputHash:stableSha256({scope,period,batches,work,population,selection}),outcome:uncovered.length||rows.some(r=>r.review.valuation.status!=='comparable'||r.review.bookedDifference.kind!=='known')?'inconclusive' as const:exceptions.length?'exceptions_detected' as const:'no_exception_detected' as const});
}
import type { KnownAmount as KnownAmountType } from '@/lib/canonical-model/money';
export type InvestmentResult=ReturnType<typeof evaluateInvestments>;
