import { previewImport,type ImportBatch } from './imports';
import { INVESTMENT_MAPPING,investmentFacts,initialInvestmentDraft,stampInvestmentWork,evaluateInvestments } from './investment-dossier';
import { InvestmentRegistry,INVESTMENT_TEMPLATE } from './investment-adapter';
import { freezePopulation,selectPopulation } from './selection';
import { periodId,type WorkpaperScope,type WorkpaperRun } from './model';
import type { Principal } from './policy';
export const INVESTMENT_PERIOD={startDate:'2024-01-01',closingDate:'2024-12-31',asOfDate:'2025-02-01',currency:'EUR' as const,validation:'provisional' as const};
const csv=(rows:{key:string;amount:string;date?:string;details:unknown}[])=>'Key;Amount;Date;Details\n'+rows.map(r=>[r.key,r.amount,r.date??INVESTMENT_PERIOD.closingDate,JSON.stringify(r.details)].map(v=>'"'+v.replaceAll('"','""')+'"').join(';')).join('\n');
export function investmentSyntheticFiles(long=false){
 const ids=['ORD','PREF','EV','DATE','ABSENT'],basis=(id:string)=>'HOLDING:'+id,perimeter=(id:string)=>id+' · classe détenue · 25 titres';
 const rows:Record<string,{key:string;amount:string;date?:string;details:unknown}[]>={};
 rows.investment_register=ids.map(id=>({key:id,amount:'100.00',details:{securityId:id,label:id==='ORD'?'Orion · titres ordinaires'+(long?' — '+ 'Détention documentée et droit à corroborer. '.repeat(15):''):id==='PREF'?'Atlas · droits préférentiels':id==='EV'?'Vega · modèle entreprise':id==='DATE'?'Nova · date différente':'Lyra · modèle absent',categoryProposed:'À qualifier',intention:'Détention à documenter par une décision motivée',accountingBase:{kind:'net_carrying',label:'Coût moins dépréciation enregistrée',perimeter:perimeter(id)}}}));
 rows.investment_distributions=ids.map(id=>({key:'DIST-'+id,amount:'40.00',details:{securityId:id,entitlementDate:'2024-12-31',basis:'DIST:'+id}}));
 rows.investment_rights=ids.map(id=>({key:'RIGHT-'+id,amount:id==='PREF'?'12.00':'0.00',details:{securityId:id,distributionId:'DIST-'+id,classId:id==='PREF'?'A-préférentielle':'Ordinaire',from:'2024-01-01',to:'2024-12-31',entitlementDate:'2024-12-31',numerator:'1',denominator:'4',homogeneous:id!=='PREF',basis:'DIST:'+id,...(id==='PREF'?{allocationReason:'Allocation de 12 EUR fournie par la décision synthétique, sans prorata de capital'}:{})}}));
 rows.investment_ledger=ids.map(id=>({key:'GL-'+id,amount:id==='ORD'?'9.00':id==='PREF'?'12.00':'10.00',details:{securityId:id,distributionId:'DIST-'+id,basis:'DIST:'+id}}));
 rows.investment_receipts=ids.map(id=>({key:'PAY-'+id,amount:id==='ORD'?'9.00':id==='PREF'?'12.00':'10.00',date:'2025-01-12',details:{securityId:id,distributionId:'DIST-'+id,basis:'DIST:'+id}}));
 rows.investment_carrying=ids.flatMap(id=>[{key:'COST-'+id,amount:'100.00',details:{securityId:id,kind:'cost',basis:basis(id)}},{key:'IMP-'+id,amount:'10.00',details:{securityId:id,kind:'impairment',basis:basis(id)}}]);
 rows.investment_models=ids.filter(id=>id!=='ABSENT').flatMap(id=>['1','2'].map(version=>({key:'MODEL-'+id+'-'+version,amount:version==='1'?'110.00':'85.00',date:id==='DATE'?'2024-11-30':'2024-12-31',details:{securityId:id,id:'EXT-'+id,version,nature:'holding_value',originNature:id==='EV'?'enterprise_value':'holding_value',perimeter:perimeter(id),basis:basis(id),assumptions:['Hypothèses externes synthétiques fournies ; aucun calcul DCF interne',version==='1'?'Plan initial':'Plan révisé : baisse des marges'],scenarios:[{label:'Prudent',amount:{amount:'70.00',currency:'EUR'},date:'2024-12-31',basis:basis(id)},{label:'Central fourni',amount:{amount:version==='1'?'110.00':'85.00',currency:'EUR'},date:'2024-12-31',basis:basis(id)},{label:'Haut fourni',amount:{amount:'120.00',currency:'EUR'},date:'2024-12-31',basis:basis(id)}]}})));
 return Object.fromEntries(Object.entries(rows).map(([type,r])=>[type,new File([csv(r)],'EXEMPLE-'+type+'.csv',{type:'text/csv'})]));
}
export async function investmentFixture(scope:WorkpaperScope={organizationId:'SYN-INVESTMENT',dossierId:'SYN-INVESTMENT',periodId:periodId(INVESTMENT_PERIOD),mode:'demo'},long=false){
 const actor:Principal={id:'Préparateur synthétique',grants:[{scope,permissions:['read','prepare','download']}]},files=investmentSyntheticFiles(long),imports:ImportBatch[]=[];
 for(const [type,file]of Object.entries(files)){const p=await previewImport(file,scope,INVESTMENT_MAPPING,actor,type,scope.mode==='real'?'investments.review':undefined);if(p.report.blocking.length)throw Error('SYNTHETIC_IMPORT_INVALID');imports.push({...p,report:{...p.report,calculationAllowed:true},approval:{actorId:actor.id,at:'2025-02-01T12:00:00.000Z',previewHash:p.previewHash}});}
 const runId='SYN-INVESTMENT-RUN',facts=investmentFacts(scope,INVESTMENT_PERIOD,imports,runId),draft=initialInvestmentDraft(facts);
 // Explicit fixture choice of version 2, not a selection algorithm.
 draft.entries=draft.entries.map(e=>{const security=facts.find(f=>f.rowId===e.registerRowId)!.details.securityId;return {...e,modelRowId:facts.find(f=>f.type==='investment_models'&&f.details.securityId===security&&f.details.version==='2')?.rowId??null,previousModelRowId:facts.find(f=>f.type==='investment_models'&&f.details.securityId===security&&f.details.version==='1')?.rowId??null};});
 const population=freezePopulation(scope,imports,'security_distribution',actor),selection=selectPopulation(population,{method:'targeted',criteria:'Toutes les lignes de titres et distributions de la recette synthétique',exclusions:[],requestedSize:population.items.length,selectedIds:population.items.map(i=>i.id)},actor),work=stampInvestmentWork(draft,imports,scope,INVESTMENT_PERIOD,runId,actor.id,'2025-02-01T12:00:00.000Z');
 const calculation=new InvestmentRegistry().execute({scope,period:INVESTMENT_PERIOD,rule:INVESTMENT_TEMPLATE.rule!,imports,population,selection,parameters:{work,runId}}),result=evaluateInvestments(scope,INVESTMENT_PERIOD,imports,runId,population,selection,work);
 const run:WorkpaperRun={id:runId,rootId:runId,revision:1,version:1,schemaVersion:'1.0.0',scope,period:INVESTMENT_PERIOD,template:INVESTMENT_TEMPLATE,state:'executed',preparedBy:actor.id,importIds:imports.map(b=>b.id),population,selection,investmentWork:work,result:calculation,evidence:result.evidence,findings:[],notes:result.exceptions.map(e=>({id:'investment:'+e.id,kind:'observation',text:e.text,amount:e.amount,blocking:true,authorId:actor.id})),events:[{id:'synthetic:1',action:'synthetic_calculation',actorId:actor.id,at:'2025-02-01T12:00:00.000Z',version:1}]};
 return {scope,actor,files,imports,draft,facts,run,result};
}
