import type { WorkpaperRun } from './model';
import { contentHash } from './model';
import type { InvestmentResult } from './investment-dossier';
const escape=(v:unknown)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function investmentDiagnostic(run:WorkpaperRun){
 const result=run.result?.result as InvestmentResult|undefined;if(!result||result.schemaVersion!=='investment-result-1')throw Error('INVESTMENT_RESULT_REQUIRED');
 const amount=(a:import('@/lib/canonical-model/money').KnownAmount)=>a.kind==='known'?a.value.amount+' EUR':a.kind==='unknown'?'Non concluant : '+a.reason:'Non applicable';
 const table=(headers:string[],rows:unknown[][])=>'<table><thead><tr>'+headers.map(h=>'<th>'+escape(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+escape(c)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
 const body=result.rows.map(r=>'<section><h2>'+escape(r.label)+'</h2><p>'+escape(r.input.securityId)+' · '+escape(r.input.distributionId)+'</p>'+table(['Contrôle','Résultat','Explication'],[['Droits / distribution',amount(r.review.expectedDividend),r.review.rightsReason],['Écart produit',amount(r.review.bookedDifference),'Produit enregistré moins droit attendu'],['Coût',r.input.cost?r.input.cost.amount.amount+' EUR':'Source requise',r.input.cost?.date],['Dépréciation enregistrée',r.input.bookedImpairment?.amount.amount??'Inconnue',r.input.bookedImpairment?.date],['Base comparée',amount(r.review.carryingAmount),r.review.accountingBase?.label],['Valeur externe',r.input.externalModel?.value.amount.amount??'Absente',r.review.valuation.reason],['Écart valeur',amount(r.review.valueDifference),r.review.valuation.conclusion],['Proposition comptable',r.review.accountingProposal?.amount.amount.amount??'Aucune',r.input.decision?.reason??'Décision motivée requise']])+ '<p>'+escape(r.input.externalModel?.id)+' · version '+escape(r.input.externalModel?.version)+' · nature '+escape(r.input.externalModel?.nature)+' · origine '+escape(r.input.externalModel?.originNature)+' · date '+escape(r.input.externalModel?.value.date)+' · périmètre '+escape(r.input.externalModel?.perimeter)+'</p><p>'+escape(r.input.externalModel?.assumptions.join(' ; '))+'</p>'+table(['Scénario fourni','Valeur EUR','Écart / état'],r.review.scenarios.map(s=>[s.label,s.value.amount.amount,amount(s.difference)+' · '+s.status]))+table(['Version — champ','Avant','Après'],r.review.versionComparison.changes.map(c=>[c.field,c.before,c.after]))+'</section>').join('');
 const html='<!doctype html><html lang="fr"><meta charset="utf-8"><title>PROBANT · Participations · diagnostic</title><style>body{font:14px/1.5 system-ui;margin:30px;color:#172033}h1{font-size:26px}h2{font-size:20px}table{border-collapse:collapse;width:100%;margin:14px 0;overflow-wrap:anywhere}th,td{padding:8px;border:1px solid #9eafc3;text-align:left;vertical-align:top}section{break-inside:avoid;margin:24px 0}p{overflow-wrap:anywhere}@media print{body{margin:0}thead{display:table-header-group}}</style><h1>Participations · diagnostic de la version '+run.version+'</h1><p>'+escape(run.scope.dossierId)+' · '+run.period.startDate+' → '+run.period.closingDate+' · revue au '+run.period.asOfDate+'</p><p>État '+escape(run.state)+' · couverture '+result.coverage.selected+' / '+result.coverage.denominator+' lignes de titres et distributions. Un écart arithmétique n’est pas une anomalie validée. Aucun scénario choisi automatiquement. Aucun avis sur les comptes.</p>'+body+ '<h2>Exclusions</h2>'+table(['Unité','Motif'],result.coverage.exclusions.map(e=>[e.id,e.reason]))+'<h2>Revue</h2><p>'+escape(run.conclusion??'Absente')+'</p>'+table(['Point','Traitement','Auteur'],run.notes.map(n=>[n.text,n.resolution?.text??'Non traité',n.resolution?.authorId??n.authorId]))+'<h2>Sources versionnées</h2>'+table(['Document','Pack','Date','Localisateur','Version'],result.facts.map(f=>[f.fileName,f.pack,f.date,(f.sheet??'CSV')+' · ligne '+f.line,f.version]))+'<p>Originaux absents du paquet ; index uniquement. Pages non applicables pour les tableaux. Hash local de reproductibilité, sans signature ni preuve inviolable : '+contentHash(run)+'</p></html>';
 return {html,json:JSON.stringify({schemaVersion:'investment-diagnostic-1',snapshotHash:contentHash(run),run,originalsIncluded:false},null,2)};
}
