import type { TaxControlDefinition } from "@/lib/canonical-model";
import { stableHash } from "@/lib/synthesis/canonical";
import { TaxControlDefinitionSchema } from "./schemas";

type DefinitionInput = Omit<TaxControlDefinition, "definitionHash">;

function definition(input: DefinitionInput): TaxControlDefinition {
  const normalized = {
    ...input,
    fiscalYears: [...input.fiscalYears].sort((left, right) => left - right),
    formVintages: [...input.formVintages].sort((left, right) => left - right),
    sourceRefs: [...input.sourceRefs].sort((left, right) =>
      `${left.sourceVersionId}:${left.locator}`.localeCompare(`${right.sourceVersionId}:${right.locator}`)),
    applicability: {
      corporateIncomeTaxRegimes: [...input.applicability.corporateIncomeTaxRegimes].sort(),
      vatRegimes: [...input.applicability.vatRegimes].sort(),
    },
    requiredDocumentTypes: [...input.requiredDocumentTypes].sort(),
    conclusiveDocumentTypes: [...input.conclusiveDocumentTypes].sort(),
    requiredFieldCodes: [...input.requiredFieldCodes].sort(),
    conclusiveFieldCodes: [...input.conclusiveFieldCodes].sort(),
    requiredParameterKeys: [...input.requiredParameterKeys].sort(),
    conclusiveParameterKeys: [...input.conclusiveParameterKeys].sort(),
    recommendationRuleIds: [...input.recommendationRuleIds].sort(),
    allowedOutcomes: [...input.allowedOutcomes].sort(),
  };
  return Object.freeze(TaxControlDefinitionSchema.parse({
    ...normalized,
    definitionHash: stableHash(normalized),
  }) as TaxControlDefinition);
}

export const TAX_CONTROL_DEFINITIONS: readonly TaxControlDefinition[] = [
  definition({
    controlId: "IS.RECONCILIATION.2058A",
    controlVersion: "2026.1.0",
    title: "Préparation du rapprochement résultat comptable / résultat fiscal 2058-A",
    purpose: "Déterminer si les données nécessaires au rapprochement du tableau 2058-A sont disponibles.",
    family: "methodology",
    domain: "tax",
    taxType: "corporate_income_tax",
    controlStage: "tax_review",
    effectiveFrom: "2026-01-01",
    effectiveTo: null,
    fiscalYears: [2026],
    formVintages: [2026],
    sourceRefs: [{
      sourceId: "form-2050-liasse",
      sourceVersionId: "form-2050-liasse-v2026",
      locator: "2058-A-SD, rubriques I, II et III",
    }],
    applicability: { corporateIncomeTaxRegimes: ["standard"], vatRegimes: [] },
    requiredDocumentTypes: ["fec", "liasse_2050_2059"],
    conclusiveDocumentTypes: ["fec", "liasse_2050_2059"],
    requiredFieldCodes: [],
    conclusiveFieldCodes: [],
    requiredParameterKeys: [],
    conclusiveParameterKeys: [],
    recommendationRuleIds: [
      "TAX.RECOMMENDATION.REQUEST_2058A",
      "TAX.RECOMMENDATION.CONFIRM_CIT_REGIME",
      "TAX.RECOMMENDATION.CONFIRM_PERIOD",
    ],
    allowedOutcomes: ["passed", "reconciliation_difference", "missing_information", "inconclusive", "review_recommendation"],
    automation: "assisted",
    maximumEvidenceStrength: "corroborated",
    capabilityStatus: "available",
    reviewRequired: true,
  }),
  definition({
    controlId: "IS.RECONCILIATION.2033B",
    controlVersion: "2026.1.0",
    title: "Préparation du rapprochement simplifié 2033-B",
    purpose: "Déterminer si les données nécessaires au rapprochement du tableau 2033-B sont disponibles.",
    family: "methodology",
    domain: "tax",
    taxType: "corporate_income_tax",
    controlStage: "tax_review",
    effectiveFrom: "2026-01-01",
    effectiveTo: null,
    fiscalYears: [2026],
    formVintages: [2026],
    sourceRefs: [{
      sourceId: "form-2033-liasse",
      sourceVersionId: "form-2033-liasse-v2026",
      locator: "2033-B-SD, partie B - Résultat fiscal",
    }],
    applicability: { corporateIncomeTaxRegimes: ["simplified"], vatRegimes: [] },
    requiredDocumentTypes: ["fec", "liasse_2033"],
    conclusiveDocumentTypes: ["fec", "liasse_2033"],
    requiredFieldCodes: [],
    conclusiveFieldCodes: [],
    requiredParameterKeys: [],
    conclusiveParameterKeys: [],
    recommendationRuleIds: [
      "TAX.RECOMMENDATION.REQUEST_2033B",
      "TAX.RECOMMENDATION.CONFIRM_CIT_REGIME",
      "TAX.RECOMMENDATION.CONFIRM_PERIOD",
    ],
    allowedOutcomes: ["passed", "reconciliation_difference", "missing_information", "inconclusive", "review_recommendation"],
    automation: "assisted",
    maximumEvidenceStrength: "corroborated",
    capabilityStatus: "available",
    reviewRequired: true,
  }),
  definition({
    controlId: "IS.RATE.REDUCED.ELIGIBILITY",
    controlVersion: "2026.1.0",
    title: "Préparation de la revue d'éligibilité au taux réduit d'IS",
    purpose: "Vérifier que les paramètres nécessaires à la revue du taux réduit sont documentés, sans calculer l'impôt.",
    family: "hardLaw",
    domain: "tax",
    taxType: "corporate_income_tax",
    controlStage: "tax_review",
    effectiveFrom: "2026-02-21",
    effectiveTo: null,
    fiscalYears: [2026],
    formVintages: [2026],
    sourceRefs: [{
      sourceId: "cgi-art-219",
      sourceVersionId: "cgi-art-219-v2026-02-21",
      locator: "article 219, I-b",
    }],
    applicability: { corporateIncomeTaxRegimes: ["standard", "simplified"], vatRegimes: [] },
    requiredDocumentTypes: ["declaration_2065"],
    conclusiveDocumentTypes: ["declaration_2065"],
    requiredFieldCodes: [],
    conclusiveFieldCodes: [],
    requiredParameterKeys: [],
    conclusiveParameterKeys: [
      "profile:capitalPaidStatus",
      "profile:ownershipStatus",
      "profile:turnoverAmountCents",
    ],
    recommendationRuleIds: [
      "TAX.RECOMMENDATION.REQUEST_2065",
      "TAX.RECOMMENDATION.CONFIRM_CIT_REGIME",
      "TAX.RECOMMENDATION.CONFIRM_CAPITAL_PAID",
      "TAX.RECOMMENDATION.CONFIRM_OWNERSHIP",
      "TAX.RECOMMENDATION.CONFIRM_TURNOVER",
    ],
    allowedOutcomes: ["passed", "potential_tax_risk", "missing_information", "inconclusive", "review_recommendation"],
    automation: "assisted",
    maximumEvidenceStrength: "corroborated",
    capabilityStatus: "available",
    reviewRequired: true,
  }),
  definition({
    controlId: "IS.COMPUTATION.RESULT_AND_TAX.2058A",
    controlVersion: "2026.1.0",
    title: "Calcul du résultat fiscal et de l'impôt sur les sociétés (réel normal)",
    purpose: "Rejouer le passage du résultat comptable à l'impôt brut et le confronter à la déclaration et à la comptabilité.",
    family: "methodology",
    domain: "tax",
    taxType: "corporate_income_tax",
    controlStage: "tax_review",
    effectiveFrom: "2026-02-21",
    effectiveTo: null,
    fiscalYears: [2026],
    formVintages: [2026],
    sourceRefs: [
      {
        sourceId: "cgi-art-209",
        sourceVersionId: "cgi-art-209-v2023-12-31",
        locator: "article 209, I, troisieme alinea",
      },
      {
        sourceId: "cgi-art-219",
        sourceVersionId: "cgi-art-219-v2026-02-21",
        locator: "article 219, I",
      },
      {
        sourceId: "form-2050-liasse",
        sourceVersionId: "form-2050-liasse-v2026",
        locator: "2058-A-SD, rubriques I, II et III",
      },
    ],
    // Régime réel normal seulement : la 2033-B (réel simplifié) relève du
    // contrôle jumeau ci-dessous, avec ses propres types de document.
    applicability: { corporateIncomeTaxRegimes: ["standard"], vatRegimes: [] },
    requiredDocumentTypes: ["liasse_2050_2059"],
    conclusiveDocumentTypes: ["declaration_2065", "liasse_2050_2059"],
    requiredFieldCodes: [],
    conclusiveFieldCodes: [],
    requiredParameterKeys: [],
    conclusiveParameterKeys: [
      "profile:capitalPaidStatus",
      "profile:ownershipStatus",
      "profile:turnoverAmountCents",
    ],
    recommendationRuleIds: [
      "TAX.RECOMMENDATION.REQUEST_2058A",
      "TAX.RECOMMENDATION.REQUEST_2065",
      "TAX.RECOMMENDATION.CONFIRM_CIT_REGIME",
      "TAX.RECOMMENDATION.CONFIRM_CAPITAL_PAID",
      "TAX.RECOMMENDATION.CONFIRM_OWNERSHIP",
      "TAX.RECOMMENDATION.CONFIRM_TURNOVER",
    ],
    // `confirmed_non_compliance` reste interdit : une extraction ou une
    // déclaration rectificative peut expliquer tout écart du MVP.
    allowedOutcomes: [
      "passed",
      "reconciliation_difference",
      "potential_tax_risk",
      "missing_information",
      "inconclusive",
      "review_recommendation",
    ],
    automation: "assisted",
    maximumEvidenceStrength: "corroborated",
    capabilityStatus: "available",
    reviewRequired: true,
  }),
  definition({
    controlId: "IS.COMPUTATION.RESULT_AND_TAX.2033B",
    controlVersion: "2026.1.0",
    title: "Calcul du résultat fiscal et de l'impôt sur les sociétés (réel simplifié)",
    purpose: "Rejouer le passage du résultat comptable à l'impôt brut et le confronter à la déclaration et à la comptabilité.",
    family: "methodology",
    domain: "tax",
    taxType: "corporate_income_tax",
    controlStage: "tax_review",
    effectiveFrom: "2026-02-21",
    effectiveTo: null,
    fiscalYears: [2026],
    formVintages: [2026],
    sourceRefs: [
      {
        sourceId: "cgi-art-209",
        sourceVersionId: "cgi-art-209-v2023-12-31",
        locator: "article 209, I, troisieme alinea",
      },
      {
        sourceId: "cgi-art-219",
        sourceVersionId: "cgi-art-219-v2026-02-21",
        locator: "article 219, I",
      },
      {
        sourceId: "form-2033-liasse",
        sourceVersionId: "form-2033-liasse-v2026",
        locator: "2033-B-SD, B - Resultat fiscal",
      },
    ],
    applicability: { corporateIncomeTaxRegimes: ["simplified"], vatRegimes: [] },
    requiredDocumentTypes: ["liasse_2033"],
    conclusiveDocumentTypes: ["declaration_2065", "liasse_2033"],
    requiredFieldCodes: [],
    conclusiveFieldCodes: [],
    requiredParameterKeys: [],
    conclusiveParameterKeys: [
      "profile:capitalPaidStatus",
      "profile:ownershipStatus",
      "profile:turnoverAmountCents",
    ],
    recommendationRuleIds: [
      "TAX.RECOMMENDATION.REQUEST_2033B",
      "TAX.RECOMMENDATION.REQUEST_2065",
      "TAX.RECOMMENDATION.CONFIRM_CIT_REGIME",
      "TAX.RECOMMENDATION.CONFIRM_CAPITAL_PAID",
      "TAX.RECOMMENDATION.CONFIRM_OWNERSHIP",
      "TAX.RECOMMENDATION.CONFIRM_TURNOVER",
    ],
    allowedOutcomes: [
      "passed",
      "reconciliation_difference",
      "potential_tax_risk",
      "missing_information",
      "inconclusive",
      "review_recommendation",
    ],
    automation: "assisted",
    maximumEvidenceStrength: "corroborated",
    capabilityStatus: "available",
    reviewRequired: true,
  }),
  definition({
    controlId: "VAT.FORM.CA3.RECONCILIATION",
    controlVersion: "2026.1.0",
    title: "Préparation du contrôle de cohérence interne CA3",
    purpose: "Déterminer si la CA3 et ses cases structurantes sont disponibles pour un contrôle ultérieur.",
    family: "methodology",
    domain: "tax",
    taxType: "vat",
    controlStage: "tax_review",
    effectiveFrom: "2026-01-01",
    effectiveTo: null,
    fiscalYears: [2026],
    formVintages: [2026],
    sourceRefs: [{
      sourceId: "form-ca3",
      sourceVersionId: "form-ca3-v2026",
      locator: "3310-CA3-SD 2026, cases 16, 23, 25 et TD",
    }],
    applicability: { corporateIncomeTaxRegimes: [], vatRegimes: ["real_normal", "mini_real"] },
    requiredDocumentTypes: ["fec", "declaration_tva_ca3"],
    conclusiveDocumentTypes: ["fec", "declaration_tva_ca3"],
    requiredFieldCodes: ["16", "23"],
    conclusiveFieldCodes: ["16", "23"],
    requiredParameterKeys: [],
    conclusiveParameterKeys: [],
    recommendationRuleIds: [
      "TAX.RECOMMENDATION.REQUEST_CA3",
      "TAX.RECOMMENDATION.CONFIRM_VAT_REGIME",
    ],
    allowedOutcomes: ["passed", "reconciliation_difference", "missing_information", "inconclusive", "review_recommendation"],
    automation: "assisted",
    maximumEvidenceStrength: "corroborated",
    capabilityStatus: "available",
    reviewRequired: true,
  }),
  definition({
    controlId: "VAT.DEDUCTIBLE.SUPPORT",
    controlVersion: "2026.1.0",
    title: "Préparation de la revue de TVA déductible",
    purpose: "Distinguer la déclaration et les écritures disponibles des factures nécessaires à une conclusion documentée.",
    family: "hardLaw",
    domain: "tax",
    taxType: "vat",
    controlStage: "tax_review",
    effectiveFrom: "2026-02-21",
    effectiveTo: null,
    fiscalYears: [2026],
    formVintages: [2026],
    sourceRefs: [
      {
        sourceId: "cgi-art-271",
        sourceVersionId: "cgi-art-271-v2026-02-21",
        locator: "article 271, I et II",
      },
      {
        sourceId: "bofip-tva-deduction",
        sourceVersionId: "bofip-tva-deduction-v2025-01-08",
        locator: "BOI-TVA-DED-40-20, paragraphes 1 et suivants",
      },
    ],
    applicability: { corporateIncomeTaxRegimes: [], vatRegimes: ["real_normal", "mini_real"] },
    requiredDocumentTypes: ["fec", "declaration_tva_ca3"],
    conclusiveDocumentTypes: ["fec", "declaration_tva_ca3", "invoice"],
    requiredFieldCodes: ["23"],
    conclusiveFieldCodes: ["23"],
    requiredParameterKeys: [],
    conclusiveParameterKeys: [],
    recommendationRuleIds: [
      "TAX.RECOMMENDATION.REQUEST_CA3",
      "TAX.RECOMMENDATION.REQUEST_INVOICES",
      "TAX.RECOMMENDATION.CONFIRM_VAT_REGIME",
    ],
    allowedOutcomes: ["passed", "potential_tax_risk", "missing_information", "inconclusive", "review_recommendation"],
    automation: "assisted",
    maximumEvidenceStrength: "corroborated",
    capabilityStatus: "available",
    reviewRequired: true,
  }),
] as const;

export function taxControlDefinitions(): readonly TaxControlDefinition[] {
  return TAX_CONTROL_DEFINITIONS;
}

