import { describe, expect, it } from 'vitest';
import { DrizzleQueryError } from 'drizzle-orm/errors';
import { equityHandlers, requireDisposableEquity } from '../equity-http';
import { EquityRuntime } from '../equity-runtime';
import { assertContext, assertEquityContext } from '../cycle-context';
import { EQUITY_DEMO_PERIOD } from '../equity-fixture';
import { periodId } from '../model';
const dossier='11111111-1111-4111-8111-111111111111',scope={organizationId:'org',dossierId:dossier,periodId:periodId(EQUITY_DEMO_PERIOD),mode:'real' as const};
const request=(extra='')=>new Request('https://probant.example.test/api/workpapers/equity?dossierId='+dossier+'&periodId='+scope.periodId+extra);
describe('Mission 11 — accès fermé et erreurs publiques',()=>{
 it('production et défaut refusés ; seul disposable est accepté',()=>{for(const env of [{},{PROBANT_EQUITY_DURABLE:'true'},{PROBANT_EQUITY_DURABLE:'disposable',VERCEL_ENV:'production'}])expect(()=>requireDisposableEquity(env)).toThrow();expect(()=>requireDisposableEquity({PROBANT_EQUITY_DURABLE:'disposable'})).not.toThrow();});
 it('contexte equity autorisé sans ouvrir les autres moteurs réels',()=>{const c={scope,period:EQUITY_DEMO_PERIOD,purpose:'real' as const,procedure:'equity.review' as const};expect(()=>assertEquityContext(c)).not.toThrow();expect(()=>assertContext(c)).toThrow();expect(()=>assertEquityContext({...c,procedure:'clients.sales'})).toThrow();});
 it('aucun SQL ni paramètre privé dans les erreurs',async()=>{const handlers=equityHandlers(()=>{throw new DrizzleQueryError('INSERT INTO private VALUES ($1)',['source-confidentielle'],new Error('driver-private'));},()=>{}),r=await handlers.GET(request());expect(r.status).toBe(503);expect(await r.text()).toBe('{"error":"EQUITY_DURABLE_UNAVAILABLE"}');});
 it('session expirée intercepte lecture, preuve et téléchargement avant toute transaction',async()=>{let transactions=0;const db={execute:async()=>[],transaction:async()=>{transactions++;throw Error('UNEXPECTED_DATABASE_CALL');}},runtime=new EquityRuntime(db,{authorize:async()=>({subject:'expired',organizationId:'org',dossierIds:[dossier],roles:['preparer'],authenticationMethod:'oidc-session' as const,amr:[],acr:null,mfaSatisfied:true,expiresAtEpochSeconds:99})},()=>100),handlers=equityHandlers(()=>runtime,()=>{});for(const q of ['', '&operation=proof&id=doc','&operation=download&id=doc'])expect((await handlers.GET(request(q))).status).toBe(401);expect(transactions).toBe(0);});
 it('accès transversal et rôle sans export refusent les pièces avant la base',async()=>{let calls=0;const db={execute:async()=>[],transaction:async()=>{calls++;throw Error('UNEXPECTED_DATABASE_CALL');}},runtime=new EquityRuntime(db,{authorize:async()=>({subject:'scoped',organizationId:'org',dossierIds:['other'],roles:['preparer'],authenticationMethod:'signed-gateway-context' as const,amr:[],acr:null,mfaSatisfied:true,expiresAtEpochSeconds:200})},()=>100),handlers=equityHandlers(()=>runtime,()=>{});expect((await handlers.GET(request('&operation=proof&id=doc'))).status).toBe(403);expect(calls).toBe(0);});
 it('erreurs métier et limites restent distinctes de l’indisponibilité serveur',async()=>{for(const [code,status] of [['UNBALANCED_INTERNAL_TRANSFER',422],['EQUITY_ACCOUNT_DUPLICATE',422],['EQUITY_PDF_PAGE_LIMIT',413]] as const){const r=await equityHandlers(()=>({check:async()=>{},equityCommand:async()=>{throw Error(code);}} as unknown as EquityRuntime),()=>{}).POST(new Request(request().url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:'execute',id:'run',expectedVersion:1})}));expect(r.status).toBe(status);expect(await r.json()).toEqual({error:code});}});
 it('une commande ne peut déléguer un rôle ou une approbation par le JSON',async()=>{let called=false;const runtime={check:async()=>{},equityCommand:async()=>{called=true;}} as unknown as EquityRuntime,handlers=equityHandlers(()=>runtime,()=>{});const r=await handlers.POST(new Request(request().url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:'execute',id:'run',expectedVersion:1,role:'reviewer',approved:true})}));expect(r.status).toBe(400);expect(called).toBe(false);});
});
