import { expect, it } from "vitest";
import { reviewEquity, type EquityInput } from "../equity";
import { period, scope } from "./fixtures";
import { proof, known } from "./cutoff-fixtures";
const v = (s: string, date = period.closingDate) => ({ amount: known(s).value, date, basis: "EUR", evidence: [proof] });
function fixture(): EquityInput { return { context: { scope, period, purpose: "synthetic_technical" }, capitalComponentId: "capital", reserveComponentIds: ["reserves"], components: [{ id: "capital", accounts: ["SYN-101"], opening: v("0.00", period.startDate), movements: [], closing: v("0.00") }, { id: "reserves", accounts: ["SYN-106"], opening: v("0.00", period.startDate), movements: [{ id: "M1", internalTransferId: "T", value: v("100.00") }], closing: v("100.00") }, { id: "result", accounts: ["SYN-12"], opening: v("100.00", period.startDate), movements: [{ id: "M2", internalTransferId: "T", value: v("-100.00") }], closing: v("0.00") }], allocations: [{ id: "A", decision: null, booked: v("100.00"), payment: null, decisionReference: "", readingValidated: false }], events: [{ id: "E", effectiveDate: period.closingDate, description: "Changement synthétique sans écriture", evidence: [proof], review: "pending", accountingMovementId: null }] }; }
it("transfert interne neutre, événement sans écriture, PV et ratio inconnus", () => { const r = reviewEquity(fixture()); expect(r.totalVariation).toEqual(known("0.00").value); expect(r.events).toHaveLength(1); expect(r.allocations[0].difference.kind).toBe("unknown"); expect(r.ratios.equityToCapital.kind).toBe("unknown"); });
it("affectation documentée différente de 10 sans conclusion juridique", () => { const x = fixture(); x.allocations[0] = { ...x.allocations[0], decision: v("90.00"), decisionReference: "SYN-PV-v1", readingValidated: true }; const r = reviewEquity(x); expect(r.allocations[0].difference).toEqual(known("10.00")); expect(r.legalConclusion.kind).toBe("unknown"); });
it("refuse transfert interne déséquilibré", () => { const x = fixture(); x.components[2].movements[0].value = v("-90.00"); expect(() => reviewEquity(x)).toThrow("UNBALANCED"); });
