import { PDFDocument } from "pdf-lib";
import { describe, it, expect } from "vitest";
import { evaluatePayables, stampPayablesWork, assertPayablesBatch, buildPayablesFacts } from "../payables-investigation";
import { PayablesRegistry, payableTemplate } from "../payables-adapter";
import { fixture, actor, presentationRun } from "./payables-fixture";
import { buildPayablesMission } from "../payables-mission";
import { contentHash } from "../model";
import { buildPayablesPackage } from "@/lib/evidence/payables-package";
const evaluate = (f: Awaited<ReturnType<typeof fixture>>) => evaluatePayables(f.scope, f.period, f.imports, "RUN", f.procedure, f.population, f.selection, f.work);
const asRun = presentationRun;
describe("Mission 08 — investigation sourcée, HT / TVA / TTC", () => {
    it("1 200 TTC : candidat 1 000 HT avec prestation antérieure et absence de FNP documentée", async () => { const r = evaluate(await fixture()), u = r.rows.find(r => r.invoiceId === "I-U")!; expect(u.status).toBe("omission_candidate"); expect(u.paidTTC?.amount).toBe("1200.00"); expect(u.unallocatedTTC?.amount).toBe("0.00"); expect(u.cutoff?.amount).toEqual({ kind: "known", value: { amount: "1000.00", currency: "EUR" } }); expect(r.events.find(e => e.invoiceId === "I-U")?.tax).toEqual({ kind: "known", value: { amount: "200.00", currency: "EUR" } }); });
    it("FNP existante et déjà enregistré n’émettent pas une nouvelle omission", async () => { const r = evaluate(await fixture()); expect(r.rows.find(r => r.invoiceId === "I-F")?.status).toBe("existing_accrual"); expect(r.rows.find(r => r.invoiceId === "I-B")?.status).toBe("booked_in_period"); expect(r.exposures).toHaveLength(2); });
    it("paiement groupé partiel : 600 TTC résiduels, non concluant, sans exposition HT ferme", async () => { const r = evaluate(await fixture()), g = r.rows.find(r => r.invoiceId === "I-G")!; expect(g.status).toBe("inconclusive"); expect(g.unallocatedTTC?.amount).toBe("600.00"); expect(g.differenceHT.kind).toBe("unknown"); expect(r.exposures.some(e => e.economicEventId === g.eventId)).toBe(false); });
    it("facture sans prestation et période ultérieure restent distinctes", async () => { const r = evaluate(await fixture()); expect(r.rows.find(r => r.invoiceId === "I-N")?.status).toBe("inconclusive"); expect(r.rows.find(r => r.invoiceId === "I-O")?.status).toBe("outside_period_justified"); expect(r.events.find(e => e.flow === "sale")?.cutoff.candidate).toBe("FAE"); });
    it("deux procédures partagent l’événement D et un seul résiduel de 600 HT", async () => { const a = await fixture("payables.purchases"), b = await fixture(); const purchases = asRun(a, "PURCHASES"), rpne = asRun(b); const imports = [...new Map([...a.imports, ...b.imports].map(b => [b.id, b])).values()]; const m = buildPayablesMission(a.scope, [purchases, rpne], imports, imports.map(b => ({ document_type: b.document.documentType, import_id: b.id }))); const d = m.exposures.find(e => e.procedureIds.length === 2)!; expect(d.amount).toEqual({ kind: "known", value: { amount: "600.00", currency: "EUR" } }); expect(m.events.find(e => e.eventId === d.economicEventId)?.observations).toHaveLength(2); expect(m.counters.planned).toBe(3); expect(m.counters.plannedControls).toBe(6); });
    it("proposition sans effet ; surallocation et mauvais tiers refusés", async () => { const f = await fixture(); const draft = structuredClone(f.draft); draft.allocations[0].status = "proposal"; f.work = stampPayablesWork(draft, f.imports, f.scope, f.period, "RUN", actor.id, "2025-02-01T11:00:00.000Z"); expect(evaluate(f).rows.find(r => r.unitId === f.imports.find(b => b.document.documentType === "payables_payments")!.rows[0].id)?.status).toBe("inconclusive"); draft.allocations[0].status = "validated"; draft.allocations.push({ ...draft.allocations[0], id: "again" }); f.work = stampPayablesWork(draft, f.imports, f.scope, f.period, "RUN", actor.id, "2025-02-01T11:00:00.000Z"); expect(() => evaluate(f)).toThrow(/OVERALLOCATED/); const wrong = structuredClone(f.imports); const payment = wrong.find(b => b.document.documentType === "payables_payments")!; payment.rows[0].original.party = "OTHER"; f.imports = wrong; f.work = { ...f.work, allocations: [f.work.allocations[0]] }; expect(() => evaluate(f)).toThrow(/PARTY_MISMATCH/); });
    it("l’adaptateur fermé refuse un moteur synthétique et exécute le contrat réel", async () => { const f = await fixture(); const request = { scope: f.scope, period: f.period, rule: payableTemplate(f.procedure).rule!, imports: f.imports, population: f.population, selection: f.selection, parameters: { work: f.work, runId: "RUN" } }; const registry = new PayablesRegistry(f.procedure); expect(registry.execute(request).execution).toBe("completed"); expect(registry.execute({ ...request, rule: { id: "synthetic.sum", version: "1.0.0" } }).execution).toBe("blocked"); });
    it("cadrage fournisseurs réutilisé sans addition de comparaisons", async () => { const f = await fixture("payables.frame"), r = evaluate(f); expect((r.technical as {
        generalToAuxiliary: {
            metrics: {
                net: {
                    amount: string;
                };
            };
        };
    }).generalToAuxiliary.metrics.net.amount).toBe("0.00"); expect(r.exposures).toEqual([]); });
    it("écran/export concordants, limites, long texte, périmé et paquet approuvé refusé", async () => { const f = await fixture(), run = asRun(f); run.conclusion = "Jugement " + "écriture <script> & pièce 文 ".repeat(100); const heads = f.imports.map(b => ({ document_type: b.document.documentType, import_id: b.id })); const m = buildPayablesMission(f.scope, [run], f.imports, heads); const pack = await buildPayablesPackage(m, run, f.imports, "diagnostic", "2025-02-01T12:00:00.000Z"); expect(pack.html).toContain("600.00 EUR"); expect(pack.html).toContain("1200.00 EUR"); expect(pack.html).toContain("1000.00 EUR"); expect(pack.html).toContain("&lt;script&gt;"); expect(pack.html).toContain("Pièces binaires absentes"); expect(pack.pdf.byteLength).toBeGreaterThan(1000);expect((await PDFDocument.load(pack.pdf)).getPageCount()).toBeGreaterThan(1); expect(JSON.parse(pack.canonicalJson).mission.hash).toBe(m.hash); await expect(buildPayablesPackage(m, run, f.imports, "approved", "2025-02-01T12:00:00.000Z")).rejects.toThrow(/LOCKED_REQUIRED/); run.state = "locked"; run.approval = { actorId: "real-reviewer", snapshotHash: contentHash(run), version: run.version, note: "Exception maintenue et documentée", at: "2025-02-01T12:00:00.000Z" }; const locked = buildPayablesMission(f.scope, [run], f.imports, heads); expect((await buildPayablesPackage(locked, run, f.imports, "approved", run.approval.at)).html).toContain("Candidat omission"); const stale = buildPayablesMission(f.scope, [run], f.imports, heads.filter(h => h.document_type !== "payables_payments")); expect(stale.procedures.find(p => p.id === "payables.rpne")?.stale).toBe(true); await expect(buildPayablesPackage(stale, run, f.imports, "approved", run.approval.at)).rejects.toThrow(/LOCKED_REQUIRED/); }, 30000);
    it("devise source, signe et absence fictive refusés ; méthode absente refusée", async () => { const f = await fixture(), source = f.imports.find(b => b.document.documentType === "payables_adjustments")!; const wrong = structuredClone(source); wrong.rows[0].original.currency = "USD"; expect(() => assertPayablesBatch(wrong, f.period)).toThrow("PAYABLE_CURRENCY_UNSUPPORTED"); const falseAbsence = structuredClone(source); falseAbsence.rows[0].normalized!.amount.amount = "1.00"; expect(() => assertPayablesBatch(falseAbsence, f.period)).toThrow("PAYABLE_ABSENCE_AMOUNT_INVALID"); const draft = structuredClone(f.draft); draft.method.source = ""; expect(() => stampPayablesWork(draft, f.imports, f.scope, f.period, "RUN", actor.id, "2025-02-01T10:00:00.000Z")).toThrow(); });
    it("méthodes divergentes empêchent le regroupement monétaire du même événement", async () => { const a = await fixture("payables.purchases"), b = await fixture(); b.work = { ...b.work, method: { ...b.work.method, version: "2" } }; const imports = [...new Map([...a.imports, ...b.imports].map(b => [b.id, b])).values()]; const m = buildPayablesMission(a.scope, [asRun(a, "PURCHASES"), asRun(b)], imports, imports.map(b => ({ document_type: b.document.documentType, import_id: b.id }))); expect(m.exposures.find(e => e.procedureIds.length === 2)?.amount.kind).toBe("unknown"); });
    it("recherche comptable non datée à clôture reste non concluante et garde le dénominateur", async () => { const f = await fixture(); const source = structuredClone(f.imports.find(b => b.document.documentType === "payables_recognition")!); source.rows[0].normalized!.date = "2025-01-12"; f.imports = f.imports.map(b => b.id === source.id ? source : b); const facts = buildPayablesFacts(f.scope, f.period, f.imports, "RUN", f.procedure); expect(facts.events.find(e => e.id === "I-U")?.cutoff.status).toBe("inconclusive"); });
});
