import { expect, it } from "vitest";
import { adaptTaxWorkpaper, exactTaxCents, type TaxAdapterInput } from "../tax-adapter";
import { createTaxPeriod, createTaxProfile } from "@/lib/tax/canonical";
import { periodInput, profileInput } from "@/lib/tax/__tests__/fixtures";
import { period, scope } from "./fixtures";
import { proof, known } from "./cutoff-fixtures";
function fixture(): TaxAdapterInput { const owned = { organizationId: scope.organizationId, dossierId: scope.dossierId, entityId: "SYN-E" }; const v = { amount: known("100.00").value, date: period.closingDate, basis: "after_tax", evidence: [proof] }; return { context: { scope, period, purpose: "synthetic_technical" }, tax: { ...owned, profile: createTaxProfile(profileInput({ ...owned, accountingPeriod: { startDate: period.startDate, endDate: period.closingDate } })), period: createTaxPeriod(periodInput({ ...owned, startDate: period.startDate, endDate: period.closingDate })), documents: [], executionStates: [], plannerVersion: "tax-control-planner-1.0.0" }, ruleVersion: "SYN-1", sourceVersions: [proof.documentVersionId], resultConvention: "profit_positive", resultBasis: "after_tax", accountingResult: v, clientAccountingResult: v, adjustments: [] }; }
it("raccord exact, profil conservé et aucune formule d’impôt inventée", () => { const x = fixture(), r = adaptTaxWorkpaper(x); expect(r.fiscalBridge).toEqual(known("100.00")); expect(r.taxDue.kind).toBe("unknown"); expect(r.taxProfileId).toBe(x.tax.profile.id); expect(r.sourceVersions).toEqual(x.sourceVersions); });
it("convention crédit/débit explicite", () => { const x = fixture(); x.resultConvention = "credits_negative"; x.accountingResult = { ...x.accountingResult, amount: known("-100.00").value }; expect(adaptTaxWorkpaper(x).accountingDifference).toEqual(known("0.00")); });
it("réel, autre dossier, conversion inexacte et double IS refusés", () => { const x = fixture(); expect(() => exactTaxCents(known("90071992547409.92").value)).toThrow(); x.context.scope = { ...scope, mode: "real" }; expect(() => adaptTaxWorkpaper(x)).toThrow(); const y = fixture(); y.resultBasis = "before_tax"; y.adjustments = [{ id: "A", economicEventId: "TAX", kind: "reintegration", isIncomeTaxExpense: true, value: y.accountingResult, method: null }]; expect(() => adaptTaxWorkpaper(y)).toThrow("DOUBLE"); const z = fixture(); z.tax = { ...z.tax, dossierId: "OTHER" }; expect(() => adaptTaxWorkpaper(z)).toThrow(); });
