import { expect, test } from "@playwright/test";
for (const width of [390, 768, 1440]) test(`atelier synthétique préparation/revue/export — ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 });
  await page.goto("/dashboard/tests");
  const workshop = page.getByRole("region", { name: "Atelier des cycles — DÉMONSTRATION" });
  await expect(workshop).toBeVisible();
  await workshop.getByRole("combobox", { name: "Cycle", exact: true }).selectOption("clients");
  const launched = page.waitForResponse((r) => r.url().endsWith("/api/workpapers") && r.request().method() === "PUT");
  await workshop.getByRole("button", { name: "Exécuter une nouvelle démonstration" }).click();
  const response = await launched;
  expect(response.status()).toBe(200);
  const result = await response.json();
  console.log("SYNTHETIC_METRIC", { width, ...result.metrics });
  await expect(workshop.getByRole("status")).toContainText("executed", { timeout: 60000 });
  const note = workshop.getByLabel(/Commentaire de préparation/);
  await note.fill("Préparation synthétique limitée, aucun verdict métier");
  await workshop.getByRole("button", { name: "Préparateur simulé : soumettre" }).click();
  await expect(workshop.getByRole("status")).toContainText("awaiting_review");
  await note.fill("Revue technique synthétique, sources réelles requises");
  await workshop.getByRole("button", { name: "Reviewer simulé : approuver le travail" }).click();
  await expect(workshop.getByRole("status")).toContainText("approved");
  await note.fill("Gel de la démonstration uniquement");
  await workshop.getByRole("button", { name: "Verrouiller la projection démonstrative" }).click();
  await expect(workshop.getByRole("status")).toContainText("locked");
  await expect(workshop.getByText(/1 prévues · 1 exécutées · 1 verrouillées/)).toBeVisible();
  await workshop.getByRole("button", { name: "Préparer l’export figé" }).click();
  await expect(workshop.getByRole("button", { name: "Télécharger Markdown" })).toBeVisible();
  await workshop.getByText(/Table exacte des montants/).click();
  await expect(workshop.getByRole("table", { name: /Valeurs du résultat/ })).toBeVisible();
  await workshop.getByRole("button", { name: "Télécharger Markdown" }).focus();
  await page.keyboard.press("Tab");
  await expect(workshop.getByRole("button", { name: "Télécharger le snapshot JSON" })).toBeFocused();
  await workshop.getByRole("heading", { name: "Atelier des cycles — DÉMONSTRATION" }).evaluate((element) => element.scrollIntoView({ block: "center" }));
  await page.screenshot({ path: `e2e/.artifacts/phase-de-${width}.png` });
  await workshop.getByText(/Table exacte des montants/).evaluate((element) => element.scrollIntoView({ block: "center" }));
  await page.screenshot({ path: `e2e/.artifacts/phase-de-table-${width}.png` });
});
