"use client";
import { useEffect, useId, useState } from "react";
import type { WorkpaperRun, EvidenceLink } from "@/lib/workpapers/model";
import type { ClientsSalesDraft, ClientsSalesFacts, ClientsSalesResult } from "@/lib/workpapers/clients-sales";
import { amountLabel, locatorLabel } from "@/lib/workpapers/client-mission";
import type { Money } from "@/lib/canonical-model/money";
import styles from "./ClientReceivablesPanel.module.css";
type EvidenceRef = ClientsSalesDraft["window"]["evidenceRefs"][number];
type SourceOption = ClientsSalesFacts["sourceOptions"][number];
type Tab = "allocations" | "estimate" | "confirmations";
const money = (amount: string): Money => ({ amount, currency: "EUR" });
function canonicalMoney(value: Money): Money { const match = /^(0|[1-9]\d*)(?:\.(\d{0,2}))?$/.exec(value.amount); return match ? money(match[1] + "." + (match[2] ?? "").padEnd(2, "0")) : value; }
const confirmationLabels: Record<string, string> = { alternative_documented: "Procédure alternative documentée", response_pending: "Réponse attendue", not_tested: "Rapprochement non testé", agrees_on_tested_items: "Accord sur les éléments testés", differences: "Différences maintenues" };
const refKey = (r: EvidenceRef) => JSON.stringify([r.importId, r.rowId]);
function nextDay(value: string) { const date = new Date(value + "T12:00:00Z"); if (!Number.isFinite(date.getTime())) return ""; date.setUTCDate(date.getUTCDate() + 1); return date.toISOString().slice(0, 10); }
function initialDraft(run: WorkpaperRun): ClientsSalesDraft { return { window: { startDate: nextDay(run.period.closingDate), endDate: run.period.asOfDate, coverage: "incomplete", note: "", evidenceRefs: [] }, creditsAbsence: null, allocations: [], estimates: [], confirmations: [] }; }
function EvidenceSelect({ label, options, value, onChange, disabled }: { label: string; options: SourceOption[]; value: EvidenceRef[]; onChange: (refs: EvidenceRef[]) => void; disabled: boolean }) {
  const keys = new Set(value.map(refKey));
  return <label className={styles.evidence}>{label}<select multiple aria-label={label} disabled={disabled} value={[...keys]} onChange={e => onChange(Array.from(e.target.selectedOptions, o => JSON.parse(o.value) as [string, string]).map(([importId, rowId]) => ({ importId, rowId })))}>{options.map(o => <option key={refKey(o)} value={refKey(o)}>{o.label} — {o.fileName}, {locatorLabel(o.locator)}</option>)}</select><span className={styles.muted}>Choisissez les lignes qui documentent ce traitement. Un registre ne remplace pas un original absent.</span></label>;
}
function ProofList({ evidence, options }: { evidence: EvidenceLink[]; options: SourceOption[] }) { return <>{evidence.length ? evidence.map(p => { const source = options.find(o => o.documentVersionId === p.documentVersionId && (!p.rowId || o.rowId === p.rowId)); return <details key={p.id}><summary>{source?.fileName ?? "Source référencée"} — {locatorLabel(p.locator)}</summary><p>{p.purpose}</p><code>{p.id}</code><code>Document {p.documentVersionId}</code><code>Ligne {p.rowId ?? "non précisée"}</code></details>; }) : <p>Pièce absente : l’incertitude reste ouverte.</p>}</>; }
export type ClientReceivablesPanelProps = { run: WorkpaperRun; draft: ClientsSalesDraft | null; facts: ClientsSalesFacts | null; editable: boolean; busy: boolean; onConfigure: (draft: ClientsSalesDraft) => void; onFreeze: (input: Pick<ClientsSalesDraft, "window" | "creditsAbsence">) => void; onDraftChange?: (draft: ClientsSalesDraft) => void };
/** Exact server results remain visible while business drafts are edited or saved. */
export function ClientReceivablesPanel({ run, draft, facts, editable, busy, onConfigure, onFreeze, onDraftChange }: ClientReceivablesPanelProps) {
  const id = useId();
  const [form, setForm] = useState<ClientsSalesDraft>(() => draft ?? initialDraft(run));
  const [tab, setTab] = useState<Tab>("allocations"), [selected, setSelected] = useState("");
  const [paymentId, setPaymentId] = useState(""), [allocationAmount, setAllocationAmount] = useState(""), [allocationProofs, setAllocationProofs] = useState<EvidenceRef[]>([]);
  useEffect(() => { setForm(draft ?? initialDraft(run)); }, [draft, run]); // New server snapshot, never an optimistic calculation.
  const result = run.result?.execution === "completed" ? run.result.result as ClientsSalesResult : null;
  const options = facts?.sourceOptions ?? [], invoices = facts?.invoices ?? [], payments = facts?.payments ?? [];
  const selectedId = invoices.some(i => i.id === selected) ? selected : invoices[0]?.id ?? "";
  const invoice = invoices.find(i => i.id === selectedId), row = result?.rows.find(r => r.invoiceId === selectedId);
  const proofList = row?.evidence ?? invoice?.evidence ?? [];
  const disabled = busy || !editable;
  const update = (change: (f: ClientsSalesDraft) => ClientsSalesDraft) => { const next = change(form); setForm(next); onDraftChange?.(next); };
  const changeWindow = (fields: Partial<ClientsSalesDraft["window"]>) => update(f => ({ ...f, window: { ...f.window, ...fields } }));
  const estimate = form.estimates.find(e => e.invoiceId === selectedId);
  const savedEstimate = result?.estimates.find(e => e.invoiceId === selectedId);
  const confirmation = form.confirmations.find(c => c.invoiceIds.includes(selectedId));
  const savedConfirmation = result?.confirmations.find(c => c.invoiceIds.includes(selectedId));
  const setEstimate = (fields: Partial<ClientsSalesDraft["estimates"][number]>) => update(f => { const old = f.estimates.find(e => e.invoiceId === selectedId); const value = { id: old?.id ?? crypto.randomUUID(), invoiceId: selectedId, method: null, base: row?.dueAtReview ?? invoice?.amount ?? money("0.00"), amount: money("0.00"), rationale: "", dispute: "", evidenceRefs: [], ...old, ...fields }; return { ...f, estimates: [...f.estimates.filter(e => e.invoiceId !== selectedId), value] }; });
  const setConfirmation = (fields: Partial<ClientsSalesDraft["confirmations"][number]>) => update(f => { const old = f.confirmations.find(c => c.invoiceIds.includes(selectedId)); const value = { id: old?.id ?? crypto.randomUUID(), invoiceIds: [selectedId], request: null, response: null, reconciliation: { status: "not_tested" as const, note: "", evidenceRefs: [] }, alternative: null, ...old, ...fields }; return { ...f, confirmations: [...f.confirmations.filter(c => !c.invoiceIds.includes(selectedId)), value] }; });
  return <section className={styles.panel} aria-labelledby={id + "-title"}>
    <h2 id={id + "-title"}>Encaissements, avoirs et jugement Clients</h2>
    <p className={styles.muted}>Version serveur {run.version}. La clôture reste figée ; les événements ultérieurs expliquent le solde à la revue. Le reste ne constitue pas une perte estimée.</p>
    <section className={styles.window} aria-labelledby={id + "-window"}><h3 id={id + "-window"}>Fenêtre d’encaissements et population</h3><div className={styles.fields}>
      <label>Début de la fenêtre<input type="date" value={form.window.startDate} disabled={disabled} onChange={e => changeWindow({ startDate: e.target.value })}/></label><label>Fin de la fenêtre<input type="date" value={form.window.endDate} disabled={disabled} onChange={e => changeWindow({ endDate: e.target.value })}/></label><label>Complétude documentée<select value={form.window.coverage} disabled={disabled} onChange={e => changeWindow({ coverage: e.target.value as ClientsSalesDraft["window"]["coverage"] })}><option value="incomplete">Fenêtre incomplète</option><option value="documented">Fenêtre documentée</option></select></label>
      <label className={styles.evidence}>Note de périmètre<textarea value={form.window.note} disabled={disabled} onChange={e => changeWindow({ note: e.target.value })}/></label><EvidenceSelect label="Preuves de la fenêtre" options={options} value={form.window.evidenceRefs} disabled={disabled} onChange={evidenceRefs => changeWindow({ evidenceRefs })}/>
      <label className={styles.check}><input type="checkbox" checked={form.creditsAbsence !== null} disabled={disabled} onChange={e => update(f => ({ ...f, creditsAbsence: e.target.checked ? { note: "", evidenceRefs: [] } : null }))}/>Absence d’avoirs documentée pour cette fenêtre</label>
      {form.creditsAbsence && <><label className={styles.evidence}>Justification de l’absence d’avoirs<textarea value={form.creditsAbsence.note} disabled={disabled} onChange={e => update(f => ({ ...f, creditsAbsence: { ...f.creditsAbsence!, note: e.target.value } }))}/></label><EvidenceSelect label="Preuves de l’absence d’avoirs" options={options} value={form.creditsAbsence.evidenceRefs} disabled={disabled} onChange={evidenceRefs => update(f => ({ ...f, creditsAbsence: { ...f.creditsAbsence!, evidenceRefs } }))}/></>}
    </div>{run.state === "draft" && editable && <button disabled={busy || !form.window.note.trim() || !form.window.evidenceRefs.length} onClick={() => onFreeze({ window: form.window, creditsAbsence: form.creditsAbsence })}>Figer les factures et cette fenêtre</button>}</section>
    {result && <details className={styles.proof}><summary>Fenêtre et avoirs documentés dans le résultat serveur</summary><p>{result.window.startDate} au {result.window.endDate} : {result.window.coverage === "documented" ? "fenêtre documentée" : "couverture incomplète"}. {result.window.note}</p><ProofList evidence={result.window.evidence} options={options}/>{result.creditsAbsence ? <><p>Absence d’avoirs documentée : {result.creditsAbsence.note}</p><ProofList evidence={result.creditsAbsence.evidence} options={options}/></> : <p>Consultez la source des avoirs ; leur absence n’est pas déclarée par ce résultat.</p>}</details>}
    {!facts && <p role="status">Importez et approuvez les sources Clients pour préparer la population.</p>}
    <div className={styles.table} tabIndex={0} role="region" aria-label="Factures Clients — défilement clavier"><table><caption>Soldes à clôture et à revue ; montants issus des sources et du calcul serveur</caption><thead><tr><th>Client / facture</th><th>Dates et âge</th><th>Solde clôture</th><th>Encaissements affectés ultérieurs</th><th>Avoirs ultérieurs</th><th>Reste à la revue</th><th>Incertitude</th></tr></thead><tbody>{invoices.map(i => { const r = result?.rows.find(v => v.invoiceId === i.id); return <tr key={i.id} aria-selected={selectedId === i.id}><th scope="row">{i.customerId}<br/><button onClick={() => setSelected(i.id)} aria-label={"Examiner la facture " + i.id}>{i.id}</button></th><td>Facture {i.issuedOn}<br/>{i.dueOn ? "Échéance " + i.dueOn : "Échéance inconnue"}<br/>{r ? r.aging.days + " " + r.aging.label : i.dueOn ? "Âge à calculer" : "Âge depuis facture ; retard indéterminé"}</td><td className={styles.money}>{amountLabel(r?.dueAtClosing ?? i.amount)}</td><td className={styles.money}>{r ? amountLabel(r.subsequentPayments) : "Non calculé"}</td><td className={styles.money}>{r ? amountLabel(r.subsequentCredits) : "Non calculé"}</td><td className={styles.money}>{r ? amountLabel(r.dueAtReview) : "Non calculé"}</td><td>{r?.uncertainties.join(" ; ") || "Recouvrabilité à documenter ; aucun jugement automatique."}</td></tr>; })}{!invoices.length && <tr><td colSpan={7}>Aucune facture ouverte figée pour cette feuille.</td></tr>}</tbody></table></div>
    {invoice && <><div className={styles.details}><section aria-label="Frise clôture à revue"><h3>Facture {selectedId} : clôture puis revue</h3><ol className={styles.timeline}><li><time>{run.period.closingDate}</time><strong>Solde ouvert à la clôture : {amountLabel(row?.dueAtClosing ?? invoice.amount)}</strong><p className={styles.muted}>Ce solde est conservé dans cette version.</p></li>{row?.timeline.map(event => <li key={event.id}><time>{event.date}</time><strong>{event.label}</strong><p>{amountLabel(event.amount)}{event.effect === "review" ? " · effet à la revue" : event.effect === "none" ? " · sans effet validé sur le solde" : " · événement de clôture"}</p><p className={styles.muted}>{event.proofIds.length ? event.proofIds.length + " référence(s) de preuve" : "Preuve attendue"}</p></li>)}<li><time>{run.period.asOfDate}</time><strong>Reste à la revue : {row ? amountLabel(row.dueAtReview) : "Non calculé"}</strong><p className={styles.muted}>Montant résiduel distinct de l’estimation de dépréciation.</p></li></ol></section><aside className={styles.proof} aria-label="Preuves de la facture"><h3>Preuves rattachées</h3><ProofList evidence={proofList} options={options}/><p className={styles.muted}>Les pièces binaires peuvent être absentes du paquet. Leur téléchargement séparé conserve le contrôle d’accès du dossier.</p></aside></div>
    <nav className={styles.tabs} aria-label="Travaux sur la facture" role="tablist">{([{ id: "allocations", label: "Allocations et résiduels" }, { id: "estimate", label: "Litiges et estimation" }, { id: "confirmations", label: "Confirmations et preuves" }] as { id: Tab; label: string }[]).map(t => <button key={t.id} id={id + "-tab-" + t.id} role="tab" tabIndex={tab === t.id ? 0 : -1} onKeyDown={e => { const order: Tab[] = ["allocations", "estimate", "confirmations"]; const current = order.indexOf(tab); const next = e.key === "ArrowRight" ? order[(current + 1) % 3] : e.key === "ArrowLeft" ? order[(current + 2) % 3] : e.key === "Home" ? order[0] : e.key === "End" ? order[2] : null; if (next) { e.preventDefault(); setTab(next); document.getElementById(id + "-tab-" + next)?.focus(); } }} aria-selected={tab === t.id} aria-controls={id + "-panel-" + t.id} onClick={() => setTab(t.id)}>{t.label}</button>)}</nav>
    <section hidden={tab !== "allocations"} id={id + "-panel-allocations"} role="tabpanel" aria-labelledby={id + "-tab-allocations"}><div className={styles.allocation}><div><h3>Propositions et allocations validées</h3><p className={styles.muted}>Une proposition d’appariement n’affecte aucun solde. Une allocation validée prend effet après le contrôle et l’accusé serveur.</p>
      {form.allocations.filter(a => a.invoiceId === selectedId).map(a => <article key={a.id} className={styles.entry}><p><strong>{a.paymentId}</strong> : {amountLabel(a.amount)} <span className={styles.badge + (a.status === "proposed" ? " " + styles.proposed : "")}>{a.status === "proposed" ? "Proposition d’appariement" : result?.allocations.some(v => v.id === a.id && v.status === "validated") ? "Allocation validée — accusé serveur" : "Allocation à valider par le serveur"}</span></p>{a.status === "validated" && result?.allocations.filter(v => v.id === a.id && v.status === "validated").map(v => <div key={v.id}><p className={styles.muted}>Allocation validée par {v.authorId} · {v.authoredAt}</p><ProofList evidence={v.evidence} options={options}/></div>)}<div className={styles.actions}>{editable && <><button disabled={busy} onClick={() => update(f => ({ ...f, allocations: f.allocations.map(v => v.id === a.id ? { ...v, status: v.status === "proposed" ? "validated" : "proposed" } : v) }))}>{a.status === "proposed" ? "Demander la validation de cette allocation" : "Revenir à une proposition"}</button><button disabled={busy} onClick={() => update(f => ({ ...f, allocations: f.allocations.filter(v => v.id !== a.id) }))}>Retirer {a.paymentId} de ce brouillon</button></>}</div></article>)}
      {editable && <form onSubmit={e => { e.preventDefault(); if (busy || !paymentId || !allocationAmount) return; update(f => ({ ...f, allocations: [...f.allocations, { id: crypto.randomUUID(), paymentId, invoiceId: selectedId, amount: money(allocationAmount), status: "proposed", evidenceRefs: allocationProofs }] })); setAllocationAmount(""); }}><div className={styles.fields}><label>Encaissement à proposer<select required disabled={busy} value={paymentId} onChange={e => setPaymentId(e.target.value)}><option value="">Choisir un encaissement</option>{payments.map(p => <option key={p.id} value={p.id}>{p.id} — {p.customerId} — {amountLabel(p.amount)}</option>)}</select></label><label>Montant de l’appariement<input required inputMode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" placeholder="300.00" disabled={busy} value={allocationAmount} onChange={e => setAllocationAmount(e.target.value)}/></label><EvidenceSelect label="Preuves de l’appariement" options={options} value={allocationProofs} disabled={busy} onChange={setAllocationProofs}/></div><button disabled={busy || !paymentId || !allocationAmount || !allocationProofs.length}>Ajouter une proposition</button></form>}
    </div><aside className={styles.proof} aria-label="Soldes résiduels des encaissements"><h3>Encaissements : résiduels serveur</h3>{result?.payments.length ? result.payments.map(p => <div className={styles.entry} key={p.id}><strong>{p.id} — {p.customerId}</strong><p>{p.kind === "advance" ? "Acompte" : p.kind === "grouped" ? "Paiement groupé" : "Encaissement"} du {p.paidOn} · {amountLabel(p.amount)}</p><p>Affecté validé : {amountLabel(p.validatedAllocated)}<br/>Proposé : {amountLabel(p.proposedAmount)}<br/>Résiduel non affecté : {amountLabel(p.residualUnallocated)}<br/>Disponible : {amountLabel(p.availableToAllocate)}</p>{p.cancelledOn && <p className={styles.status}>Annulé le {p.cancelledOn}</p>}</div>) : <p>Exécutez le calcul pour obtenir les résiduels validés. Les brouillons ne mettent pas ces montants à jour.</p>}</aside></div></section>
    <section hidden={tab !== "estimate"} id={id + "-panel-estimate"} role="tabpanel" aria-labelledby={id + "-tab-estimate"}><h3>Jugement documenté sur la facture {selectedId}</h3><p className={styles.status}>L’ancienneté et le reste à la revue ne suffisent pas à établir une dépréciation ni une créance entièrement sûre.</p>{savedEstimate && <p>Estimation serveur : {amountLabel(savedEstimate.amount)} · Auteur réel : {savedEstimate.authorId} · {savedEstimate.authoredAt}. {savedEstimate.status === "documented" ? "Méthode et base documentées" : "Estimation non étayée"}</p>}
      <div className={styles.fields}><label className={styles.evidence}>Litige / incertitude<textarea value={estimate?.dispute ?? ""} disabled={disabled} onChange={e => setEstimate({ dispute: e.target.value })}/></label><label>Base de l’estimation<input inputMode="decimal" value={estimate?.base.amount ?? ""} disabled={disabled} onChange={e => setEstimate({ base: money(e.target.value) })}/></label><label>Montant estimé<input inputMode="decimal" value={estimate?.amount.amount ?? ""} disabled={disabled} onChange={e => setEstimate({ amount: money(e.target.value) })}/></label><label className={styles.check}><input type="checkbox" checked={!!estimate?.method} disabled={disabled} onChange={e => setEstimate({ method: e.target.checked ? { id: "", version: "", source: "", basis: "", from: run.period.startDate, to: run.period.closingDate } : null })}/>Méthode documentée disponible</label>
      {estimate?.method && (["id", "version", "source", "basis", "from", "to"] as const).map(key => <label key={key}>{{ id: "Identifiant de méthode", version: "Version de méthode", source: "Source de la méthode", basis: "Convention / base de calcul", from: "Méthode applicable du", to: "Méthode applicable au" }[key]}<input type={key === "from" || key === "to" ? "date" : "text"} value={estimate.method![key]} disabled={disabled} onChange={e => setEstimate({ method: { ...estimate.method!, [key]: e.target.value } })}/></label>)}
      <label className={styles.evidence}>Raisonnement de l’estimation<textarea value={estimate?.rationale ?? ""} disabled={disabled} onChange={e => setEstimate({ rationale: e.target.value })}/></label><EvidenceSelect label="Pièces de l’estimation" options={options} value={estimate?.evidenceRefs ?? []} disabled={disabled} onChange={evidenceRefs => setEstimate({ evidenceRefs })}/></div>{!estimate?.method && <p className={styles.muted}>Méthode absente : estimation non étayée, incertitude maintenue.</p>}
    </section>
    <section hidden={tab !== "confirmations"} id={id + "-panel-confirmations"} role="tabpanel" aria-labelledby={id + "-tab-confirmations"}><h3>Suivi de confirmation pour {selectedId}</h3><p className={styles.muted}>Consignez les demandes, réponses et procédures alternatives. Ce suivi n’envoie aucun message externe.</p>{savedConfirmation && <p>Dernier auteur réel : {savedConfirmation.authorId} · {savedConfirmation.authoredAt} · {confirmationLabels[savedConfirmation.status] ?? "Suivi à examiner"}</p>}
      <div className={styles.fields}><label className={styles.check}><input type="checkbox" disabled={disabled} checked={!!confirmation?.request} onChange={e => setConfirmation({ request: e.target.checked ? { date: run.period.asOfDate, channel: "", evidenceRefs: [] } : null, ...(e.target.checked ? {} : { response: null }) })}/>Demande documentée</label>{confirmation?.request && <><label>Date de demande<input type="date" value={confirmation.request.date} disabled={disabled} onChange={e => setConfirmation({ request: { ...confirmation.request!, date: e.target.value } })}/></label><label>Canal de demande<input value={confirmation.request.channel} disabled={disabled} onChange={e => setConfirmation({ request: { ...confirmation.request!, channel: e.target.value } })}/></label><EvidenceSelect label="Preuves de la demande" options={options} value={confirmation.request.evidenceRefs} disabled={disabled} onChange={evidenceRefs => setConfirmation({ request: { ...confirmation.request!, evidenceRefs } })}/></>}
      <label className={styles.check}><input type="checkbox" disabled={disabled || !confirmation?.request} checked={!!confirmation?.response} onChange={e => setConfirmation({ response: e.target.checked ? { date: run.period.asOfDate, confirmedAt: run.period.closingDate, origin: "unknown", channel: "", evidenceRefs: [], originEvidenceRefs: [] } : null })}/>Réponse reçue</label>{confirmation?.response && <><label>Date de réponse<input type="date" value={confirmation.response.date} disabled={disabled} onChange={e => setConfirmation({ response: { ...confirmation.response!, date: e.target.value } })}/></label><label>Solde confirmé à la date<input type="date" value={confirmation.response.confirmedAt} disabled={disabled} onChange={e => setConfirmation({ response: { ...confirmation.response!, confirmedAt: e.target.value } })}/></label><label>Origine déclarée<select value={confirmation.response.origin} disabled={disabled} onChange={e => setConfirmation({ response: { ...confirmation.response!, origin: e.target.value as NonNullable<ClientsSalesDraft["confirmations"][number]["response"]>["origin"] } })}><option value="unknown">Origine inconnue</option><option value="client_provided">Transmise par le client</option><option value="direct_documented">Réponse directe documentée</option></select></label><label>Canal de réponse<input value={confirmation.response.channel} disabled={disabled} onChange={e => setConfirmation({ response: { ...confirmation.response!, channel: e.target.value } })}/></label><EvidenceSelect label="Preuves de la réponse" options={options} value={confirmation.response.evidenceRefs} disabled={disabled} onChange={evidenceRefs => setConfirmation({ response: { ...confirmation.response!, evidenceRefs } })}/><EvidenceSelect label="Preuves de l’origine directe" options={options} value={confirmation.response.originEvidenceRefs} disabled={disabled} onChange={originEvidenceRefs => setConfirmation({ response: { ...confirmation.response!, originEvidenceRefs } })}/></>}
      <label>Rapprochement de confirmation<select value={confirmation?.reconciliation.status ?? "not_tested"} disabled={disabled} onChange={e => setConfirmation({ reconciliation: { ...(confirmation?.reconciliation ?? { note: "", evidenceRefs: [] }), status: e.target.value as ClientsSalesDraft["confirmations"][number]["reconciliation"]["status"] } })}><option value="not_tested">Non testé</option><option value="agrees_on_tested_items">Accord sur les éléments testés</option><option value="differences">Différences à expliquer</option></select></label><label className={styles.evidence}>Note de rapprochement<textarea value={confirmation?.reconciliation.note ?? ""} disabled={disabled} onChange={e => setConfirmation({ reconciliation: { ...(confirmation?.reconciliation ?? { status: "not_tested", evidenceRefs: [] }), note: e.target.value } })}/></label><EvidenceSelect label="Preuves du rapprochement" options={options} value={confirmation?.reconciliation.evidenceRefs ?? []} disabled={disabled} onChange={evidenceRefs => setConfirmation({ reconciliation: { ...(confirmation?.reconciliation ?? { status: "not_tested", note: "" }), evidenceRefs } })}/>
      <label className={styles.check}><input type="checkbox" checked={!!confirmation?.alternative} disabled={disabled} onChange={e => setConfirmation({ alternative: e.target.checked ? { performedOn: run.period.asOfDate, note: "", evidenceRefs: [] } : null })}/>Procédure alternative documentée</label>{confirmation?.alternative && <><label>Date de la procédure alternative<input type="date" value={confirmation.alternative.performedOn} disabled={disabled} onChange={e => setConfirmation({ alternative: { ...confirmation.alternative!, performedOn: e.target.value } })}/></label><label className={styles.evidence}>Travail alternatif réalisé<textarea value={confirmation.alternative.note} disabled={disabled} onChange={e => setConfirmation({ alternative: { ...confirmation.alternative!, note: e.target.value } })}/></label><EvidenceSelect label="Preuves de la procédure alternative" options={options} value={confirmation.alternative.evidenceRefs} disabled={disabled} onChange={evidenceRefs => setConfirmation({ alternative: { ...confirmation.alternative!, evidenceRefs } })}/></>}
      </div><p className={styles.status}>L’origine déclarée et les lignes de registre ne suffisent pas à authentifier un original absent. La revue du travail ne prouve pas automatiquement le recouvrement.</p>{savedConfirmation && <><p className={styles.muted}>{savedConfirmation.record.response ? "Réponse du " + savedConfirmation.record.response.date + " ; origine retenue : " + (savedConfirmation.record.response.origin === "direct_documented" ? "directe documentée" : savedConfirmation.record.response.origin === "client_provided" ? "transmise par le client" : "non authentifiée") : "Aucune réponse documentée dans le résultat serveur."}</p><ProofList evidence={savedConfirmation.evidence} options={options}/></>}
    </section>
    {editable && run.state !== "draft" && <div className={styles.actions}><button disabled={busy} onClick={() => onConfigure({ ...form, allocations: form.allocations.map(a => ({ ...a, amount: canonicalMoney(a.amount) })), estimates: form.estimates.map(e => ({ ...e, base: canonicalMoney(e.base), amount: canonicalMoney(e.amount) })) })}>Sauvegarder allocations et jugement</button><p className={styles.muted}>Les montants restent ceux du dernier calcul serveur jusqu’à l’exécution de cette configuration sauvegardée.</p></div>}
    </>}
    {result?.credits.length ? <section aria-label="Avoirs du résultat serveur"><h3>Avoirs et rattachement</h3>{result.credits.map(credit => <article className={styles.entry} key={credit.id}><p><strong>{credit.id}</strong> · {credit.customerId} · facture {credit.invoiceId} · {amountLabel(credit.amount)} · {credit.issuedOn}</p><p>{credit.status === "applied" ? "Avoir affecté à la revue" : "Avoir à rattacher ; aucune réduction de solde validée"}</p><ProofList evidence={credit.evidence} options={options}/></article>)}</section> : null}
    {result?.exceptions.length ? <section aria-label="Exceptions Clients"><h3>Exceptions et incertitudes de cette version</h3>{result.exceptions.map(e => <article className={styles.entry} key={e.id}><strong>{e.label}</strong><p>{e.message}</p><p className={styles.muted}>{e.targetId} · {amountLabel(e.amount)} · {e.proofIds.length} référence(s) de preuve</p></article>)}<p className={styles.muted}>Ces exceptions restent reliées à la Synthèse et à l’export de cette version, y compris après revue.</p></section> : null}
  </section>;
}
