"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { amountLabel, locatorLabel, missionSheetHref, type ClientMissionSnapshot, type MissionFilter } from "@/lib/workpapers/client-mission";
import styles from "./ClientMissionSynthesis.module.css";
type ExportFormat = "html" | "pdf" | "json" | "manifest" | "exceptions_csv" | "decisions_csv" | "procedures_csv" | "sources_csv";
const csvFormats = [{ id: "exceptions_csv", label: "Exceptions" }, { id: "decisions_csv", label: "Décisions" }, { id: "procedures_csv", label: "Procédures" }, { id: "sources_csv", label: "Index des sources" }] as const;
type View = { actorId: string; permissions: string[]; mission: ClientMissionSnapshot };
const filters: { id: MissionFilter; label: string }[] = [{ id: "all", label: "Tous les travaux" }, { id: "blocked", label: "Blocages" }, { id: "exceptions", label: "Exceptions à expliquer" }, { id: "evidence", label: "Pièces attendues" }, { id: "review", label: "Revues" }, { id: "stale", label: "Travaux périmés" }];
export function ClientMissionSynthesis({ initialDossierId = "", initialPeriodId = "", initialRootId = "", initialRunId = "", initialVersion }: { initialDossierId?: string; initialPeriodId?: string; initialRootId?: string; initialRunId?: string; initialVersion?: number }) {
  const [dossier, setDossier] = useState(initialDossierId), [period, setPeriod] = useState(initialPeriodId);
  const [scope, setScope] = useState({ dossierId: initialDossierId, periodId: initialPeriodId });
  const [rootId, setRootId] = useState(initialRootId), [version, setVersion] = useState<{ id: string; version: number } | null>(initialRunId && Number.isSafeInteger(initialVersion) && initialVersion! > 0 ? { id: initialRunId, version: initialVersion! } : null);
  const [view, setView] = useState<View | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(false);
  const [filter, setFilter] = useState<MissionFilter>("all"), [proofId, setProofId] = useState<string | null>(null), [exporting, setExporting] = useState(false);
  const load = useCallback(async () => {
    if (!scope.dossierId || !scope.periodId) return;
    setLoading(true); setError("");
    try {
      const q = new URLSearchParams({ ...scope, operation: "mission", ...(rootId ? { rootId } : {}), ...(version ? { id: version.id, version: String(version.version) } : {}) });
      const response = await fetch("/api/workpapers/clients?" + q, { cache: "no-store" });
      const data = await response.json();
      if (!response.ok) throw new Error(response.status === 401 ? "Session requise ou expirée : reconnectez-vous." : response.status === 403 ? "Accès refusé à ce dossier." : response.status === 503 ? "La chaîne de recette durable est indisponible ou désactivée." : "La synthèse demandée est indisponible. Vérifiez le dossier et la version.");
      if (!data.mission || !data.actorId) throw new Error("Réponse serveur incomplète.");
      setView(data);
    } catch (e) { setError(e instanceof Error ? e.message : "Chargement impossible"); setView(null); }
    finally { setLoading(false); }
  }, [scope, rootId, version]);
  useEffect(() => { void load(); }, [load]);
  const m = view?.mission, p = m?.procedure;
  const approvedReady = p?.state === "locked" && !p.stale && p.comparisons.every(c => c.conventionValidated);
  const comparisonRows = p?.comparisons.flatMap(c => c.rows.map(row => ({ ...row, comparison: c.label, convention: c.convention, coverage: c.coverage }))) ?? [];
  const focusedRow = comparisonRows.find(r => r.id === proofId);
  const sales = p?.sales;
  const salesProofTargets = sales ? [
    { id: "window", label: "Fenêtre documentée clôture → revue", proofs: sales.window.evidence },
    { id: "credits-absence", label: "Absence d’avoirs documentée", proofs: sales.creditsAbsence?.evidence ?? [] },
    ...sales.rows.map(r => ({ id: "invoice:" + r.invoiceId, label: "Facture " + r.invoiceId, proofs: r.evidence })),
    ...sales.credits.map(r => ({ id: "credit:" + r.id, label: "Avoir " + r.id, proofs: r.evidence })),
    ...sales.payments.map(r => ({ id: "payment:" + r.id, label: "Paiement " + r.id, proofs: r.evidence })),
    ...sales.allocations.map(r => ({ id: "allocation:" + r.id, label: "Allocation " + r.id, proofs: r.evidence })),
    ...sales.estimates.map(r => ({ id: "estimate:" + r.id, label: "Estimation " + r.id, proofs: r.evidence })),
    ...sales.confirmations.map(r => ({ id: "confirmation:" + r.id, label: "Confirmation " + r.id + " v" + r.record.version, proofs: r.evidence })),
  ] : [];
  const allSalesProofs = salesProofTargets.flatMap(t => t.proofs);
  const exceptionTargets = sales?.exceptions.map(e => ({ id: "exception:" + e.id, label: e.label + " · " + e.targetId, proofs: allSalesProofs.filter(p => e.proofIds.includes(p.id)).filter((p, index, all) => all.findIndex(other => other.id === p.id) === index) })) ?? [];
  const focusedSales = [...salesProofTargets, ...exceptionTargets].find(t => t.id === proofId);
  const selectedProofs = (focusedRow?.proofs ?? focusedSales?.proofs ?? p?.evidence ?? []).filter((proof, index, all) => all.findIndex(other => other.id === proof.id) === index);
  const visibleNotes = p?.notes.filter(n => filter === "all" || filter === "blocked" && n.blocking && !n.resolution) ?? [];
  const queue = m?.queue.filter(q => filter === "all" || q.category === filter) ?? [];
  const visibleRows = comparisonRows.filter(r => filter === "all" || filter === "exceptions" && (r.exception || r.difference.kind !== "known") || filter === "stale" && p?.stale || filter === "review" && (p?.review || p?.state === "awaiting_review"));
  async function download(kind: "diagnostic" | "approved", format: ExportFormat) {
    if (!m || exporting) return;
    setExporting(true); setError("");
    try {
      const session = await fetch("/api/auth/session", { cache: "no-store" }), identity = await session.json();
      if (!session.ok || !identity.authenticated || !identity.csrfToken) throw new Error("Session requise ou expirée : reconnectez-vous.");
      const response = await fetch("/api/workpapers/clients/export", { method: "POST", headers: { "Content-Type": "application/json", "x-probant-csrf": identity.csrfToken },
        body: JSON.stringify({ dossierId: m.scope.dossierId, periodId: m.scope.periodId, ...(m.assignment.rootId ? { rootId: m.assignment.rootId } : {}), ...(p?.runId ? { id: p.runId, version: p.version } : {}), kind, format, expectedSnapshotHash: m.hash }) });
      if (!response.ok) { const e = await response.json(); throw new Error(response.status === 409 ? "L’état serveur a changé depuis l’affichage. Actualisez la synthèse puis refaites l’export." : response.status === 401 ? "Votre session a expiré." : response.status === 403 ? "Votre identité ne peut pas exporter ce dossier." : e.error === "EXPORT_APPROVED_CURRENT_LOCKED_REQUIRED" ? "Un paquet approuvé exige une version courante, revue et verrouillée." : "L’export a été refusé par le serveur."); }
      if (response.headers.get("X-Probant-Snapshot") !== m.hash) throw new Error("L’export ne correspond pas à l’état affiché.");
      const url = URL.createObjectURL(await response.blob()), a = document.createElement("a");
      a.href = url; a.download = response.headers.get("Content-Disposition")?.match(/filename="([^"]+)"/)?.[1] ?? "probant-clients-" + kind + "." + format;
      a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
    } catch (e) { setError(e instanceof Error ? e.message : "Export impossible"); }
    finally { setExporting(false); }
  }
  return <main className={styles.workspace}>
    <nav aria-label="Familles de travaux" className={styles.families}><Link href="/dashboard/synthese">Constats historiques DEMO SA</Link><Link href="/dashboard/tests">Atelier synthétique</Link><span aria-current="page">Procédures de mission · Clients</span></nav>
    <header className={styles.header}><div><p className={styles.eyebrow}>MISSION · RECETTE JETABLE</p><h1>Revue et Synthèse Clients</h1><p>Le cadrage et les travaux Clients, leurs preuves et les décisions sur chaque version.</p></div><Link className={styles.button} href={m && p?.runId && p.version ? missionSheetHref(m.scope, { id: p.runId, version: p.version }, filter) : m ? "/clients-framing?" + new URLSearchParams({ dossierId: m.scope.dossierId, periodId: m.scope.periodId }) : "/clients-framing"}>Ouvrir la feuille pilote</Link></header>
    <form className={styles.scope} onSubmit={e => { e.preventDefault(); setVersion(null); setRootId(""); setScope({ dossierId: dossier.trim(), periodId: period.trim() }); }}><label>Dossier<input required value={dossier} onChange={e => setDossier(e.target.value)} placeholder="Identifiant du dossier"/></label><label>Période<input required value={period} onChange={e => setPeriod(e.target.value)} placeholder="Identifiant de période de la feuille"/></label><button className={styles.button} disabled={loading}>Charger la mission</button><Link href={"/api/auth/login?returnTo=" + encodeURIComponent("/clients-framing/synthesis?" + new URLSearchParams(scope))}>Se connecter</Link></form>
    <p className={styles.muted}>Cette Synthèse reprend le programme fermé des procédures Clients. Les constats DEMO SA et les exercices de l’atelier gardent leurs propres sources.</p>
    {loading && <p role="status">Lecture de l’état serveur…</p>}{error && <p role="alert" className={styles.alert}>{error}</p>}
    {m && p && <>
      <div className={styles.missionMeta}><span>Dossier {m.scope.dossierId}</span><span>Organisation {m.scope.organizationId}</span><span>Identité connectée : {view.actorId}</span><button onClick={() => void load()} disabled={loading}>Actualiser</button></div>
      {m.assignment.choices.length > 1 && <label>Feuille affectée au programme<select value={m.assignment.rootId ?? ""} onChange={e => { setRootId(e.target.value); setVersion(null); }}><option value="" disabled>Choisir une feuille</option>{m.assignment.choices.map(id => <option key={id} value={id}>{m.assignment.options.find(o => o.rootId === id)?.label ?? id} · {id}</option>)}</select></label>}
      <div className={styles.programme}><strong>Programme {m.program.version}</strong><span>{m.counters.executed}/{m.counters.planned} procédure exécutée</span><span>{m.counters.testedParts}/{m.counters.plannedParts} contrôles complets</span><span>{m.counters.reviewed}/{m.counters.planned} revue documentée et courante</span><span>{m.counters.exceptions} exceptions</span></div>
      <section className={styles.programStates} aria-label="Procédures du programme"><h2>Programme et décisions</h2><div className={styles.tableScroll}><table><thead><tr><th>Procédure</th><th>Version</th><th>Résultat / revue</th><th>Actualité et accès</th></tr></thead><tbody>{m.procedures.map(procedure => <tr key={procedure.id} aria-selected={procedure.id === p.id}><th scope="row">{procedure.label}{procedure.id === p.id && <p>Procédure sélectionnée</p>}</th><td>{procedure.runId ?? "À préparer"} · v{procedure.version ?? "—"}</td><td>{procedure.resultLabel}<p>{procedure.reviewLabel}{procedure.review && " · " + procedure.review.actorId}</p></td><td>{procedure.stale ? procedure.staleReasons.join(" ") : procedure.runId ? "Version courante" : "Procédure prévue, non préparée"}{procedure.runId && procedure.version && <Link href={missionSheetHref(m.scope, { id: procedure.runId, version: procedure.version }, "all")}>Ouvrir cette version</Link>}</td></tr>)}</tbody></table></div><p className={styles.muted}>Chaque décision porte sur sa propre procédure et version. Les exceptions restent distinctes de l’avancement du programme.</p></section>
      <div className={styles.version}><p>{p.period && `${p.period.startDate} au ${p.period.closingDate} · revue au ${p.period.asOfDate} · `}Feuille {p.runId ?? "À préparer"} · révision {p.revision ?? "—"} · version affichée {p.version ?? "—"}. Préparateur : {p.preparedBy ?? "Non attribué"}.</p>{m.versionIndex.length > 0 && <label>Version à examiner<select aria-label="Version à examiner" value={p.runId + ":v" + p.version} onChange={e => { const v = m.versionIndex.find(v => v.id + ":v" + v.version === e.target.value)!; setVersion({ id: v.id, version: v.version }); }}><option value={m.assignment.currentRunId + ":v" + m.assignment.currentVersion}>Courante · v{m.assignment.currentVersion}</option>{m.versionIndex.filter(v => v.id !== m.assignment.currentRunId || v.version !== m.assignment.currentVersion).map(v => <option key={v.id + ":" + v.version} value={v.id + ":v" + v.version}>r{v.revision} · v{v.version} · {v.state}</option>)}</select></label>}</div>
      {p.stale && <p role="status" className={styles.alert}>Travail périmé — {p.staleReasons.join(" ")}</p>}
      <nav className={styles.filters} aria-label="Filtres métier">{filters.map(f => <button key={f.id} aria-pressed={filter === f.id} onClick={() => setFilter(f.id)}>{f.label}</button>)}</nav>
      <div className={styles.layout}>
        <aside className={styles.queue}><h2>File de travail</h2><p className={styles.muted}>Priorité aux blocages et aux travaux périmés.</p>{queue.length ? <ol>{queue.map(q => <li key={q.id} data-category={q.category}><Link href={q.href}>{q.label}</Link><p>{q.detail}</p></li>)}</ol> : <p>Aucune action dans ce filtre.</p>}</aside>
        <section className={styles.decisions}><h2>{p.id === "clients.sales" ? "Décisions Clients et ventes" : "Décisions et résidus de cadrage"}</h2><p className={styles.outcome}>{p.resultLabel}</p><p className={styles.review}>{p.reviewLabel}{p.review && " · " + p.review.actorId + " · " + p.review.at}</p><p>{p.conclusion}</p>
          <p className={styles.muted}>Revue documentée ne signifie pas conformité des comptes.</p>
          {sales && <SalesMissionDetails sales={sales} filter={filter} stale={p.stale} onProof={setProofId}/>}
          <div className={styles.tableScroll} tabIndex={0} role="region" aria-label="Décisions détaillées — défilement clavier"><table><caption>Version {p.version ?? "—"} · résultat {p.resultId ?? "non exécuté"}</caption><thead><tr><th>Rapprochement / clé</th><th>Différence</th><th>Constat après revue</th><th>Preuve et feuille</th></tr></thead><tbody>{visibleRows.map(r => <tr key={r.id} aria-selected={proofId === r.id}><th scope="row">{r.comparison}<br/>{r.key}</th><td>{amountLabel(r.difference)}</td><td>{r.exception ? "Exception maintenue" : r.difference.kind !== "known" ? "Incertitude" : "Aucun écart sur cette clé"}</td><td><button onClick={() => setProofId(r.id)} aria-label={"Examiner les preuves de " + r.key}>Examiner les preuves</button>{p.runId && p.version && <Link href={missionSheetHref(m.scope, { id: p.runId, version: p.version }, filter)}>Ouvrir la feuille v{p.version}</Link>}</td></tr>)}{visibleNotes.map(n => <tr key={n.id}><th scope="row">Commentaire de {n.authorId}</th><td>{amountLabel(n.amount)}</td><td>{n.text}<p>{n.resolution ? "Traitement documenté : " + n.resolution.text : n.blocking ? "Point bloquant ouvert" : "À expliquer"}</p></td><td>{p.runId && p.version && <Link href={missionSheetHref(m.scope, { id: p.runId, version: p.version }, "blocked", n.id)}>Voir le commentaire</Link>}</td></tr>)}{!visibleRows.length && !visibleNotes.length && !sales && <tr><td colSpan={4}>Aucun résultat dans ce filtre.</td></tr>}</tbody></table></div>
          <div className={styles.coverage}><h3>Périmètre testé</h3><p>{p.coverage.numerator}/{p.coverage.denominator ?? "inconnu"} {p.coverage.unit}. {p.coverage.criteria}.</p><p>Exclusions : {p.coverage.exclusions.length ? p.coverage.exclusions.map(e => e.id + " : " + e.reason).join(" ; ") : "Aucune"}.</p>{p.comparisons.map(c => <p key={c.id}>{c.label} : {c.coverage.numerator}/{c.coverage.denominator ?? "inconnu"} {c.coverage.unit}. Exclusions : {c.coverage.exclusions.length ? c.coverage.exclusions.map(e => e.reason).join(" ; ") : "aucune"}.<br/><span className={styles.muted}>{c.convention}</span></p>)}<p className={styles.muted}>{m.amountGrouping.reason}</p></div>
          <h3>Avant / après revue</h3><div className={styles.comparison}><div><strong>Version soumise {p.beforeReview?.version ?? "—"}</strong><p>{p.beforeReview?.conclusion ?? "Aucune soumission conservée pour cette version."}</p><p>{p.beforeReview?.resultLabel}</p></div><div><strong>Après revue · version {p.afterReview?.version ?? "—"}</strong><p>{p.review?.note ?? "Aucune décision de revue."}</p><p>{p.afterReview?.resultLabel}</p></div></div>
          <details><summary>Historique des versions et décisions</summary><ul>{m.versionIndex.map(v => <li key={v.id + ":" + v.version}>r{v.revision} v{v.version} · {v.state} · {v.actorId}{v.approval && " · " + v.approval.actorId + " : " + v.approval.note}{v.reviewNotes.map(n => <p key={n.id}>{n.authorId} : {n.text}</p>)}<code>{v.contentHash}</code></li>)}</ul></details>
        </section>
        <aside className={styles.proof} aria-label="Panneau de preuve"><h2>Preuves de la version</h2><p>{focusedRow ? focusedRow.comparison + " · " + focusedRow.key : focusedSales?.label ?? "Sélectionnez une clé, une facture ou une décision dans la table."}</p>{focusedRow && <p>Gauche {amountLabel(focusedRow.left)}<br/>Droite {amountLabel(focusedRow.right)}</p>}
          {selectedProofs.length ? selectedProofs.map((e, i) => { const source = m.sources.find(s => s.id === e.documentVersionId); return <div key={e.id + ":" + i} className={styles.source}><strong>{source?.fileName ?? e.documentVersionId}</strong><p>{locatorLabel(e.locator)}</p><p>{source?.current ? "Source courante" : "Source remplacée ou absente"}</p><details><summary>Identité et version de la preuve</summary><code>{e.id}</code><code>Ligne {e.rowId ?? "—"}</code><code>Document {e.documentVersionId}</code><code>SHA-256 {source?.sha256 ?? "absent"}</code></details>{source?.available && view.permissions.includes("download") && <a href={"/api/workpapers/clients?" + new URLSearchParams({ dossierId: m.scope.dossierId, periodId: m.scope.periodId, operation: "download", id: e.documentVersionId })}>Télécharger l’original séparément</a>}</div>; }) : <p>Aucune preuve rattachée.</p>}
          <h3>Index des pièces</h3>{m.sources.map(s => <div className={styles.source} key={s.id}><strong>{s.label}</strong><p>{s.fileName ?? "Pièce attendue et absente"}</p><p>{s.available ? s.current ? "Courante" : "Périmée" : "Absente"} · binaire absent du paquet</p><p>Approbation : {s.approvedBy ?? "Non approuvée"} · {s.approvedAt ?? "—"}</p><details><summary>Versions de la source et du mapping</summary><code>{s.id}</code><code>SHA-256 {s.sha256 ?? "absent"}</code><p>Parseur {s.parserVersion ?? "—"} · mapping {s.mappingVersion ?? "—"}</p><code>{s.mappingHash ?? "Absent"}</code></details></div>)}
        </aside>
      </div>
      <section className={styles.exports}><h2>Export de cet état serveur</h2><p>Résumé, procédures, population, calculs, exceptions, décisions et index des pièces. Les originaux sont à télécharger séparément.</p>{view.permissions.includes("download") ? <><div><strong>Diagnostic</strong>{(["html", "pdf", "json", "manifest"] as const).map(f => <button key={f} disabled={exporting} onClick={() => void download("diagnostic", f)}>{f === "html" ? "HTML imprimable" : f.toUpperCase()}</button>)}<select aria-label="Télécharger un CSV diagnostic" value="" disabled={exporting} onChange={e => void download("diagnostic", e.target.value as ExportFormat)}><option value="" disabled>CSV…</option>{csvFormats.map(f => <option key={f.id} value={f.id}>{f.label}</option>)}</select></div><div><strong>Paquet approuvé · procédure sélectionnée</strong>{(["html", "pdf", "json", "manifest"] as const).map(f => <button key={f} disabled={exporting || !approvedReady} onClick={() => void download("approved", f)}>{f === "html" ? "HTML imprimable" : f.toUpperCase()}</button>)}<select aria-label="Télécharger un CSV du paquet approuvé" value="" disabled={exporting || !approvedReady} onChange={e => void download("approved", e.target.value as ExportFormat)}><option value="" disabled>CSV…</option>{csvFormats.map(f => <option key={f.id} value={f.id}>{f.label}</option>)}</select></div><p>{exporting ? "Génération et contrôle serveur…" : approvedReady ? "Procédure sélectionnée courante, revue et verrouillée. Aucune approbation implicite des autres procédures ni opinion sur les comptes." : "Paquet approuvé disponible après revue distincte et verrouillage de la version courante."}</p></> : <p>Votre identité ne dispose pas de la permission d’export.</p>}<details><summary>Limites et identité de l’état</summary><ul>{m.limitations.map(l => <li key={l}>{l}</li>)}</ul><code>{m.hash}</code></details></section>
    </>}
  </main>;
}

function SalesMissionDetails({ sales: s, filter, stale, onProof }: { sales: NonNullable<ClientMissionSnapshot["procedure"]["sales"]>; filter: MissionFilter; stale: boolean; onProof: (id: string) => void }) {
  const exceptions = s.exceptions.filter(e => filter === "all" || filter === "exceptions" || filter === "evidence" && !e.proofIds.length || filter === "stale" && stale || filter === "review");
  return <div className={styles.salesDetails}>
    <p>Clôture {s.closingDate} → revue {s.reviewDate}. Fenêtre {s.window.startDate} → {s.window.endDate} · {s.window.coverage === "documented" ? "documentée" : "incomplète"}.</p>
    <p>{s.window.note} <button onClick={() => onProof("window")}>Preuves de la fenêtre</button></p>
    {s.creditsAbsence && <p>Avoirs : {s.creditsAbsence.note} <button onClick={() => onProof("credits-absence")}>Preuves de l’absence d’avoirs</button></p>}
    <p className={styles.muted}>Solde de clôture figé. Le reste dû ne constitue ni une perte estimée ni une créance entièrement sûre. L’échéance absente produit un âge depuis facture.</p>
    <div className={styles.tableScroll} tabIndex={0} role="region" aria-label="Factures et encaissements"><table><caption>Soldes clôture / revue et incertitudes</caption><thead><tr><th>Client / facture</th><th>Clôture</th><th>Encaissements / avoirs</th><th>Reste revue / âge</th><th>Incertitude / preuve</th></tr></thead><tbody>{s.rows.map(r => <tr key={r.invoiceId}><th scope="row">{r.customerId} / {r.invoiceId}<p>Facture {r.issuedOn}<br/>Échéance {r.dueOn ?? "inconnue"}</p></th><td>{amountLabel(r.dueAtClosing)}</td><td>{amountLabel(r.subsequentPayments)}<p>Avoirs {amountLabel(r.subsequentCredits)}</p></td><td>{amountLabel(r.dueAtReview)}<p>{r.aging.days} {r.aging.label}<br/>Retard {r.overdueDays === null ? "non déterminé" : r.overdueDays + " jours"}</p></td><td>{r.uncertainties.map(t => <p key={t}>{t}</p>)}<button onClick={() => onProof("invoice:" + r.invoiceId)}>Preuves de la facture {r.invoiceId}</button></td></tr>)}</tbody></table></div>
    <div className={styles.tableScroll} tabIndex={0} role="region" aria-label="Exceptions Clients versionnées"><table><caption>Exceptions maintenues après revue</caption><thead><tr><th>Contrôle / objet</th><th>Constat</th><th>Montant / preuve</th></tr></thead><tbody>{exceptions.map(e => <tr key={e.id}><th scope="row">{e.label}<p>{e.controlId} · {e.targetId}</p></th><td>{e.message}<p>Exception maintenue</p></td><td>{amountLabel(e.amount)}<button onClick={() => onProof("exception:" + e.id)}>Preuves de l’exception {e.targetId}</button><code>{e.id}</code></td></tr>)}{!exceptions.length && <tr><td colSpan={3}>Aucune exception dans ce filtre ; la portée du test reste limitée.</td></tr>}</tbody></table></div>
    <details><summary>Frise clôture → revue et événements</summary>{s.rows.map(r => <div key={r.invoiceId}><h3>Facture {r.invoiceId}</h3><ol className={styles.timeline}>{r.timeline.map(t => <li key={t.id}><strong>{t.date} · {t.label}</strong><p>{amountLabel(t.amount)} · {t.effect === "closing" ? "Clôture figée" : t.effect === "review" ? "Effet à la revue uniquement" : "Aucun effet automatique sur les soldes"}</p><code>{t.proofIds.join(" ; ") || "Calcul issu des événements documentés"}</code></li>)}</ol></div>)}</details>
    <details><summary>Avoirs et rattachement</summary>{s.credits.length ? s.credits.map(c => <div key={c.id} className={styles.source}><strong>Avoir {c.id} · {c.customerId} / {c.invoiceId}</strong><p>{c.issuedOn} · {amountLabel(c.amount)} · {c.status === "applied" ? "Avoir affecté au solde de revue" : "À rattacher — aucun effet sur les soldes"}</p><button onClick={() => onProof("credit:" + c.id)}>Preuves de l’avoir {c.id}</button></div>) : <p>Aucun avoir importé ; la justification de l’absence figure ci-dessus lorsqu’elle est documentée.</p>}</details>
    <details><summary>Allocations et paiements résiduels</summary><div className={styles.tableScroll}><table><caption>Propositions distinctes des allocations validées</caption><thead><tr><th>Paiement / tiers</th><th>Montant / état</th><th>Affecté / proposé</th><th>Résiduel / disponible</th></tr></thead><tbody>{s.payments.map(p => <tr key={p.id}><th scope="row">{p.id} / {p.customerId}<p>{p.kind}</p></th><td>{amountLabel(p.amount)} · {p.paidOn}<p>{p.cancelledOn ? "Annulation " + p.cancelledOn : "Actif"}</p></td><td>{amountLabel(p.validatedAllocated)}<p>Proposé {amountLabel(p.proposedAmount)}</p></td><td>{amountLabel(p.residualUnallocated)}<p>Disponible {amountLabel(p.availableToAllocate)}</p><button onClick={() => onProof("payment:" + p.id)}>Preuves du paiement {p.id}</button></td></tr>)}</tbody></table></div>{s.allocations.map(a => <div key={a.id} className={styles.source}><strong>{a.id} · {a.paymentId} → {a.invoiceId}</strong><p>{amountLabel(a.amount)} · {a.status === "validated" ? "Allocation validée" : "Appariement proposé — aucun effet sur les soldes"}</p><p>{a.authorId} · {a.authoredAt}</p><button onClick={() => onProof("allocation:" + a.id)}>Preuves de l’allocation {a.id}</button></div>)}</details>
    <details><summary>Litiges et estimations</summary>{s.estimates.length ? s.estimates.map(e => <div key={e.id} className={styles.source}><strong>{e.invoiceId} · estimation {e.id}</strong><p>{e.method ? e.method.id + " @ " + e.method.version + " · " + e.method.source + " · " + e.method.basis + " · " + e.method.from + " → " + e.method.to : "Méthode absente — estimation non conclue"}</p><p>Base {amountLabel(e.base)} · estimation déclarée {amountLabel(e.amount)} · écart {amountLabel(e.difference)}</p><p>Litige : {e.dispute || "Non documenté"}. {e.rationale}</p><p>Auteur réel : {e.authorId} · {e.authoredAt}</p><button onClick={() => onProof("estimate:" + e.id)}>Preuves de l’estimation {e.id}</button></div>) : <p>Estimation non documentée ; aucun jugement automatique de perte ou de sûreté.</p>}</details>
    <details><summary>Confirmations et pièces reliées</summary>{s.confirmations.length ? s.confirmations.map(c => <div key={c.id} className={styles.source}><strong>Confirmation {c.id} v{c.record.version} · {c.invoiceIds.join(", ")}</strong><p>Demande {c.record.request?.date ?? "non documentée"} · réponse {c.record.response?.date ?? "absente"} · {c.status}</p><p>Origine déclarée : {c.declaredOrigin ?? "absente"}. Origine établie : {c.record.response?.origin === "unknown" ? "inconnue — original externe et revue attendus" : c.record.response?.origin ?? "absente"}.</p><p>{c.record.reconciliation.status} · {c.record.reconciliation.note}</p>{c.record.alternative && <p>Alternative {c.record.alternative.performedOn} : {c.record.alternative.note}</p>}<p>Auteur réel : {c.authorId} · {c.authoredAt}. Aucun envoi externe automatique.</p><button onClick={() => onProof("confirmation:" + c.id)}>Preuves de la confirmation {c.id}</button></div>) : <p>Aucune confirmation documentée.</p>}</details>
    <p className={styles.muted}>Cadrage lié {s.framing.runId} v{s.framing.version} · {s.framing.contentHash}</p>
  </div>;
}
