'use client';
import { useEffect, useRef, useState } from 'react';
import type { PDFDocumentProxy, RenderTask } from 'pdfjs-dist';
import s from './Equity.module.css';
export function EquityProofPage({url,page,label}:{url:string;page:number;label:string}){
 const canvas=useRef<HTMLCanvasElement>(null),[state,setState]=useState('Chargement de la page…'),[text,setText]=useState(''),[attempt,setAttempt]=useState(0),[loading,setLoading]=useState(true);
 useEffect(()=>{const controller=new AbortController();let active=true,document:PDFDocumentProxy|undefined,render:RenderTask|undefined;setState('Chargement de la page…');setText('');setLoading(true);if(canvas.current){canvas.current.width=0;canvas.current.height=0;}void(async()=>{try{const response=await fetch(url.split('#')[0],{cache:'no-store',signal:controller.signal});if(!response.ok)throw Error(response.status===403?'Accès à la pièce refusé.':response.status===401?'Session expirée : reconnectez-vous.':'Pièce indisponible.');const bytes=new Uint8Array(await response.arrayBuffer()),pdf=await import('pdfjs-dist');pdf.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).toString();document=await pdf.getDocument({data:bytes,isEvalSupported:false}).promise;if(!active)return;if(page<1||page>document.numPages)throw Error('Page absente de cette version.');const source=await document.getPage(page);if(!active)return;const viewport=source.getViewport({scale:1.4}),target=canvas.current,context=target?.getContext('2d');if(!target||!context)return;target.height=viewport.height;target.width=viewport.width;render=source.render({canvasContext:context,viewport});await render.promise;const content=await source.getTextContent();if(active){setText(content.items.map(i=>'str' in i?i.str:'').join(' '));setState('Page '+page+' de '+document.numPages+' · version téléchargée');}}catch(e){if(active)setState(e instanceof Error?e.message:'Lecture PDF impossible.');}finally{if(active)setLoading(false);}})();return()=>{active=false;controller.abort();render?.cancel();void document?.destroy();};},[url,page,attempt]);
 return <figure className={s.pdf}><figcaption className={s.muted} role='status'>{state}</figcaption><button disabled={loading} onClick={()=>setAttempt(v=>v+1)}>Relire cette page</button><canvas ref={canvas} role='img' aria-label={label+' — page '+page} /><details><summary>Texte extrait de cette page</summary><p>{text||'Aucun texte extrait ; consultez la page ou ouvrez le PDF.'}</p></details></figure>;
}
