'use client';
import { useState } from 'react';
import type { WorkpaperRun } from '@/lib/workpapers/model';
import type { EquityFact } from './EquityView';
import s from './Equity.module.css';
export function EquityReview({run,facts,canPrepare,canReview,busy,demo,command}:{run:WorkpaperRun;facts:EquityFact[];canPrepare:boolean;canReview:boolean;busy:boolean;demo:boolean;command:(cmd:string,extra?:Record<string,unknown>)=>void}){
 const[text,setText]=useState(''),[proof,setProof]=useState(''),[noteId,setNoteId]=useState(run.notes[0]?.id??'');const source=facts.find(f=>f.rowId===proof),citation=source?{documentVersionId:source.documentVersionId,rowId:source.rowId,...(source.page?{page:source.page}:{})}:undefined,valid=!!citation&&!!text.trim();
 return <><h2>Décisions humaines et revue</h2><p>Chaque traitement cite une pièce du dossier, sa version et son localisateur. La revue conserve les exceptions du calcul.</p>{demo&&<p className={s.banner}>Recette en lecture seule. Une identité synthétique ne peut ni soumettre ni approuver un dossier réel.</p>}<div className={s.comparison}><div><h3>Avant revue · version soumise</h3><p>Préparateur {run.preparedBy}</p><p>{run.conclusion??'Conclusion non documentée'}</p><p className={s.muted}>Empreinte soumise : {run.submittedHash??'Non soumise'}</p><p>{run.notes.length} observations conservées</p></div><div><h3>Après revue · décision humaine</h3><p>{run.approval?'Auteur '+run.approval.actorId:'Revue distincte attendue'}</p><p>{run.approval?.note??'Aucune décision de revue à cette version'}</p><p>Un statut revu ne vaut pas conformité juridique.</p></div></div>
 <ul className={s.queue}>{run.notes.map(n=><li key={n.id} tabIndex={-1} id={'equity-note-'+n.id}><strong>{n.text}</strong><p className={s.muted}>Constat par {n.authorId}</p><p>{n.resolution?.text??'Traitement attendu'}</p>{n.resolution&&<p className={s.muted}>Traitement par {n.resolution.authorId}</p>}</li>)}</ul>
 <fieldset disabled={busy||demo||(!canPrepare&&!canReview)}><legend>Traitement ou décision à enregistrer</legend><label>Pièce et version<select value={proof} onChange={e=>setProof(e.target.value)}><option value=''>Choisir la source citée</option>{facts.map(f=><option key={f.rowId} value={f.rowId}>{f.fileName} · {f.page?'page '+f.page:f.id} · version {f.version.slice(0,12)}</option>)}</select></label><label>Raisonnement et portée<textarea value={text} onChange={e=>setText(e.target.value)} placeholder='Écart expliqué, réserve maintenue, travaux complémentaires…' /></label>{source&&<p className={s.muted}>Citation : {source.fileName} · {source.documentVersionId} · version {source.version}{source.page?' · page '+source.page:''}</p>}<label>Observation à traiter<select value={noteId} onChange={e=>setNoteId(e.target.value)}><option value=''>Choisir une observation</option>{run.notes.map(n=><option key={n.id} value={n.id}>{n.text}</option>)}</select></label><div className={s.actions}><button disabled={!canPrepare||!valid||!noteId||busy} onClick={()=>command('resolve',{noteId,text,citation})}>Documenter le traitement de l’observation</button><button disabled={!canPrepare||!valid||busy} onClick={()=>command('conclude',{text,citation})}>Sauvegarder la conclusion de travaux</button><button disabled={!canReview||run.state!=='awaiting_review'||!valid||busy} onClick={()=>command('review',{decision:'changes_requested',text,citation,submittedHash:run.submittedHash})}>Demander une reprise</button><button disabled={!canReview||run.state!=='awaiting_review'||!valid||busy} onClick={()=>command('review',{decision:'approved',text,citation,submittedHash:run.submittedHash})}>Approuver les travaux de cette version</button></div></fieldset><div className={s.actions}><button className={s.primary} disabled={!canPrepare||busy||!run.conclusion||run.notes.some(n=>n.blocking&&!n.resolution)} onClick={()=>command('submit')}>Soumettre à une autre identité autorisée</button><button disabled={!canReview||busy||run.state!=='approved'} onClick={()=>command('lock')}>Verrouiller la version approuvée</button></div><p className={s.muted}>L’identité et les droits sont vérifiés au serveur ; l’auto-approbation est refusée.</p></>;
}
