'use client';
import { useEffect, useRef, useState } from 'react';
import { periodId, type WorkpaperRun } from '@/lib/workpapers/model';
import type { AccountingPeriod } from '@/lib/canonical-model/period';
import type { ImportBatch } from '@/lib/workpapers/imports';
import type { EquityDraft } from '@/lib/workpapers/equity-dossier';
import type { EquityMission } from '@/lib/workpapers/equity-mission';
import { EQUITY_TYPES, EQUITY_LABELS, equityEventTarget, EQUITY_FAILURES } from '@/lib/workpapers/equity-program';
import { EquityPreparation, emptyEquityDraft } from './EquityPreparation';
import { EquityImportForm } from './EquityImportForm';
import { EquityResults } from './EquityResults';
import { EquityReview } from './EquityReview';
import { equityAmount, STATES, type EquityFact } from './EquityView';
import s from './Equity.module.css';
type Initial={dossierId:string;periodId:string;id?:string;version?:number;event:string;filter:string;tab:string;demo:boolean;incomplete:boolean;longText:boolean};
type View={actorId:string;permissions:string[];runs:WorkpaperRun[];imports:ImportBatch[];sourceHeads:{document_type:string;import_id:string}[];facts:Record<string,EquityFact[]>};
const emptyPeriod:AccountingPeriod={startDate:'',closingDate:'',asOfDate:'',currency:'EUR',validation:'provisional'};
const tabs=[['population','Population'],['tests','Tests'],['exceptions','Exceptions'],['proof','Pièces'],['review','Revue']] as const;
function draftOf(run:WorkpaperRun){if(!run.equityWork)return emptyEquityDraft();const{authorId:_a,authoredAt:_t,...draft}=run.equityWork;void _a;void _t;return draft;}
export function equityFailure(status:number,code:string){if(EQUITY_FAILURES[code]&&![401,403,409,503].includes(status))return EQUITY_FAILURES[code];if(status===413)return 'Le fichier, la population ou le paquet dépasse la limite de ce parcours. Réduisez le volume fourni.';return status===401?'Session requise ou expirée : reconnectez-vous.':status===403?'Accès refusé pour cette identité, ou auto-approbation interdite.':status===409?'Une version ou une source a changé. Comparez les états avant de reprendre.':status===503?'La chaîne durable est désactivée ou indisponible. Une infrastructure de recette jetable est requise.':'L’opération ne peut pas être enregistrée. Vérifiez les champs, le mapping et les pièces de cette version.';}
export function EquityWorkspace({initial,synthesis=false}:{initial:Initial;synthesis?:boolean}){
 const demoCase=initial.incomplete?'incomplete':initial.longText?'long':'';
 const[scope,setScope]=useState({dossierId:initial.dossierId,periodId:initial.periodId}),[dossier,setDossier]=useState(initial.dossierId),[period,setPeriod]=useState(emptyPeriod),[target,setTarget]=useState({id:initial.id,version:initial.version}),[view,setView]=useState<View|null>(null),[mission,setMission]=useState<EquityMission|null>(null),[draft,setDraft]=useState<EquityDraft>(emptyEquityDraft),[tab,setTab]=useState(tabs.some(t=>t[0]===initial.tab)?initial.tab:'tests'),[busy,setBusy]=useState(false),[status,setStatus]=useState('Aucune sauvegarde effectuée'),[error,setError]=useState(''),[conflict,setConflict]=useState<WorkpaperRun|null>(null),[preview,setPreview]=useState<ImportBatch|null>(null),[criteria,setCriteria]=useState(''),[exclusions,setExclusions]=useState<Record<string,string>>({});
 const csrf=useRef(''),inflight=useRef(false),pending=useRef<{body:Record<string,unknown>|FormData;imports:boolean;key:string}|null>(null),tabsRef=useRef<(HTMLButtonElement|null)[]>([]);
 const run=mission?.run??view?.runs.find(r=>r.id===target.id)??(view?.runs.length===1?view.runs[0]:undefined),facts=run?view?.facts[run.id]??[]:[],real=!initial.demo,current=!!run&&!mission?.stale,canPrepare=real&&current&&view?.permissions.includes('prepare')&&view.actorId===run!.preparedBy&&['draft','ready','executed'].includes(run!.state),canReview=real&&current&&view?.permissions.includes('review')&&view.actorId!==run!.preparedBy;
 const q=(extra:Record<string,string>={})=>new URLSearchParams({...scope,...extra});
 const links=initial.demo?new URLSearchParams({demo:'1',...(demoCase?{case:demoCase}:{})}):q(run?{id:run.id,version:String(run.version)}:{});
 async function session(){const r=await fetch('/api/auth/session',{cache:'no-store'}),d=await r.json();if(!r.ok||!d.csrfToken)throw Error(equityFailure(r.ok?401:r.status,d.error??'SESSION_INVALID'));csrf.current=d.csrfToken;}
 async function load(focus=target){if(real&&(!scope.dossierId||!scope.periodId))return;setBusy(true);setError('');try{if(initial.demo){const r=await fetch('/api/workpapers/equity/demo'+(demoCase?'?case='+demoCase:''),{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error('Exemple synthétique désactivé sur cet environnement.');setMission(d.mission);setView({actorId:d.actorId,permissions:[],runs:[d.mission.run],imports:[],sourceHeads:[],facts:{[d.mission.run.id]:d.facts}});setPeriod(d.mission.run.period);setDraft(draftOf(d.mission.run));return;}
 await session();const extra=focus.id?{id:focus.id,...(focus.version?{version:String(focus.version)}:{})}:{};const results=await Promise.all([fetch('/api/workpapers/equity?'+q({...extra,...(focus.version?{operation:'version'}:{})}),{cache:'no-store'}),fetch('/api/workpapers/equity?'+q({...extra,operation:'mission'}),{cache:'no-store'})]);const data=await Promise.all(results.map(r=>r.json()));for(let i=0;i<results.length;i++)if(!results[i].ok)throw Error(equityFailure(results[i].status,data[i].error));setView(data[0]);setMission(data[1].mission);const r=data[1].mission.run??data[0].runs.find((r:WorkpaperRun)=>r.id===focus.id);if(r){setDraft(draftOf(r));setPeriod(r.period);}setConflict(null);
 }catch(e){setError(e instanceof Error?e.message:'Lecture impossible');}finally{setBusy(false);}}
 useEffect(()=>{void load();/* Explicit scope/version navigation only. */ // eslint-disable-next-line react-hooks/exhaustive-deps
 },[scope,target.id,target.version]);
 function change(d:EquityDraft){setDraft(d);pending.current=null;setStatus('Modifications non sauvegardées');}
 async function mutate(body:Record<string,unknown>|FormData,imports=false,retry=false){if(!real||inflight.current)return;const active=document.activeElement as HTMLElement|null,position={x:scrollX,y:scrollY};inflight.current=true;setBusy(true);setStatus('Sauvegarde en cours…');setError('');if(!retry)pending.current={body,imports,key:crypto.randomUUID()};const p=pending.current!;try{await session();const r=await fetch('/api/workpapers/equity'+(p.imports?'/imports':'')+'?'+q(),{method:'POST',headers:{'x-probant-csrf':csrf.current,'Idempotency-Key':p.key,...(p.body instanceof FormData?{}:{'Content-Type':'application/json'})},body:p.body instanceof FormData?p.body:JSON.stringify(p.body)}),d=await r.json();if(r.status===409&&d.current){setConflict(d.current);setStatus('Conflit de modification');return;}if(!r.ok)throw Error(equityFailure(r.status,d.error));pending.current=null;setStatus('Sauvegardée — accusé serveur reçu');if(d.batch&&p.body instanceof FormData)setPreview(d.batch);else if(d.batch){setPreview(null);await load({id:run?.id,version:undefined});}if(d.run){setTarget({id:d.run.id,version:undefined});setDraft(draftOf(d.run));await load({id:d.run.id,version:undefined});}
 }catch(e){setStatus('Échec de sauvegarde');setError(e instanceof Error?e.message:'Échec serveur');}finally{inflight.current=false;setBusy(false);requestAnimationFrame(()=>{if(active?.isConnected)active.focus({preventScroll:true});window.scrollTo(position.x,position.y);});}}
 const command=(command:string,extra:Record<string,unknown>={})=>run&&void mutate({command,id:run.id,expectedVersion:run.version,...extra});
 async function exportFile(format:string,kind='diagnostic'){if(!mission)return;setBusy(true);setError('');try{if(initial.demo){const r=await fetch('/api/workpapers/equity/demo?format=html'+(demoCase?'&case='+demoCase:''));if(!r.ok)throw Error('Export synthétique indisponible');saveBlob(await r.blob(),'EXEMPLE-capitaux-diagnostic.html');return;}await session();const r=await fetch('/api/workpapers/equity/export',{method:'POST',headers:{'Content-Type':'application/json','x-probant-csrf':csrf.current},body:JSON.stringify({...scope,id:run?.id,version:run?.version,kind,format,expectedSnapshotHash:mission.hash})});if(!r.ok){const d=await r.json();throw Error(equityFailure(r.status,d.error));}saveBlob(await r.blob(),'probant-capitaux-'+kind+'.'+format);}catch(e){setError(e instanceof Error?e.message:'Export impossible');}finally{setBusy(false);}}
 function saveBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
 const proofUrl=(id:string,page:number)=>initial.demo?'/api/workpapers/equity/demo?format=pdf-proof#page='+page:'/api/workpapers/equity?'+q({operation:'proof',id})+'#page='+page;
 const sourceIds=view?.sourceHeads.map(h=>h.import_id)??[],choices=facts.filter(f=>['equity_ledger','equity_decisions'].includes(f.type));
 return <main className={s.workspace}><nav className={s.links}><a href='/dashboard/synthese'>DEMO SA · constats historiques</a><a href='/dashboard/tests#cycle-demo-title'>Atelier synthétique</a><span>{initial.demo?'Recette synthétique':'Procédures de mission'}</span></nav><header className={s.header}><p className={s.eyebrow}>MISSION 11 · CAPITAUX PROPRES</p><h1>{synthesis?'Synthèse des décisions':'Décisions et mouvements'}</h1><p>Une décision, sa date d’effet, ses écritures et ses règlements.</p>{run&&<p className={s.muted}>Dossier {run.scope.dossierId} · période {run.period.startDate} → {run.period.closingDate} · revue au {run.period.asOfDate} · EUR</p>}<nav className={s.links}><a href={(synthesis?'/equity':'/equity/synthesis')+'?'+links}>{synthesis?'Ouvrir la feuille':'Synthèse et export'}</a><a href='/equity?demo=1'>Voir la recette synthétique</a>{real&&<a href={'/api/auth/login?returnTo='+encodeURIComponent((synthesis?'/equity/synthesis':'/equity')+'?'+links)}>Se connecter</a>}</nav></header>{initial.demo&&<p className={s.banner}>Exemple synthétique, séparé des constats historiques DEMO SA. Les montants et l’auteur servent à la recette ; aucune sauvegarde durable ni approbation de mission.</p>}
 {real&&<section className={s.section}><details open={!scope.periodId}><summary>Organisation, dossier et période</summary><p>L’organisation et les permissions proviennent de votre session serveur.</p><div className={s.form}><label>Identité du dossier<input value={dossier} onChange={e=>setDossier(e.target.value)} placeholder='Identifiant du dossier autorisé' /></label>{(['startDate','closingDate','asOfDate'] as const).map((k,i)=><label key={k}>{['Début','Clôture','Date de revue'][i]}<input type='date' value={period[k]} onChange={e=>setPeriod({...period,[k]:e.target.value})} /></label>)}<p className={s.muted}>Période de travail provisoire ; dates à corroborer par les sources.</p></div><button disabled={busy||!dossier||!period.startDate||!period.closingDate||!period.asOfDate} onClick={()=>{setScope({dossierId:dossier,periodId:periodId(period)});setTarget({id:undefined,version:undefined});setView(null);setMission(null);}}>Charger ce dossier</button></details></section>}
 <div className={s.status} role='status' aria-live='polite'>{busy?'Chargement / sauvegarde en cours…':status}{run&&' · version '+run.version+' · révision '+run.revision+' · '+(STATES[run.state]??run.state)}</div>{view&&<p className={s.muted}>Identité {view.actorId} · préparateur {run?.preparedBy??'À définir'}{run?.equityWork&&' · convention par '+run.equityWork.authorId}</p>}{error&&<div role='alert' className={s.banner+' '+s.error}><p>{error}</p><button disabled={busy} onClick={()=>void load()}>Recharger</button>{pending.current&&<button disabled={busy} onClick={()=>void mutate(pending.current!.body,pending.current!.imports,true)}>Rejouer la même requête</button>}</div>}{mission?.stale&&<p className={s.banner}>Travaux périmés : version ou source remplacée. L’ancienne décision est conservée. Une nouvelle révision est nécessaire.</p>}
 {conflict&&<section className={s.banner} role='alert'><h2>Conflit de modification</h2><div className={s.comparison}><div><h3>Votre modification</h3><p>Base version {run?.version} · {draft.method.id} / {draft.method.version}</p><p>{draft.method.note}</p><p>{draft.components.map(c=>c.label+': '+c.accounts.join(', ')).join(' ; ')}</p></div><div><h3>État serveur — version {conflict.version}</h3><p>Auteur {conflict.events.at(-1)?.actorId}</p><p>{conflict.equityWork?.method.note}</p><p>{conflict.equityWork?.components.map(c=>c.label+': '+c.accounts.join(', ')).join(' ; ')}</p></div></div><p>Votre brouillon est conservé à l’écran. Recharger adopte la version serveur.</p><button onClick={()=>{pending.current=null;void load({id:conflict.id,version:undefined});}}>Adopter la version serveur</button></section>}
 {!run&&!busy&&<section className={s.empty}><h2>Dossier de décisions à préparer</h2><p>Ouverture/clôture, GL, variation, décisions, PV/actes et règlements forment des sources distinctes. Aucun résultat n’est déduit sans préparation.</p>{view?.permissions.includes('prepare')&&<button className={s.primary} onClick={()=>void mutate({command:'create_equity',period,instanceKey:crypto.randomUUID()})}>Créer la feuille de cette période</button>}{view&&view.runs.length>1&&<ul>{view.runs.map(r=><li key={r.id}><button onClick={()=>setTarget({id:r.id,version:undefined})}>{r.id} · révision {r.revision} · version {r.version}</button></li>)}</ul>}</section>}
 {run&&synthesis&&<><section className={s.section}><h2>Programme et file de travail</h2><p>{mission?.program.procedures} procédure · {mission?.program.controls} contrôles prévus. Les compteurs proviennent du programme, indépendamment du nombre d’exceptions.</p>{mission?.result&&<div className={s.scroll}><table className={s.table}><thead><tr><th>Contrôle</th><th>Testé / population</th><th>Unité</th></tr></thead><tbody>{mission.result.controls.map(c=><tr key={c.label}><th scope='row'>{c.label}</th><td>{c.numerator} / {c.denominator}</td><td>{c.unit}</td></tr>)}</tbody></table></div>}<p>Exclusions : {mission?.result?.coverage.exclusions.length??0} · {mission?.result?.coverage.exclusions.map(e=>e.reason).join(' ; ')||'Aucune exclusion renseignée'}</p><ul className={s.queue}>{mission?.queue.map(item=><li key={item.id}><span className={s.badge+' '+s.issue}>{item.kind==='review'?'Revue attendue':item.kind==='stale'?'Périmé':'À instruire'}</span><a href={initial.demo?'/equity?demo=1'+(demoCase?'&case='+demoCase:'')+'&event='+encodeURIComponent(new URL(item.href,'http://localhost').searchParams.get('event')??item.id)+'&filter='+encodeURIComponent(item.kind):item.href}>{item.text}</a></li>)}</ul></section><section className={s.section}><h2>Export de cette version</h2><p>Le diagnostic expose les limites et les exceptions. Le paquet approuvé exige une revue distincte, un verrouillage et des sources courantes. Les originaux restent absents du paquet ; leur index est fourni.</p><div className={s.actions}><button disabled={busy||(!initial.demo&&!view?.permissions.includes('download'))} onClick={()=>void exportFile('html')}>Diagnostic HTML imprimable</button>{real&&<><button disabled={busy||!view?.permissions.includes('download')} onClick={()=>void exportFile('pdf')}>Diagnostic PDF</button><button disabled={busy||!mission?.approved||!view?.permissions.includes('download')} onClick={()=>void exportFile('html','approved')}>Paquet approuvé HTML</button></>}</div><p className={s.muted}>Aucun avis juridique automatique ; export standard, sans archivage certifié.</p></section></>}
 {run&&!synthesis&&<><div className={s.tabs} role='tablist' aria-label='Feuille Capitaux propres'>{tabs.map(([id,label],index)=><button key={id} ref={el=>{tabsRef.current[index]=el;}} role='tab' id={'equity-tab-'+id} aria-controls={'equity-panel-'+id} aria-selected={tab===id} tabIndex={tab===id?0:-1} onClick={()=>setTab(id)} onKeyDown={e=>{const next=e.key==='ArrowRight'?(index+1)%tabs.length:e.key==='ArrowLeft'?(index+tabs.length-1)%tabs.length:e.key==='Home'?0:e.key==='End'?tabs.length-1:null;if(next!==null){e.preventDefault();setTab(tabs[next][0]);tabsRef.current[next]?.focus();}}}>{label}</button>)}</div><section className={s.section} role='tabpanel' id={'equity-panel-'+tab} aria-labelledby={'equity-tab-'+tab}>
 {tab==='population'&&<><h2>Population et sélection</h2><p>Unité : décision et mouvement. Sources d’ouverture/clôture et pièces utilisées en corroboration ; dates d’effet distinctes.</p><EquityPreparation draft={draft} change={change} facts={facts} disabled={!canPrepare||busy} /><label>Critères de sélection<textarea disabled={!canPrepare||!!run.population||busy} value={criteria} onChange={e=>setCriteria(e.target.value)} placeholder='Décrire la population, les risques et les exclusions' /></label><div className={s.scroll}><table className={s.table}><thead><tr><th>Unité / source</th><th>Date</th><th>Motif d’exclusion explicite, sinon sélectionnée</th></tr></thead><tbody>{choices.map(f=><tr key={f.rowId}><th scope='row'>{f.id} · {EQUITY_LABELS[f.type]}</th><td>{f.date}</td><td><label>Exclusion de {f.id}<input disabled={!canPrepare||!!run.population||busy} value={exclusions[f.rowId]??run.selection?.exclusions.find(e=>e.id===f.rowId)?.reason??''} onChange={e=>setExclusions(v=>({...v,[f.rowId]:e.target.value}))} /></label></td></tr>)}</tbody></table></div><p>Population figée : {run.population?.items.length??'Non figée'} · sélection : {run.selection?.selectedIds.length??'À définir'}</p><div className={s.actions}><button className={s.primary} disabled={!canPrepare||busy||(!run.population&&(!criteria.trim()||!sourceIds.length))} onClick={()=>command(run.population?'configure_equity':'freeze_equity',{draft,...(!run.population?{importIds:sourceIds,criteria,excluded:Object.entries(exclusions).filter(([,reason])=>reason.trim()).map(([id,reason])=>({id,reason}))}:{})})}>{run.population?'Sauvegarder la convention — invalider le calcul':'Figer les sources, la population et la sélection'}</button>{run.population&&<button disabled={busy||!canPrepare} onClick={()=>command('execute')}>Exécuter cette version</button>}</div></>}
 {tab==='tests'&&(mission?.result?<EquityResults result={mission.result} initialEvent={initial.event} initialFilter={initial.filter} facts={facts} proofUrl={proofUrl} />:<div className={s.empty}><h2>Tests non exécutés</h2>{run.result&&run.result.execution!=='completed'&&<div className={s.banner} role='alert'>{[...run.result.blockedControls,...run.result.warnings].map((code,index)=><p key={index}>{EQUITY_FAILURES[code]??'Ce calcul est bloqué ou non concluant. Vérifiez les sources et la convention ; une nouvelle révision est nécessaire.'}</p>)}</div>}<p>Approuvez les imports dans Pièces, puis documentez la cartographie et la sélection dans Population.</p><button onClick={()=>setTab('proof')}>Préparer les pièces</button><button onClick={()=>setTab('population')}>Préparer la population</button></div>)}
 {tab==='exceptions'&&<><h2>Exceptions à expliquer</h2><p>Les constats du calcul sont conservés après la revue. Un traitement humain ne les transforme pas en conformité juridique.</p>{mission?.result?.exceptions.length?mission.result.exceptions.map(e=><article className={s.note} key={e.id}><h3>{e.text}</h3><p>{equityAmount(e.amount)}</p><a href={'/equity?'+links+'&event='+encodeURIComponent(equityEventTarget(e))+'&filter='+encodeURIComponent(e.status)}>Ouvrir le point dans les tests</a><p>{run.notes.find(n=>n.id==='equity:'+e.id)?.resolution?.text??'Traitement à documenter dans Revue'}</p></article>):<p>Aucun constat disponible à cette version, ou aucun point détecté dans les travaux fournis.</p>}</>}
 {tab==='proof'&&<><h2>Pièces et versions</h2>{real&&<EquityImportForm period={run.period} disabled={busy||!view?.permissions.includes('prepare')||!current} preview={preview} send={body=>void mutate(body instanceof FormData?body:{...body,expectedSourceId:view?.sourceHeads.find(h=>h.document_type===preview?.document.documentType)?.import_id??null},true)} />}<p className={s.muted}>L’import approuvé devient la source courante. Son remplacement invalide les travaux figés ; la décision précédente reste dans l’historique.</p><ul className={s.queue}>{(mission?.sources.length?mission.sources:view?.imports.map(b=>({id:b.document.id,fileName:b.document.fileName,version:b.document.byteHash,current:view.sourceHeads.some(h=>h.import_id===b.id),format:b.document.format}))??[]).map(source=><li key={source.id}><strong>{source.fileName}</strong> · {source.current?'Courante':'Remplacée'}<p className={s.muted}>{source.id} · version {source.version}</p>{source.format==='pdf'&&(initial.demo||view?.permissions.includes('download'))&&<a target='_blank' rel='noreferrer' href={proofUrl(source.id,1)}>Ouvrir le document versionné</a>}</li>)}</ul>{EQUITY_TYPES.filter(t=>!facts.some(f=>f.type===t)).length>0&&<p className={s.banner}>Sources absentes : {EQUITY_TYPES.filter(t=>!facts.some(f=>f.type===t)).map(t=>EQUITY_LABELS[t]).join(' ; ')}. Leur absence n’est pas assimilée à un montant nul.</p>}<button onClick={()=>setTab('population')}>Relier les décisions aux pages dans Population</button></>}
 {tab==='review'&&<EquityReview run={run} facts={facts} canPrepare={!!canPrepare} canReview={!!canReview} busy={busy} demo={initial.demo} command={command} />}
 </section><section className={s.section}><h2>Historique de versions</h2><div className={s.actions}>{mission?.versions.map(v=><button key={v.id+':'+v.version} disabled={busy||initial.demo} onClick={()=>setTarget({id:v.id,version:v.version})}>Rév. {v.revision} · v{v.version} · {STATES[v.state]??v.state}</button>)}{real&&<button disabled={busy||!view?.permissions.includes('prepare')} onClick={()=>command('revise')}>Créer une nouvelle révision</button>}</div></section></>}
 </main>;
}
