'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { EquityResult } from '@/lib/workpapers/equity-dossier';
import { EQUITY_STATUS, equityEventSelection } from '@/lib/workpapers/equity-program';
import { equityAmount, type EquityFact } from './EquityView';
import s from './Equity.module.css';
import { EquityProofPage } from './EquityProofPage';
export function EquityResults({result,initialEvent='',initialFilter='',facts,proofUrl}:{result:EquityResult;initialEvent?:string;initialFilter?:string;facts:EquityFact[];proofUrl:(id:string,page:number)=>string}){
 const returnPosition=useRef<{x:number;y:number}|null>(null);
 const [selected,setSelected]=useState(initialEvent),[filter,setFilter]=useState(initialFilter),[search,setSearch]=useState(''),[expanded,setExpanded]=useState<string[]>([]),[descending,setDescending]=useState(false);const opener=useRef<HTMLButtonElement|null>(null);
 const close=useCallback(()=>{setSelected('');opener.current?.focus({preventScroll:true});if(returnPosition.current)window.scrollTo(returnPosition.current.x,returnPosition.current.y);returnPosition.current=null;},[]);
 useEffect(()=>{function escape(event:KeyboardEvent){if(event.key==='Escape'&&selected){close();}}document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape);},[selected,close]);
 const selection=equityEventSelection(selected),selectedId=selection.id,isSelected=(unit:string,id:string)=>selectedId===id&&(!selection.unit||selection.unit===unit);
 const decision=(!selection.unit||selection.unit==='decision')?result.decisions.find(d=>d.id===selectedId):undefined,movement=selection.unit==='row'?result.unmapped.find(m=>m.row.id===selectedId):(!selection.unit||selection.unit==='movement')?result.components.flatMap(c=>c.movements).find(m=>m.id===selectedId)??result.unmapped.find(m=>m.id===selectedId):undefined,component=result.components.find(c=>c.id===(decision?.component??movement?.component??selectedId)),proof=decision?.pv??(movement?{documentVersionId:movement.batch.document.id,page:movement.row.locator.page??0,fileName:movement.batch.document.fileName,format:movement.batch.document.format}:undefined);
 const rows=result.decisions.filter(d=>(!filter||d.statuses.includes(filter))&&(!search||(d.id+' '+d.description).toLocaleLowerCase('fr').includes(search.toLocaleLowerCase('fr'))));
 function choose(id:string,button:HTMLButtonElement){opener.current=button;setSelected(id);}function focusProof(){returnPosition.current={x:window.scrollX,y:window.scrollY};document.getElementById('equity-proof-panel')?.focus();}
 return <div className={s.grid}><div><h2>Tableau de variation</h2><p className={s.muted}>EUR signés · ouverture + mouvements = clôture. Le transfert interne conserve un effet total nul.</p><div className={s.scroll} tabIndex={0} aria-label='Tableau de variation, défilement horizontal'><table className={s.table}><caption>Composantes déclarées · développez une ligne pour voir les mouvements</caption><thead><tr><th scope='col'><button onClick={()=>setDescending(!descending)}>Composante {descending?'↓':'↑'}</button></th><th scope='col'>Comptes</th><th scope='col' className={s.amount}>Ouverture</th><th scope='col' className={s.amount}>Mouvements</th><th scope='col' className={s.amount}>Clôture</th><th scope='col' className={s.amount}>Résiduel du pont</th><th scope='col' className={s.amount}>Variation fournie − GL</th></tr></thead>{[...result.components].sort((a,b)=>a.label.localeCompare(b.label,'fr')*(descending?-1:1)).map(c=><tbody key={c.id}><tr className={isSelected('component',c.id)?s.selected:undefined}><th scope='row'><button aria-expanded={expanded.includes(c.id)} onClick={()=>setExpanded(v=>v.includes(c.id)?v.filter(id=>id!==c.id):[...v,c.id])}>{expanded.includes(c.id)?'−':'+'} {c.label}</button></th><td>{c.accounts.join(', ')}</td><td className={s.amount} title={c.opening.kind==='unknown'?c.opening.reason:''}>{equityAmount(c.opening)}</td><td className={s.amount} title={c.variation.kind==='unknown'?c.variation.reason:''}>{equityAmount(c.variation)}</td><td className={s.amount}>{equityAmount(c.closing)}</td><td className={s.amount}>{equityAmount(c.difference)}</td><td className={s.amount}>{equityAmount(c.variationDifference)}</td></tr>{expanded.includes(c.id)&&<tr className={s.expanded}><td colSpan={7}>{c.movements.length?<div className={s.scroll}><table className={s.table}><caption>Mouvements de {c.label}</caption><thead><tr><th>Mouvement</th><th>Date comptable</th><th>Décision</th><th>Transfert</th><th className={s.amount}>EUR signé</th></tr></thead><tbody>{c.movements.map(m=><tr key={m.id} className={isSelected('movement',m.id)?s.selected:undefined}><td><button onClick={e=>choose('movement:'+m.id,e.currentTarget)}>{m.id}</button> {m.description}</td><td>{m.date}</td><td>{m.decisionId||'Non renseignée'}</td><td>{m.transferId||'—'}</td><td className={s.amount}>{equityAmount({kind:'known',value:m.amount})}</td></tr>)}</tbody></table></div>:<p>Aucun mouvement dans le GL fourni sur cette composante.</p>}</td></tr>}</tbody>)}<tfoot><tr><th scope='row' colSpan={2}>Total du périmètre déclaré</th><td className={s.amount}>{equityAmount(result.totals.opening)}</td><td className={s.amount}>{equityAmount(result.totals.variation)}</td><td className={s.amount}>{equityAmount(result.totals.closing)}</td><td colSpan={2}>Aucun avis juridique</td></tr></tfoot></table></div>
 <section className={s.section}><h2>Décisions et rapprochements</h2><div className={s.row}><label>Rechercher une décision<input type='search' value={search} onChange={e=>setSearch(e.target.value)} placeholder='Identité ou libellé' /></label><label>Filtre métier<select value={filter} onChange={e=>setFilter(e.target.value)}><option value=''>Toutes les décisions</option>{Object.entries(EQUITY_STATUS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div><p className={s.muted}>{rows.length} décision(s) visible(s) / {result.decisions.length}. Montants votés en magnitude ; comptabilisation comparée sur la période testée. La frise conserve aussi les écritures ultérieures documentées.</p>{rows.length?<div className={s.scroll} tabIndex={0} aria-label='Décisions et rapprochements, défilement horizontal'><table className={s.table}><thead><tr><th>Décision</th><th>Vote / effet</th><th className={s.amount}>Voté</th><th className={s.amount}>Comptabilisé</th><th className={s.amount}>Comptabilisé − voté</th><th>Règlements distincts</th><th>Statut</th></tr></thead><tbody>{rows.map(d=><tr key={d.id} className={isSelected('decision',d.id)?s.selected:undefined}><th scope='row'><div className={s.decisionActions}><button onClick={e=>choose('decision:'+d.id,e.currentTarget)}>{d.id}</button>{isSelected('decision',d.id)&&<button onClick={focusProof}>Consulter la preuve</button>}</div><p>{d.description}</p></th><td><time>{d.decisionDate}</time><br />Effet <time>{d.effectiveDate}</time></td><td className={s.amount}>{equityAmount({kind:'known',value:d.amount})}</td><td className={s.amount}>{equityAmount(d.booked)}</td><td className={s.amount}>{equityAmount(d.difference)}</td><td>{d.payments.length?d.payments.map(p=><p key={p.id}>{equityAmount({kind:'known',value:p.amount})}<br />{p.date} · {p.id}</p>):'Non documentés'}</td><td>{d.statuses.map(status=><span key={status} className={s.badge+' '+(!['transfer','matched'].includes(status)?s.issue:'')}>{EQUITY_STATUS[status]??status}</span>)}</td></tr>)}</tbody></table></div>:<p className={s.empty}>Aucune décision ne correspond à ces filtres. <button onClick={()=>{setFilter('');setSearch('');}}>Réinitialiser</button></p>}</section>
 <section className={s.section}><h2>Écritures sans décision documentée</h2>{result.orphans.length?<ul className={s.queue}>{result.orphans.map(o=><li key={o.id}><button onClick={e=>choose('movement:'+o.id,e.currentTarget)}>{o.id}</button> · {o.account} · {o.date} · {equityAmount({kind:'known',value:o.amount})}<p>{EQUITY_STATUS[o.status]}</p></li>)}</ul>:<p>Aucune écriture orpheline trouvée dans la sélection fournie.</p>}</section>
 <section className={s.section}><h2>Limites du dossier</h2>{result.unmapped.length>0&&<><h3>Comptes ou composantes hors cartographie</h3><ul className={s.queue}>{result.unmapped.map(m=><li key={m.row.id}><button onClick={e=>choose('row:'+m.row.id,e.currentTarget)}>{m.id}</button> · {m.component} / {m.account} · {equityAmount({kind:'known',value:m.amount})}<p>{m.batch.document.fileName} · cartographie à compléter</p></li>)}</ul></>}{result.transfers.map(t=><p key={t.id}>{t.id} · {t.label} · {equityAmount({kind:'known',value:t.amount})}</p>)}<p>{result.legalConclusion.kind==='known'?'À instruire':result.legalConclusion.reason}</p><ul>{result.limitations.map(l=><li key={l}>{l}</li>)}</ul></section></div>
 <aside id='equity-proof-panel' tabIndex={-1} className={s.proof} aria-label='Preuve et dates du mouvement' onKeyDown={e=>{if(e.key==='Escape')close();}}><h2>{selected?'Détail · '+(decision?.id??movement?.id??component?.label??selectedId):'Preuve et dates'}</h2>{selected&&<button onClick={close}>Fermer le détail</button>}{!selected?<p>Sélectionnez une décision ou développez une composante pour consulter le mouvement et sa source.</p>:<><p>{decision?.description??movement?.description??component?.label??'Point de cartographie à compléter'}</p>{movement&&<p>Composante {movement.component} · compte {movement.account} · montant source {equityAmount({kind:'known',value:movement.amount})}</p>}{component&&!decision&&!movement&&<p>Ouverture {equityAmount(component.opening)} · mouvements {equityAmount(component.variation)} · clôture {equityAmount(component.closing)}</p>}{decision?<ol className={s.timeline}><li><time>{decision.decisionDate}</time>Décision · {equityAmount({kind:'known',value:decision.amount})}</li><li><time>{decision.effectiveDate}</time>Date d’effet explicite</li>{decision.bookings.map(m=><li key={m.id}><time>{m.date}</time>Comptabilisation{m.inPeriod?'':' hors période testée'} · {equityAmount({kind:'known',value:m.amount})} · {m.id}</li>)}{decision.payments.map(p=><li key={p.id}><time>{p.date}</time>Paiement distinct · {equityAmount({kind:'known',value:p.amount})}</li>)}</ol>:movement?<ol className={s.timeline}><li><time>{movement.date}</time>Date comptable</li><li><time>{movement.effectiveDate||'Non documentée'}</time>Date d’effet</li></ol>:null}
 {proof&&proof.format==='pdf'&&proof.page>0?<><p>{proof.fileName} · page {proof.page}</p><p className={s.muted}>Document {proof.documentVersionId}</p><a href={proofUrl(proof.documentVersionId,proof.page)} target='_blank' rel='noreferrer'>Ouvrir cette page du PV</a><EquityProofPage label={proof.fileName+' · '+proof.documentVersionId} page={proof.page} url={proofUrl(proof.documentVersionId,proof.page)} /></>:<p className={s.banner}>{decision?'PV absent ou lecture non documentée à une page versionnée.':'Ce mouvement est lié à une ligne source ; voir l’onglet Pièces.'}</p>}
 <h3>Sources du point</h3><ul>{(decision?.evidence??(movement?[movement.proof]:component?.evidence??[])).map(p=>{const f=facts.find(f=>f.rowId===p.rowId);return <li key={p.id}>{f?.fileName??p.documentVersionId} · {p.locator?.page?'page '+p.locator?.page:'ligne '+(p.locator?.row??'?')}<p className={s.muted}>{p.documentVersionId}</p></li>;})}</ul></>}</aside></div>;
}
