'use client';
import type { EquityDraft } from '@/lib/workpapers/equity-dossier';
import { EQUITY_FAMILIES, EQUITY_FAMILY_LABELS } from '@/lib/workpapers/equity-program';
import type { EquityFact } from './EquityView';
import s from './Equity.module.css';
export function emptyEquityDraft():EquityDraft{return {schemaVersion:'equity-dossier-1',method:{id:'',version:'',note:'',proofRowIds:[]},socialForm:'',completeComponentSet:false,ledgerCoverage:'incomplete',decisionsCoverage:'incomplete',components:EQUITY_FAMILIES.map(f=>({id:f,label:EQUITY_FAMILY_LABELS[f],family:f,accounts:[],state:'in_scope',reason:''})),interpretations:[]};}
function FactSelect({facts,value,onChange,label}:{facts:EquityFact[];value:string;onChange:(id:string)=>void;label:string}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}><option value=''>Choisir une source/version</option>{facts.map(f=><option key={f.rowId} value={f.rowId}>{f.fileName} · {f.page?'page '+f.page:f.id} · {f.version.slice(0,12)}</option>)}</select></label>;}
export function EquityPreparation({draft,change,facts,disabled}:{draft:EquityDraft;change:(d:EquityDraft)=>void;facts:EquityFact[];disabled:boolean}){
 const proofs=facts.filter(f=>['equity_minutes','equity_acts'].includes(f.type)&&f.page),decisions=facts.filter(f=>f.type==='equity_decisions');
 const update=(index:number,value:Partial<EquityDraft['components'][number]>)=>change({...draft,components:draft.components.map((c,i)=>i===index?{...c,...value}:c)});
 return <fieldset disabled={disabled}><legend>Cartographie et convention de travail</legend><p className={s.muted}>Checklist interne à corroborer. Toutes les composantes pertinentes sont à déclarer ; les comptes ne sont pas limités au compte 10.</p><div className={s.form}><label>Forme sociale à corroborer<input value={draft.socialForm} onChange={e=>change({...draft,socialForm:e.target.value})} /></label><label>Identité de méthode<input value={draft.method.id} onChange={e=>change({...draft,method:{...draft.method,id:e.target.value}})} /></label><label>Version de méthode<input value={draft.method.version} onChange={e=>change({...draft,method:{...draft.method,version:e.target.value}})} /></label><FactSelect facts={facts} label='Source/version de la méthode' value={draft.method.proofRowIds[0]??''} onChange={id=>change({...draft,method:{...draft.method,proofRowIds:id?[id]:[]}})} /><label>Couverture du GL<select value={draft.ledgerCoverage} onChange={e=>change({...draft,ledgerCoverage:e.target.value as EquityDraft['ledgerCoverage']})}><option value='incomplete'>Incomplète / à corroborer</option><option value='documented'>Documentée par les sources</option></select></label><label>Couverture du registre des décisions<select value={draft.decisionsCoverage} onChange={e=>change({...draft,decisionsCoverage:e.target.value as EquityDraft['decisionsCoverage']})}><option value='incomplete'>Incomplète / à corroborer</option><option value='documented'>Documentée par les sources</option></select></label></div><label>Convention, limites et corroboration<textarea value={draft.method.note} onChange={e=>change({...draft,method:{...draft.method,note:e.target.value}})} /></label><label className={s.check}><input type='checkbox' checked={draft.completeComponentSet} onChange={e=>change({...draft,completeComponentSet:e.target.checked})} />Cartographie complète déclarée et corroborée pour ce dossier</label>
 <div className={s.scroll} tabIndex={0} aria-label='Cartographie des composantes'><table className={s.table}><thead><tr><th>Composante / famille</th><th>Comptes explicites</th><th>Applicabilité</th><th>Justification / pièce</th></tr></thead><tbody>{draft.components.map((c,i)=><tr key={c.id}><th scope='row'><label>Libellé<input value={c.label} onChange={e=>update(i,{label:e.target.value})} /></label><p className={s.muted}>{c.id} · {EQUITY_FAMILY_LABELS[c.family]}</p></th><td><label>Comptes séparés par virgule<input value={c.accounts.join(', ')} onChange={e=>update(i,{accounts:e.target.value.split(',').map(a=>a.trim()).filter(Boolean)})} placeholder='101, 109, …' /></label></td><td><label>Statut<select value={c.state} onChange={e=>update(i,{state:e.target.value as typeof c.state})}><option value='in_scope'>À inclure dans le périmètre</option><option value='not_applicable'>Non applicable, à justifier</option></select></label></td><td><label>Motif<input value={c.reason} onChange={e=>update(i,{reason:e.target.value})} /></label><FactSelect label='Citation de justification' facts={facts} value={c.proofRowId??''} onChange={id=>update(i,{proofRowId:id||undefined})} /></td></tr>)}</tbody></table></div><button onClick={()=>change({...draft,components:[...draft.components,{id:'other-'+(draft.components.length+1),label:'Composante à documenter',family:'other',accounts:[],state:'in_scope',reason:''}]})}>Ajouter une composante pertinente</button>
 <h3>Lecture des PV et actes</h3><p>Cette lecture relie une décision au document, à sa version et à sa page. L’index PDF ne valide aucun montant automatiquement.</p>{decisions.length?decisions.map(d=>{const reading=draft.interpretations.find(i=>i.decisionId===d.id);const set=(v:{proofRowId?:string;note?:string})=>{const next={decisionId:d.id,proofRowId:v.proofRowId??reading?.proofRowId??'',note:v.note??reading?.note??''};change({...draft,interpretations:[...draft.interpretations.filter(i=>i.decisionId!==d.id),...(next.proofRowId?[next]:[])]});};return <div className={s.row} key={d.id}><p>{d.id} · {d.description}</p><FactSelect label='Page lue' facts={proofs} value={reading?.proofRowId??''} onChange={id=>set({proofRowId:id})} /><label>Constat de lecture<input value={reading?.note??''} onChange={e=>set({note:e.target.value})} placeholder='Montant, date d’effet, portée…' /></label></div>;}):<p>Importez et approuvez le registre des décisions pour établir ces liens.</p>}</fieldset>;
}
