'use client';
import { useEffect,useRef,useState } from 'react';
import { contentHash,periodId,type WorkpaperRun } from '@/lib/workpapers/model';
import type { AccountingPeriod } from '@/lib/canonical-model/period';
import type { ImportBatch } from '@/lib/workpapers/imports';
import { INVESTMENT_TYPES,INVESTMENT_LABELS,INVESTMENT_MAPPING,initialInvestmentDraft,type InvestmentDraft,type InvestmentFact,type InvestmentResult } from '@/lib/workpapers/investment-dossier';
import { equityAmount,STATES } from './EquityView';
import s from './Equity.module.css';
import layout from './Investment.module.css';
const tabs=[['population','Population'],['tests','Tests'],['exceptions','Exceptions'],['proof','Pièces'],['review','Revue']] as const;
const badges={comparable:'Comparable',non_comparable:'Non comparable',source_required:'Source requise'};
const natures={enterprise_value:'Valeur d’entreprise',equity_value:'Valeur des fonds propres',holding_value:'Valeur de détention'};
type View={actorId:string;permissions:string[];runs:WorkpaperRun[];imports:ImportBatch[];facts:Record<string,InvestmentFact[]>;sourceHeads:{document_type:string;import_id:string}[]};
const emptyPeriod:AccountingPeriod={startDate:'',closingDate:'',asOfDate:'',currency:'EUR',validation:'provisional'};
export function InvestmentWorkspace({initial}:{initial:{demo:boolean;case:string;dossierId:string;periodId:string;id:string;tab:string}}){
 const[scope,setScope]=useState({dossierId:initial.dossierId,periodId:initial.periodId}),[dossier,setDossier]=useState(initial.dossierId),[period,setPeriod]=useState(emptyPeriod),[view,setView]=useState<View|null>(null),[target,setTarget]=useState(initial.id),[tab,setTab]=useState(tabs.some(t=>t[0]===initial.tab)?initial.tab:'tests'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('Aucune sauvegarde effectuée'),[draft,setDraft]=useState<InvestmentDraft>({schemaVersion:'investment-review-1',entries:[]}),[dirty,setDirty]=useState(false),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[sort,setSort]=useState<'asc'|'desc'>('asc'),[selected,setSelected]=useState(''),[criteria,setCriteria]=useState(''),[excluded,setExcluded]=useState<Record<string,string>>({}),[preview,setPreview]=useState<ImportBatch|null>(null),[sourceType,setSourceType]=useState<string>(INVESTMENT_TYPES[0]),[sheet,setSheet]=useState(''),[reviewText,setReviewText]=useState(''),[citation,setCitation]=useState(''),[conflict,setConflict]=useState<WorkpaperRun|null>(null);
 const tabsRef=useRef<(HTMLButtonElement|null)[]>([]),rowButtons=useRef<Record<string,HTMLButtonElement|null>>({}),panel=useRef<HTMLElement|null>(null),pending=useRef<{body:Record<string,unknown>|FormData;imports:boolean;key:string}|null>(null),csrf=useRef(''),inflight=useRef(false);
 const run=view?.runs.find(r=>r.id===target)??(view?.runs.length===1?view.runs[0]:undefined),facts=run?view?.facts[run.id]??[]:[],result=run?.result?.result as InvestmentResult|undefined;
 const stale=!!run&&!!run.population&&(run.importIds.some(id=>!view?.sourceHeads.some(h=>h.import_id===id))||!!view?.sourceHeads.some(h=>!run.importIds.includes(h.import_id))),canPrepare=!initial.demo&&!stale&&view?.permissions.includes('prepare')&&run?.preparedBy===view.actorId&&['draft','ready','executed'].includes(run.state),canReview=!initial.demo&&!stale&&view?.permissions.includes('review')&&run?.preparedBy!==view.actorId;
 const rows=result?.rows??[],chosen=rows.find(r=>r.id===selected),visible=rows.filter(r=>(filter==='all'||r.review.valuation.status===filter)&&(!search||[r.label,r.input.securityId,r.input.distributionId].join(' ').toLocaleLowerCase('fr').includes(search.toLocaleLowerCase('fr')))).sort((a,b)=>(sort==='asc'?1:-1)*a.label.localeCompare(b.label,'fr'));
 const q=(extra:Record<string,string>={})=>new URLSearchParams({...scope,...extra});
 const failure=(code:number)=>code===401?'Session requise ou expirée : reconnectez-vous.':code===403?'Accès refusé ou auto-approbation interdite.':code===409?'Une source ou une version a changé. Comparez les états avant de reprendre.':code===503?'Chaîne durable désactivée ou indisponible : infrastructure de recette jetable requise.':'Opération refusée : vérifiez les champs, les associations et les preuves.';
 async function session(){const r=await fetch('/api/auth/session',{cache:'no-store'}),d=await r.json();if(!r.ok||!d.csrfToken)throw Error(failure(r.ok?401:r.status));csrf.current=d.csrfToken;}
 async function load(id=target){if(!initial.demo&&(!scope.dossierId||!scope.periodId))return;setBusy(true);setError('');try{if(!initial.demo)await session();const url=initial.demo?'/api/workpapers/participations/demo'+(initial.case?'?case='+encodeURIComponent(initial.case):''):'/api/workpapers/participations?'+q(id?{id}:{});const r=await fetch(url,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(initial.demo?'La recette synthétique est désactivée ou indisponible dans cet environnement.':failure(r.status));setView(d);const current=d.runs.find((r:WorkpaperRun)=>r.id===id)??(d.runs.length===1?d.runs[0]:null);if(current){setTarget(current.id);setPeriod(current.period);setDraft(current.investmentWork?{schemaVersion:'investment-review-1',entries:current.investmentWork.entries}:initialInvestmentDraft(d.facts[current.id]??[]));}setDirty(false);setConflict(null);}catch(e){setError(e instanceof Error?e.message:'Chargement impossible');}finally{setBusy(false);}}
 useEffect(()=>{void load();/* Scope changes deliberately load the selected dossier. */ // eslint-disable-next-line react-hooks/exhaustive-deps
 },[scope.dossierId,scope.periodId]);
 useEffect(()=>{if(selected)panel.current?.focus({preventScroll:true});},[selected]);
 function close(){const id=selected;setSelected('');rowButtons.current[id]?.focus({preventScroll:true});}
 async function mutate(body:Record<string,unknown>|FormData,imports=false,retry=false){if(initial.demo||inflight.current)return;inflight.current=true;setBusy(true);setError('');try{await session();const key=retry?pending.current?.key:crypto.randomUUID();if(!key)throw Error('Requête à rejouer absente');pending.current={body,imports,key};const r=await fetch('/api/workpapers/participations'+(imports?'/imports':'')+'?'+q(),{method:'POST',headers:{'Idempotency-Key':key,'x-probant-csrf':csrf.current,...(body instanceof FormData?{}:{'Content-Type':'application/json'})},body:body instanceof FormData?body:JSON.stringify(body)}),d=await r.json();if(!r.ok){if(r.status===409&&d.current)setConflict(d.current);throw Error(failure(r.status));}pending.current=null;setStatus(imports?'Source confirmée par le serveur':'Sauvegardée · version '+d.run.version);if(d.batch&&!d.batch.approval){setPreview(d.batch);return;}setPreview(null);await load(d.run?.id??run?.id??target);}catch(e){setError(e instanceof Error?e.message:'Enregistrement impossible');}finally{inflight.current=false;setBusy(false);}}
 function command(command:string,extra:Record<string,unknown>={}){if(run)void mutate({command,id:run.id,expectedVersion:run.version,...extra});}
 function edit(index:number,value:Partial<InvestmentDraft['entries'][number]>){setDraft(v=>({...v,entries:v.entries.map((e,i)=>i===index?{...e,...value}:e)}));setDirty(true);setStatus('Brouillon modifié · calcul à invalider après sauvegarde');}
 async function exportFile(){if(!run)return;setBusy(true);setError('');try{if(!initial.demo)await session();const r=await fetch(initial.demo?'/api/workpapers/participations/demo?format=html':'/api/workpapers/participations/export',{method:initial.demo?'GET':'POST',headers:initial.demo?{}:{'Content-Type':'application/json','x-probant-csrf':csrf.current},...(initial.demo?{}:{body:JSON.stringify({...scope,id:run.id,version:run.version,expectedHash:contentHash(run),format:'html'})})});if(!r.ok)throw Error(failure(r.status));const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='participations-diagnostic.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Export impossible');}finally{setBusy(false);}}
 const cite=facts.find(f=>f.rowId===citation),citationValue=cite?{rowId:cite.rowId,documentVersionId:cite.documentVersionId}:null;
 function sourceLink(f:InvestmentFact){return initial.demo?'/api/workpapers/participations/demo?source='+f.type:'/api/workpapers/participations?'+q({operation:'download',id:f.documentVersionId});}
 return <main className={s.workspace}><nav className={s.links}><a href='/dashboard/synthese'>Synthèse du dossier</a><a href='/dashboard/tests#cycle-demo-title'>Atelier synthétique</a><a href='/participations?demo=1'>Recette Participations</a></nav><header className={s.header}><p className={s.eyebrow}>MISSION 12 · PARTICIPATIONS</p><h1>Droits, distributions et valeur</h1><p>Relier les titres détenus aux droits applicables, au produit enregistré et à une valeur comparable.</p>{run&&<p className={s.muted}>Dossier {run.scope.dossierId} · {run.period.startDate} → {run.period.closingDate} · revue au {run.period.asOfDate} · EUR · version {run.version} · {STATES[run.state]??run.state}</p>}</header>
 {initial.demo&&<p className={s.banner}>Recette entièrement synthétique en lecture seule. Les sept packs CSV sont réellement importés. Aucune approbation ni sauvegarde de mission réelle.</p>}
 {!initial.demo&&<form className={s.form} onSubmit={e=>{e.preventDefault();setScope({dossierId:dossier,periodId:periodId(period)});}}><label>Dossier autorisé<input value={dossier} onChange={e=>setDossier(e.target.value)} required /></label>{(['startDate','closingDate','asOfDate'] as const).map((key,i)=><label key={key}>{['Ouverture','Clôture','Revue au'][i]}<input type='date' value={period[key]} onChange={e=>setPeriod(v=>({...v,[key]:e.target.value}))} required /></label>)}<button disabled={busy}>Charger le dossier</button><a href={'/api/auth/login?returnTo='+encodeURIComponent('/participations?'+q())}>Se connecter</a></form>}
 <p className={s.status} role='status' aria-live='polite'>{busy?'Chargement / sauvegarde en cours…':initial.demo?'Exemple synthétique chargé':status}</p>
 {error&&<section role='alert' className={s.banner+' '+s.error}><p>{error}</p><button onClick={()=>void load()} disabled={busy}>Recharger</button>{pending.current&&<button disabled={busy} onClick={()=>void mutate(pending.current!.body,pending.current!.imports,true)}>Rejouer la même requête</button>}</section>}
 {dirty&&<p className={s.banner}>Brouillon modifié : le résultat affiché appartient à la version précédente. Sauvegardez puis exécutez à nouveau.</p>}{stale&&<p className={s.banner}>Périmé : une source a été remplacée. Les résultats et décisions anciens sont conservés ; créez une révision avant de poursuivre.</p>}
 {conflict&&<section className={s.banner}><h2>Conflit de version</h2><div className={s.comparison}><div><h3>Votre brouillon</h3>{draft.entries.map((e,i)=><p key={i}>Ligne {i+1} · modèle {facts.find(f=>f.rowId===e.modelRowId)?.id??'Absent'} · décision {e.decision?.reason??'Absente'}</p>)}</div><div><h3>Serveur · version {conflict.version}</h3>{conflict.investmentWork?.entries.map((e,i)=><p key={i}>Ligne {i+1} · modèle {facts.find(f=>f.rowId===e.modelRowId)?.id??'Source différente'} · décision {e.decision?.reason??'Absente'}</p>)}</div></div><button onClick={()=>void load()}>Adopter la version serveur</button></section>}
 {view&&view.runs.length>1&&<label>Feuille à examiner<select value={target} onChange={e=>{setTarget(e.target.value);void load(e.target.value);}}><option value="">Choisir une feuille</option>{view.runs.map(r=><option key={r.id} value={r.id}>{r.id} · révision {r.revision} · version {r.version}</option>)}</select></label>}{!run&&!busy&&<section className={s.empty}><h2>Population à préparer</h2><p>Importez le registre, les droits, les distributions, le GL, les encaissements, le coût/dépréciation et les modèles externes versionnés.</p>{view?.permissions.includes('prepare')&&<button onClick={()=>void mutate({command:'create_investment',period,instanceKey:crypto.randomUUID()})}>Créer la feuille Participations</button>}</section>}
 {run&&<><div className={s.tabs} role='tablist' aria-label='Feuille Participations'>{tabs.map(([id,label],i)=><button key={id} ref={el=>{tabsRef.current[i]=el;}} role='tab' id={'investment-tab-'+id} aria-controls='investment-panel' aria-selected={tab===id} tabIndex={tab===id?0:-1} onClick={()=>setTab(id)} onKeyDown={e=>{const next=e.key==='ArrowRight'?(i+1)%tabs.length:e.key==='ArrowLeft'?(i+tabs.length-1)%tabs.length:e.key==='Home'?0:e.key==='End'?tabs.length-1:null;if(next!==null){e.preventDefault();setTab(tabs[next][0]);tabsRef.current[next]?.focus();}}}>{label}</button>)}</div>
 <section role='tabpanel' id='investment-panel' aria-labelledby={'investment-tab-'+tab} className={s.section}>
 {tab==='population'&&<><h2>Population et choix documentés</h2><p>Unité : lignes de titres et distributions. {result?.coverage.selected??run.selection?.selectedIds.length??'Non figée'} / {result?.coverage.denominator??run.population?.items.length??'Population à définir'}. Exclusions motivées conservées.</p><label>Critères de sélection<textarea disabled={!canPrepare||!!run.population} value={criteria||run.selection?.criteria||''} onChange={e=>setCriteria(e.target.value)} /></label>
 {draft.entries.map((entry,i)=>{const register=facts.find(f=>f.rowId===entry.registerRowId),models=facts.filter(f=>f.type==='investment_models');return <fieldset key={i} className={s.note}><legend>{register?.details.label as string??'Ligne '+(i+1)}</legend><div className={s.form}>
 {(['distributionRowId','rightsRowId','costRowId','impairmentRowId','modelRowId','previousModelRowId'] as const).map((key,j)=>{const types=['investment_distributions','investment_rights','investment_carrying','investment_carrying','investment_models','investment_models'];const choices=key.includes('Model')||key==='modelRowId'?models:facts.filter(f=>f.type===types[j]);return <label key={key}>{['Distribution','Droits applicables','Coût','Dépréciation','Modèle examiné — choix explicite','Version à comparer'][j]}<select disabled={!canPrepare||busy} value={entry[key]??''} onChange={e=>edit(i,{[key]:e.target.value||null})}><option value=''>Source absente / à qualifier</option>{choices.map(f=><option key={f.rowId} value={f.rowId}>{f.id} · {f.details.version as string??f.date}</option>)}</select></label>;})}
 </div><p className={s.muted}>Associations GL : {entry.ledgerIds.map(id=>facts.find(f=>f.rowId===id)?.id).join(', ')||'Absent'} · règlements : {entry.receiptIds.map(id=>facts.find(f=>f.rowId===id)?.id).join(', ')||'Absents'}</p>
 <label>Exclusion de la ligne de titre — motif explicite<input disabled={!canPrepare||!!run.population} value={excluded[entry.registerRowId]??run.selection?.exclusions.find(e=>e.id===entry.registerRowId)?.reason??''} onChange={e=>setExcluded(v=>({...v,[entry.registerRowId]:e.target.value}))} /></label>
  <div className={s.form}>{(['ledgerIds','receiptIds'] as const).map((key,j)=><label key={key}>{j===0?'Écritures GL associées':'Encaissements associés'}<select multiple disabled={!canPrepare||busy} value={entry[key]} onChange={e=>edit(i,{[key]:Array.from(e.target.selectedOptions).map(o=>o.value)})}>{facts.filter(f=>f.type===(j===0?'investment_ledger':'investment_receipts')&&f.details.securityId===register?.details.securityId).map(f=><option key={f.rowId} value={f.rowId}>{f.id} · {f.date} · {f.amount.amount} EUR</option>)}</select></label>)}</div>
 {entry.distributionRowId&&<label>Exclusion de cette distribution — motif explicite<input disabled={!canPrepare||!!run.population} value={excluded[entry.distributionRowId]??run.selection?.exclusions.find(e=>e.id===entry.distributionRowId)?.reason??''} onChange={e=>setExcluded(v=>({...v,[entry.distributionRowId!]:e.target.value}))} /></label>}
 <details><summary>Décision motivée de classification et proposition</summary><p>La décision reste une proposition à revoir. Aucun seuil de détention ne la déclenche.</p><label>Catégorie proposée<input disabled={!canPrepare} value={entry.decision?.category??''} onChange={e=>edit(i,{decision:{category:e.target.value,reason:entry.decision?.reason??'',citationRowId:entry.decision?.citationRowId??entry.registerRowId,date:period.asOfDate,...(entry.decision?.proposedAmount?{proposedAmount:entry.decision.proposedAmount}:{})}})} /></label><label>Motivation<textarea disabled={!canPrepare} value={entry.decision?.reason??''} onChange={e=>edit(i,{decision:{category:entry.decision?.category??'',reason:e.target.value,citationRowId:entry.decision?.citationRowId??entry.registerRowId,date:period.asOfDate,...(entry.decision?.proposedAmount?{proposedAmount:entry.decision.proposedAmount}:{})}})} /></label><label>Pièce citée<select disabled={!canPrepare} value={entry.decision?.citationRowId??entry.registerRowId} onChange={e=>edit(i,{decision:{category:entry.decision?.category??'',reason:entry.decision?.reason??'',citationRowId:e.target.value,date:period.asOfDate,...(entry.decision?.proposedAmount?{proposedAmount:entry.decision.proposedAmount}:{})}})}>{facts.filter(f=>f.details.securityId===register?.details.securityId).map(f=><option key={f.rowId} value={f.rowId}>{f.fileName} · ligne {f.line} · {f.id}</option>)}</select></label><label>Proposition de dépréciation (EUR, décimales avec point ; facultatif)<input disabled={!canPrepare} value={entry.decision?.proposedAmount?.amount??''} onChange={e=>edit(i,{decision:{category:entry.decision?.category??'',reason:entry.decision?.reason??'',citationRowId:entry.decision?.citationRowId??entry.registerRowId,date:period.asOfDate,...(e.target.value?{proposedAmount:{amount:e.target.value,currency:'EUR'}}:{})}})} /></label></details></fieldset>;})}
 <div className={s.actions}><button disabled={!canPrepare||busy||!draft.entries.length||(!run.population&&!criteria.trim())} onClick={()=>command(run.population?'configure_investment':'freeze_investment',{draft,...(!run.population?{importIds:view!.sourceHeads.map(h=>h.import_id),criteria,excluded:Object.entries(excluded).filter(([,reason])=>reason.trim()).map(([id,reason])=>({id,reason}))}:{})})}>{run.population?'Sauvegarder et invalider le calcul':'Figer sources, population et sélection'}</button><button disabled={!canPrepare||busy||dirty||!run.population} onClick={()=>command('execute')}>Exécuter la revue</button></div></>}
 {tab==='tests'&&<><h2>Participations et distributions</h2><div className={s.row}><label>Recherche explicite<input value={search} onChange={e=>setSearch(e.target.value)} /></label><label>Comparabilité de la valeur<select value={filter} onChange={e=>setFilter(e.target.value)}><option value='all'>Toutes</option>{Object.entries(badges).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><p className={s.muted}>Écart produit = enregistré − droit attendu. Écart valeur = valeur externe − base comptable. EUR, sans compensation ni anomalie validée.</p>
 <div className={s.grid}><div><div className={s.scroll}><table className={s.table+" "+layout.participations}><colgroup>{[210,170,125,115,125,145,170].map((width,i)=><col key={i} style={{width}} />)}</colgroup><caption>{visible.length} distributions affichées · population {result?.coverage.denominator??'Non calculée'} lignes de titres et distributions</caption><thead><tr><th aria-sort={sort==='asc'?'ascending':'descending'}><button onClick={()=>setSort(v=>v==='asc'?'desc':'asc')}>Participation ↕</button></th><th>Distribution / droits</th><th className={s.amount}>Produit attendu</th><th className={s.amount}>Enregistré</th><th className={s.amount}>Écart produit</th><th className={s.amount}>Base comptable</th><th>Valeur</th></tr></thead><tbody>{visible.map(row=><tr key={row.id} className={selected===row.id?s.selected:undefined}><th scope='row'><button className={layout.rowTitle} ref={el=>{rowButtons.current[row.id]=el;}} onClick={()=>setSelected(row.id)} aria-label={'Détail de '+row.label}>{row.label}</button><p>{row.input.securityId}</p></th><td>{row.input.distributionId??'Absente'}<br />{row.input.rights?.classId??'Source requise'}<br /><span className={s.badge}>{badges[row.review.rightsStatus]}</span></td><td className={s.amount}>{equityAmount(row.review.expectedDividend)}</td><td className={s.amount}>{row.input.bookedDividend?equityAmount({kind:'known',value:row.input.bookedDividend.amount}):'Source requise'}</td><td className={s.amount}>{equityAmount(row.review.bookedDifference)}</td><td className={s.amount}>{equityAmount(row.review.carryingAmount)}<p>{row.review.accountingBase?.kind==='net_carrying'?'Valeur nette':'Coût explicite'}</p></td><td><span className={s.badge+(row.review.valuation.status!=='comparable'?' '+s.issue:'')}>{badges[row.review.valuation.status]}</span><p>{row.review.valuation.status==='comparable'?equityAmount(row.review.valueDifference):'Non concluant'}</p></td></tr>)}</tbody></table></div>{!visible.length&&<p className={s.empty}>{rows.length?'Aucun résultat pour ces filtres.':'Aucun calcul disponible. Préparez et exécutez la population.'}</p>}{result?.uncovered.length? <p className={s.banner}>Population partielle : {result.uncovered.length} unités sélectionnées sans association documentée, non concluant.</p>:null}</div>
 {chosen?<aside ref={panel} tabIndex={-1} className={s.proof} aria-label='Détail de la participation' onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();close();}}}><button onClick={close}>Fermer le détail (Escape)</button><h2 className={layout.panelTitle}>{chosen.label}</h2>{chosen.label.length>120&&<details><summary>Libellé complet</summary><p>{chosen.label}</p></details>}<h3>Droits et produit</h3><p>{chosen.review.rightsReason}</p><p>Date d’attribution : {chosen.input.entitlementDate??'Source requise'} · applicables {chosen.input.rights?.from??'?'} → {chosen.input.rights?.to??'?'}</p><p>Droit attendu : {equityAmount(chosen.review.expectedDividend)} · enregistré : {chosen.input.bookedDividend?.amount.amount??'Inconnu'} EUR</p><p>Encaissement distinct : {chosen.input.receivedDividend?.amount.amount??'Source requise'} EUR · {chosen.input.receivedDividend?.date??'Date inconnue'}</p><p className={s.muted}>Écritures GL : {chosen.input.bookedEntries?.map(v=>v.amount.amount+" EUR au "+v.date).join(" ; ")||"Source requise"}</p><p className={s.muted}>Encaissements : {chosen.input.receivedEntries?.map(v=>v.amount.amount+" EUR au "+v.date).join(" ; ")||"Source requise"}</p><h3>Valeur externe</h3><span className={s.badge}>{badges[chosen.review.valuation.status]}</span><p>{chosen.review.valuation.reason}</p><p>Base : {chosen.input.accountingBase?.label} · coût {chosen.input.cost?.amount.amount??"Source requise"} EUR · dépréciation {chosen.input.bookedImpairment?.amount.amount??'Inconnue'} EUR · comparée {equityAmount(chosen.review.carryingAmount)}</p>{chosen.input.externalModel?<><p>{chosen.input.externalModel.id} · version {chosen.input.externalModel.version} · {natures[chosen.input.externalModel.nature]}</p><p>Nature d’origine : {natures[chosen.input.externalModel.originNature??chosen.input.externalModel.nature]}</p><p>Date : {chosen.input.externalModel.value.date} · périmètre : {chosen.input.externalModel.perimeter} · base : {chosen.input.externalModel.value.basis}</p><p>Valeur fournie : {chosen.input.externalModel.value.amount.amount} EUR</p><ul>{chosen.input.externalModel.assumptions.map((a,i)=><li key={i}>{a}</li>)}</ul><div className={s.scroll}><table className={s.table} style={{minWidth:450}}><caption>Scénarios fournis, aucun choix favorable automatique</caption><thead><tr><th>Scénario</th><th>Valeur EUR</th><th>Comparaison</th></tr></thead><tbody>{chosen.review.scenarios.map(sc=><tr key={sc.label}><th scope='row'>{sc.label}</th><td className={s.amount}>{sc.value.amount.amount}</td><td>{badges[sc.status]} · {equityAmount(sc.difference)}</td></tr>)}</tbody></table></div></>:<p className={s.banner}>Modèle absent : source requise ; valeur non concluante.</p>}
 <h3>Différences de versions</h3><p>{chosen.review.versionComparison.reason}</p>{chosen.review.versionComparison.changes.length?<dl>{chosen.review.versionComparison.changes.map(c=><div key={c.field} className={s.note}><dt>{c.field}</dt><dd style={{margin:0}}>{c.before||'Absent'} → {c.after||'Absent'}</dd></div>)}</dl>:<p>Aucune différence disponible.</p>}
 <h3>Décision comptable</h3><p>{chosen.review.classificationStatus}</p><p>{chosen.input.decision?.reason??'Décision motivée requise. Aucun seuil universel de détention.'}</p><p>Proposition : {chosen.review.accountingProposal?chosen.review.accountingProposal.amount.amount.amount+' EUR · à revoir':'Aucune proposition comptable validée'}</p>
 <h3>Preuves de cette ligne</h3>{facts.filter(f=>f.details.securityId===chosen.input.securityId).map(f=><p key={f.rowId}><a href={sourceLink(f)}>{f.fileName}</a> · ligne {f.line??'non disponible'} · {f.sheet??'CSV'} · pack {f.pack} · date {f.date}<br /><span className={s.muted}>Version {f.version} · {f.id}</span></p>)}</aside>:<aside className={s.proof}><h2>Détail et preuves</h2><p>Ouvrez une participation pour voir les droits, les dates, le modèle, les scénarios fournis et les versions des sources.</p></aside>}</div></>}
 {tab==='exceptions'&&<><h2>Points à instruire</h2><p>Un écart reste arithmétique ; une valeur non comparable reste non concluante après revue.</p>{result?.exceptions.length?result.exceptions.map(e=><article className={s.note} key={e.id}><h3>{rows.find(r=>r.id===e.rowId)?.label}</h3><p>{e.text} · {equityAmount(e.amount)}</p><button onClick={()=>{setTab('tests');setSelected(e.rowId);}}>Voir le détail</button><p>{run.notes.find(n=>n.id==='investment:'+e.id)?.resolution?.text??'Traitement humain requis'}</p></article>):<p>Aucun constat disponible pour cette version.</p>}</>}
 {tab==='proof'&&<><h2>Sources et imports</h2><p>CSV ou XLSX manuellement importés, versionnés et approuvés. Aucun connecteur documentaire externe. Les modèles sont fournis par l’utilisateur.</p>{!initial.demo&&view?.permissions.includes('prepare')&&<form className={s.form} onSubmit={e=>{e.preventDefault();const file=(e.currentTarget.elements.namedItem('sourceFile') as HTMLInputElement).files?.[0];if(!file)return;const form=new FormData();form.set('file',file);form.set('mapping',JSON.stringify({...INVESTMENT_MAPPING,...(sheet?{sheet}:{})}));form.set('period',JSON.stringify(period));form.set('documentType',sourceType);void mutate(form,true);}}><label>Type de source<select value={sourceType} onChange={e=>setSourceType(e.target.value)}>{INVESTMENT_TYPES.map(t=><option key={t} value={t}>{INVESTMENT_LABELS[t]}</option>)}</select></label><label>Source locale<input name='sourceFile' type='file' accept='.csv,.xlsx' required /></label><label>Feuille XLSX (explicite)<input value={sheet} onChange={e=>setSheet(e.target.value)} /></label><button disabled={busy}>Lire l’aperçu</button></form>}{preview&&<section className={s.banner}><h3>Aperçu à approuver</h3><p>{preview.document.fileName} · {preview.rows.length} lignes · {preview.report.status}</p><p>Version {preview.document.byteHash}</p><button disabled={busy||!!preview.report.blocking.length} onClick={()=>void mutate({command:"approve_import",importId:preview.id,previewHash:preview.previewHash,expectedSourceId:view?.sourceHeads.find(h=>h.document_type===preview.document.documentType)?.import_id??null},true)}>Approuver cette source</button></section>}
 <div className={s.scroll}><table className={s.table}><caption>Sources figées et localisateurs</caption><thead><tr><th>Document / pack</th><th>Élément</th><th>Date</th><th>Localisateur</th><th>Version</th><th>État</th></tr></thead><tbody>{facts.map(f=><tr key={f.rowId}><th scope='row'><a href={sourceLink(f)}>{f.fileName}</a><p>{INVESTMENT_LABELS[f.type]} · {f.pack}</p></th><td>{f.id}</td><td>{f.date}</td><td>{f.sheet??'CSV'} · ligne {f.line}</td><td>{f.version}</td><td>{view?.sourceHeads.some(h=>h.import_id===view.imports.find(b=>b.document.id===f.documentVersionId)?.id)?'Courante':'Remplacée / historique'}</td></tr>)}</tbody></table></div><p className={s.muted}>La page n’existe pas pour ces tableaux ; feuille et ligne sont citées. Les pièces PDF et leur lecture professionnelle sont hors de cette recette structurée.</p></>}
 {tab==='review'&&<><h2>Revue de cette version</h2><p>La revue documente le jugement humain ; elle ne transforme pas les valeurs non comparables en conclusions sur les comptes.</p><p>Préparateur : {run.preparedBy} · auteur de la convention : {run.investmentWork?.authorId??'À définir'} · {STATES[run.state]??run.state}</p><label>Motivation / traitement<textarea disabled={initial.demo||busy} value={reviewText} onChange={e=>setReviewText(e.target.value)} /></label><label>Pièce et ligne citées<select disabled={initial.demo||busy} value={citation} onChange={e=>setCitation(e.target.value)}><option value=''>Choisir une preuve de cette version</option>{facts.map(f=><option value={f.rowId} key={f.rowId}>{f.fileName} · {f.id} · ligne {f.line}</option>)}</select></label>
 {run.notes.map(note=><article key={note.id} className={s.note}><p>{note.text}</p><p>{note.resolution?.text??'Traitement non enregistré'}</p><button disabled={!canPrepare||busy||!reviewText.trim()||!citationValue} onClick={()=>command('resolve',{noteId:note.id,text:reviewText,citation:citationValue})}>Enregistrer le traitement motivé</button></article>)}<p>{run.conclusion??'Conclusion professionnelle à documenter'}</p><div className={s.actions}><button disabled={!canPrepare||busy||!reviewText.trim()||!citationValue} onClick={()=>command('conclude',{text:reviewText,citation:citationValue})}>Enregistrer la conclusion</button><button disabled={!canPrepare||busy||dirty||run.state!=='executed'} onClick={()=>command('submit')}>Soumettre à une autre identité</button>{(['approved','changes_requested'] as const).map(decision=><button key={decision} disabled={!canReview||busy||run.state!=='awaiting_review'||!reviewText.trim()||!citationValue} onClick={()=>command('review',{decision,text:reviewText,citation:citationValue,submittedHash:run.submittedHash})}>{decision==='approved'?'Approuver cette revue':'Demander une correction'}</button>)}<button disabled={!canReview||busy||run.state!=='approved'} onClick={()=>command('lock')}>Verrouiller la feuille</button><button disabled={initial.demo||busy||!view?.permissions.includes('prepare')} onClick={()=>command('revise')}>Créer une révision</button></div>{initial.demo&&<p className={s.banner}>Revue et décisions réelles désactivées dans cet exemple.</p>}
 <button disabled={busy||!result||(!initial.demo&&!view?.permissions.includes("download"))} onClick={()=>void exportFile()}>Diagnostic HTML imprimable</button><h3>Historique</h3><ol>{run.events.map(e=><li key={e.id}>{e.action} · {e.actorId} · version {e.version} · {e.at}</li>)}</ol><h3>Limites</h3><ul>{rows[0]?.review.limitations.map(l=><li key={l}>{l}</li>)}</ul></>}
 </section></>}
 </main>;
}
