"use client";
import { useState } from "react";
import type { InvestigationRow, PayablesResult } from "@/lib/workpapers/payables-investigation";
import { STATUS_LABELS, payablesUnitLabel } from "@/lib/workpapers/payables-program";
import { amountLabel, locatorLabel } from "@/lib/workpapers/client-mission";
import type { WorkpaperRun } from "@/lib/workpapers/model";
import type { framePayables } from "@/lib/workpapers/payables";
import s from "./Payables.module.css";
export function PayablesDetails({ result, run, initialEvent, initialFilter = "all", canDownload = false }: {
    result: PayablesResult;
    run: WorkpaperRun;
    initialEvent?: string;
    initialFilter?: string;
    canDownload?: boolean;
}) {
    const [filter, setFilter] = useState(initialFilter), [selected, setSelected] = useState<string | null>(initialEvent ? result.rows.find(r => r.eventId === initialEvent)?.id ?? null : null);
    const row = result.rows.find(r => r.id === selected), visible = result.rows.filter(r => filter === "all" || filter === "exceptions" ? filter !== "exceptions" || ["omission_candidate", "inconclusive"].includes(r.status) : r.status === filter);
    const proofLinks = (r: InvestigationRow) => [...new Map(r.evidence.map(e => [e.id, e])).values()];
    const cutoffHref = (event?: string) => "/cutoff?" + new URLSearchParams({ dossierId: run.scope.dossierId, periodId: run.scope.periodId, id: run.id, version: String(run.version), ...(event ? { event } : {}) });
    const frame = result.procedure === "payables.frame" ? result.technical as ReturnType<typeof framePayables> : null;
    return <section className={s.section}><h2>Investigation · version {run.version}</h2><p className={s.notice}>Paiements TTC et passif potentiel HT sont distincts. Prestation inconnue ou allocation incomplète : non concluant. La fenêtre de paiements ne prouve pas l’exhaustivité des dettes.</p>
 <div className={s.meta}>{result.controls.map((c, i) => <span key={i}>{c.label} : {c.numerator}/{c.denominator} {payablesUnitLabel(c.unit)}</span>)}</div><p className={s.muted}>Sélection : {result.coverage.selected}/{result.coverage.denominator}. Exclusions : {result.coverage.exclusions.map(e => e.id + " : " + e.reason).join(" ; ") || "aucune"}. Les compteurs viennent du programme.</p>
 {frame && [frame.generalToAuxiliary, frame.auxiliaryToAged].map(c => <div className={s.scroll} key={c.left + c.right} tabIndex={0} role="region" aria-label={c.left + " / " + c.right}><table><caption>{c.left} / {c.right} · écart net {amountLabel(c.metrics.net)} · brut inexpliqué {amountLabel(c.metrics.grossUnexplained)}</caption><thead><tr><th>Clé</th><th>Source</th><th>Cible</th><th>Résiduel</th></tr></thead><tbody>{c.metrics.units.map(u => <tr key={u.id}><th scope="row">{u.id}</th><td>{amountLabel(u.source)}</td><td>{amountLabel(u.target)}</td><td>{amountLabel(u.residual)}</td></tr>)}</tbody></table></div>)}
 {!frame && <><nav className={s.filters} aria-label="Filtres d’investigation">{["all", "exceptions", ...Object.keys(STATUS_LABELS)].map(f => <button key={f} aria-pressed={filter === f} onClick={() => setFilter(f)}>{f === "all" ? "Tous" : f === "exceptions" ? "À expliquer" : STATUS_LABELS[f as keyof typeof STATUS_LABELS]}</button>)}</nav><div className={s.grid}><div className={s.scroll} tabIndex={0} role="region" aria-label="Investigation — défilement clavier"><table><caption>Identité d’événement partagée entre Achats et RPNE ; aucune addition entre les procédures</caption><thead><tr><th>Tiers / facture</th><th>Statut</th><th>Payé / résiduel TTC</th><th>Écart ou candidat HT</th><th>Preuve et dates</th></tr></thead><tbody>{visible.map(r => <tr key={r.id} aria-selected={selected === r.id}><th scope="row">{r.party}<p>{r.invoiceId ?? "Facture à identifier"}</p></th><td>{STATUS_LABELS[r.status]}</td><td>{amountLabel(r.paidTTC ?? undefined)}<p>Résiduel {amountLabel(r.unallocatedTTC ?? undefined)}</p></td><td>{amountLabel(r.status === "omission_candidate" && r.cutoff ? r.cutoff.amount : r.differenceHT)} HT</td><td><button onClick={() => setSelected(r.id)}>Examiner {r.invoiceId ?? r.id}</button>{r.eventId && <p><a href={cutoffHref(r.eventId)}>Même événement dans le cut-off</a></p>}</td></tr>)}{!visible.length && <tr><td colSpan={5}>Aucun élément dans ce filtre.</td></tr>}</tbody></table></div><aside className={s.proof} aria-label="Panneau de preuve"><h2>{row?.invoiceId ?? "Preuves et dates"}</h2>{row ? <><p>{STATUS_LABELS[row.status]} · {row.party}</p><p>Candidat technique cut-off : {row.cutoff?.candidate??"aucun"} · jugement et méthode à revoir</p><code>{row.eventId}</code><ol className={s.timeline}>{[...row.timeline, { label: "Revue", date: run.period.asOfDate, verified: false }].sort((a, b) => (a.date ?? "9999").localeCompare(b.date ?? "9999")).map((t, i) => <li key={i}><time>{t.date ?? "Date inconnue"}</time><br />{t.label} · {t.verified ? "provenance documentée" : "à corroborer"}</li>)}</ol><p>{row.reasons.join(" ; ")}</p>{proofLinks(row).map(e => <div key={e.id}><p>{e.purpose} · {locatorLabel(e.locator)}</p><details><summary>Identité / version de source</summary><code>{e.documentVersionId}</code><code>{e.rowId}</code></details>{canDownload && <a href={"/api/workpapers/payables?" + new URLSearchParams({ dossierId: run.scope.dossierId, periodId: run.scope.periodId, operation: "download", id: e.documentVersionId })}>Télécharger la pièce séparément</a>}</div>)}</> : <p>Sélectionnez une facture dans la table. Les originaux sont absents du paquet exporté.</p>}</aside></div></>}
 <a href={cutoffHref()}>Vue transversale cut-off · ventes / achats</a><details><summary>Limites du résultat</summary><ul>{result.limitations.map(l => <li key={l}>{l}</li>)}</ul></details></section>;
}
