import type { AccountingPeriod } from "@/lib/canonical-model/period";
import type { Money } from "@/lib/canonical-model/money";
import { periodId, type EvidenceLink, type WorkpaperRun } from "@/lib/workpapers/model";
import type { ClientsSalesDraft, ClientsSalesFacts, ClientsSalesResult } from "@/lib/workpapers/clients-sales";
export function receivablesPresentationFixture() {
  const m = (amount: string): Money => ({ amount, currency: "EUR" });
  const period: AccountingPeriod = { startDate: "2024-01-01", closingDate: "2024-12-31", asOfDate: "2025-02-28", currency: "EUR", validation: "provisional" };
  const scope = { organizationId: "actual-org", dossierId: "11111111-1111-4111-8111-111111111111", periodId: periodId(period), mode: "real" as const };
  const proof: EvidenceLink = { id: "proof-invoice", scope, procedureId: "clients-sales", documentVersionId: "document-invoices", rowId: "row-invoice", locator: { row: 2 }, precision: "row", status: "verified", purpose: "Facture ouverte à clôture" };
  const paymentProof: EvidenceLink = { ...proof, id: "proof-payment", documentVersionId: "document-payments", rowId: "row-payment", purpose: "Encaissement ultérieur" };
  const refs = [{ importId: "import-payments", rowId: "row-payment" }];
  const facts: ClientsSalesFacts = { invoices: [{ id: "INV-1000", customerId: "Client A", amount: m("1000.00"), issuedOn: "2024-01-10", letteringStatus: "unknown", bookedImpairment: { kind: "unknown", reason: "Non documentée" }, evidence: [proof] }], payments: [{ id: "PAY-300", customerId: "Client A", amount: m("300.00"), paidOn: "2025-01-15", kind: "payment", evidence: [paymentProof] }], credits: [], sourceOptions: [{ importId: "import-invoices", rowId: "row-invoice", documentVersionId: "document-invoices", fileName: "factures.csv", label: "INV-1000", locator: { row: 2 }, kind: "clients_invoices" }, { importId: "import-payments", rowId: "row-payment", documentVersionId: "document-payments", fileName: "encaissements.csv", label: "PAY-300", locator: { row: 2 }, kind: "clients_payments" }] };
  const draft: ClientsSalesDraft = { window: { startDate: "2025-01-01", endDate: "2025-02-28", coverage: "documented", note: "Relevé des encaissements jusqu’au 28 février", evidenceRefs: refs }, creditsAbsence: { note: "Aucun avoir dans cette fenêtre", evidenceRefs: refs }, allocations: [{ id: "allocation-300", paymentId: "PAY-300", invoiceId: "INV-1000", amount: m("300.00"), status: "validated", evidenceRefs: refs }], estimates: [], confirmations: [] };
  const result: ClientsSalesResult = { schemaVersion: "clients-sales-result-1", scope, runId: "clients-sales", framing: { runId: "frame", rootId: "frame", version: 12, contentHash: "f".repeat(64) }, window: { ...draft.window, documentVersionIds: ["document-payments"], evidence: [paymentProof] }, creditsAbsence: { ...draft.creditsAbsence!, evidence: [paymentProof] }, closingDate: period.closingDate, reviewDate: period.asOfDate, rows: [{ invoiceId: "INV-1000", customerId: "Client A", issuedOn: "2024-01-10", dueOn: null, cancelledOn: null, dueAtClosing: m("1000.00"), subsequentPayments: m("300.00"), subsequentCredits: m("0.00"), dueAtReview: m("700.00"), aging: { from: "2024-01-10", label: "jours depuis facture — échéance inconnue", days: 415, basis: "invoice" }, overdueDays: null, uncertainties: ["Recouvrabilité non étayée"], evidence: [proof, paymentProof], confirmationIds: [], timeline: [{ id: "payment-event", date: "2025-01-15", kind: "payment", label: "Encaissement affecté PAY-300", amount: { kind: "known", value: m("300.00") }, proofIds: [paymentProof.id], effect: "review" }] }], payments: [{ ...facts.payments[0], cancelledOn: null, validatedAllocated: m("300.00"), proposedAmount: m("0.00"), residualUnallocated: m("0.00"), availableToAllocate: m("0.00"), status: "active" }], allocations: [{ ...draft.allocations[0], authorId: "actual-preparer", authoredAt: "2025-03-01T12:00:00Z", evidence: [paymentProof] }], credits: [], estimates: [], confirmations: [], exceptions: [{ id: "missing-estimate", controlId: "impairment", code: "CLIENT_ESTIMATE_MISSING", label: "Estimation à documenter", targetId: "INV-1000", message: "Un reste de 700 ne constitue pas une perte estimée.", amount: { kind: "unknown", reason: "Méthode absente" }, proofIds: [proof.id] }], controls: [{ id: "cashCredit", label: "Encaissements et avoirs", outcome: "no_exception_detected", numerator: 1, denominator: 1, exclusions: [] }, { id: "impairment", label: "Estimation et litiges", outcome: "inconclusive", numerator: 0, denominator: 1, exclusions: [] }, { id: "confirmations", label: "Confirmations", outcome: "inconclusive", numerator: 0, denominator: 1, exclusions: [] }], mode: "real", conclusion: null };
  const run: WorkpaperRun = { id: "clients-sales", rootId: "clients-sales", revision: 1, version: 6, schemaVersion: "1.0.0", scope, period, template: { id: "clients.sales", version: "1.0.0", objective: "Clients et ventes", kind: "calculated", assertions: [], requiredDocumentTypes: [] }, state: "executed", preparedBy: "actual-preparer", importIds: ["import-invoices", "import-payments"], evidence: [proof, paymentProof], notes: [], findings: [], events: [{ id: "server-event", action: "executed", actorId: "actual-preparer", at: "2025-03-01T12:00:00Z", version: 6 }], result: { id: "result-clients-sales", calculationKey: "clients.sales", ruleVersion: "1.0.0", inputHash: "d".repeat(64), scope, period, execution: "completed", outcome: "inconclusive", sourceRefs: [], input: draft, result, warnings: [], blockedControls: [], findings: [] } };
  run.clientsWork = { ...draft, schemaVersion: "clients-sales-1", framing: { runId: "frame", rootId: "frame", version: 12, contentHash: "f".repeat(64) }, window: { ...draft.window, documentVersionIds: ["document-payments"] }, allocations: draft.allocations.map(a => ({ ...a, authorId: "actual-preparer", authoredAt: "2025-03-01T12:00:00Z" })), estimates: [], confirmations: [] };
  return { run, draft, facts, result, refs, period };
}
