// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { ClientReceivablesPanel } from "../ClientReceivablesPanel";
import { ClientsSalesImportForm } from "../ClientsSalesImportForm";
import { receivablesPresentationFixture } from "./client-receivables-fixture";
import type { ClientsSalesDraft } from "@/lib/workpapers/clients-sales";
afterEach(cleanup);
function mount() { const f = receivablesPresentationFixture(), configure = vi.fn(), freeze = vi.fn(), dirty = vi.fn(); const props = { run: f.run, draft: f.draft, facts: f.facts, editable: true, busy: false, onConfigure: configure, onFreeze: freeze, onDraftChange: dirty }; return { ...f, configure, freeze, dirty, props, ...render(<ClientReceivablesPanel {...props}/>) }; }
function invoiceRow() { return screen.getByRole("row", { name: /Client A INV-1000/ }); }
describe("Clients et ventes — présentation des faits serveur", () => {
  it("montre 1 000 à clôture, 300 affectés et 700 à la revue sans inventer de retard ni de perte", () => { mount(); const row = within(invoiceRow()); expect(row.getByText("1000.00 EUR")).toBeTruthy(); expect(row.getByText("300.00 EUR")).toBeTruthy(); expect(row.getByText("700.00 EUR")).toBeTruthy(); expect(row.getByText(/Échéance inconnue/)).toBeTruthy(); expect(row.getByText(/jours depuis facture/)).toBeTruthy(); expect(row.queryByText(/retard de \d/)).toBeNull(); expect(screen.getByText("Un reste de 700 ne constitue pas une perte estimée.")).toBeTruthy(); expect(screen.queryByText(/créance entièrement sûre$/)).toBeNull(); });
  it("distingue la proposition et les montants calculés ; aucun total optimiste pendant la sauvegarde", () => { const f = mount(); expect(screen.getByText("Allocation validée — accusé serveur")).toBeTruthy(); fireEvent.click(screen.getByRole("button", { name: "Revenir à une proposition" })); expect(screen.getByText("Proposition d’appariement")).toBeTruthy(); fireEvent.click(screen.getByRole("button", { name: "Sauvegarder allocations et jugement" })); const draft: ClientsSalesDraft = f.configure.mock.calls[0][0]; expect(draft.allocations[0].status).toBe("proposed"); expect(draft.allocations[0]).not.toHaveProperty("authorId"); expect(draft).not.toHaveProperty("actorId"); f.rerender(<ClientReceivablesPanel {...f.props} busy/>); expect(within(invoiceRow()).getByText("700.00 EUR")).toBeTruthy(); expect(within(invoiceRow()).getByText("1000.00 EUR")).toBeTruthy(); expect(screen.getByRole("button", { name: "Sauvegarder allocations et jugement" })).toHaveProperty("disabled", true); });
  it("un événement d’annulation reçu du serveur change la revue et garde le solde de clôture", () => { const f = mount(); const result = { ...f.result, rows: f.result.rows.map(r => ({ ...r, dueAtReview: { amount: "1000.00", currency: "EUR" as const }, subsequentPayments: { amount: "0.00", currency: "EUR" as const }, timeline: [...r.timeline, { id: "cancel", date: "2025-02-01", kind: "cancellation" as const, label: "Annulation après clôture PAY-300", amount: { kind: "known" as const, value: { amount: "300.00", currency: "EUR" as const } }, proofIds: [], effect: "review" as const }] })), payments: f.result.payments.map(p => ({ ...p, cancelledOn: "2025-02-01" })) }; f.rerender(<ClientReceivablesPanel {...f.props} run={{ ...f.run, version: 7, result: { ...f.run.result!, result } }}/>); const cells = within(invoiceRow()).getAllByRole("cell"); expect(cells[1].textContent).toBe("1000.00 EUR"); expect(cells[4].textContent).toBe("1000.00 EUR"); expect(screen.getByText("Annulation après clôture PAY-300")).toBeTruthy(); expect(screen.getByText("Annulé le 2025-02-01")).toBeTruthy(); });
  it("une méthode absente reste une incertitude et la préparation ne fournit aucun auteur", () => { const f = mount(); fireEvent.click(screen.getByRole("tab", { name: "Litiges et estimation" })); fireEvent.change(screen.getByLabelText("Litige / incertitude"), { target: { value: "Litige en cours, preuves à compléter" } }); fireEvent.change(screen.getByLabelText("Montant estimé"), { target: { value: "70" } }); expect(screen.getByText("Méthode absente : estimation non étayée, incertitude maintenue.")).toBeTruthy(); fireEvent.click(screen.getByRole("button", { name: "Sauvegarder allocations et jugement" })); const draft = f.configure.mock.calls[0][0] as ClientsSalesDraft; expect(draft.estimates[0].method).toBeNull(); expect(draft.estimates[0].amount.amount).toBe("70.00"); expect(draft.estimates[0]).not.toHaveProperty("authorId"); expect(draft.estimates[0]).not.toHaveProperty("approvedBy"); expect(within(invoiceRow()).getByText("700.00 EUR")).toBeTruthy(); });
  it("la confirmation reste reliée aux références importées et ne propose aucun envoi externe", () => { const f = mount(); fireEvent.click(screen.getByRole("tab", { name: "Confirmations et preuves" })); fireEvent.click(screen.getByLabelText("Demande documentée")); fireEvent.change(screen.getByLabelText("Canal de demande"), { target: { value: "Demande hors application documentée" } }); const select = screen.getByLabelText("Preuves de la demande") as HTMLSelectElement; select.options[1].selected = true; fireEvent.change(select); fireEvent.click(screen.getByLabelText("Réponse reçue")); fireEvent.change(screen.getByLabelText("Canal de réponse"), { target: { value: "Courrier reçu" } }); fireEvent.click(screen.getByRole("button", { name: "Sauvegarder allocations et jugement" })); const draft = f.configure.mock.calls[0][0] as ClientsSalesDraft; expect(draft.confirmations[0].request!.evidenceRefs).toEqual(f.refs); expect(draft.confirmations[0].response!.origin).toBe("unknown"); expect(draft.confirmations[0]).not.toHaveProperty("authorId"); expect(screen.queryByRole("button", { name: /envoyer/i })).toBeNull(); expect(screen.getByText(/Ce suivi n’envoie aucun message externe/)).toBeTruthy(); });
  it("transmet une fenêtre documentée à figer et conserve la navigation clavier des onglets", () => { const f = mount(); f.rerender(<ClientReceivablesPanel {...f.props} run={{ ...f.run, state: "draft", result: undefined }}/>); fireEvent.click(screen.getByRole("button", { name: "Figer les factures et cette fenêtre" })); expect(f.freeze).toHaveBeenCalledWith({ window: f.draft.window, creditsAbsence: f.draft.creditsAbsence }); const tab = screen.getByRole("tab", { name: "Allocations et résiduels" }); tab.focus(); fireEvent.keyDown(tab, { key: "ArrowRight" }); expect(screen.getByRole("tab", { name: "Litiges et estimation" })).toBe(document.activeElement); expect(screen.getByRole("tab", { name: "Litiges et estimation" }).getAttribute("aria-selected")).toBe("true"); });
});
describe("mapping Clients fermé", () => {
  it("déclare le solde clôture, la devise et une échéance facultative sans inventer de mapping", () => { const f = receivablesPresentationFixture(), preview = vi.fn(); render(<ClientsSalesImportForm period={f.period} busy={false} onPreview={preview}/>); const file = new File(["id;amount;date;customer;currency\nINV-1000;1000.00;2024-01-10;Client A;EUR"], "factures.csv", { type: "text/csv" }); fireEvent.change(screen.getByLabelText("Fichier Clients CSV ou XLSX"), { target: { files: [file] } }); fireEvent.submit(screen.getByRole("button", { name: "Analyser la source Clients" }).closest("form")!); const data: FormData = preview.mock.calls[0][0], mapping = JSON.parse(String(data.get("mapping"))); expect(data.get("documentType")).toBe("clients_invoices"); expect(mapping).toMatchObject({ version: "clients-sales-1", sales: { customerColumn: "customer", currencyColumn: "currency" }, currency: "EUR" }); expect(mapping.sales).not.toHaveProperty("dueOnColumn"); expect(mapping).not.toHaveProperty("actorId"); expect(mapping).not.toHaveProperty("approval"); expect(screen.getByText(/Le montant importé est le solde ouvert à la clôture/)).toBeTruthy(); });
  it("signale les originaux absents du registre et demande la facture cible pour les avoirs", () => { const f = receivablesPresentationFixture(); render(<ClientsSalesImportForm period={f.period} busy={false} onPreview={vi.fn()}/>); fireEvent.change(screen.getByLabelText("Source Clients"), { target: { value: "clients_support" } }); expect(screen.getByText(/Une ligne de registre ne remplace pas un original absent/)).toBeTruthy(); fireEvent.change(screen.getByLabelText("Source Clients"), { target: { value: "clients_credits" } }); expect(screen.getByLabelText("Colonne facture de l’avoir")).toHaveProperty("required", true); });
});
