// @vitest-environment jsdom
import { afterEach,it,expect,vi } from 'vitest';
import { File as NodeFile } from 'node:buffer';
import { cleanup,render,screen,fireEvent,waitFor } from '@testing-library/react';
import { InvestmentWorkspace } from '../InvestmentWorkspace';
import { investmentFixture } from '@/lib/workpapers/investment-fixture';
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
const BrowserFile=File;
const initial={demo:true,case:'',dossierId:'',periodId:'',id:'',tab:'tests'};
async function view(){vi.stubGlobal('File',NodeFile);const f=await investmentFixture();return {f,data:{actorId:f.actor.id,permissions:[],runs:[f.run],facts:{[f.run.id]:f.facts},imports:f.imports,sourceHeads:f.imports.map(b=>({document_type:b.document.documentType,import_id:b.id}))}};}
it('détail, différences, scénarios et Escape conservent le contexte et restituent le focus',async()=>{const {data}=await view();vi.stubGlobal('fetch',vi.fn(async()=>Response.json(data)));render(<InvestmentWorkspace initial={initial} />);const button=await screen.findByRole('button',{name:/Détail de Orion/});fireEvent.click(button);const panel=screen.getByRole('complementary',{name:'Détail de la participation'});expect(panel.textContent).toContain('Coût moins dépréciation enregistrée');expect(panel.textContent).toContain('Central fourni');expect(panel.textContent).toContain('110.00 EUR → 85.00 EUR');fireEvent.keyDown(panel,{key:'Escape'});expect(screen.queryByRole('complementary',{name:'Détail de la participation'})).toBeNull();expect(document.activeElement).toBe(button);});
it('filtre sans résultat reste explicite et navigation clavier des onglets fonctionne',async()=>{const {data}=await view();vi.stubGlobal('fetch',vi.fn(async()=>Response.json(data)));render(<InvestmentWorkspace initial={initial} />);await screen.findByRole('button',{name:/Détail de Orion/});fireEvent.change(screen.getByLabelText('Recherche explicite'),{target:{value:'aucun-titre'}});expect(screen.getByText('Aucun résultat pour ces filtres.')).toBeTruthy();const tests=screen.getByRole('tab',{name:'Tests'});fireEvent.keyDown(tests,{key:'ArrowRight'});expect(screen.getByRole('tab',{name:'Exceptions'}).getAttribute('aria-selected')).toBe('true');});
it('l’approbation UI envoie la commande du contrat et attend l’accusé serveur',async()=>{const {f,data}=await view();const preview={...f.imports[0],approval:undefined,report:{...f.imports[0].report,calculationAllowed:false}},run={...f.run,state:'draft',population:undefined,selection:undefined,investmentWork:undefined,result:undefined,importIds:[],notes:[]};let approved=false;const realView={...data,permissions:['prepare','read'],runs:[run],imports:[],facts:{[run.id]:[]},sourceHeads:[]};vi.stubGlobal('fetch',vi.fn(async(url:string,options?:RequestInit)=>{if(url==='/api/auth/session')return Response.json({csrfToken:'synthetic-csrf'});if(options?.method==='POST'){if(options.body instanceof FormData)return Response.json({batch:preview});const body=JSON.parse(options.body as string);expect(body.command).toBe('approve_import');expect(body.previewHash).toBe(preview.previewHash);approved=true;return Response.json({batch:f.imports[0]});}return Response.json(realView);}));render(<InvestmentWorkspace initial={{...initial,demo:false,dossierId:'11111111-1111-4111-8111-111111111111',periodId:f.scope.periodId}} />);await screen.findByRole('tab',{name:'Pièces'});fireEvent.click(screen.getByRole('tab',{name:'Pièces'}));fireEvent.change(screen.getByLabelText('Source locale'),{target:{files:[new BrowserFile(['synthetic file'],'source.csv',{type:'text/csv'})]}});fireEvent.submit(screen.getByRole('button',{name:'Lire l’aperçu'}).closest('form')!);await screen.findByRole('button',{name:'Approuver cette source'});expect(approved).toBe(false);fireEvent.click(screen.getByRole('button',{name:'Approuver cette source'}));await waitFor(()=>expect(approved).toBe(true));await waitFor(()=>expect(screen.queryByText('Aperçu à approuver')).toBeNull());});
