import { canonicalCompare, canonicalJson, stableSha256 } from "@/lib/synthesis/canonical";
import { cashAmountLabel, cashLocatorLabel, type CashMissionSnapshot } from "@/lib/workpapers/cash-mission";
import { assertScope, contentHash, validateRun, type EvidenceLink, type WorkpaperRun } from "@/lib/workpapers/model";
import type { ImportBatch } from "@/lib/workpapers/imports";
import { artifact } from "./package";
import { buildCsv } from "./csv";
import { buildPdfFromAccessibleHtml } from "./pdf";
import type { EvidenceExportPackage, EvidenceManifest } from "./types";

export type CashExportKind = "diagnostic" | "approved";
export function assertCashPackage(mission: CashMissionSnapshot, run: WorkpaperRun | null, kind: CashExportKind) {
  const { hash, ...body } = mission;
  if (stableSha256(body) !== hash) throw new Error("EXPORT_SNAPSHOT_HASH_INVALID");
  if (run) {
    validateRun(run); assertScope(mission.scope, run.scope);
    if (run.id !== mission.procedure.runId || run.version !== mission.procedure.version || contentHash(run) !== mission.procedure.contentHash) throw new Error("EXPORT_VERSION_INVALID");
  } else if (mission.procedure.runId) throw new Error("EXPORT_RUN_REQUIRED");
  if (kind === "approved" && (!run || run.state !== "locked" || mission.procedure.stale || !mission.procedure.cash || !run.approval || run.approval.snapshotHash !== contentHash(run))) throw new Error("EXPORT_APPROVED_CURRENT_LOCKED_REQUIRED");
}
const escapeHtml = (value: unknown) => String(value ?? "—").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
function table(title: string, headings: string[], rows: unknown[][]) {
  return `<table><caption>${escapeHtml(title)}</caption><thead><tr>${headings.map(h => `<th scope="col">${escapeHtml(h)}</th>`).join("")}</tr></thead><tbody>${rows.length ? rows.map(row => `<tr>${row.map(cell => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`).join("") : `<tr><td colspan="${headings.length}">Aucun élément.</td></tr>`}</tbody></table>`;
}
const links = (proofs: Pick<EvidenceLink, "id" | "documentVersionId" | "rowId" | "locator">[]) => proofs.map(p => p.id + " · " + p.documentVersionId + "/" + (p.rowId ?? "document entier") + " · " + cashLocatorLabel(p.locator)).join(" ; ") || "Pièce attendue ou absente";
function cashDetails(m: CashMissionSnapshot) {
  const c = m.procedure.cash;
  if (!c) return "<section><h2>Pont bancaire</h2><p>Aucun résultat Trésorerie exploitable pour cette version.</p></section>";
  return "<section><h2>Pont bancaire par compte — clôture et apurement séparés</h2><p>Clôture " + escapeHtml(c.closingDate) + " ; revue " + escapeHtml(c.reviewDate) + ". Convention " + escapeHtml(c.convention.version) + " validée par " + escapeHtml(c.convention.validatedBy) + " : " + escapeHtml(c.convention.meaning) + "</p>"
    + "<p>Fenêtre " + escapeHtml(c.window.startDate) + " → " + escapeHtml(c.window.endDate) + " ; couverture " + escapeHtml(c.window.coverage === "documented" ? "documentée" : "incomplète") + " ; " + escapeHtml(c.window.note) + " ; pièces " + escapeHtml(links(c.window.evidence)) + ".</p>"
    + "<p class='notice'>Des totaux concordants ne donnent aucune assurance d’authenticité. Les apurements postérieurs ne modifient jamais les soldes à la clôture. Caisse et VMP sont hors de ce pont.</p>"
    + table("Population des comptes de trésorerie", ["Compte GL / banque / référence", "Devise / nature", "Périmètre", "Preuves"], c.accounts.map(a => [a.glAccount + " / " + a.bankId + " / " + a.accountReference + " · " + a.label, a.currency + " / " + a.nature, a.inScope ? "Compte bancaire EUR testé" : "Exclu : " + a.exclusionReason, links(a.evidence)]))
    + table("Pont de rapprochement", ["Compte", "Relevé", "+ Remises", "− Paiements", "± Autres", "= Reconstitué", "GL", "Écart du pont"], c.accounts.map(a => a.bridge.status === "computed"
      ? [a.accountId, cashAmountLabel(a.bridge.statement.amount), cashAmountLabel(a.bridge.receiptsInTransit), cashAmountLabel(a.bridge.outstandingPayments), cashAmountLabel(a.bridge.otherItems), cashAmountLabel(a.bridge.reconstructed), cashAmountLabel(a.bridge.ledger.amount), cashAmountLabel(a.bridge.difference)]
      : [a.accountId, a.bridge.status === "excluded" ? "Exclu" : "Non calculé", "—", "—", "—", "—", a.bridge.status === "incomplete" ? cashAmountLabel(a.bridge.ledger.amount) : "—", a.bridge.status === "excluded" ? a.bridge.reason : a.bridge.missing.join(" ; ")]))
    + table("Écarts de source (distincts de l’écart du pont)", ["Compte", "ERB comptable − GL", "ERB banque − relevé", "Arithmétique de l’ERB", "Suspens non expliqués (brut)"], c.accounts.filter(a => a.bridge.status === "computed").map(a => a.bridge.status === "computed" ? [a.accountId, cashAmountLabel(a.bridge.bookSourceDifference), cashAmountLabel(a.bridge.bankSourceDifference), cashAmountLabel(a.bridge.erbArithmeticDifference), cashAmountLabel(a.bridge.grossUnexplained) + " · " + a.bridge.unexplainedCount + " ligne(s)"] : []))
    + table("Suspens à la clôture et apurement", ["Compte / suspens / nature", "Montant / date / âge", "Explication / pièce", "Statut et sens", "Apuré / reste", "Allocations et correction"], c.accounts.flatMap(a => a.items.map(i => [
      a.accountId + " / " + i.itemId + " / " + i.kind, cashAmountLabel(i.amount) + " · " + i.date + " · " + i.ageDays + " jours à la clôture", (i.explanation || "Aucune explication") + " · pièce " + (i.pieceRef || "non renseignée") + " · " + links(i.evidence),
      i.statusLabel + " — " + i.statusMeaning + (i.exclusionReason ? " Motif : " + i.exclusionReason : ""), cashAmountLabel(i.settledAmount) + " / " + cashAmountLabel(i.remainingAmount),
      [...i.allocations.map(x => x.id + " : " + x.settlementId + " " + cashAmountLabel(x.amount) + " le " + x.settlementDate + " · " + x.authorId + " · " + x.authoredAt), ...(i.correction ? ["Correction " + i.correction.id + " : " + i.correction.reason + " · " + i.correction.authorId + " · " + links(i.correction.evidence)] : [])].join(" ; ") || "Aucune"])))
    + table("Mouvements postérieurs (fenêtre)", ["Compte / mouvement", "Montant / date", "Libellé / pièce", "Alloué / non alloué"], c.accounts.flatMap(a => a.settlements.map(s => [a.accountId + " / " + s.settlementId, cashAmountLabel(s.amount) + " · " + s.date, s.label + " · " + s.pieceRef + " · " + links(s.evidence), cashAmountLabel(s.allocated) + " / " + cashAmountLabel(s.unallocated)])))
    + table("Exceptions et incertitudes conservées après revue", ["Identité / contrôle / cible", "Constat", "Montant", "Preuves"], c.exceptions.map(e => [e.id + " / " + e.controlId + " / " + e.targetId, e.label + " ; " + e.message, cashAmountLabel(e.amount), e.proofIds.join(" ; ") || "Pièce attendue"])) + "</section>";
}
export function cashMissionHtml(m: CashMissionSnapshot, run: WorkpaperRun | null, kind: CashExportKind, createdAt: string) {
  const p = m.procedure;
  const status = kind === "approved" ? "Paquet du pont bancaire approuvé et verrouillé — portée : cette procédure uniquement" : "Export diagnostic — ne constitue pas un paquet approuvé";
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>PROBANT — Trésorerie</title><style>
body{font:15px/1.55 system-ui,sans-serif;color:#18283c;background:white;margin:2rem auto;max-width:1120px;padding:0 1rem}h1{font-size:26px}h2{font-size:20px;margin-top:2rem}p,td,th{overflow-wrap:anywhere;white-space:pre-wrap}table{width:100%;border-collapse:collapse;margin:1rem 0;table-layout:fixed}caption{text-align:left;font-weight:700;margin:.5rem 0}th,td{text-align:left;vertical-align:top;border:1px solid #b5bfcb;padding:7px;font-size:12px}th{background:#edf1f6}thead{display:table-header-group}tr{break-inside:avoid}header{border-bottom:2px solid #344b67}.notice{border-left:4px solid #ab7015;padding:1rem;background:#fff7e4}@page{size:A4 landscape;margin:16mm}@media print{body{max-width:none;margin:0;padding:0;font-size:11px}h2{break-after:avoid}th{background:#eee}table{font-size:10px}.notice{background:none}}
</style></head><body><header><p>Procédures de mission · infrastructure de recette jetable</p><h1>Trésorerie — ${escapeHtml(p.label)}</h1><p>${escapeHtml(status)}</p><p>Dossier ${escapeHtml(m.scope.dossierId)} · Organisation ${escapeHtml(m.scope.organizationId)} · Période ${escapeHtml(m.scope.periodId)}</p><p>Feuille ${escapeHtml(p.runId)} · révision ${escapeHtml(p.revision)} · version ${escapeHtml(p.version)} · préparation ${escapeHtml(p.preparedBy)}</p><p>État serveur ${escapeHtml(m.hash)} · état établi au ${escapeHtml(createdAt)}</p></header>
<section><h2>Résumé humain</h2><p>${escapeHtml(p.resultLabel)}. ${escapeHtml(p.reviewLabel)}.</p><p>${escapeHtml(p.conclusion)}</p><p class="notice">${escapeHtml(p.stale ? "Travail périmé : " + p.staleReasons.join(" ") : "Sources courantes à la génération de cet état.")} Une revue documentée ne vaut pas conformité des comptes ; aucune opinion automatique.</p><p>Programme ${escapeHtml(m.program.id)} @ ${escapeHtml(m.program.version)} : ${m.counters.executed}/${m.counters.planned} procédure exécutée ; ${m.counters.testedParts}/${m.counters.plannedParts} contrôles complets ; ${m.counters.exceptions} exceptions ; ${m.counters.uncertainties} incertitudes. Les exceptions ne constituent pas le dénominateur du programme.</p><p>Hors périmètre de ce programme : ${escapeHtml(m.program.outOfScope.join(" ; "))}.</p></section>
<section><h2>File de travail priorisée</h2>${table("Actions liées à cette version", ["Priorité", "Catégorie", "Action", "Détail / identité"], m.queue.map(q => [q.priority, q.category, q.label, q.detail + " · " + q.id + " · " + q.href]))}</section>
<section><h2>Procédure, population et sélection</h2>${table("Programme fermé", ["Procédure", "Contrôles prévus", "Conventions"], m.program.procedures.map(d => [d.label + " @ " + d.version, d.tests.map(t => t.label).join(" ; "), p.controls.map(c => c.label + " : " + c.convention).join(" ")]))}<p>Couverture ${p.coverage.numerator}/${p.coverage.denominator ?? "inconnu"} ${escapeHtml(p.coverage.unit)}. Critères : ${escapeHtml(p.coverage.criteria)}.</p>${table("Exclusions motivées de la population", ["Unité", "Raison"], p.coverage.exclusions.map(e => [e.id, e.reason]))}${table("Contrôles et dénominateurs", ["Contrôle", "Résultat", "Numérateur / dénominateur", "Exclusions"], p.controls.map(c => [c.label, c.outcome ?? "Non exécuté", c.coverage.numerator + "/" + (c.coverage.denominator ?? "inconnu") + " " + c.coverage.unit, c.coverage.exclusions.map(e => e.id + " : " + e.reason).join(" ; ") || "Aucune"]))}${table("Population figée", ["Unité", "Montant GL", "Lignes sources", "Sélection"], run?.population?.items.map(item => [item.id, cashAmountLabel(item.amount), item.rowIds.join(" ; "), run.selection?.selectedIds.includes(item.id) ? "Sélectionnée" : "Exclue avec motif"]) ?? [])}</section>
${cashDetails(m)}<section><h2>Décisions et comparaison avant / après revue</h2><p>Résultat ${escapeHtml(p.resultId)} · entrées ${escapeHtml(p.resultInputHash)} · contenu ${escapeHtml(p.contentHash)}.</p>${table("Décision sur la version", ["Auteur réel", "Version approuvée / date", "Décision motivée", "Résultat après revue"], p.review ? [[p.review.actorId, p.review.approvedVersion + " · " + p.review.at, p.review.note, p.resultLabel]] : [])}${table("Avant / après revue", ["Moment", "Version / résultat", "Conclusion", "Traitements documentés"], [p.beforeReview && ["Soumission", p.beforeReview.version + " / " + p.beforeReview.resultId, p.beforeReview.conclusion, p.beforeReview.notes.map(n => n.text + " : " + (n.resolution?.text ?? "Ouvert")).join(" ; ")], p.afterReview && ["Après revue", p.afterReview.version + " / " + p.afterReview.resultId, p.afterReview.conclusion, p.afterReview.notes.map(n => n.text + " : " + (n.resolution?.text ?? "Ouvert")).join(" ; ")]].filter((r): r is string[] => !!r))}${table("Commentaires / exceptions et leur traitement", ["Identité", "Auteur", "Texte", "Traitement"], p.notes.map(n => [n.id, n.authorId, n.text, n.resolution ? n.resolution.text + " · " + n.resolution.authorId + " · " + n.resolution.at : n.blocking ? "Bloquant ouvert" : "Ouvert"]))}${table("Versions et anciennes décisions", ["Identité / version", "État / empreinte", "Auteur", "Décision conservée"], m.versionIndex.map(v => [v.id + " · r" + v.revision + " v" + v.version, v.state + " · " + v.contentHash, v.actorId, v.approval ? v.approval.actorId + " : " + v.approval.note : v.reviewNotes.map(n => n.authorId + " : " + n.text).join(" ; ") || v.events.at(-1)?.action || "Aucune approbation"]))}</section>
<section><h2>Sources et index des pièces</h2><p class="notice">Les originaux binaires ne sont pas inclus dans ce paquet. Leur téléchargement séparé exige la permission d’export du même dossier. Une pièce absente ne devient pas une preuve fournie.</p>${table("Index des pièces versionnées", ["Pièce / identité", "Version / SHA-256", "Provenance / approbation", "Présence et actualité"], m.sources.map(s => [s.label + " · " + (s.fileName ?? "Attendue") + " · " + s.id, s.importId + " · " + (s.sha256 ?? "Absent"), "Parseur " + s.parserVersion + " ; mapping " + s.mappingVersion + "/" + s.mappingHash + " ; " + s.approvedBy + " · " + s.approvedAt, !s.available ? (s.required ? "Pièce requise absente" : "Pièce conditionnelle absente") : (s.current ? "Source courante" : "Source remplacée / périmée") + " · binaire absent du paquet"]))}${table("Localisateurs des lignes sources", ["Document versionné", "Ligne", "Localisateur"], m.sources.flatMap(s => s.locators.map(l => [s.id, l.rowId, cashLocatorLabel(l.locator)])))}</section>
<section><h2>Incertitudes et limites</h2><ul>${[...m.limitations, ...p.coverage.limitations, ...(run?.result?.warnings ?? []), ...(run?.result?.blockedControls ?? []), "PDF standard dérivé du HTML, sans certification PDF/A ; caractères hors alphabet Latin-1 remplacés dans ce PDF. HTML et JSON conservent le texte Unicode."].map(l => `<li>${escapeHtml(l)}</li>`).join("")}</ul><p>Famille de ce rapport : procédures de mission. Les constats historiques DEMO SA et l’atelier synthétique ne sont pas inclus.</p></section></body></html>`;
}
export async function buildCashMissionPackage(mission: CashMissionSnapshot, run: WorkpaperRun | null, imports: ImportBatch[], kind: CashExportKind, createdAt: string): Promise<EvidenceExportPackage> {
  assertCashPackage(mission, run, kind);
  const sourceIds = new Set(mission.sources.filter(s => s.available).map(s => s.importId));
  const batches = imports.filter(b => sourceIds.has(b.id)).sort((a, b) => canonicalCompare(a.id, b.id)); batches.forEach(b => assertScope(mission.scope, b.scope));
  if (batches.length !== sourceIds.size) throw new Error("EXPORT_SOURCE_REQUIRED");
  const report = { exportSchemaVersion: "cash-mission-1.0.0", kind, createdAt, mission, run, imports: batches, binaryFilesIncluded: false };
  const canonical = canonicalJson(report), html = cashMissionHtml(mission, run, kind, createdAt), p = mission.procedure, c = p.cash;
  const csv = {
    findings: buildCsv(["procedureId", "runId", "version", "resultId", "controlId", "code", "id", "accountId", "target", "amount", "message", "proofs"], (c?.exceptions ?? []).map(e => ({ procedureId: p.id, runId: p.runId, version: p.version, resultId: p.resultId, controlId: e.controlId, code: e.code, id: e.id, accountId: e.accountId, target: e.targetId, amount: cashAmountLabel(e.amount), message: e.message, proofs: e.proofIds }))),
    reviewEvents: buildCsv(["procedureId", "runId", "version", "actorId", "at", "action", "note"], mission.versionIndex.flatMap(v => v.events.slice(-1).map(e => ({ ...e, procedureId: p.id, runId: v.id, version: v.version, note: v.approval?.note ?? "" })))),
    controls: buildCsv(["procedureId", "runId", "version", "ruleVersion", "controlId", "label", "outcome", "complete", "numerator", "denominator", "unit", "exclusions"], p.controls.map(x => ({ procedureId: p.id, runId: p.runId, version: p.version, ruleVersion: x.ruleVersion, controlId: x.id, label: x.label, outcome: x.outcome ?? "not_executed", complete: x.complete, numerator: x.coverage.numerator, denominator: x.coverage.denominator, unit: x.coverage.unit, exclusions: x.coverage.exclusions.map(e => e.id + ":" + e.reason) }))),
    sources: buildCsv(["id", "importId", "type", "fileName", "sha256", "approvedBy", "approvedAt", "available", "required", "current", "binaryInPackage", "locators"], mission.sources.map(s => ({ ...s, locators: s.locators.map(l => l.rowId + ":" + cashLocatorLabel(l.locator)) }))),
  };
  const pdf = await buildPdfFromAccessibleHtml(html, { title: "PROBANT - Tresorerie - " + kind, createdAt });
  const base = "probant-tresorerie-" + kind + "-" + mission.hash.slice(0, 12);
  const manifest: EvidenceManifest = { manifestVersion: "1.0.0", applicationVersion: "0.1.0", dossierId: mission.scope.dossierId, snapshotId: mission.hash, createdAt,
    sourceDocuments: batches.map(b => ({ id: b.document.id, fileName: b.document.fileName, documentType: b.document.documentType, sha256: b.document.byteHash, parserVersion: b.document.parserVersion, location: { provider: "postgres-cash", key: b.id, versionId: b.document.id } })),
    parserVersions: Object.fromEntries(batches.map(b => [b.document.id, b.document.parserVersion])), ruleSetVersion: mission.program.version,
    referenceSetVersion: "cash-closed-contract-1.0.0", policyVersion: "server-dossier-permissions-1.0.0", snapshotSha256: mission.hash, reviewEventsDigest: stableSha256(mission.versionIndex),
    artifacts: [artifact("canonical_json", base + ".json", "application/json", canonical), artifact("findings_csv", base + "-exceptions.csv", "text/csv;charset=utf-8", csv.findings),
      artifact("review_events_csv", base + "-decisions.csv", "text/csv;charset=utf-8", csv.reviewEvents), artifact("controls_csv", base + "-procedures.csv", "text/csv;charset=utf-8", csv.controls),
      artifact("sources_csv", base + "-sources.csv", "text/csv;charset=utf-8", csv.sources), artifact("accessible_html", base + ".html", "text/html;charset=utf-8", html),
      artifact("pdf", base + ".pdf", "application/pdf", pdf, { derivedFrom: base + ".html", validation: { pdfA: { status: "not_validated", profile: null, validator: null, validatedAt: null } } })],
    limitations: [...mission.limitations.map((message, i) => ({ code: "cash_limit_" + i, message, subjects: [] as string[] })),
      { code: "package_kind_" + kind, message: kind === "approved" ? "Procédure Trésorerie approuvée et verrouillée ; aucune opinion sur les comptes." : "Diagnostic, y compris des versions historiques ou périmées ; aucune approbation du paquet.", subjects: [mission.hash] },
      { code: "pdf_standard_unicode", message: "PDF standard sans PDF/A ; caractères hors Latin-1 remplacés. HTML et JSON préservent Unicode.", subjects: [base + ".pdf"] }] };
  return { manifest, manifestJson: canonicalJson(manifest), canonicalJson: canonical, csv, html, pdf };
}
