import { canonicalJson, stableSha256 } from "@/lib/synthesis/canonical";
import { amountLabel, locatorLabel, type ClientMissionSnapshot } from "@/lib/workpapers/client-mission";
import { assertScope, contentHash, validateRun, type WorkpaperRun } from "@/lib/workpapers/model";
import type { ImportBatch } from "@/lib/workpapers/imports";
import { artifact } from "./package";
import { buildCsv } from "./csv";
import { buildPdfFromAccessibleHtml } from "./pdf";
import type { EvidenceExportPackage, EvidenceManifest } from "./types";
export type ClientExportKind = "diagnostic" | "approved";
export function assertClientPackage(mission: ClientMissionSnapshot, run: WorkpaperRun | null, kind: ClientExportKind) {
  const { hash, ...body } = mission;
  if (stableSha256(body) !== hash) throw new Error("EXPORT_SNAPSHOT_HASH_INVALID");
  if (run) {
    validateRun(run); assertScope(mission.scope, run.scope);
    if (run.id !== mission.procedure.runId || run.version !== mission.procedure.version || contentHash(run) !== mission.procedure.contentHash) throw new Error("EXPORT_VERSION_INVALID");
  } else if (mission.procedure.runId) throw new Error("EXPORT_RUN_REQUIRED");
  if (kind === "approved" && (!run || run.state !== "locked" || mission.procedure.stale || !run.approval || run.approval.snapshotHash !== contentHash(run))) throw new Error("EXPORT_APPROVED_CURRENT_LOCKED_REQUIRED");
}
const escapeHtml = (value: unknown) => String(value ?? "—").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
function table(title: string, headings: string[], rows: unknown[][]) {
  return `<table><caption>${escapeHtml(title)}</caption><thead><tr>${headings.map(h => `<th scope="col">${escapeHtml(h)}</th>`).join("")}</tr></thead><tbody>${rows.length ? rows.map(row => `<tr>${row.map(cell => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`).join("") : `<tr><td colspan="${headings.length}">Aucun élément.</td></tr>`}</tbody></table>`;
}
export function clientMissionHtml(m: ClientMissionSnapshot, run: WorkpaperRun | null, kind: ClientExportKind, createdAt: string) {
  const p = m.procedure;
  const status = kind === "approved" ? "Paquet du cadrage approuvé et verrouillé" : "Export diagnostic — ne constitue pas un paquet approuvé";
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>PROBANT — Synthèse Clients</title><style>
body{font:15px/1.55 system-ui,sans-serif;color:#18283c;background:white;margin:2rem auto;max-width:1120px;padding:0 1rem}h1{font-size:26px}h2{font-size:20px;margin-top:2rem}p,td,th{overflow-wrap:anywhere;white-space:pre-wrap}table{width:100%;border-collapse:collapse;margin:1rem 0;table-layout:fixed}caption{text-align:left;font-weight:700;margin:.5rem 0}th,td{text-align:left;vertical-align:top;border:1px solid #b5bfcb;padding:7px;font-size:12px}th{background:#edf1f6}thead{display:table-header-group}tr{break-inside:avoid}header{border-bottom:2px solid #344b67}a{color:#17497b}.notice{border-left:4px solid #ab7015;padding:1rem;background:#fff7e4}@page{size:A4 landscape;margin:16mm}@media print{body{max-width:none;margin:0;padding:0;font-size:11px}h2{break-after:avoid}th{background:#eee}table{font-size:10px}.notice{background:none}}
</style></head><body><header><p>Procédures de mission · infrastructure de recette jetable</p><h1>Synthèse du cadrage Clients</h1><p>${escapeHtml(status)}</p><p>Dossier ${escapeHtml(m.scope.dossierId)} · Organisation ${escapeHtml(m.scope.organizationId)} · Période ${escapeHtml(m.scope.periodId)}</p><p>Feuille ${escapeHtml(p.runId)} · révision ${escapeHtml(p.revision)} · version ${escapeHtml(p.version)} · préparation ${escapeHtml(p.preparedBy)}</p><p>État serveur ${escapeHtml(m.hash)} · export du ${escapeHtml(createdAt)}</p></header>
<section><h2>Résumé humain</h2><p>${escapeHtml(p.resultLabel)}. ${escapeHtml(p.reviewLabel)}.</p><p>${escapeHtml(p.conclusion)}</p><p class="notice">${escapeHtml(p.stale ? "Travail périmé : " + p.staleReasons.join(" ") : "Sources courantes à la génération de cet état.")} Une revue documentée ne vaut pas conformité des comptes ; aucune opinion automatique.</p><p>Programme ${escapeHtml(m.program.id)} @ ${escapeHtml(m.program.version)} : ${m.counters.executed}/${m.counters.planned} procédure exécutée ; ${m.counters.testedParts}/${m.counters.plannedParts} rapprochements complets ; ${m.counters.exceptions} résidus non nuls. Ces résidus ne constituent pas le dénominateur du programme.</p></section>
<section><h2>File de travail priorisée</h2>${table("Actions liées à cette version", ["Priorité", "Catégorie", "Action", "Détail / identité"], m.queue.map(q => [q.priority, q.category, q.label, q.detail + " · " + q.id + " · " + q.href]))}</section>
<section><h2>Procédures, population et sélection</h2>${table("Programme fermé", ["Procédure", "Tests prévus", "Exclusions du programme"], m.program.procedures.map(d => [d.label + " @ " + d.version, d.tests.map(t => t.label).join(" ; "), m.program.exclusions.length ? m.program.exclusions.map(e => e.id + ": " + e.reason).join(" ; ") : "Aucune"]))}<p>Couverture ${p.coverage.numerator}/${p.coverage.denominator ?? "inconnu"} ${escapeHtml(p.coverage.unit)}. Critères : ${escapeHtml(p.coverage.criteria)}.</p>${table("Exclusions explicites de la sélection", ["Unité", "Raison"], p.coverage.exclusions.map(e => [e.id, e.reason]))}${table("Population figée", ["Unité", "Montant", "Sources / lignes", "Sélection"], run?.population?.items.map(item => [item.id, amountLabel(item.amount), item.rowIds.join(" ; "), run.selection?.selectedIds.includes(item.id) ? "Sélectionnée" : "Exclue ou non sélectionnée"]) ?? [])}</section>
<section><h2>Calculs et exceptions</h2><p>${escapeHtml(m.amountGrouping.reason)}</p>${p.comparisons.map(c => `<h3>${escapeHtml(c.label)}</h3><p>Couverture ${c.coverage.numerator}/${c.coverage.denominator ?? "inconnu"} ${escapeHtml(c.coverage.unit)}. Exclusions : ${escapeHtml(c.coverage.exclusions.length ? c.coverage.exclusions.map(e => e.id + ": " + e.reason).join(" ; ") : "Aucune")}.</p><p>Convention ${c.conventionValidated ? "validée par le contrat de calcul" : "non validée"} : ${escapeHtml(c.convention)}. Règle ${escapeHtml(c.ruleVersion)} · entrées ${escapeHtml(c.inputHash)}.</p><p>Net du rapprochement ${escapeHtml(amountLabel(c.net ?? undefined))} ; brut ${escapeHtml(amountLabel(c.gross ?? undefined))}. Ces valeurs restent propres à ce rapprochement.</p>${table(c.label + " — détail des clés", ["Clé / identité", "Gauche", "Droite", "Différence / statut", "Preuves versionnées"], c.rows.map(row => [row.key + " · " + row.id, amountLabel(row.left), amountLabel(row.right), amountLabel(row.difference) + " · " + (row.exception ? "Exception maintenue" : row.difference.kind !== "known" ? "Incertitude" : "Aucun écart sur cette clé"), row.proofs.map(e => e.documentVersionId + "/" + e.rowId + " · " + locatorLabel(e.locator)).join(" ; ")]))}`).join("")}</section>
<section><h2>Décisions et comparaison avant / après revue</h2><p>Résultat ${escapeHtml(p.resultId)} · entrées ${escapeHtml(p.resultInputHash)} · contenu ${escapeHtml(p.contentHash)}.</p>${table("Décision sur la version", ["Auteur réel", "Version approuvée / date", "Décision motivée", "Résultat après revue"], p.review ? [[p.review.actorId, p.review.approvedVersion + " · " + p.review.at, p.review.note, p.resultLabel]] : [])}${table("Avant / après revue", ["Moment", "Version / résultat", "Conclusion", "Traitements documentés"], [p.beforeReview && ["Soumission", p.beforeReview.version + " / " + p.beforeReview.resultId, p.beforeReview.conclusion, p.beforeReview.notes.map(n => n.text + " : " + (n.resolution?.text ?? "Ouvert")).join(" ; ")], p.afterReview && ["Après revue", p.afterReview.version + " / " + p.afterReview.resultId, p.afterReview.conclusion, p.afterReview.notes.map(n => n.text + " : " + (n.resolution?.text ?? "Ouvert")).join(" ; ")]].filter((r): r is string[] => !!r))}${table("Commentaires / exceptions et leur traitement", ["Identité", "Auteur / date", "Texte", "Traitement"], p.notes.map(n => [n.id, n.authorId + " · date de création non disponible", n.text, n.resolution ? n.resolution.text + " · " + n.resolution.authorId + " · " + n.resolution.at : n.blocking ? "Bloquant ouvert" : "Ouvert"]))}${table("Versions et anciennes décisions", ["Identité / version", "État / empreinte", "Auteur", "Décision conservée"], m.versionIndex.map(v => [v.id + " · r" + v.revision + " v" + v.version, v.state + " · " + v.contentHash, v.actorId, v.approval ? v.approval.actorId + " : " + v.approval.note : v.reviewNotes.map(n => n.authorId + " : " + n.text).join(" ; ") || v.events.at(-1)?.action || "Aucune approbation"]))}</section>
<section><h2>Sources et index des pièces</h2><p class="notice">Les originaux binaires ne sont pas inclus dans ce paquet. Leur téléchargement séparé exige la permission d’export du même dossier. Une pièce absente ne devient pas une preuve fournie.</p>${table("Index des pièces versionnées", ["Pièce / identité", "Version / SHA-256", "Provenance / approbation", "Présence et actualité"], m.sources.map(s => [s.label + " · " + (s.fileName ?? "Attendue") + " · " + s.id, s.importId + " · " + (s.sha256 ?? "Absent"), "Parseur " + s.parserVersion + " ; mapping " + s.mappingVersion + "/" + s.mappingHash + " ; " + s.approvedBy + " · " + s.approvedAt, !s.available ? "Pièce attendue et absente" : (s.current ? "Source courante" : "Source remplacée / périmée") + " · binaire absent du paquet"]))}${table("Localisateurs des lignes sources", ["Document versionné", "Ligne", "Localisateur"], m.sources.flatMap(s => s.locators.map(l => [s.id, l.rowId, locatorLabel(l.locator)])))}${table("Preuves rattachées à la procédure", ["Preuve", "Document / ligne", "Localisateur / usage"], p.evidence.map(e => [e.id, e.documentVersionId + " / " + e.rowId, locatorLabel(e.locator) + " · " + e.purpose]))}</section>
<section><h2>Incertitudes et limites</h2><ul>${[...m.limitations, ...p.coverage.limitations, ...(run?.result?.warnings ?? []), ...(run?.result?.blockedControls ?? []), "PDF standard dérivé du HTML, sans certification PDF/A ; caractères hors alphabet Latin-1 remplacés dans ce PDF. HTML et JSON conservent le texte Unicode."].map(l => `<li>${escapeHtml(l)}</li>`).join("")}</ul><p>Famille de ce rapport : procédures de mission. Les constats historiques DEMO SA et l’atelier synthétique ne sont pas inclus.</p></section></body></html>`;
}
export async function buildClientMissionPackage(mission: ClientMissionSnapshot, run: WorkpaperRun | null, imports: ImportBatch[], kind: ClientExportKind, createdAt: string): Promise<EvidenceExportPackage> {
  assertClientPackage(mission, run, kind);
  const sourceIds = new Set(mission.sources.filter(s => s.available).map(s => s.importId));
  const batches = imports.filter(b => sourceIds.has(b.id)); batches.forEach(b => assertScope(mission.scope, b.scope));
  if (batches.length !== sourceIds.size) throw new Error("EXPORT_SOURCE_REQUIRED");
  const report = { exportSchemaVersion: "clients-mission-1.0.0", kind, createdAt, mission, run, imports: batches, binaryFilesIncluded: false };
  const canonical = canonicalJson(report), html = clientMissionHtml(mission, run, kind, createdAt);
  const csv = {
    findings: buildCsv(["comparison", "id", "key", "difference", "exception", "proofs"], mission.procedure.comparisons.flatMap(c => c.rows.map(r => ({ comparison: c.id, id: r.id, key: r.key, difference: amountLabel(r.difference), exception: r.exception, proofs: r.proofs.map(p => p.id) })))),
    reviewEvents: buildCsv(["runId", "version", "actorId", "at", "action"], mission.versionIndex.flatMap(v => v.events.slice(-1).map(e => ({ ...e, runId: v.id, version: v.version })))),
    controls: buildCsv(["id", "version", "label", "plannedTests", "testedParts", "coverage", "exclusions"], mission.program.procedures.map(p => ({ id: p.id, version: p.version, label: p.label, plannedTests: p.tests.length, testedParts: mission.counters.testedParts, coverage: mission.procedure.coverage.numerator + "/" + mission.procedure.coverage.denominator, exclusions: mission.procedure.coverage.exclusions.map(e => e.id + ":" + e.reason) }))),
    sources: buildCsv(["id", "importId", "fileName", "sha256", "current", "binaryInPackage"], mission.sources.map(s => ({ ...s }))),
  };
  const pdf = await buildPdfFromAccessibleHtml(html, { title: "PROBANT - Cadrage Clients - " + kind, createdAt });
  const base = "probant-clients-" + kind + "-" + mission.hash.slice(0, 12);
  const manifest: EvidenceManifest = { manifestVersion: "1.0.0", applicationVersion: "0.1.0", dossierId: mission.scope.dossierId, snapshotId: mission.hash,
    createdAt, sourceDocuments: batches.map(b => ({ id: b.document.id, fileName: b.document.fileName, documentType: b.document.documentType, sha256: b.document.byteHash, parserVersion: b.document.parserVersion, location: { provider: "postgres-clients", key: b.id, versionId: b.document.id } })),
    parserVersions: Object.fromEntries(batches.map(b => [b.document.id, b.document.parserVersion])), ruleSetVersion: mission.program.version,
    referenceSetVersion: "clients-frame-contract-1.0.0", policyVersion: "server-dossier-permissions-1.0.0", snapshotSha256: mission.hash,
    reviewEventsDigest: stableSha256(mission.versionIndex),
    artifacts: [artifact("canonical_json", base + ".json", "application/json", canonical), artifact("findings_csv", base + "-exceptions.csv", "text/csv;charset=utf-8", csv.findings),
      artifact("review_events_csv", base + "-decisions.csv", "text/csv;charset=utf-8", csv.reviewEvents), artifact("controls_csv", base + "-procedures.csv", "text/csv;charset=utf-8", csv.controls),
      artifact("sources_csv", base + "-sources.csv", "text/csv;charset=utf-8", csv.sources), artifact("accessible_html", base + ".html", "text/html;charset=utf-8", html),
      artifact("pdf", base + ".pdf", "application/pdf", pdf, { derivedFrom: base + ".html", validation: { pdfA: { status: "not_validated", profile: null, validator: null, validatedAt: null } } })],
    limitations: [...mission.limitations.map((message, i) => ({ code: "clients_limit_" + i, message, subjects: [] as string[] })),
      { code: "package_kind_" + kind, message: kind === "approved" ? "Cadrage approuvé et verrouillé ; aucune opinion sur les comptes." : "Diagnostic, y compris des versions historiques ou périmées ; aucune approbation du paquet.", subjects: [mission.hash] },
      { code: "pdf_standard_unicode", message: "PDF standard sans PDF/A ; caractères hors Latin-1 remplacés. HTML et JSON préservent Unicode.", subjects: [base + ".pdf"] }],
  };
  return { manifest, manifestJson: canonicalJson(manifest), canonicalJson: canonical, csv, html, pdf };
}
