import { canonicalCompare, canonicalJson, stableSha256 } from "@/lib/synthesis/canonical";
import { equityAmountLabel, equityLocatorLabel, type EquityMissionSnapshot } from "@/lib/workpapers/equity-mission";
import { EQ_DECISION_TEXT, EQ_ENTRY_TEXT } from "@/lib/workpapers/equity-review";
import { EQ_COMPONENT_LABELS, EQ_DECISION_TYPE_LABELS, EQ_NATURE_LABELS, type EqNature } from "@/lib/workpapers/equity-sources";
import { assertScope, contentHash, validateRun, type WorkpaperRun } from "@/lib/workpapers/model";
import type { ImportBatch } from "@/lib/workpapers/imports";
import { artifact } from "./package";
import { buildCsv } from "./csv";
import { buildPdfFromAccessibleHtml } from "./pdf";
import type { EvidenceExportPackage, EvidenceManifest } from "./types";

export type EquityExportKind = "diagnostic" | "approved";
export function assertEquityPackage(mission: EquityMissionSnapshot, run: WorkpaperRun | null, kind: EquityExportKind) {
  const { hash, ...body } = mission;
  if (stableSha256(body) !== hash) throw new Error("EXPORT_SNAPSHOT_HASH_INVALID");
  if (run) {
    validateRun(run); assertScope(mission.scope, run.scope);
    if (run.id !== mission.procedure.runId || run.version !== mission.procedure.version || contentHash(run) !== mission.procedure.contentHash) throw new Error("EXPORT_VERSION_INVALID");
  } else if (mission.procedure.runId) throw new Error("EXPORT_RUN_REQUIRED");
  if (kind === "approved" && (!run || run.state !== "locked" || mission.procedure.stale || !mission.procedure.equity || !run.approval || run.approval.snapshotHash !== contentHash(run))) throw new Error("EXPORT_APPROVED_CURRENT_LOCKED_REQUIRED");
}
const escapeHtml = (value: unknown) => String(value ?? "—").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
function table(title: string, headings: string[], rows: unknown[][]) {
  return `<table><caption>${escapeHtml(title)}</caption><thead><tr>${headings.map(h => `<th scope="col">${escapeHtml(h)}</th>`).join("")}</tr></thead><tbody>${rows.length ? rows.map(row => `<tr>${row.map(cell => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`).join("") : `<tr><td colspan="${headings.length}">Aucun élément.</td></tr>`}</tbody></table>`;
}
const citation = (c?: { fileName: string; documentVersionId: string; page?: number; pieceRef?: string }) => c ? "Pièce citée : " + (c.pieceRef ? c.pieceRef + " · " : "") + c.fileName + " · version " + c.documentVersionId + (c.page ? " · page " + c.page : "") : "Aucune pièce citée";
const ratioLabel = (r: { kind: string; numerator?: string; denominator?: string; reason?: string; value?: { amount: string } }) => r.kind === "ratio" ? r.numerator + " / " + r.denominator + " (centimes)" : r.reason ?? "—";
const columnLabel = (c: string) => c === "ouverture" ? "Ouverture" : c === "cloture" ? "Clôture" : EQ_NATURE_LABELS[c as EqNature] ?? c;
function details(m: EquityMissionSnapshot) {
  const e = m.procedure.equity;
  if (!e) return "<section><h2>Capitaux propres</h2><p>Aucun résultat Capitaux propres exploitable pour cette version.</p></section>";
  const natures = e.natures;
  return "<section><h2>Capitaux propres — tableau de variation, décisions et mouvements</h2><p>Exercice " + escapeHtml(e.startDate) + " → " + escapeHtml(e.closingDate) + " ; revue " + escapeHtml(e.reviewDate) + ". Convention " + escapeHtml(e.convention.version) + " validée par " + escapeHtml(e.convention.validatedBy) + " : " + escapeHtml(e.convention.meaning) + "</p>"
    + "<p class='notice'>" + escapeHtml(e.legalMeaning) + "</p><p>" + escapeHtml(e.method.meaning) + "</p>"
    + table("Cartographie des composantes (modèle de bilan, art. 821-1 PCG)", ["Composante", "Statut", "Comptes", "Motif"], e.cartography.map(c => [c.label, c.status === "provided" ? "Fournie" : c.status === "excluded" ? "Exclue" : "Non fournie", c.accounts.join(", ") || "—", c.reason ?? "—"]))
    + table("Tableau de variation reconstitué (balance et écritures)", ["Composante", "Ouverture", ...natures.map(n => EQ_NATURE_LABELS[n]), "Clôture attendue", "Clôture observée", "Écart"], [
      ...e.components.map(c => [c.label + (c.inScope ? "" : " (exclue)"), equityAmountLabel(c.opening), ...natures.map(n => c.movements[n] ? equityAmountLabel(c.movements[n]) : "—"), equityAmountLabel(c.expected), equityAmountLabel(c.closing), c.status === "excluded" ? "Exclue : " + c.exclusionReason : c.status === "incomplete" ? "Incomplète : " + c.missing.join(" ") : equityAmountLabel(c.difference)]),
      ["Total des capitaux propres (composantes testées)", equityAmountLabel(e.totals.opening), ...natures.map(n => e.totals.movements[n] ? equityAmountLabel(e.totals.movements[n]) : "—"), equityAmountLabel(e.totals.expected), equityAmountLabel(e.totals.closing), equityAmountLabel(e.totals.difference) + " · " + e.totals.computedComponents + "/" + e.totals.inScopeComponents + " composantes calculées"]])
    + table("Transferts internes (effet nul sur le total)", ["Transfert", "Lignes", "Composantes", "Total"], e.transfers.map(t => [t.transferRef, t.lines.map(l => l.entryId + " " + EQ_COMPONENT_LABELS[l.component] + " " + l.amount.amount).join(" ; "), t.components.map(c => EQ_COMPONENT_LABELS[c]).join(", "), t.total.amount + " EUR"]))
    + (e.statement.provided ? table("Tableau fourni ↔ reconstitué (cellules)", ["Composante / colonne", "Fourni", "Reconstitué", "Écart (fourni − reconstitué)"], e.statement.cells.map(c => [EQ_COMPONENT_LABELS[c.component] + " / " + columnLabel(c.column), equityAmountLabel(c.provided), equityAmountLabel(c.rebuilt), equityAmountLabel(c.difference)])) : "<p>Tableau de variation fourni absent : aucune cellule comparée.</p>")
    + table("Décisions : décision / comptabilisation / paiement", ["Décision / ligne", "Type / composante", "Dates (décision → effet)", "PV / page / lecture", "Voté", "Comptabilisé", "Payé", "Écart (comptabilisé − voté)", "Statut"], (e.decisions ?? []).map(d => [d.decisionId + " / " + d.lineId + (d.label ? " · " + d.label : ""), EQ_DECISION_TYPE_LABELS[d.type] + " / " + EQ_COMPONENT_LABELS[d.component], d.decisionDate + " → " + d.effectDate, (d.pv.pieceRef || "aucune référence") + " · " + (d.pv.status === "available" ? "page " + d.pv.page + "/" + d.pv.pageCount + " · version " + d.pv.documentVersionId : d.pv.status === "missing" ? "PV absent" : "page introuvable") + " · lecture " + (d.reading.status === "validated" ? "validée par " + d.reading.authorId + " (" + d.reading.authoredAt + ")" : d.reading.status === "pending" ? "à valider" : "impossible"), equityAmountLabel(d.voted), equityAmountLabel(d.booked), equityAmountLabel(d.payment), equityAmountLabel(d.difference), EQ_DECISION_TEXT[d.status].label + " — " + d.statusMeaning]))
    + table("Écritures de l’exercice", ["Écriture", "Compte / composante", "Nature", "Date / effet", "Montant", "Décision / transfert", "Statut"], e.entries.map(x => [x.entryId + (x.label ? " · " + x.label : ""), x.account + " / " + EQ_COMPONENT_LABELS[x.component], EQ_NATURE_LABELS[x.nature], x.date + " / " + x.effectDate + (x.effectStatus === "outside_period" ? " (hors période)" : ""), equityAmountLabel(x.amount), (x.decisionRef ?? "—") + " / " + (x.transferRef ?? "—"), EQ_ENTRY_TEXT[x.decisionStatus].label]))
    + table("Règlements", ["Règlement", "Décision citée", "Date", "Montant", "Rattaché"], (e.payments ?? []).map(p => [p.paymentId + (p.label ? " · " + p.label : ""), p.decisionRef, p.date, equityAmountLabel(p.amount), p.linked ? "Oui" : "Décision absente du registre"]))
    + table("Rapports arithmétiques — aucune conclusion juridique", ["Rapport", "Valeur exacte", "Sens"], [["Capitaux propres / capital", ratioLabel(e.ratios.equityToCapital), e.ratios.meaning], ["Réserves / capital", ratioLabel(e.ratios.reservesToCapital), e.ratios.meaning], ["Conclusion juridique", e.legalConclusion.reason, e.legalMeaning]])
    + table("Exceptions et incertitudes conservées après revue", ["Identité / contrôle / cible", "Constat", "Montant", "Preuves"], e.exceptions.map(x => [x.id + " / " + x.controlId + " / " + x.targetId, x.label + " ; " + x.message, equityAmountLabel(x.amount), x.proofIds.join(" ; ") || "Pièce attendue"])) + "</section>";
}
export function equityMissionHtml(m: EquityMissionSnapshot, run: WorkpaperRun | null, kind: EquityExportKind, createdAt: string) {
  const p = m.procedure;
  const status = kind === "approved" ? "Paquet Capitaux propres approuvé et verrouillé — portée : cette procédure uniquement, aucune conclusion juridique" : "Export diagnostic — ne constitue pas un paquet approuvé";
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>PROBANT — Capitaux propres</title><style>
body{font:15px/1.55 system-ui,sans-serif;color:#18283c;background:white;margin:2rem auto;max-width:1120px;padding:0 1rem}h1{font-size:26px}h2{font-size:20px;margin-top:2rem}p,td,th{overflow-wrap:anywhere;white-space:pre-wrap}table{width:100%;border-collapse:collapse;margin:1rem 0;table-layout:fixed}caption{text-align:left;font-weight:700;margin:.5rem 0}th,td{text-align:left;vertical-align:top;border:1px solid #b5bfcb;padding:7px;font-size:12px}th{background:#edf1f6}thead{display:table-header-group}tr{break-inside:avoid}header{border-bottom:2px solid #344b67}.notice{border-left:4px solid #ab7015;padding:1rem;background:#fff7e4}@page{size:A4 landscape;margin:16mm}@media print{body{max-width:none;margin:0;padding:0;font-size:11px}h2{break-after:avoid}th{background:#eee}table{font-size:9px}.notice{background:none}}
</style></head><body><header><p>Procédures de mission · infrastructure de recette jetable</p><h1>Capitaux propres — ${escapeHtml(p.label)}</h1><p>${escapeHtml(status)}</p><p>Dossier ${escapeHtml(m.scope.dossierId)} · Organisation ${escapeHtml(m.scope.organizationId)} · Période ${escapeHtml(m.scope.periodId)}</p><p>Feuille ${escapeHtml(p.runId)} · révision ${escapeHtml(p.revision)} · version ${escapeHtml(p.version)} · préparation ${escapeHtml(p.preparedBy)}</p><p>État serveur ${escapeHtml(m.hash)} · état établi au ${escapeHtml(createdAt)}</p></header>
<section><h2>Résumé humain</h2><p>${escapeHtml(p.resultLabel)}. ${escapeHtml(p.reviewLabel)}. ${escapeHtml(p.legal.conclusion)}.</p><p>${escapeHtml(p.conclusion)}</p><p class="notice">${escapeHtml(p.stale ? "Travail périmé : " + p.staleReasons.join(" ") : "Sources courantes à la génération de cet état.")} Une revue documentée ne vaut ni conformité des comptes ni régularité juridique ; aucune opinion automatique.</p><p>Programme ${escapeHtml(m.program.id)} @ ${escapeHtml(m.program.version)} : ${m.counters.executed}/${m.counters.planned} procédure exécutée ; ${m.counters.testedParts}/${m.counters.plannedParts} contrôles complets ; ${m.counters.exceptions} exceptions ; ${m.counters.uncertainties} incertitudes. Les exceptions ne constituent pas le dénominateur du programme.</p><p>Hors périmètre de ce programme : ${escapeHtml(m.program.outOfScope.join(" ; "))}.</p></section>
<section><h2>File de travail priorisée</h2>${table("Actions liées à cette version", ["Priorité", "Catégorie", "Action", "Détail / identité"], m.queue.map(q => [q.priority, q.category, q.label, q.detail + " · " + q.id + " · " + q.href]))}</section>
<section><h2>Procédure, population et sélection</h2>${table("Programme fermé", ["Procédure", "Contrôles prévus", "Conventions"], m.program.procedures.map(d => [d.label + " @ " + d.version, d.tests.map(t => t.label).join(" ; "), p.controls.map(c => c.label + " : " + c.convention).join(" ")]))}<p>Couverture ${p.coverage.numerator}/${p.coverage.denominator ?? "inconnu"} ${escapeHtml(p.coverage.unit)}. Critères : ${escapeHtml(p.coverage.criteria)}.</p>${table("Exclusions motivées de la population", ["Unité", "Raison"], p.coverage.exclusions.map(e => [e.id, e.reason]))}${table("Contrôles et dénominateurs", ["Contrôle", "Résultat", "Numérateur / dénominateur", "Exclusions"], p.controls.map(c => [c.label, c.outcome ?? "Non exécuté", c.coverage.numerator + "/" + (c.coverage.denominator ?? "inconnu") + " " + c.coverage.unit, c.coverage.exclusions.map(e => e.id + " : " + e.reason).join(" ; ") || "Aucune"]))}${table("Population figée", ["Unité", "Montant signé", "Lignes sources", "Sélection"], run?.population?.items.map(item => [item.id, equityAmountLabel(item.amount), item.rowIds.length + " ligne(s)", run.selection?.selectedIds.includes(item.id) ? "Sélectionnée" : "Exclue avec motif"]) ?? [])}</section>
${details(m)}<section><h2>Décisions humaines et comparaison avant / après revue</h2><p>Résultat ${escapeHtml(p.resultId)} · entrées ${escapeHtml(p.resultInputHash)} · contenu ${escapeHtml(p.contentHash)}.</p>${table("Décision sur la version", ["Auteur réel", "Version approuvée / date", "Décision motivée", "Résultat après revue"], p.review ? [[p.review.actorId, p.review.approvedVersion + " · " + p.review.at, p.review.note, p.resultLabel]] : [])}${table("Avant / après revue", ["Moment", "Version / résultat", "Conclusion", "Traitements documentés"], [p.beforeReview && ["Soumission", p.beforeReview.version + " / " + p.beforeReview.resultId, p.beforeReview.conclusion, p.beforeReview.notes.map(n => n.text + " : " + (n.resolution?.text ?? "Ouvert")).join(" ; ")], p.afterReview && ["Après revue", p.afterReview.version + " / " + p.afterReview.resultId, p.afterReview.conclusion, p.afterReview.notes.map(n => n.text + " : " + (n.resolution?.text ?? "Ouvert")).join(" ; ")]].filter((r): r is string[] => !!r))}${table("Commentaires / exceptions, traitement et pièce citée", ["Identité", "Auteur", "Texte", "Traitement et citation"], p.notes.map(n => [n.id, n.authorId, n.text + (n.citation ? " — " + citation(n.citation) : ""), n.resolution ? n.resolution.text + " · " + n.resolution.authorId + " · " + n.resolution.at + " · " + citation(n.resolution.citation) : n.blocking ? "Bloquant ouvert" : "Ouvert"]))}${table("Versions, lectures de PV et anciennes décisions", ["Identité / version", "État / empreinte", "Lectures validées (pièce · version · page)", "Auteur", "Décision conservée"], m.versionIndex.map(v => [v.id + " · r" + v.revision + " v" + v.version, v.state + " · " + v.contentHash, v.readings.map(r => r.lineId + " : " + r.pieceRef + " · " + r.documentVersionId + " · p." + r.page + " (" + r.authorId + ")").join(" ; ") || "Aucune", v.actorId, v.approval ? v.approval.actorId + " : " + v.approval.note : v.reviewNotes.map(n => n.authorId + " : " + n.text).join(" ; ") || v.events.at(-1)?.action || "Aucune approbation"]))}</section>
<section><h2>Sources et index des pièces</h2><p class="notice">Les originaux binaires (PV compris) ne sont pas inclus dans ce paquet. Leur téléchargement séparé exige la permission d’export du même dossier. Une pièce absente ne devient pas une preuve fournie.</p>${table("Index des pièces versionnées", ["Pièce / identité", "Version / SHA-256", "Provenance / approbation", "Présence et actualité"], m.sources.map(s => [s.label + " · " + (s.fileName ?? "Attendue") + " · " + s.id, s.importId + " · " + (s.sha256 ?? "Absent"), "Parseur " + s.parserVersion + " ; mapping " + s.mappingVersion + "/" + s.mappingHash + " ; " + s.approvedBy + " · " + s.approvedAt, !s.available ? (s.required ? "Pièce requise absente" : "Pièce conditionnelle absente") : (s.current ? "Source courante" : "Source remplacée / périmée") + " · " + s.rowCount + (s.type === "eq_minutes" ? " page(s)" : " ligne(s)") + " · binaire absent du paquet"]))}${table("Localisateurs des lignes et pages sources", ["Document versionné", "Ligne ou page", "Localisateur"], m.sources.flatMap(s => s.locators.map(l => [s.id, l.rowId, equityLocatorLabel(l.locator)])))}</section>
<section><h2>Incertitudes et limites</h2><ul>${[...m.limitations, ...p.coverage.limitations, ...(run?.result?.warnings ?? []), ...(run?.result?.blockedControls ?? []), "PDF standard dérivé du HTML, sans certification PDF/A ; caractères hors alphabet Latin-1 remplacés dans ce PDF. HTML et JSON conservent le texte Unicode."].map(l => `<li>${escapeHtml(l)}</li>`).join("")}</ul><p>Famille de ce rapport : procédures de mission. Les constats historiques DEMO SA et l’atelier synthétique ne sont pas inclus.</p></section></body></html>`;
}
export async function buildEquityMissionPackage(mission: EquityMissionSnapshot, run: WorkpaperRun | null, imports: ImportBatch[], kind: EquityExportKind, createdAt: string): Promise<EvidenceExportPackage> {
  assertEquityPackage(mission, run, kind);
  const sourceIds = new Set(mission.sources.filter(s => s.available).map(s => s.importId));
  const batches = imports.filter(b => sourceIds.has(b.id)).sort((a, b) => canonicalCompare(a.id, b.id)); batches.forEach(b => assertScope(mission.scope, b.scope));
  if (batches.length !== sourceIds.size) throw new Error("EXPORT_SOURCE_REQUIRED");
  const report = { exportSchemaVersion: "equity-mission-1.0.0", kind, createdAt, mission, run, imports: batches, binaryFilesIncluded: false };
  const canonical = canonicalJson(report), html = equityMissionHtml(mission, run, kind, createdAt), p = mission.procedure, e = p.equity;
  const csv = {
    findings: buildCsv(["procedureId", "runId", "version", "resultId", "controlId", "code", "id", "component", "target", "amount", "message", "proofs"], (e?.exceptions ?? []).map(x => ({ procedureId: p.id, runId: p.runId, version: p.version, resultId: p.resultId, controlId: x.controlId, code: x.code, id: x.id, component: x.component, target: x.targetId, amount: equityAmountLabel(x.amount), message: x.message, proofs: x.proofIds }))),
    reviewEvents: buildCsv(["procedureId", "runId", "version", "actorId", "at", "action", "note"], mission.versionIndex.flatMap(v => v.events.slice(-1).map(ev => ({ ...ev, procedureId: p.id, runId: v.id, version: v.version, note: v.approval?.note ?? "" })))),
    controls: buildCsv(["procedureId", "runId", "version", "ruleVersion", "controlId", "label", "outcome", "complete", "numerator", "denominator", "unit", "exclusions"], p.controls.map(x => ({ procedureId: p.id, runId: p.runId, version: p.version, ruleVersion: x.ruleVersion, controlId: x.id, label: x.label, outcome: x.outcome ?? "not_executed", complete: x.complete, numerator: x.coverage.numerator, denominator: x.coverage.denominator, unit: x.coverage.unit, exclusions: x.coverage.exclusions.map(ex => ex.id + ":" + ex.reason) }))),
    sources: buildCsv(["id", "importId", "type", "fileName", "sha256", "approvedBy", "approvedAt", "available", "required", "current", "binaryInPackage", "locators"], mission.sources.map(s => ({ ...s, locators: s.locators.map(l => l.rowId + ":" + equityLocatorLabel(l.locator)) }))),
  };
  const pdf = await buildPdfFromAccessibleHtml(html, { title: "PROBANT - Capitaux propres - " + kind, createdAt });
  const base = "probant-capitaux-propres-" + kind + "-" + mission.hash.slice(0, 12);
  const manifest: EvidenceManifest = { manifestVersion: "1.0.0", applicationVersion: "0.1.0", dossierId: mission.scope.dossierId, snapshotId: mission.hash, createdAt,
    sourceDocuments: batches.map(b => ({ id: b.document.id, fileName: b.document.fileName, documentType: b.document.documentType, sha256: b.document.byteHash, parserVersion: b.document.parserVersion, location: { provider: "postgres-eq", key: b.id, versionId: b.document.id } })),
    parserVersions: Object.fromEntries(batches.map(b => [b.document.id, b.document.parserVersion])), ruleSetVersion: mission.program.version,
    referenceSetVersion: "equity-closed-contract-1.0.0", policyVersion: "server-dossier-permissions-1.0.0", snapshotSha256: mission.hash, reviewEventsDigest: stableSha256(mission.versionIndex),
    artifacts: [artifact("canonical_json", base + ".json", "application/json", canonical), artifact("findings_csv", base + "-exceptions.csv", "text/csv;charset=utf-8", csv.findings),
      artifact("review_events_csv", base + "-decisions.csv", "text/csv;charset=utf-8", csv.reviewEvents), artifact("controls_csv", base + "-procedures.csv", "text/csv;charset=utf-8", csv.controls),
      artifact("sources_csv", base + "-sources.csv", "text/csv;charset=utf-8", csv.sources), artifact("accessible_html", base + ".html", "text/html;charset=utf-8", html),
      artifact("pdf", base + ".pdf", "application/pdf", pdf, { derivedFrom: base + ".html", validation: { pdfA: { status: "not_validated", profile: null, validator: null, validatedAt: null } } })],
    limitations: [...mission.limitations.map((message, i) => ({ code: "equity_limit_" + i, message, subjects: [] as string[] })),
      { code: "package_kind_" + kind, message: kind === "approved" ? "Procédure Capitaux propres approuvée et verrouillée ; aucune opinion sur les comptes ni conclusion juridique." : "Diagnostic, y compris des versions historiques ou périmées ; aucune approbation du paquet.", subjects: [mission.hash] },
      { code: "pdf_standard_unicode", message: "PDF standard sans PDF/A ; caractères hors Latin-1 remplacés. HTML et JSON préservent Unicode.", subjects: [base + ".pdf"] }] };
  return { manifest, manifestJson: canonicalJson(manifest), canonicalJson: canonical, csv, html, pdf };
}
