import { canonicalCompare, canonicalJson, stableSha256 } from "@/lib/synthesis/canonical";
import { fiscalAmountLabel, fiscalLocatorLabel, fxCents, type FiscalMissionSnapshot } from "@/lib/workpapers/fiscal-mission";
import { CIT_CATEGORY_LABELS, CIT_TREATMENT_LABELS, VAT_EXPLANATION_LABELS, VAT_ROLE_LABELS } from "@/lib/workpapers/fiscal-labels";
import { assertScope, contentHash, validateRun, type WorkpaperRun } from "@/lib/workpapers/model";
import type { ImportBatch } from "@/lib/workpapers/imports";
import { artifact } from "./package";
import { buildCsv } from "./csv";
import { buildPdfFromAccessibleHtml } from "./pdf";
import type { EvidenceExportPackage, EvidenceManifest } from "./types";

export type FiscalExportKind = "diagnostic" | "approved";
export function assertFiscalPackage(mission: FiscalMissionSnapshot, run: WorkpaperRun | null, kind: FiscalExportKind) {
  const { hash, ...body } = mission;
  if (stableSha256(body) !== hash) throw new Error("EXPORT_SNAPSHOT_HASH_INVALID");
  if (run) {
    validateRun(run); assertScope(mission.scope, run.scope);
    if (run.id !== mission.procedure.runId || run.version !== mission.procedure.version || contentHash(run) !== mission.procedure.contentHash) throw new Error("EXPORT_VERSION_INVALID");
  } else if (mission.procedure.runId) throw new Error("EXPORT_RUN_REQUIRED");
  if (kind === "approved" && (!run || run.state !== "locked" || mission.procedure.stale || (!mission.procedure.vat && !mission.procedure.cit) || !run.approval || run.approval.snapshotHash !== contentHash(run))) throw new Error("EXPORT_APPROVED_CURRENT_LOCKED_REQUIRED");
}
const escapeHtml = (value: unknown) => String(value ?? "—").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
function table(title: string, headings: string[], rows: unknown[][]) {
  return `<table><caption>${escapeHtml(title)}</caption><thead><tr>${headings.map(h => `<th scope="col">${escapeHtml(h)}</th>`).join("")}</tr></thead><tbody>${rows.length ? rows.map(row => `<tr>${row.map(cell => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`).join("") : `<tr><td colspan="${headings.length}">Aucun élément.</td></tr>`}</tbody></table>`;
}
const citation = (c?: { fileName: string; documentVersionId: string; page?: number; row?: number; zone?: string }) => c ? "Pièce citée : " + c.fileName + " · version " + c.documentVersionId + (c.row ? " · ligne " + c.row : "") + (c.page ? " · page " + c.page : "") + (c.zone ? " · " + c.zone : "") : "Aucune pièce citée";
function citDetails(m: FiscalMissionSnapshot) {
  const r = m.procedure.cit!, f = r.framing, b = r.bridge, c = r.computation;
  return "<section><h2>IS — " + escapeHtml(m.procedure.periodLabel) + "</h2>"
    + "<p>Moteur " + escapeHtml(r.engine.name) + " " + escapeHtml(r.engine.version) + " · calcul " + escapeHtml(r.engine.calculationVersion) + " · instantané " + escapeHtml(r.engine.snapshotHash) + " · statut " + escapeHtml(r.engine.status) + " · impôt " + escapeHtml(r.engine.taxImpactStatus) + " · barème " + escapeHtml(r.engine.rateScheduleId ?? "non publié") + " · exercice " + r.fiscalYear + " · millésime " + r.formVintage + ".</p>"
    + "<p>Profil : régime " + escapeHtml(r.profile.regime) + ", intégration " + escapeHtml(r.profile.groupStatus) + ", " + (r.profile.status === "confirmed" ? "confirmé par " + escapeHtml(r.profile.confirmedBy) + " le " + escapeHtml(r.profile.confirmedAt) + " — " + escapeHtml(citation(r.profile.evidence ?? undefined)) : "non confirmé") + ".</p><p>" + escapeHtml(r.method) + "</p>"
    + table("Résultat comptable cadré (FEC ↔ liasse)", ["Grandeur", "Montant"], [["Résultat des classes 6 et 7 du FEC (après impôt)", fxCents(f.resultAfterTaxCents)], ["Impôt sur les bénéfices comptabilisé (695)", fxCents(f.taxChargeCents)], ["Résultat avant impôt", fxCents(f.resultBeforeTaxCents)],
      ["Dette d’impôt (444)", fxCents(f.taxLiabilityCents)], ["Résultat comptable déclaré" + (f.declaredBox ? " (case " + f.declaredBox + ")" : ""), fxCents(f.declaredResultCents)], ["Écart (FEC − déclaré)", fxCents(f.differenceCents) + (f.reason ? " · " + f.reason : "")]])
    + table("Pont fiscal documenté (base " + (b.basis === "after_tax" ? "après" : "avant") + " impôt)", ["Étape", "Montant"], [["Résultat de départ", fxCents(b.startCents)], ["Réintégrations documentées", fxCents(b.reintegrationsCents)], ["Déductions documentées", fxCents(b.deductionsCents)],
      ["Résultat documenté", fxCents(b.documentedResultCents)], ["Résultat fiscal avant déficits déclaré" + (b.declaredBox ? " (case " + b.declaredBox + ")" : ""), fxCents(b.declaredCents)], ["Résidu non expliqué", fxCents(b.residualCents) + (b.reason ? " · " + b.reason : "")]])
    + table("Retraitements documentés", ["Retraitement", "Nature / sens", "Montant", "Traitement", "Pièce et source"], r.adjustments.map(a => [a.id + " — " + a.label + " (" + a.authorId + ", " + a.at + ")", CIT_CATEGORY_LABELS[a.category] + " / " + (a.direction === "reintegration" ? "réintégration" : "déduction"), fxCents(a.amountCents),
      CIT_TREATMENT_LABELS[a.treatment] + (a.inEngine ? " · intégré au calcul" : ""), citation(a.citation) + " · " + (a.legalSource ? a.legalSource.title + " (" + a.legalSource.locator + ", " + a.legalSource.url + ", vérifié le " + a.legalSource.lastVerifiedAt + ")" : "source du registre non citée")]))
    + (c ? table("Calcul du moteur IS", ["Étape", "Variation", "Cumul", "Statut"], c.steps.map(s => [s.label, fxCents(s.deltaCents), fxCents(s.runningTotalCents), s.status]))
      + table("Tranches du barème publié", ["Tranche", "Taux", "Base allouée", "Impôt", "Éligibilité / conditions", "Source"], c.brackets.map(t => [t.label + (t.applied ? "" : " (non appliquée)"), (t.rateBasisPoints / 100) + " %", fxCents(t.allocatedBaseCents), fxCents(t.taxCents),
        t.eligibility + (t.conditions.length ? " — " + t.conditions.map(x => x.label + " : " + x.status + (x.observedValue ? " (" + x.observedValue + ")" : "")).join(" ; ") : ""), t.sourceRefs.map(s => s.sourceVersionId + " " + s.locator).join(" ; ")]))
      + "<p>IS brut calculé : " + fxCents(c.grossTaxCents) + " · base imposable " + fxCents(c.taxableBaseCents) + " · déficits imputés " + fxCents(c.deficitOffsetCents) + " (" + escapeHtml(c.deficitStatus) + ").</p>"
      : "<p class='notice'>Calcul non exécuté : moteur bloqué. Aucun impôt n’est présenté.</p>")
    + table("Rapprochements du moteur", ["Ligne", "Calcul", "Déclaré / comptabilisé", "Écart", "Statut"], r.comparisons.map(x => [x.label, fxCents(x.leftCents), fxCents(x.rightCents) + (x.rightBox ? " (" + x.rightBox + ")" : ""), fxCents(x.differenceCents), x.status]))
    + table("Lignes de la liasse et de la 2065", ["Formulaire / case", "Libellé", "Montant", "Lu par le moteur", "Localisation"], r.declaration.lines.map(l => [l.formNumber + " / " + l.code, l.label, fxCents(l.amountCents), l.readByEngine ? "Oui" : "Non", fiscalLocatorLabel(l.locator)]))
    + table("Règles bloquées et source requise", ["Règle", "Catégorie", "Source requise"], r.blockedRules.map(x => [x.label + " (" + x.code + ")", x.category, x.requiredSource + (x.sources.length ? " · " + x.sources.map(s => s.title + " — " + s.url + " — vérifié le " + s.lastVerifiedAt).join(" ; ") : "")]))
    + table("Exceptions et incertitudes conservées après revue", ["Identité", "Constat", "Montant"], r.exceptions.map(x => [x.id, x.label + " ; " + x.message, fiscalAmountLabel(x.amount)]))
    + "<p>Autres impôts et taxes du registre, capacités séparées non couvertes par cette feuille : " + escapeHtml(r.otherTaxes.map(t => t.title).join(" ; ")) + ".</p></section>";
}
function details(m: FiscalMissionSnapshot) {
  if (m.procedure.cit) return citDetails(m);
  const r = m.procedure.vat;
  if (!r) return "<section><h2>Fiscalité</h2><p>Aucun résultat fiscal exploitable pour cette version.</p></section>";
  return "<section><h2>TVA — " + escapeHtml(m.procedure.periodLabel) + " (" + escapeHtml(r.period.startDate) + " → " + escapeHtml(r.period.endDate) + ")</h2>"
    + "<p>Moteur " + escapeHtml(r.engine.name) + " " + escapeHtml(r.engine.version) + " · calcul " + escapeHtml(r.engine.calculationVersion) + " · instantané " + escapeHtml(r.engine.snapshotHash) + " · statut " + escapeHtml(r.engine.status) + " · niveau de preuve " + escapeHtml(r.engine.evidenceTier) + " · couverture normative " + escapeHtml(r.engine.coverage?.status ?? "—") + ".</p>"
    + "<p>Profil : régime " + escapeHtml(r.profile.vatRegime) + ", groupe " + escapeHtml(r.profile.vatGroupStatus) + ", " + (r.profile.status === "confirmed" ? "confirmé par " + escapeHtml(r.profile.confirmedBy) + " le " + escapeHtml(r.profile.confirmedAt) + " — " + escapeHtml(citation(r.profile.evidence ?? undefined)) : "non confirmé") + ". Formulaire attendu " + escapeHtml(r.engine.expectedForm) + ", millésime " + r.formVintage + ".</p>"
    + "<p class='notice'>" + escapeHtml(r.rateMeaning) + "</p><p>" + escapeHtml(r.method) + "</p>"
    + table("Comptabilisé / déclaré / écart", ["Ligne", "Théorique", "Comptabilisé", "Déclaré (case)", "Écart (comptabilisé − déclaré)"], r.comparison.map(c => [c.label, fxCents(c.theoreticalCents), fxCents(c.accountedCents), fxCents(c.declaredCents) + (c.declaredBox ? " (case " + c.declaredBox + ")" : ""), fxCents(c.differenceCents)]))
    + table("Pont explicatif", ["Étape", "Montant", "Pièce citée"], [["Net comptabilisé", fxCents(r.bridge.startCents), "Écritures du FEC"], ...r.bridge.items.map(i => [VAT_EXPLANATION_LABELS[i.kind] + " — " + i.label + " (" + i.authorId + ", " + i.at + ")", fxCents(i.amountCents), citation(i.citation)]),
      ["Net expliqué", fxCents(r.bridge.explainedCents), ""], ["Net déclaré" + (r.bridge.declaredBox ? " (case " + r.bridge.declaredBox + ")" : ""), fxCents(r.bridge.declaredCents), r.declaration.fileName ?? "Déclaration absente"], ["Résidu non expliqué", fxCents(r.bridge.residualCents), r.bridge.reason ?? ""]])
    + table("Paiements et crédit reporté", ["Rapprochement", "Statut", "Valeurs", "Écart"], [["Paiements ↔ net déclaré", r.payments.status, "Payé " + fxCents(r.payments.paidCents) + " · déclaré " + fxCents(r.payments.declaredDueCents) + (r.payments.reason ? " · " + r.payments.reason : ""), fxCents(r.payments.differenceCents)],
      ["Crédit reporté", r.credit.status, "Case " + (r.credit.previous?.box ?? "—") + " précédente " + fxCents(r.credit.previous?.creditToCarryCents) + " · case " + (r.credit.currentBox ?? "—") + " de la période " + fxCents(r.credit.currentReceivedCents) + (r.credit.reason ? " · " + r.credit.reason : ""), fxCents(r.credit.differenceCents)]])
    + table("Lignes de la déclaration", ["Case", "Libellé / rôle", "Montant", "Lu par le moteur", "Écritures liées", "Localisation"], r.declaration.lines.map(l => [l.code, l.label + (l.role ? " — " + VAT_ROLE_LABELS[l.role] : ""), fxCents(l.amountCents), l.readByEngine ? "Oui" : "Non", l.candidateIds.length, fiscalLocatorLabel(l.locator)]))
    + table("Taux constatés (non approuvés comme taux légaux)", ["Sens / taux", "Statut", "Base", "TVA comptabilisée", "TVA théorique", "Origine"], r.rates.map(x => [x.direction + " · " + x.label, x.status, fxCents(x.baseCents), fxCents(x.vatAccountedCents), fxCents(x.vatTheoreticalCents), x.origin]))
    + table("Écritures de TVA de la période", ["Écriture", "Date / pièce", "Base", "TVA", "Taux constaté", "Signaux", "Pièce"], r.entries.map(e => [e.journalCode + " " + e.ecritureNum + (e.creditNote ? " (avoir)" : ""), e.date + " / " + (e.pieceRef ?? "—"), fxCents(e.baseCents), fxCents(e.vatCents), e.observedRateBasisPoints === null ? "—" : (e.observedRateBasisPoints / 100).toFixed(2) + " %", e.signals.join(", ") || "—", e.piece.status === "found" ? e.piece.ref + " · " + e.piece.fileName + " · " + fiscalLocatorLabel(e.piece.locator) : e.piece.status === "missing" ? "Absente de l’inventaire" : "Inventaire non fourni"]))
    + table("Contrôles du moteur", ["Contrôle", "Résultat", "Niveau de preuve", "Valeur lue / référence / écart", "Détail"], r.controls.map(c => [c.controlId + " — " + c.title, c.outcome, c.evidenceTier, fxCents(c.observedCents) + " / " + fxCents(c.comparedCents) + " / " + (c.comparable ? fxCents(c.differenceCents) : "sans objet"), c.detail]))
    + table("Règles bloquées et source requise", ["Règle", "Catégorie", "Contrôles", "Source requise"], r.blockedRules.map(b => [b.label + " (" + b.code + ")", b.category, b.controls.join(", ") || "—", b.requiredSource + (b.sources.length ? " · " + b.sources.map(s => s.title + " — " + s.url + " — vérifié le " + s.lastVerifiedAt).join(" ; ") : "")]))
    + table("Exceptions et incertitudes conservées après revue", ["Identité / contrôle", "Constat", "Montant"], r.exceptions.map(x => [x.id + " / " + (x.controlId ?? "—"), x.label + " ; " + x.message, fiscalAmountLabel(x.amount)]))
    + "<p>Autres impôts et taxes du registre, capacités séparées non couvertes par cette feuille : " + escapeHtml(r.otherTaxes.map(t => t.title).join(" ; ")) + ".</p></section>";
}
export function fiscalMissionHtml(m: FiscalMissionSnapshot, run: WorkpaperRun | null, kind: FiscalExportKind, createdAt: string) {
  const p = m.procedure;
  const status = kind === "approved" ? "Paquet " + (p.tax === "cit" ? "IS" : "TVA") + " approuvé et verrouillé — portée : " + (p.tax === "cit" ? "cet exercice" : "cette période") + " uniquement, aucune liquidation ni conformité déclarée" : "Export diagnostic — ne constitue pas un paquet approuvé";
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>PROBANT — Fiscalité (TVA, IS)</title><style>
body{font:15px/1.55 system-ui,sans-serif;color:#18283c;background:white;margin:2rem auto;max-width:1120px;padding:0 1rem}h1{font-size:26px}h2{font-size:20px;margin-top:2rem}p,td,th{overflow-wrap:anywhere;white-space:pre-wrap}table{width:100%;border-collapse:collapse;margin:1rem 0;table-layout:fixed}caption{text-align:left;font-weight:700;margin:.5rem 0}th,td{text-align:left;vertical-align:top;border:1px solid #b5bfcb;padding:7px;font-size:12px}th{background:#edf1f6}thead{display:table-header-group}tr{break-inside:avoid}header{border-bottom:2px solid #344b67}.notice{border-left:4px solid #ab7015;padding:1rem;background:#fff7e4}@page{size:A4 landscape;margin:16mm}@media print{body{max-width:none;margin:0;padding:0;font-size:11px}h2{break-after:avoid}th{background:#eee}table{font-size:9px}.notice{background:none}}
</style></head><body><header><p>Procédures de mission · infrastructure de recette jetable</p><h1>Fiscalité — ${escapeHtml(p.periodLabel ?? p.label)}</h1><p>${escapeHtml(status)}</p><p>Dossier ${escapeHtml(m.scope.dossierId)} · Organisation ${escapeHtml(m.scope.organizationId)} · Exercice ${escapeHtml(m.scope.periodId)}</p><p>Feuille ${escapeHtml(p.runId)} · révision ${escapeHtml(p.revision)} · version ${escapeHtml(p.version)} · préparation ${escapeHtml(p.preparedBy)}</p><p>État serveur ${escapeHtml(m.hash)} · état établi au ${escapeHtml(createdAt)}</p></header>
<section><h2>Résumé humain</h2><p>${escapeHtml(p.resultLabel)}. ${escapeHtml(p.reviewLabel)}. ${escapeHtml(p.legal.conclusion)}.</p><p>${escapeHtml(p.conclusion)}</p><p class="notice">${escapeHtml(p.stale ? "Travail périmé : " + p.staleReasons.join(" ") : "Sources courantes à la génération de cet état.")} ${escapeHtml(p.legal.meaning)}</p><p>Programme ${escapeHtml(m.program.id)} @ ${escapeHtml(m.program.version)} : ${m.counters.executed}/${m.counters.planned} période(s) exécutée(s) ; ${m.counters.testedParts}/${m.counters.plannedParts} contrôles complets pour cette période ; ${m.counters.exceptions} exceptions ; ${m.counters.uncertainties} incertitudes.</p><p>Hors périmètre : ${escapeHtml(m.program.outOfScope.join(" ; "))}.</p></section>
<section><h2>Périodes du programme</h2>${table("Navigation par impôt et période", ["Période", "État", "Résultat", "Revue", "Exceptions / incertitudes / règles bloquées", "Péremption"], m.periods.map(x => [x.label, x.state, x.resultLabel, x.reviewLabel, x.exceptions + " / " + x.uncertainties + " / " + x.blockedRules, x.stale ? x.staleReasons.join(" ") : "Courante"]))}</section>
<section><h2>File de travail priorisée</h2>${table("Actions liées à cette version", ["Priorité", "Catégorie", "Action", "Détail / identité"], m.queue.map(q => [q.priority, q.category, q.label, q.detail + " · " + q.id + " · " + q.href]))}</section>
<section><h2>Procédure, population et sélection</h2><p>Couverture ${p.coverage.numerator}/${p.coverage.denominator ?? "inconnu"} ${escapeHtml(p.coverage.unit)}. Critères : ${escapeHtml(p.coverage.criteria)}.</p>${table("Exclusions motivées de la population", ["Unité", "Raison"], p.coverage.exclusions.map(e => [e.id, e.reason]))}${table("Contrôles du programme", ["Contrôle", "Résultat", "Numérateur / dénominateur", "Convention"], p.controls.map(c => [c.label, c.outcome ?? "Non exécuté", c.coverage.numerator + "/" + (c.coverage.denominator ?? "inconnu") + " " + c.coverage.unit, c.convention]))}</section>
${details(m)}<section><h2>Décisions humaines et comparaison avant / après revue</h2><p>Résultat ${escapeHtml(p.resultId)} · entrées ${escapeHtml(p.resultInputHash)} · contenu ${escapeHtml(p.contentHash)}.</p>${table("Décision sur la version", ["Auteur réel", "Version approuvée / date", "Décision motivée", "Résultat après revue"], p.review ? [[p.review.actorId, p.review.approvedVersion + " · " + p.review.at, p.review.note, p.resultLabel]] : [])}${table("Avant / après revue", ["Moment", "Version / résultat", "Conclusion", "Traitements documentés"], [p.beforeReview && ["Soumission", p.beforeReview.version + " / " + p.beforeReview.resultId, p.beforeReview.conclusion, p.beforeReview.notes.map(n => n.text + " : " + (n.resolution?.text ?? "Ouvert")).join(" ; ")], p.afterReview && ["Après revue", p.afterReview.version + " / " + p.afterReview.resultId, p.afterReview.conclusion, p.afterReview.notes.map(n => n.text + " : " + (n.resolution?.text ?? "Ouvert")).join(" ; ")]].filter((r): r is string[] => !!r))}${table("Commentaires / exceptions, traitement et pièce citée", ["Identité", "Auteur", "Texte", "Traitement et citation"], p.notes.map(n => [n.id, n.authorId, n.text + (n.citation ? " — " + citation(n.citation) : ""), n.resolution ? n.resolution.text + " · " + n.resolution.authorId + " · " + n.resolution.at + " · " + citation(n.resolution.citation) : n.blocking ? "Bloquant ouvert" : "Ouvert"]))}${table("Versions, profil et explications", ["Identité / version", "État / empreinte", "Profil", "Explications citées", "Décision conservée"], m.versionIndex.map(v => [v.id + " · r" + v.revision + " v" + v.version, v.state + " · " + v.contentHash, v.profile ? v.profile.regime + " · " + v.profile.status + (v.profile.evidence ? " · " + v.profile.evidence : "") : "—", v.explanations.map(e => e.id + " " + e.amountCents + " c · " + e.documentVersionId + (e.row ? " l." + e.row : "") + " (" + e.authorId + ")").join(" ; ") || "Aucune", v.approval ? v.approval.actorId + " : " + v.approval.note : v.reviewNotes.map(n => n.authorId + " : " + n.text).join(" ; ") || v.events.at(-1)?.action || "Aucune approbation"]))}</section>
<section><h2>Sources et index des pièces</h2><p class="notice">Les originaux binaires ne sont pas inclus dans ce paquet. Leur téléchargement séparé exige la permission d’export du même dossier. Une pièce absente ne devient pas une preuve fournie.</p>${table("Index des pièces versionnées", ["Pièce / identité", "Version / SHA-256", "Provenance / approbation", "Présence et actualité"], m.sources.map(s => [s.label + " · " + (s.fileName ?? "Attendue") + " · " + s.id, s.importId + " · " + (s.sha256 ?? "Absent"), "Parseur " + s.parserVersion + " ; mapping " + s.mappingVersion + "/" + s.mappingHash + " ; " + s.approvedBy + " · " + s.approvedAt, !s.available ? (s.required ? "Pièce requise absente" : "Pièce conditionnelle absente") : (s.current ? "Source courante" : "Source remplacée / périmée") + " · " + s.rowCount + " ligne(s) · binaire absent du paquet"]))}${table("Versions remplacées (conservées)", ["Clé", "Fichier / SHA-256", "Approuvée le", "Utilisée par cette version"], m.replaced.map(x => [x.key, x.fileName + " · " + x.sha256, x.approvedAt, x.usedByRun ? "Oui — travail périmé" : "Non"]))}${table("Localisateurs des lignes sources", ["Document versionné", "Ligne", "Localisateur"], m.sources.flatMap(s => s.locators.map(l => [s.id, l.rowId, fiscalLocatorLabel(l.locator)])))}</section>
<section><h2>Incertitudes et limites</h2><ul>${[...m.limitations, ...p.coverage.limitations, ...(run?.result?.warnings ?? []), ...(run?.result?.blockedControls ?? []), "PDF standard dérivé du HTML, sans certification PDF/A ; caractères hors alphabet Latin-1 remplacés dans ce PDF. HTML et JSON conservent le texte Unicode."].map(l => `<li>${escapeHtml(l)}</li>`).join("")}</ul><p>Famille de ce rapport : procédures de mission. Le cockpit fiscal de démonstration n’est pas inclus.</p></section></body></html>`;
}
export async function buildFiscalMissionPackage(mission: FiscalMissionSnapshot, run: WorkpaperRun | null, imports: ImportBatch[], kind: FiscalExportKind, createdAt: string): Promise<EvidenceExportPackage> {
  assertFiscalPackage(mission, run, kind);
  const sourceIds = new Set(mission.sources.filter(s => s.available).map(s => s.importId));
  const batches = imports.filter(b => sourceIds.has(b.id)).sort((a, b) => canonicalCompare(a.id, b.id)); batches.forEach(b => assertScope(mission.scope, b.scope));
  if (batches.length !== sourceIds.size) throw new Error("EXPORT_SOURCE_REQUIRED");
  // FEC rows are summarized in the package: the original stays downloadable separately, with the same permissions.
  const packaged = batches.map(b => b.document.documentType === "fx_fec" ? { ...b, rows: [], rowCount: b.rows.length } : b);
  const report = { exportSchemaVersion: "fiscal-mission-1.0.0", kind, createdAt, mission, run, imports: packaged, binaryFilesIncluded: false };
  const canonical = canonicalJson(report), html = fiscalMissionHtml(mission, run, kind, createdAt), p = mission.procedure, r = p.vat ?? p.cit;
  const csv = {
    findings: buildCsv(["procedureId", "runId", "version", "resultId", "controlId", "code", "id", "amount", "message"], (r?.exceptions ?? []).map(x => ({ procedureId: p.id, runId: p.runId, version: p.version, resultId: p.resultId, controlId: x.controlId ?? "", code: x.code, id: x.id, amount: fiscalAmountLabel(x.amount), message: x.label + " — " + x.message }))),
    reviewEvents: buildCsv(["procedureId", "runId", "version", "actorId", "at", "action", "note"], mission.versionIndex.flatMap(v => v.events.slice(-1).map(ev => ({ ...ev, procedureId: p.id, runId: v.id, version: v.version, note: v.approval?.note ?? "" })))),
    controls: buildCsv(["procedureId", "runId", "version", "ruleVersion", "controlId", "label", "outcome", "complete", "numerator", "denominator", "unit"], p.controls.map(x => ({ procedureId: p.id, runId: p.runId, version: p.version, ruleVersion: x.ruleVersion, controlId: x.id, label: x.label, outcome: x.outcome ?? "not_executed", complete: x.complete, numerator: x.coverage.numerator, denominator: x.coverage.denominator, unit: x.coverage.unit }))),
    sources: buildCsv(["id", "importId", "type", "key", "fileName", "sha256", "approvedBy", "approvedAt", "available", "required", "current", "binaryInPackage"], mission.sources.map(s => ({ ...s }))),
  };
  const pdf = await buildPdfFromAccessibleHtml(html, { title: "PROBANT - Fiscalite " + (p.tax === "cit" ? "IS" : "TVA") + " - " + kind, createdAt });
  const base = "probant-fiscal-" + (p.tax === "cit" ? "is" : "tva") + "-" + kind + "-" + mission.hash.slice(0, 12);
  const manifest: EvidenceManifest = { manifestVersion: "1.0.0", applicationVersion: "0.1.0", dossierId: mission.scope.dossierId, snapshotId: mission.hash, createdAt,
    sourceDocuments: batches.map(b => ({ id: b.document.id, fileName: b.document.fileName, documentType: b.document.documentType, sha256: b.document.byteHash, parserVersion: b.document.parserVersion, location: { provider: "postgres-fx", key: b.id, versionId: b.document.id } })),
    parserVersions: Object.fromEntries(batches.map(b => [b.document.id, b.document.parserVersion])), ruleSetVersion: mission.program.version,
    referenceSetVersion: "tax-registry-" + (r?.engine.calculationVersion ?? "not-executed"), policyVersion: "server-dossier-permissions-1.0.0", snapshotSha256: mission.hash, reviewEventsDigest: stableSha256(mission.versionIndex),
    artifacts: [artifact("canonical_json", base + ".json", "application/json", canonical), artifact("findings_csv", base + "-exceptions.csv", "text/csv;charset=utf-8", csv.findings),
      artifact("review_events_csv", base + "-decisions.csv", "text/csv;charset=utf-8", csv.reviewEvents), artifact("controls_csv", base + "-procedures.csv", "text/csv;charset=utf-8", csv.controls),
      artifact("sources_csv", base + "-sources.csv", "text/csv;charset=utf-8", csv.sources), artifact("accessible_html", base + ".html", "text/html;charset=utf-8", html),
      artifact("pdf", base + ".pdf", "application/pdf", pdf, { derivedFrom: base + ".html", validation: { pdfA: { status: "not_validated", profile: null, validator: null, validatedAt: null } } })],
    limitations: [...mission.limitations.map((message, i) => ({ code: "fiscal_limit_" + i, message, subjects: [] as string[] })),
      { code: "package_kind_" + kind, message: kind === "approved" ? "Procédure " + (p.tax === "cit" ? "IS de l’exercice" : "TVA de la période") + " approuvée et verrouillée ; aucune liquidation, conformité ni opinion." : "Diagnostic, y compris des versions historiques ou périmées ; aucune approbation du paquet.", subjects: [mission.hash] },
      { code: "pdf_standard_unicode", message: "PDF standard sans PDF/A ; caractères hors Latin-1 remplacés. HTML et JSON préservent Unicode.", subjects: [base + ".pdf"] }] };
  return { manifest, manifestJson: canonicalJson(manifest), canonicalJson: canonical, csv, html, pdf };
}
