import { canonicalCompare, canonicalJson, stableSha256 } from "@/lib/synthesis/canonical";
import { fixedAssetAmountLabel, fixedAssetLocatorLabel, type FixedAssetMissionSnapshot } from "@/lib/workpapers/fixed-asset-mission";
import { FA_RECALC_TEXT, FA_SUPPORT_TEXT } from "@/lib/workpapers/fixed-asset-review";
import { FA_MOVEMENT_LABELS, FA_STATUS_LABELS, FA_TABLE_LABELS, FA_TABLES } from "@/lib/workpapers/fixed-asset-sources";
import { assertScope, contentHash, validateRun, type EvidenceLink, type WorkpaperRun } from "@/lib/workpapers/model";
import type { ImportBatch } from "@/lib/workpapers/imports";
import { artifact } from "./package";
import { buildCsv } from "./csv";
import { buildPdfFromAccessibleHtml } from "./pdf";
import type { EvidenceExportPackage, EvidenceManifest } from "./types";

export type FixedAssetExportKind = "diagnostic" | "approved";
export function assertFixedAssetPackage(mission: FixedAssetMissionSnapshot, run: WorkpaperRun | null, kind: FixedAssetExportKind) {
  const { hash, ...body } = mission;
  if (stableSha256(body) !== hash) throw new Error("EXPORT_SNAPSHOT_HASH_INVALID");
  if (run) {
    validateRun(run); assertScope(mission.scope, run.scope);
    if (run.id !== mission.procedure.runId || run.version !== mission.procedure.version || contentHash(run) !== mission.procedure.contentHash) throw new Error("EXPORT_VERSION_INVALID");
  } else if (mission.procedure.runId) throw new Error("EXPORT_RUN_REQUIRED");
  if (kind === "approved" && (!run || run.state !== "locked" || mission.procedure.stale || !mission.procedure.assets || !run.approval || run.approval.snapshotHash !== contentHash(run))) throw new Error("EXPORT_APPROVED_CURRENT_LOCKED_REQUIRED");
}
const escapeHtml = (value: unknown) => String(value ?? "—").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
function table(title: string, headings: string[], rows: unknown[][]) {
  return `<table><caption>${escapeHtml(title)}</caption><thead><tr>${headings.map(h => `<th scope="col">${escapeHtml(h)}</th>`).join("")}</tr></thead><tbody>${rows.length ? rows.map(row => `<tr>${row.map(cell => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`).join("") : `<tr><td colspan="${headings.length}">Aucun élément.</td></tr>`}</tbody></table>`;
}
const links = (proofs: Pick<EvidenceLink, "id" | "documentVersionId" | "rowId" | "locator">[]) => proofs.map(p => p.id + " · " + p.documentVersionId + "/" + (p.rowId ?? "document entier") + " · " + fixedAssetLocatorLabel(p.locator)).join(" ; ") || "Pièce attendue ou absente";
function details(m: FixedAssetMissionSnapshot) {
  const a = m.procedure.assets;
  if (!a) return "<section><h2>Immobilisations</h2><p>Aucun résultat Immobilisations exploitable pour cette version.</p></section>";
  const tableRow = (t: typeof FA_TABLES[number]) => a.units.map(u => {
    const x = u.tables[t];
    return x.status === "computed" ? [u.unitId + " · " + u.family, fixedAssetAmountLabel(x.opening), fixedAssetAmountLabel(x.additions), fixedAssetAmountLabel(x.disposals), fixedAssetAmountLabel(x.reversals), fixedAssetAmountLabel(x.reclassifications), fixedAssetAmountLabel(x.expected), fixedAssetAmountLabel(x.closing), fixedAssetAmountLabel(x.difference)]
      : [u.unitId + " · " + u.family, x.status === "excluded" ? "Exclu : " + x.reason : "Incomplet : " + x.missing.join(" "), "—", "—", "—", "—", "—", "—", "Non calculé"];
  });
  return "<section><h2>Immobilisations — ponts séparés, cadrage, pièces et recalcul</h2><p>Exercice " + escapeHtml(a.startDate) + " → " + escapeHtml(a.closingDate) + " ; revue " + escapeHtml(a.reviewDate) + ". Convention " + escapeHtml(a.convention.version) + " validée par " + escapeHtml(a.convention.validatedBy) + " : " + escapeHtml(a.convention.meaning) + "</p>"
    + "<p class='notice'>La VNC est une différence arithmétique, pas une conclusion de valeur. Aucune conclusion d’existence physique. Aucun paramètre implicite.</p>"
    + table("Population des actifs et composants", ["Actif / composant", "Famille / statut", "Périmètre", "VNC arithmétique"], a.units.map(u => [u.unitId + " · " + u.label, u.family + " / " + FA_STATUS_LABELS[u.status], u.inScope ? "Testé" : "Exclu : " + u.exclusionReason, fixedAssetAmountLabel(u.vnc)]))
    + FA_TABLES.map(t => table("Pont " + FA_TABLE_LABELS[t] + " par actif", ["Actif", "Ouverture", "+ Entrées", "− Sorties", "− Reprises", "± Reclassements", "= Attendu", "Clôture observée", "Écart"], tableRow(t))).join("")
    + table("Ponts par famille (actifs calculés uniquement, avec dénominateur)", ["Famille / tableau", "Actifs calculés / testés", "Ouverture", "Entrées", "Sorties", "Reprises", "Reclassements", "Clôture", "Écart net / brut non compensé"], a.families.flatMap(f => FA_TABLES.map(t => { const x = f.tables[t]; return [f.family + " / " + FA_TABLE_LABELS[t], (x.inScopeUnits === 0 ? "aucun actif testé (exclus avec motif)" : x.computedUnits + "/" + x.inScopeUnits + (x.complete ? "" : " (partiel)")), fixedAssetAmountLabel(x.opening), fixedAssetAmountLabel(x.additions), fixedAssetAmountLabel(x.disposals), fixedAssetAmountLabel(x.reversals), fixedAssetAmountLabel(x.reclassifications), fixedAssetAmountLabel(x.closing), fixedAssetAmountLabel(x.difference) + " / " + fixedAssetAmountLabel(x.absoluteDifference) + " · " + x.unitsWithDifference + " actif(s)"]; })))
    + table("Cadrage registre → GL (débit positif)", ["Compte / tableau", "Registre converti", "GL", "Écart", "Actifs", "Preuves"], a.framing.rows.map(r => [r.account + " / " + (r.table ? FA_TABLE_LABELS[r.table] : "—") + " · " + r.label, fixedAssetAmountLabel(r.register), fixedAssetAmountLabel(r.ledger), fixedAssetAmountLabel(r.difference), r.units.join(", ") || "Aucun", links(r.evidence)]))
    + table("Mouvements bruts et pièces", ["Actif / ligne", "Mouvement", "Registre", "Pièce", "Statut et sens", "Écart"], a.units.flatMap(u => u.supports.map(s => [u.unitId + " / " + s.lineId, FA_MOVEMENT_LABELS[s.movement] + " · " + s.date, fixedAssetAmountLabel(s.amount), s.piece ? s.piece.pieceId + " · " + s.piece.kind + " · " + fixedAssetAmountLabel(s.piece.amount) + " · " + s.piece.date : "Absente (" + (s.pieceRef || "sans référence") + ")", FA_SUPPORT_TEXT[s.status].label + " — " + s.statusMeaning, fixedAssetAmountLabel(s.difference)])))
    + table("Méthodes documentées", ["Méthode / version", "Nature", "Source citée", "Validité", "Auteur", "Actifs"], a.methods.map(x => [x.id + " v" + x.version + " · " + x.label, x.kind === "linear" ? "Linéaire" : "Non couverte", x.source + " · base : " + x.basis, x.from + " → " + x.to + (x.applicable ? " (applicable)" : " (non applicable à la clôture)"), x.authorId + " · " + x.authoredAt, x.unitsUsing]))
    + "<p>" + escapeHtml(a.formula) + "</p>"
    + table("Recalcul documenté", ["Actif", "Statut et motif", "Méthode", "Entrées (coût / résiduel / base / durée / prorata / mise en service)", "Recalculé", "Comptabilisé", "Écart"], a.units.map(u => { const r = u.recalculation; return [u.unitId, FA_RECALC_TEXT[r.status].label + " — " + r.reason, r.method ? r.method.id + " v" + r.method.version : "—", [fixedAssetAmountLabel(r.inputs.cost), fixedAssetAmountLabel(r.inputs.residual), fixedAssetAmountLabel(r.inputs.base), (r.inputs.durationMonths ?? "?") + " mois", (r.inputs.prorataNumerator ?? "?") + "/" + (r.inputs.prorataDenominator ?? "?"), r.inputs.inServiceDate ?? "?"].join(" / "), fixedAssetAmountLabel(r.recalculated), fixedAssetAmountLabel(r.booked), fixedAssetAmountLabel(r.difference)]; }))
    + table("Exceptions et incertitudes conservées après revue", ["Identité / contrôle / cible", "Constat", "Montant", "Preuves"], a.exceptions.map(e => [e.id + " / " + e.controlId + " / " + e.targetId, e.label + " ; " + e.message, fixedAssetAmountLabel(e.amount), e.proofIds.join(" ; ") || "Pièce attendue"])) + "</section>";
}
export function fixedAssetMissionHtml(m: FixedAssetMissionSnapshot, run: WorkpaperRun | null, kind: FixedAssetExportKind, createdAt: string) {
  const p = m.procedure;
  const status = kind === "approved" ? "Paquet Immobilisations approuvé et verrouillé — portée : cette procédure uniquement" : "Export diagnostic — ne constitue pas un paquet approuvé";
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>PROBANT — Immobilisations</title><style>
body{font:15px/1.55 system-ui,sans-serif;color:#18283c;background:white;margin:2rem auto;max-width:1120px;padding:0 1rem}h1{font-size:26px}h2{font-size:20px;margin-top:2rem}p,td,th{overflow-wrap:anywhere;white-space:pre-wrap}table{width:100%;border-collapse:collapse;margin:1rem 0;table-layout:fixed}caption{text-align:left;font-weight:700;margin:.5rem 0}th,td{text-align:left;vertical-align:top;border:1px solid #b5bfcb;padding:7px;font-size:12px}th{background:#edf1f6}thead{display:table-header-group}tr{break-inside:avoid}header{border-bottom:2px solid #344b67}.notice{border-left:4px solid #ab7015;padding:1rem;background:#fff7e4}@page{size:A4 landscape;margin:16mm}@media print{body{max-width:none;margin:0;padding:0;font-size:11px}h2{break-after:avoid}th{background:#eee}table{font-size:10px}.notice{background:none}}
</style></head><body><header><p>Procédures de mission · infrastructure de recette jetable</p><h1>Immobilisations — ${escapeHtml(p.label)}</h1><p>${escapeHtml(status)}</p><p>Dossier ${escapeHtml(m.scope.dossierId)} · Organisation ${escapeHtml(m.scope.organizationId)} · Période ${escapeHtml(m.scope.periodId)}</p><p>Feuille ${escapeHtml(p.runId)} · révision ${escapeHtml(p.revision)} · version ${escapeHtml(p.version)} · préparation ${escapeHtml(p.preparedBy)}</p><p>État serveur ${escapeHtml(m.hash)} · état établi au ${escapeHtml(createdAt)}</p></header>
<section><h2>Résumé humain</h2><p>${escapeHtml(p.resultLabel)}. ${escapeHtml(p.reviewLabel)}.</p><p>${escapeHtml(p.conclusion)}</p><p class="notice">${escapeHtml(p.stale ? "Travail périmé : " + p.staleReasons.join(" ") : "Sources courantes à la génération de cet état.")} Une revue documentée ne vaut pas conformité des comptes ; aucune opinion automatique.</p><p>Programme ${escapeHtml(m.program.id)} @ ${escapeHtml(m.program.version)} : ${m.counters.executed}/${m.counters.planned} procédure exécutée ; ${m.counters.testedParts}/${m.counters.plannedParts} contrôles complets ; ${m.counters.exceptions} exceptions ; ${m.counters.uncertainties} incertitudes. Les exceptions ne constituent pas le dénominateur du programme.</p><p>Hors périmètre de ce programme : ${escapeHtml(m.program.outOfScope.join(" ; "))}.</p></section>
<section><h2>File de travail priorisée</h2>${table("Actions liées à cette version", ["Priorité", "Catégorie", "Action", "Détail / identité"], m.queue.map(q => [q.priority, q.category, q.label, q.detail + " · " + q.id + " · " + q.href]))}</section>
<section><h2>Procédure, population et sélection</h2>${table("Programme fermé", ["Procédure", "Contrôles prévus", "Conventions"], m.program.procedures.map(d => [d.label + " @ " + d.version, d.tests.map(t => t.label).join(" ; "), p.controls.map(c => c.label + " : " + c.convention).join(" ")]))}<p>Couverture ${p.coverage.numerator}/${p.coverage.denominator ?? "inconnu"} ${escapeHtml(p.coverage.unit)}. Critères : ${escapeHtml(p.coverage.criteria)}.</p>${table("Exclusions motivées de la population", ["Unité", "Raison"], p.coverage.exclusions.map(e => [e.id, e.reason]))}${table("Contrôles et dénominateurs", ["Contrôle", "Résultat", "Numérateur / dénominateur", "Exclusions"], p.controls.map(c => [c.label, c.outcome ?? "Non exécuté", c.coverage.numerator + "/" + (c.coverage.denominator ?? "inconnu") + " " + c.coverage.unit, c.coverage.exclusions.map(e => e.id + " : " + e.reason).join(" ; ") || "Aucune"]))}${table("Population figée", ["Unité", "Brut de clôture", "Lignes sources", "Sélection"], run?.population?.items.map(item => [item.id, fixedAssetAmountLabel(item.amount), item.rowIds.length + " ligne(s)", run.selection?.selectedIds.includes(item.id) ? "Sélectionnée" : "Exclue avec motif"]) ?? [])}</section>
${details(m)}<section><h2>Décisions et comparaison avant / après revue</h2><p>Résultat ${escapeHtml(p.resultId)} · entrées ${escapeHtml(p.resultInputHash)} · contenu ${escapeHtml(p.contentHash)}.</p>${table("Décision sur la version", ["Auteur réel", "Version approuvée / date", "Décision motivée", "Résultat après revue"], p.review ? [[p.review.actorId, p.review.approvedVersion + " · " + p.review.at, p.review.note, p.resultLabel]] : [])}${table("Avant / après revue", ["Moment", "Version / résultat", "Conclusion", "Traitements documentés"], [p.beforeReview && ["Soumission", p.beforeReview.version + " / " + p.beforeReview.resultId, p.beforeReview.conclusion, p.beforeReview.notes.map(n => n.text + " : " + (n.resolution?.text ?? "Ouvert")).join(" ; ")], p.afterReview && ["Après revue", p.afterReview.version + " / " + p.afterReview.resultId, p.afterReview.conclusion, p.afterReview.notes.map(n => n.text + " : " + (n.resolution?.text ?? "Ouvert")).join(" ; ")]].filter((r): r is string[] => !!r))}${table("Commentaires / exceptions et leur traitement", ["Identité", "Auteur", "Texte", "Traitement"], p.notes.map(n => [n.id, n.authorId, n.text, n.resolution ? n.resolution.text + " · " + n.resolution.authorId + " · " + n.resolution.at : n.blocking ? "Bloquant ouvert" : "Ouvert"]))}${table("Versions, méthodes et anciennes décisions", ["Identité / version", "État / empreinte", "Méthodes documentées", "Auteur", "Décision conservée"], m.versionIndex.map(v => [v.id + " · r" + v.revision + " v" + v.version, v.state + " · " + v.contentHash, v.methods.map(x => x.id + " v" + x.version + " (" + x.authorId + ")").join(" ; ") || "Aucune", v.actorId, v.approval ? v.approval.actorId + " : " + v.approval.note : v.reviewNotes.map(n => n.authorId + " : " + n.text).join(" ; ") || v.events.at(-1)?.action || "Aucune approbation"]))}</section>
<section><h2>Sources et index des pièces</h2><p class="notice">Les originaux binaires ne sont pas inclus dans ce paquet. Leur téléchargement séparé exige la permission d’export du même dossier. Une pièce absente ne devient pas une preuve fournie.</p>${table("Index des pièces versionnées", ["Pièce / identité", "Version / SHA-256", "Provenance / approbation", "Présence et actualité"], m.sources.map(s => [s.label + " · " + (s.fileName ?? "Attendue") + " · " + s.id, s.importId + " · " + (s.sha256 ?? "Absent"), "Parseur " + s.parserVersion + " ; mapping " + s.mappingVersion + "/" + s.mappingHash + " ; " + s.approvedBy + " · " + s.approvedAt, !s.available ? (s.required ? "Pièce requise absente" : "Pièce conditionnelle absente") : (s.current ? "Source courante" : "Source remplacée / périmée") + " · binaire absent du paquet"]))}${table("Localisateurs des lignes sources", ["Document versionné", "Ligne", "Localisateur"], m.sources.flatMap(s => s.locators.map(l => [s.id, l.rowId, fixedAssetLocatorLabel(l.locator)])))}</section>
<section><h2>Incertitudes et limites</h2><ul>${[...m.limitations, ...p.coverage.limitations, ...(run?.result?.warnings ?? []), ...(run?.result?.blockedControls ?? []), "PDF standard dérivé du HTML, sans certification PDF/A ; caractères hors alphabet Latin-1 remplacés dans ce PDF. HTML et JSON conservent le texte Unicode."].map(l => `<li>${escapeHtml(l)}</li>`).join("")}</ul><p>Famille de ce rapport : procédures de mission. Les constats historiques DEMO SA et l’atelier synthétique ne sont pas inclus.</p></section></body></html>`;
}
export async function buildFixedAssetMissionPackage(mission: FixedAssetMissionSnapshot, run: WorkpaperRun | null, imports: ImportBatch[], kind: FixedAssetExportKind, createdAt: string): Promise<EvidenceExportPackage> {
  assertFixedAssetPackage(mission, run, kind);
  const sourceIds = new Set(mission.sources.filter(s => s.available).map(s => s.importId));
  const batches = imports.filter(b => sourceIds.has(b.id)).sort((a, b) => canonicalCompare(a.id, b.id)); batches.forEach(b => assertScope(mission.scope, b.scope));
  if (batches.length !== sourceIds.size) throw new Error("EXPORT_SOURCE_REQUIRED");
  const report = { exportSchemaVersion: "fixed-assets-mission-1.0.0", kind, createdAt, mission, run, imports: batches, binaryFilesIncluded: false };
  const canonical = canonicalJson(report), html = fixedAssetMissionHtml(mission, run, kind, createdAt), p = mission.procedure, a = p.assets;
  const csv = {
    findings: buildCsv(["procedureId", "runId", "version", "resultId", "controlId", "code", "id", "unitId", "table", "target", "amount", "message", "proofs"], (a?.exceptions ?? []).map(e => ({ procedureId: p.id, runId: p.runId, version: p.version, resultId: p.resultId, controlId: e.controlId, code: e.code, id: e.id, unitId: e.unitId, table: e.table, target: e.targetId, amount: fixedAssetAmountLabel(e.amount), message: e.message, proofs: e.proofIds }))),
    reviewEvents: buildCsv(["procedureId", "runId", "version", "actorId", "at", "action", "note"], mission.versionIndex.flatMap(v => v.events.slice(-1).map(e => ({ ...e, procedureId: p.id, runId: v.id, version: v.version, note: v.approval?.note ?? "" })))),
    controls: buildCsv(["procedureId", "runId", "version", "ruleVersion", "controlId", "label", "outcome", "complete", "numerator", "denominator", "unit", "exclusions"], p.controls.map(x => ({ procedureId: p.id, runId: p.runId, version: p.version, ruleVersion: x.ruleVersion, controlId: x.id, label: x.label, outcome: x.outcome ?? "not_executed", complete: x.complete, numerator: x.coverage.numerator, denominator: x.coverage.denominator, unit: x.coverage.unit, exclusions: x.coverage.exclusions.map(e => e.id + ":" + e.reason) }))),
    sources: buildCsv(["id", "importId", "type", "fileName", "sha256", "approvedBy", "approvedAt", "available", "required", "current", "binaryInPackage", "locators"], mission.sources.map(s => ({ ...s, locators: s.locators.map(l => l.rowId + ":" + fixedAssetLocatorLabel(l.locator)) }))),
  };
  const pdf = await buildPdfFromAccessibleHtml(html, { title: "PROBANT - Immobilisations - " + kind, createdAt });
  const base = "probant-immobilisations-" + kind + "-" + mission.hash.slice(0, 12);
  const manifest: EvidenceManifest = { manifestVersion: "1.0.0", applicationVersion: "0.1.0", dossierId: mission.scope.dossierId, snapshotId: mission.hash, createdAt,
    sourceDocuments: batches.map(b => ({ id: b.document.id, fileName: b.document.fileName, documentType: b.document.documentType, sha256: b.document.byteHash, parserVersion: b.document.parserVersion, location: { provider: "postgres-fa", key: b.id, versionId: b.document.id } })),
    parserVersions: Object.fromEntries(batches.map(b => [b.document.id, b.document.parserVersion])), ruleSetVersion: mission.program.version,
    referenceSetVersion: "fixed-assets-closed-contract-1.0.0", policyVersion: "server-dossier-permissions-1.0.0", snapshotSha256: mission.hash, reviewEventsDigest: stableSha256(mission.versionIndex),
    artifacts: [artifact("canonical_json", base + ".json", "application/json", canonical), artifact("findings_csv", base + "-exceptions.csv", "text/csv;charset=utf-8", csv.findings),
      artifact("review_events_csv", base + "-decisions.csv", "text/csv;charset=utf-8", csv.reviewEvents), artifact("controls_csv", base + "-procedures.csv", "text/csv;charset=utf-8", csv.controls),
      artifact("sources_csv", base + "-sources.csv", "text/csv;charset=utf-8", csv.sources), artifact("accessible_html", base + ".html", "text/html;charset=utf-8", html),
      artifact("pdf", base + ".pdf", "application/pdf", pdf, { derivedFrom: base + ".html", validation: { pdfA: { status: "not_validated", profile: null, validator: null, validatedAt: null } } })],
    limitations: [...mission.limitations.map((message, i) => ({ code: "fixed_assets_limit_" + i, message, subjects: [] as string[] })),
      { code: "package_kind_" + kind, message: kind === "approved" ? "Procédure Immobilisations approuvée et verrouillée ; aucune opinion sur les comptes." : "Diagnostic, y compris des versions historiques ou périmées ; aucune approbation du paquet.", subjects: [mission.hash] },
      { code: "pdf_standard_unicode", message: "PDF standard sans PDF/A ; caractères hors Latin-1 remplacés. HTML et JSON préservent Unicode.", subjects: [base + ".pdf"] }] };
  return { manifest, manifestJson: canonicalJson(manifest), canonicalJson: canonical, csv, html, pdf };
}
