import { canonicalJson, stableSha256 } from "@/lib/synthesis/canonical";
import { contentHash, validateRun, assertScope, type WorkpaperRun } from "@/lib/workpapers/model";
import type { ImportBatch } from "@/lib/workpapers/imports";
import type { PayablesMission } from "@/lib/workpapers/payables-mission";
import type { framePayables } from "@/lib/workpapers/payables";
import { STATUS_LABELS, payablesStateLabel, payablesUnitLabel } from "@/lib/workpapers/payables-program";
import { amountLabel, locatorLabel } from "@/lib/workpapers/client-mission";
import { buildCsv } from "./csv";
import { artifact } from "./package";
import { buildPdfFromAccessibleHtml } from "./pdf";
import type { EvidenceManifest, EvidenceExportPackage } from "./types";
const esc = (value: unknown) => String(value ?? "—").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
const table = (caption: string, headers: string[], rows: unknown[][]) => "<table><caption>" + esc(caption) + "</caption><thead><tr>" + headers.map(h => "<th scope='col'>" + esc(h) + "</th>").join("") + "</tr></thead><tbody>" + rows.map(row => "<tr>" + row.map(c => "<td>" + esc(c) + "</td>").join("") + "</tr>").join("") + "</tbody></table>";
export function payablesHtml(m: PayablesMission, run: WorkpaperRun | null, kind: "diagnostic" | "approved", at: string) {
    const selected = m.procedures.find(p => p.run?.id === run?.id), status = kind === "approved" ? "Paquet approuvé — portée limitée à la procédure sélectionnée" : "Export diagnostic — aucune approbation du paquet";
    return "<!doctype html><html lang='fr'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width'><title>PROBANT — Achats et fournisseurs</title><style>body{font:15px/1.5 system-ui;color:#18283c;margin:2rem auto;max-width:1150px;padding:0 1rem}table{width:100%;table-layout:fixed;border-collapse:collapse;margin:1rem 0}caption{text-align:left;font-weight:700}th,td{border:1px solid #bdc8d3;padding:7px;text-align:left;vertical-align:top;overflow-wrap:anywhere;white-space:pre-wrap;font-size:11px}thead{display:table-header-group}tr{break-inside:avoid}h2{break-after:avoid}.notice{border-left:4px solid #b97817;padding:1rem}p{overflow-wrap:anywhere}@page{size:A4 landscape;margin:16mm}@media print{body{margin:0;max-width:none;padding:0}h2{font-size:17px}thead{display:table-header-group}}</style></head><body><header><h1>Achats, fournisseurs et cut-off</h1><p>" + esc(status) + "</p><p>Dossier " + esc(m.scope.dossierId) + " ; organisation " + esc(m.scope.organizationId) + " ; période " + esc(m.scope.periodId) + "</p><p>Feuille " + esc(run?.id) + " v" + esc(run?.version) + " ; auteur " + esc(run?.preparedBy) + " ; état serveur " + esc(m.hash) + " ; " + esc(at) + "</p></header><h2>Résumé humain</h2><p>" + esc(selected?.label) + " : " + esc(run?.conclusion ?? "Conclusion humaine non renseignée") + "</p><p>" + esc(selected?.reviewLabel) + ". " + esc(selected?.stale ? selected.staleReasons.join(" ") : "Sources référencées courantes à cet état") + ".</p><p class='notice'>La fenêtre de paiements ne prouve pas l’exhaustivité des dettes. Une prestation inconnue ou une allocation incomplète reste non concluante. Résiduel TTC et candidat HT sont distincts. Aucune opinion automatique.</p><h2>Décisions et programme</h2><p>" + m.counters.executed + "/" + m.counters.planned + " procédures exécutées ; " + m.counters.plannedControls + " contrôles prévus indépendamment des exceptions.</p>"
        + table("Décisions par procédure/version", ["Procédure", "Identité / version", "Couverture et exclusions", "État et décision"], m.procedures.map(p => [p.label, (p.run?.id ?? "Absente") + " v" + (p.run?.version ?? "—"), p.coverage.numerator + "/" + (p.coverage.denominator ?? "inconnu") + " " + payablesUnitLabel(p.coverage.unit) + " ; sélection " + p.coverage.selected + " ; exclusions " + p.coverage.exclusions.map(e => e.id + ":" + e.reason).join(" ; "), (p.stale ? "Périmée : " + p.staleReasons.join(" ") : payablesStateLabel(p.run?.state)) + " ; " + p.reviewLabel + " ; " + (p.run?.approval?.note ?? "Non approuvée") + (p.run?.id === run?.id ? " ; procédure sélectionnée" : " ; contexte, aucune approbation implicite")]))
        + m.procedures.map(p => "<h2>" + esc(p.label) + "</h2><p>Contrôles prévus : " + esc(p.plannedControls.join(" ; ")) + ".</p><p>Méthode " + esc(p.result?.work.method.id) + " @ " + esc(p.result?.work.method.version) + " ; source " + esc(p.result?.work.method.source) + " ; auteur " + esc(p.result?.work.authorId) + " ; " + esc(p.result?.work.method.note) + ".</p><p>Comptes : " + esc(p.result?.work.accounts.join(", ")) + ". Fenêtre " + esc(p.result?.window.startDate) + " → " + esc(p.result?.window.endDate) + " ; " + esc(p.result?.window.coverage) + " ; " + esc(p.result?.window.note) + ".</p>"
            + (p.result?.procedure === "payables.frame" ? [(p.result.technical as ReturnType<typeof framePayables>).generalToAuxiliary, (p.result.technical as ReturnType<typeof framePayables>).auxiliaryToAged].map(c => table(c.left + " / " + c.right + " : net " + amountLabel(c.metrics.net) + " ; brut inexpliqué " + amountLabel(c.metrics.grossUnexplained), ["Clé", "Source", "Cible", "Résiduel"], c.metrics.units.map(u => [u.id, amountLabel(u.source), amountLabel(u.target), amountLabel(u.residual)]))).join("") : "")
            + table("Population et sélection figées", ["Unité / montant", "Sources", "Sélection"], p.run?.population?.items.map(i => [i.id + " : " + amountLabel(i.amount), i.rowIds.join(" ; "), p.run!.selection?.selectedIds.includes(i.id) ? "Sélectionnée" : "Non sélectionnée ou exclue"]) ?? [])
            + table("Investigation", ["Événement / tiers / facture", "Statut", "Paiement TTC / résiduel TTC", "Différence ou candidat HT", "Motifs / limites"], p.result?.rows.map(r => [r.eventId + " / " + r.party + " / " + r.invoiceId, STATUS_LABELS[r.status], r.paidTTC ? amountLabel(r.paidTTC) + " ; résiduel " + amountLabel(r.unallocatedTTC ?? undefined) : "Sans paiement dans ce parcours", amountLabel(r.status === "omission_candidate" && r.cutoff ? r.cutoff.amount : r.differenceHT) + " HT", r.reasons.join(" ; ")]) ?? [])
            + table("Contrôles prévus : numérateur / dénominateur", ["Contrôle", "Testé", "Population", "Unité", "Exclusions"], p.controls.map(c => [c.label, c.numerator, c.denominator, payablesUnitLabel(c.unit), c.exclusions.map(e => e.id + ":" + e.reason).join(" ; ")]))
            + table("Avant / après revue", ["Version soumise", "Conclusion avant revue", "Décision de revue", "Exceptions conservées"], [[p.beforeReview?.version, p.beforeReview?.conclusion, p.run?.approval?.actorId + " : " + p.run?.approval?.note, p.run?.notes.map(n => n.text).join(" ; ")]])
            + table("Frise des dates", ["Unité / événement", "Date", "Fait", "Vérification de provenance"], p.result?.rows.flatMap(r => r.timeline.map(t => [r.id, t.date, t.label, t.verified ? "Provenance documentée" : "Pièce attendue"])) ?? [])
            + table("Exceptions et traitement après revue", ["Point", "Montant / base", "Auteur", "Traitement — exception conservée"], p.run?.notes.map(n => [n.text, amountLabel(n.amount), n.authorId, n.resolution ? n.resolution.text + " ; " + n.resolution.authorId + " ; " + n.resolution.at : "Non résolue"]) ?? [])).join("")
        + "<h2>Événements économiques et unités</h2><p>" + esc(m.amountConvention) + "</p>"
        + table("Bases HT / TVA / TTC sourcées", ["Procédure / version", "Événement / facture / flux", "HT", "TVA", "TTC"], m.procedures.flatMap(p => p.result?.events.map(e => [p.id + " v" + p.run!.version, e.cutoff.economicEventId + " / " + e.invoiceId + " / " + e.flow, amountLabel(e.net), amountLabel(e.tax), amountLabel(e.gross)]) ?? []))
        + table("Expositions uniques, sans doublon entre Achats et RPNE", ["Événement", "Résiduel HT", "Procédures", "Preuves"], m.exposures.map(e => [e.economicEventId, amountLabel(e.amount) + " HT", e.procedureIds.join(" ; "), e.evidence.map(p => p.id).join(" ; ")]))
        + "<h2>Index des pièces et localisateurs</h2><p>Pièces binaires absentes du paquet. Les lignes normalisées sont incluses ; les originaux se téléchargent avec les permissions du dossier.</p>"
        + table("Sources/version/présence", ["Source / fichier", "Document / import / empreinte", "Provenance", "Présence"], m.sources.map(s => [s.label + " / " + s.fileName, s.id + " / " + s.importId + " / " + s.sha256, s.parserVersion + " / " + s.mappingVersion + " / " + s.mappingHash + " ; " + s.approvedBy + " / " + s.approvedAt, (s.current ? "Courante" : "Remplacée / périmée") + " ; binaire absent"]))
        + table("Sources attendues absentes", ["Type", "Pièce attendue"], m.missingSources.map(s => [s.type, s.label]))
        + table("Index des preuves liées", ["Procédure / version", "Preuve / source / ligne", "Localisateur / usage"], m.procedures.flatMap(p => p.run?.evidence.map(e => [p.id + " / " + p.run!.id + " v" + p.run!.version, e.id + " / " + e.documentVersionId + " / " + e.rowId, locatorLabel(e.locator) + " ; " + e.purpose]) ?? []))
        + "<h2>Incertitudes et limites</h2><ul>" + [...m.limitations, ...m.procedures.flatMap(p => p.result?.limitations ?? []), "PDF standard, sans certification PDF/A ; hors Latin-1 remplacé dans le PDF. HTML et JSON conservent Unicode."].map(l => "<li>" + esc(l) + "</li>").join("") + "</ul><p>Famille : procédures de mission. DEMO SA historique et atelier synthétique exclus de ce paquet.</p></body></html>";
}
export async function buildPayablesPackage(m: PayablesMission, run: WorkpaperRun | null, imports: ImportBatch[], kind: "diagnostic" | "approved", at: string): Promise<EvidenceExportPackage> {
    const { hash, ...body } = m;
    if (stableSha256(body) !== hash)
        throw new Error("EXPORT_SNAPSHOT_HASH_INVALID");
    const selected = m.procedures.find(p => p.run?.id === m.selectedRunId && p.run?.version === m.selectedVersion);
    if (m.selectedRunId && !run)
        throw new Error("EXPORT_RUN_REQUIRED");
    if (run) {
        validateRun(run);
        assertScope(m.scope, run.scope);
        if (run.id !== m.selectedRunId || run.version !== m.selectedVersion || contentHash(run) !== contentHash(selected!.run!))
            throw new Error("EXPORT_VERSION_INVALID");
    }
    if (kind === "approved" && (!run || run.state !== "locked" || selected?.stale || run.approval?.snapshotHash !== contentHash(run) || run.result?.execution !== "completed"))
        throw new Error("EXPORT_APPROVED_CURRENT_LOCKED_REQUIRED");
    const ids = new Set(m.sources.map(s => s.importId)), batches = imports.filter(b => ids.has(b.id));
    if (batches.length !== ids.size)
        throw new Error("EXPORT_SOURCE_REQUIRED");
    batches.forEach(b => assertScope(m.scope, b.scope));
    const canonical = canonicalJson({ exportSchemaVersion: "payables-mission-1", kind, at, mission: m, run, imports: batches, binaryFilesIncluded: false }), html = payablesHtml(m, run, kind, at);
    const csv = { findings: buildCsv(["procedureId", "runId", "version", "eventId", "invoiceId", "status", "paidTTC", "residualTTC", "candidateHT", "reasons"], m.procedures.flatMap(p => p.result?.rows.map(r => ({ procedureId: p.id, runId: p.run!.id, version: p.run!.version, eventId: r.eventId, invoiceId: r.invoiceId, status: STATUS_LABELS[r.status], paidTTC: amountLabel(r.paidTTC ?? undefined), residualTTC: amountLabel(r.unallocatedTTC ?? undefined), candidateHT: amountLabel(r.status === "omission_candidate" && r.cutoff ? r.cutoff.amount : r.differenceHT), reasons: r.reasons })) ?? [])), reviewEvents: buildCsv(["procedureId", "runId", "version", "actorId", "at", "action"], m.procedures.flatMap(p => p.run?.events.map(e => ({ ...e, procedureId: p.id, runId: p.run!.id })) ?? [])), controls: buildCsv(["procedureId", "control", "numerator", "denominator", "unit", "exclusions"], m.procedures.flatMap(p => p.controls.map(c => ({ procedureId: p.id, control: c.label, ...c })))), sources: buildCsv(["id", "importId", "fileName", "sha256", "current", "binaryInPackage"], m.sources) };
    const pdf = await buildPdfFromAccessibleHtml(html, { title: "PROBANT - Achats fournisseurs - " + kind, createdAt: at }), base = "probant-payables-" + kind + "-" + m.hash.slice(0, 12);
    const manifest: EvidenceManifest = { manifestVersion: "1.0.0", applicationVersion: "0.1.0", dossierId: m.scope.dossierId, snapshotId: m.hash, createdAt: at, sourceDocuments: batches.map(b => ({ id: b.document.id, fileName: b.document.fileName, documentType: b.document.documentType, sha256: b.document.byteHash, parserVersion: b.document.parserVersion, location: { provider: "postgres-workpapers", key: b.id, versionId: b.document.id } })), parserVersions: Object.fromEntries(batches.map(b => [b.document.id, b.document.parserVersion])), ruleSetVersion: m.program.version, referenceSetVersion: "payables-internal-contract-1", policyVersion: "server-dossier-permissions-1", snapshotSha256: m.hash, reviewEventsDigest: stableSha256(m.procedures.map(p => p.run?.events ?? [])), artifacts: [artifact("canonical_json", base + ".json", "application/json", canonical), artifact("findings_csv", base + "-exceptions.csv", "text/csv;charset=utf-8", csv.findings), artifact("review_events_csv", base + "-decisions.csv", "text/csv;charset=utf-8", csv.reviewEvents), artifact("controls_csv", base + "-procedures.csv", "text/csv;charset=utf-8", csv.controls), artifact("sources_csv", base + "-sources.csv", "text/csv;charset=utf-8", csv.sources), artifact("accessible_html", base + ".html", "text/html;charset=utf-8", html), artifact("pdf", base + ".pdf", "application/pdf", pdf, { derivedFrom: base + ".html", validation: { pdfA: { status: "not_validated", profile: null, validator: null, validatedAt: null } } })], limitations: m.limitations.map((message, i) => ({ code: "payables_limit_" + i, message, subjects: [] })) };
    return { manifest, manifestJson: canonicalJson(manifest), canonicalJson: canonical, csv, html, pdf };
}
